dnbexperience/eufemia

packages/dnb-ui-lib/src/components/input/Input.js, packages/dnb-ui-lib/src/components/input/__tests__/Input.test.js, packages/dnb-ui-lib/src/components/textarea/Textarea.js, packages/dnb-ui-lib/src/components/textarea/__tests__/Textarea.test.js, packages/dnb-ui-lib/stories/components/Input.js
- This will fix #240 + #textarea as well witch had the same issue
=> fix: fix #input and #textarea empty value change

packages/dnb-design-system-portal/src/docs/uilib/development.md
Dead link to https://eufemia.dnb.no/uilib/confluence.tech.dnb.no/display/EDS/ should now link to https://confluence.tech.dnb.no/display/EDS/
=> Fix dead link to confluence

packages/dnb-design-system-portal/src/docs/uilib/components/space/Examples.js, packages/dnb-design-system-portal/src/docs/uilib/components/space/info.md, packages/dnb-design-system-portal/src/docs/uilib/usage/layout/spacing.md, packages/dnb-ui-lib/src/components/space/Space.js, packages/dnb-ui-lib/src/components/space/SpacingHelper.js, packages/dnb-ui-lib/src/components/space/__tests__/Space.test.js, packages/dnb-ui-lib/src/components/space/__tests__/SpacingHelper.test.js
This PR enhance the overall used spacing API with an additional `space` prop, that accepts an object. But also a boolean, number or string to target all four directions at once.
=> feat: enhance #space to support booleans and strings, along with object

packages/dnb-design-system-portal/src/docs/uilib/components/global-status/Examples.js
Tertiary button in global-status/Examples.js requires an icon.
Removed the following info message that occurs when visiting the portal for GlobalStatus:
=> chore: tertiary button requires an icon

packages/dnb-design-system-portal/src/docs/design-system/about.md
Link to WCAG 2.1 did not work.
When clicking, it sent me to https://eufemia.dnb.no/design-system/www.w3.org/TR/WCAG21/
https://eufemia.dnb.no/design-system/about#standards
=> fix: change url to WCAG 2.1

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap, packages/dnb-eufemia/src/components/progress-indicator/__tests__/__snapshots__/ProgressIndicator.test.js.snap, packages/dnb-eufemia/src/components/progress-indicator/style/_progress-indicator.scss
Issue:
https://user-images.githubusercontent.com/1359205/117585915-6745f680-b115-11eb-9869-be6df27c8208.mov
After fix:
https://user-images.githubusercontent.com/1359205/117586003-d7ed1300-b115-11eb-89e1-d066c2995b92.mov
=> fix: border radius transition issue in safari

packages/dnb-eufemia/src/components/button/Button.js, packages/dnb-eufemia/src/components/button/__tests__/Button.test.js, packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.js.snap, packages/dnb-eufemia/src/components/global-error/__tests__/__snapshots__/GlobalError.test.js.snap, packages/dnb-eufemia/src/components/help-button/__tests__/__snapshots__/HelpButton.test.js.snap, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.js.snap, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap, packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.js.snap, packages/dnb-eufemia/src/components/tabs/__tests__/__snapshots__/Tabs.test.js.snap, packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.js.snap
This PR fixes a wrong defined check for adding type
- Added a test to ensure we have type=button
- Because a button will else be able to submit a <form>
- An Anchor does not need that
=> fix: ensure that a button still has type button

packages/dnb-design-system-portal/src/docs/uilib/components/form-status/properties.md, packages/dnb-eufemia-sandbox/stories/components/FormStatus.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.js.snap, packages/dnb-eufemia/src/components/form-status/FormStatus.js, packages/dnb-eufemia/src/components/form-status/__tests__/FormStatus.test.js, packages/dnb-eufemia/src/components/form-status/__tests__/__snapshots__/FormStatus.test.js.snap, packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.js.snap
Add role attribute to FormStatus component, so when an "error" is shown it's picked up by a screen reader.
The FormStatus component will now add `role="alert"` unless the `disableRole` prop on FormStatus is set to `true`.
I have created two tests, testing that the `role="alert"` is only set if the `disableRole` prop is false.
I also added a new section in the storybook, that toggles the FormStatus when the submit button is clicked. On mac with VoiceOver this triggers the screen reader to read the contents of the status.
=> fix: add role attribute to form-status

packages/dnb-eufemia/src/shared/libs/bodyScrollLock.js
By using margin, instead of padding, we avoid the content movement when the scroller gets removed.
=> fix: fix #modal #drawer page width and content movement

packages/dnb-design-system-portal/src/docs/uilib/components/progress-indicator/properties.md, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap, packages/dnb-eufemia/src/components/progress-indicator/ProgressIndicator.js, packages/dnb-eufemia/src/components/progress-indicator/ProgressIndicatorCircular.js, packages/dnb-eufemia/src/components/progress-indicator/ProgressIndicatorLinear.js, packages/dnb-eufemia/src/components/progress-indicator/__tests__/ProgressIndicator.test.js, packages/dnb-eufemia/src/components/progress-indicator/__tests__/__snapshots__/ProgressIndicator.test.js.snap
This PR adds the possibility to customize the aria-label and title of progress indicator.
It also formats the default aria-label and title (progress prop value), using "NumberFormat" percent.
**Before this PR**
Title and aria-label - https://eufemia.dnb.no/uilib/components/progress-indicator/demos:
**Changes in this PR**
Formatting the default aria-label, and title, using "NumberFormat" for percent with 2 decimals:
Customizing the aria-label and title of progress indicator, by passing the `title` property:
=> feat: customize aria-label and title of progress indicator

packages/dnb-design-system-portal/src/docs/uilib/components/space/properties.md, packages/dnb-eufemia/src/components/skeleton/__tests__/__snapshots__/Skeleton.test.js.snap, packages/dnb-eufemia/src/components/space/Space.js, packages/dnb-eufemia/src/components/space/__tests__/__snapshots__/Space.test.js.snap, packages/dnb-eufemia/src/components/space/style/_space.scss
- This feature is an edge case, and is not needed often
- It is used in the new StepIndicator demos
=> fix: add `stretch` property to space

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.js.snap, packages/dnb-eufemia/src/components/input/style/_input.scss
The clear button on the input field has a not-allowed mouse cursor type – when its not visible.
This PR changes the mouse cursor type to be default instead of "not-allowed".
=> fix: fix input clear button mouse cursor issue

packages/dnb-eufemia/src/components/checkbox/__tests__/__snapshots__/Checkbox.test.js.snap, packages/dnb-eufemia/src/components/checkbox/style/themes/dnb-checkbox-theme-ui.scss
This PR fixes a request by Marthe.
The change: When using the `status` prop, and the status changes while the users toggles the checkbox, it will potentially confuse a user when the checkbox still is green, but gets red one the element focus disappears. 
This  commit will ensure the visual state changes as expected.
Here is a quick demo of this new version: https://codesandbox.io/s/eufemia-checkbox-state-styles-660bn?file=/src/App.tsx
=> fix(checkbox): fix state styling during state change when status gets enabled

packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.js.snap, packages/dnb-eufemia/src/components/section/__tests__/__snapshots__/Section.test.js.snap, packages/dnb-eufemia/src/components/section/style/_section.scss
Here is a quick CSB that demos the issue: https://codesandbox.io/s/eufemia-textarea-in-nested-sections-0lnvt?file=/src/App.tsx
The border of the textarea dissapers when used in nested sections.
=> fix: lower z-index usage in #section component and support up to 5 nested sections

packages/dnb-eufemia/src/components/number-format/NumberUtils.d.ts, packages/dnb-eufemia/src/components/number-format/NumberUtils.js
The motivation for making this change is that we migrate our apps to TypeScript, and it seems like the currency param of the number format function only accepts a boolean value(according to the declaration file), but I believe/think the actual implementation accepts a string(Currency code (ISO 4217)) as well.
https://github.com/dnbexperience/eufemia/blob/e412541451c1bc1ab44aea645ae79e954bcde70f/packages/dnb-eufemia/src/components/number-format/NumberUtils.js#L45
https://github.com/dnbexperience/eufemia/blob/e412541451c1bc1ab44aea645ae79e954bcde70f/packages/dnb-eufemia/src/components/number-format/NumberUtils.js#L117
We use the number format function quite a few places in our apps, and especially in our tests 🙏
=> fix: currency param should accept string and boolean values

packages/dnb-eufemia/src/components/dropdown/Dropdown.js, packages/dnb-eufemia/src/components/input/Input.js, packages/dnb-eufemia/src/components/input/__tests__/Input.test.js, packages/dnb-eufemia/src/components/radio/RadioGroup.js, packages/dnb-eufemia/src/components/tabs/Tabs.js, packages/dnb-eufemia/src/components/tabs/TabsContentWrapper.js, packages/dnb-eufemia/src/components/toggle-button/ToggleButtonGroup.js
- This PR removes the usage of aria-labelledby on input fields
- fixes usage of multi usage (internal + extenal) merge of aria-labelledby on several components, like Slider
My tests has shown that both VoiceOver (latest) and NVDA (latest) works well with only aria-placeholder for placeholder usage. So both the label and the placeholder are getting accounced. 
Also added tests to verify the behaviour.
=> fix: fix aria-labelledby & remove it on input fields for better a11y

packages/dnb-eufemia/src/components/modal/Modal.js, packages/dnb-eufemia/src/components/modal/ModalContent.js, packages/dnb-eufemia/src/components/modal/ModalHeader.js, packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.js, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.js.snap, packages/dnb-eufemia/src/shared/locales/en-GB.js, packages/dnb-eufemia/src/shared/locales/nb-NO.js
This PR contains changes to the Modal/Drawer component.
The reason: axe-core reports failure about the usage of several role="main"
- Remove `role="main"` on Mac/iOS/Safari
- All other enviroments will use `role="dialog"`
- If no modal title is given, a `aria-label="Dialog"` will be present, defiend in the locale/translation files
=> fix: remove main role from modal and enhance usage of aria linking

packages/dnb-eufemia/src/components/step-indicator/StepIndicator.js, packages/dnb-eufemia/src/components/step-indicator/StepIndicatorProps.js
Seems like it was a ```s``` too much in the variable name of step indicator's TypeScript types.
```stepIndicatorPropsTypes``` vs. ```stepIndicatorPropTypes```.
I think this is what causes the definition file to not include the correct types.
_NB: Make sure you include *PropType in the variable name. This also effects references inside a single file._ - https://eufemia.dnb.no/uilib/development/types#sharing-proptypes-between-components
=> fix: typescript types for step-indicator

packages/dnb-eufemia/src/components/date-picker/DatePickerAddon.js, packages/dnb-eufemia/src/components/date-picker/DatePickerCalendar.js, packages/dnb-eufemia/src/components/date-picker/DatePickerFooter.js, packages/dnb-eufemia/src/components/date-picker/DatePickerInput.js, packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.js, packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.js
Ensure date-picker fires on_change event when clearing a date – but only if there has been a valid one before
=> fix: ensure date-picker fires on_change event when clearing a date

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.js.snap, packages/dnb-eufemia/src/components/checkbox/__tests__/__snapshots__/Checkbox.test.js.snap, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.js.snap, packages/dnb-eufemia/src/components/form-status/__tests__/__snapshots__/FormStatus.test.js.snap, packages/dnb-eufemia/src/components/form-status/style/_form-status.scss, packages/dnb-eufemia/src/components/global-error/__tests__/__snapshots__/GlobalError.test.js.snap, packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.js.snap, packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.js.snap, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.js.snap, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap, packages/dnb-eufemia/src/components/radio/__tests__/__snapshots__/Radio.test.js.snap, packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.js.snap, packages/dnb-eufemia/src/components/switch/__tests__/__snapshots__/Switch.test.js.snap, packages/dnb-eufemia/src/components/textarea/__tests__/__snapshots__/Textarea.test.js.snap, packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.js.snap
Instead of always having a text cursor, it could inherit cursor when used in a button(which usually has a pointer cursor):
From:
https://user-images.githubusercontent.com/1359205/136777000-10611946-889a-454f-922f-433ebaceafb8.mov
To:
https://user-images.githubusercontent.com/1359205/136776867-3ab2adfb-13aa-42ee-adc8-31b93a26a5e9.mov
=> feat: FormStatus's cursor will be inherit when used in a button

packages/dnb-eufemia-sandbox/stories/components/GlobalStatus.js, packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/form-status/FormStatus.js, packages/dnb-eufemia/src/components/global-status/GlobalStatus.js, packages/dnb-eufemia/src/components/global-status/GlobalStatusProvider.js, packages/dnb-eufemia/src/components/global-status/__tests__/GlobalStatus.test.js, packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.js.snap, packages/dnb-eufemia/src/components/input-masked/InputMaskedProps____.js, packages/dnb-eufemia/src/shared/AnimateHeight.js
This PR fixes an issue where Autocomplete (also DatePicker) includes nested FormStatus, because of inherited components. The inherited, and not visible one did cause the message to disappear in the GlobalStatus – basically at the same time it should have been visible.
Also, it enhances the height animation of a GlobalStatus for when a message is added or removed.
=> Enhance handling of FormStatus / GlobalStatus race condition

.github/workflows/actions.yml
In order to "overwrite" existing branches, named `--visual-reports`, we can force push with lease as a solution.
=> chore: only run CI on push, and not on PR + push

packages/dnb-eufemia/scripts/prepub/commitToBranch.js
This PR will ensure visual test snapshots get always pushed to the `*--visual-reports` branch, regardless if it exists from before or not.
=> chore: force push visual reports

packages/dnb-design-system-portal/scripts/deploy.js, packages/dnb-eufemia/package.json, packages/dnb-eufemia/scripts/prepub/commitToBranch.js
This PR changes how we skip CI to be GitHub conform. GitHub [blog says](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/) they have to be lower case. 
Why do we need the change? 
During release, when the change log gets commited back to release, we don't want this commit to run again. Right now it does run, e.g.:
https://github.com/dnbexperience/eufemia/commit/3d2923a70724b84c6b83362a33851727e1ba101a
=> chore: use lower case when skipping CI

packages/dnb-eufemia/src/components/button/__tests__/Button.screenshot.test.js, packages/dnb-eufemia/src/components/heading/__tests__/Heading.screenshot.test.js, packages/dnb-eufemia/src/components/icon/__tests__/Icon.screenshot.test.js, packages/dnb-eufemia/src/components/number-format/__tests__/NumberFormat.screenshot.test.js, packages/dnb-eufemia/src/core/jest/jestSetupScreenshots.js, packages/dnb-eufemia/src/elements/__tests__/Anchor.screenshot.test.js, packages/dnb-eufemia/src/style/core/helper-classes/__tests__/HelperClasses.screenshot.test.js, packages/dnb-eufemia/src/style/elements/__tests__/Typography.screenshot.test.js
I have seen this visual test fail too often, so we may skip it on CI. Not sure if then just the next one will fail. Probably. But from my experience, the href test has been a fragile thing before.
=> chore: skip fragile visual tests

.github/workflows/actions.yml, packages/dnb-design-system-portal/gatsby-node.js, packages/dnb-eufemia/scripts/prepub/tasks/makeLibStyles.js, packages/dnb-eufemia/scripts/prepub/tasks/makeMainStyle.js, packages/dnb-eufemia/scripts/release/babel-cjs.sh, packages/dnb-eufemia/scripts/release/babel-es.sh, packages/dnb-eufemia/scripts/release/babel-esm.sh, packages/dnb-eufemia/scripts/release/copyStyles.js
This PR ensures we invalidate the build cache when there are dependency changes. Also, make it more clear when to consume the prebuild.
And create the the cjs and es styles in their build steps (post build), instead in the pre build step.
=> chore: fix portal build cache

packages/dnb-design-system-portal/gatsby-config.js, packages/dnb-design-system-portal/gatsby-node.js, packages/dnb-design-system-portal/src/docs/uilib/development/portal.md, packages/dnb-design-system-portal/src/docs_dummy/dummy.md, packages/dnb-design-system-portal/src/docs_dummy/dummy/info.md, packages/dnb-design-system-portal/src/shared/menu/MainMenu.js, packages/dnb-design-system-portal/src/shared/menu/SearchBar.js, packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.js, packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.js, packages/dnb-design-system-portal/src/shared/tags/Tabbar.js, packages/dnb-design-system-portal/src/templates/mdx.js, packages/dnb-design-system-portal/src/uilib/search/searchQuery.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.js, packages/dnb-eufemia/src/fragments/drawer-list/DrawerListProvider.js
This PR changes how the Portal source data. The old method was made before Gatsby had `createSchemaCustomization` and `createResolvers`, which should ensure we do not miss the "title" anymore, as this should be much more stable.
=> chore: refactor Portal data structure and sourcing

jsconfig.json, package.json, tsconfig.json, yarn.lock
VSCode uses this to let its internal TS to work, but it gets too little config, so we rather sue tscofnig and give it more details there.
=> chore: replace jsconfig with jsconfig

.yarnrc.yml, packages/dnb-design-system-portal/gatsby-config.js, packages/dnb-eufemia-sandbox/stories/components/Breadcrumb.tsx, packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx, packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx, tsconfig.json
This PR makes Storybook running again. After we added tsconfig it had some problems due to the underlaing docgen usage and our ts setup.
Also, remove flag in gatsby-config for much faster dev startup time.
=> fix: fix Breadcrumb Storybook Docgen issue

packages/dnb-eufemia-sandbox/stories/components/Autocomplete.js, packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.js
This PR fixes two bugs – similar code wise, but with a different outcome. 
In both cases, we get a new `data` array, but used internally the old one, while using the new `value`.
=> Fix Autocomplete data value handling

.github/workflows/build-check.yml, .github/workflows/release.yml, .github/workflows/verify.yml
During 9.16 release I had to force push the changes in this PR in order to get i tout. It looks like the release workflow does not run a a branch, when it is "dependent". It bypass instead the most important steps. 
But because we already run both the Verify and the Build Check on main, we can omit it for now, and just release.
=> chore: release without dependent checks

packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js, packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js
When selecting partial or all input masked content, the selection got lost. This PR fixes this behaviour by checking if the user has selected more than one char.
=> fix(InputMasked): fix manual range selection

packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
This PR fixes an issue when `allowLeadingZeroes` was true while typing
Reproduction [CSB](https://codesandbox.io/s/inputmasked-bug-leading-zeroes-l0hf5)
=> fix(InputMasked): fix misplaced leading zero while typing

packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js, packages/dnb-eufemia/src/components/input-masked/TextMask.js, packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js
This PR fixes also a reported issue. It occurres when an empty string was given initially. Then the update value prop did not make any changes.  
Reproduction [CSB](https://codesandbox.io/s/inputmasked-bug-empty-string-s4zp2?file=/src/App.jsx)
=> fix(InputMasked): handle initial empty string value

packages/dnb-design-system-portal/.eslintrc, packages/dnb-design-system-portal/gatsby-config.js, packages/dnb-design-system-portal/src/docs/uilib/components/breadcrumb/Examples.js, packages/dnb-eufemia/.eslintrc, tsconfig.json
This is a React v17 feature. With this PR we can use it today already. Not sure if I personally will use it that often. But its a feature of Gatsby 4.1, so why not enable it right.
=> chore(Portal): make React import optional

packages/dnb-eufemia/src/components/number-format/NumberUtils.d.ts
export format and cleanNumber as functions and not types
format and cleanNumber were exported as `type` instead of as a function.
This makes typescript complain about it being used as a type and not a value
=> Fix(NumberFormat): types for NumberUtils

packages/dnb-eufemia/package.json, packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js, packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js, packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js, packages/dnb-eufemia/src/shared/component-helper.js, packages/dnb-eufemia/src/shared/helpers.js, yarn.lock
Among issues like: a dot appears on the Android soft keyboard, but this lets the user not enter a coma.
Android sends just 229 on most of the keycodes when using the keyDown event.
It always returns 229 because it is a W3C standard to return 229 when an "Input Method Editor" is processing and the event is keydown.  It appeared in a 2010 W3C spec linked below.
A [codepen](https://codepen.io/ashconnolly/pen/WyWgPG?__cf_chl_captcha_tk__=30wzbiTaXd90vfTkcOT6ijFBIqzQToyJk6R65lT3k9U-1637164880-0-gaNycGzNB2U) on that topic.
Because the InputMasked is using the keycode in several ways – we have to do someting.
As of now, we simply avoid using `inputmode`.
Reprod from Marius K. [CSB](https://codesandbox.io/s/optimistic-herschel-uu43h?file=/src/App.jsx)
=> fix(InputMasked): inputmode usage on Android phones

packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/info.md, packages/dnb-eufemia-sandbox/stories/components/StepIndicator.js, packages/dnb-eufemia/src/components/step-indicator/StepIndicator.js, packages/dnb-eufemia/src/components/step-indicator/StepIndicatorContext.js, packages/dnb-eufemia/src/components/step-indicator/StepIndicatorItem.js, packages/dnb-eufemia/src/components/step-indicator/StepIndicatorModal.js, packages/dnb-eufemia/src/components/step-indicator/StepIndicatorProps.js, packages/dnb-eufemia/src/components/step-indicator/StepIndicatorSidebar.js, packages/dnb-eufemia/src/components/step-indicator/StepIndicatorTriggerButton.js, packages/dnb-eufemia/src/components/step-indicator/__tests__/StepIndicator.test.js, packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator-v1.test.js.snap, packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.js.snap, packages/dnb-eufemia/src/components/step-indicator/style/_step-indicator.scss, packages/dnb-eufemia/src/shared/EventEmitter.js
This PR is a small rewrite where the StepIndicator uses now `React.Portal` to show the Sidebar list (if a Sidebar is given). This change is mainly of internal interrest – its only to ensure we only have ONE context and state, instead of tyring to sync it as before.
Also, this PR will show the Sidebar by default (desktop) – so it gets rendered in desktop mode during SSR – we do this only to lower the layout shift on larger screens, and to avoid large horizontal flickering. 
A skeleton list is rendered during SSR, as long as not the original `data` also is given to the Sidebar.
=> StepIndicator SSR enhancement

packages/dnb-design-system-portal/src/docs/uilib/helpers/functions.md, packages/dnb-eufemia-sandbox/stories/components/Modal.js, packages/dnb-eufemia/src/components/modal/Modal.js, packages/dnb-eufemia/src/components/modal/ModalContent.js, packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.js, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.js.snap, packages/dnb-eufemia/src/components/modal/style/_modal-mixins.scss, packages/dnb-eufemia/src/components/modal/style/_modal.scss, packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js, packages/dnb-eufemia/src/shared/component-helper.js, packages/dnb-eufemia/src/shared/helpers.js
This PR aims to enhacne performance issues when opening the Modal / Drawer while a large amount of table rows are already in the DOM.
The first approach was to lower the amount of DOM maniulations during the invalidatione phase. But;
- Tests confirm that we can't remove `tabindex=-1` 
- And the same tests do also confirm, that making the attribute changes do take actualy the lowest amount of all CPU usage. On a table with 10 000 rows, it takes under 0.5s
So what takes the most CPU? Its the browser re-paint phase. Why does the browser need to make a repoiant when the Modal opens and closes? Because it changes every visible pixle:
- we need to change some styles on the body and html element to lock scrolling
- we show an overlay with opacity
Now, this PR still includes a couple of …
=> Enhance Modal / Drawer Performance

packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.js
Adding a test to confim it. Heres a codesandbox that [confirms](https://codesandbox.io/s/eufemia-autocomplete-form-submit-weyzq?file=/src/App.tsx) it got fixed in v9.14
=> chore(Autocomplete): add test to confirm the submit button has type="button"

packages/dnb-eufemia/src/components/global-status/GlobalStatus.js, packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.js.snap
Before refactoring Modal, this PR removes the dependencies attached to Modal Close button in GlobalStatus
=> chore: Remove Globalstatus dependency to Modal closebutton

packages/dnb-eufemia/src/components/input-masked/InputMasked.js, packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js, packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js, packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js
The InputMasked did not properly handle provider/context props as well as accepting local props when a custom mask only is used. This PR fixes both.
=> fix(InputMasked): inherit of provider/context props

packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx
Fixing a reported issue when sending down props to `<Breadcrumb.Item data-testid="breadcrumb-item-card" onClick={null}/>` without interaction. Check out the [slack thread](https://dnb-it.slack.com/archives/CMXABCHEY/p1640792268004600).
Successfully ran tests and screenshot tests, as well as manual testing 👍
=> fix(Breadcrumb): forward props in BreadcrumbItem to span as well

packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx, packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx
Improved accessibility of the current breadcrumb-item by using [aria-current="page"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) instead of aria-current="true".
From MDN: _"...In a breadcrumb list, when a link within a set of pagination links is styled to indicate the user is currently on that page, aria-current="page" should be set on that link"_
=> fix(Breadcrumb): improve accessibility

packages/dnb-eufemia/src/shared/Context.js
Global context did not work on Typescript components because of object ordering
=> fix: fixed global context bug that removed component props

packages/dnb-eufemia/src/components/date-picker/DatePicker.js, packages/dnb-eufemia/src/components/date-picker/DatePickerFooter.js, packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.js
Doesn't seem like property `reset_button_text` of DatePicker was used at all 🤔 
The reported bug can be read here: https://dnb-it.slack.com/archives/CMXABCHEY/p1642090852041200
CodeSandbox: https://codesandbox.io/s/eufemia-starter-forked-isxjv?file=/src/App.tsx
=> fix: fix reset_button_text property of DatePicker

packages/dnb-design-system-portal/src/docs/uilib/components.md
Seems like we've forgotten about updating this page when adding new components, https://eufemia.dnb.no/uilib/components
The description texts used for the components(see [here](https://eufemia-choreaddmissingcomponentstocom.gtsb.io/uilib/components)), is just copy+pasted from the description in their respective .md file. These descriptions could be improved, suggestions are welcomed 🙏
=> chore: add missing components to components docs

packages/dnb-design-system-portal/src/docs/contribute/first-contribution.md, packages/dnb-design-system-portal/src/docs/uilib/elements.md
Removes the following warning from the terminal: 
_Attempted import error: 'cite' is not exported from '@dnb/eufemia/src' (imported as 'cite')_
And from the dev console:
_export 'cite' (imported as 'cite') was not found in '@dnb/eufemia/src' (possible exports: Accordion, Anchor, Autocomplete, Blockquote, Breadcrumb, Button, Checkbox, Code, DatePicker, Dd, Div, Dl, Dropdown, Dt, FormLabel, FormRow, FormSet, FormStatus, GlobalError, GlobalStatus, H, H1, H2, H3, H4, H5, H6, Heading, HelpButton, Hr, Icon, IconPrimary, Img, Ingress, Input, InputMasked, Lead, Li, Link, Logo, Modal, NumberFormat, Ol, P, Pagination, Paragraph, ProgressIndicator, Radio, Section, Skeleton, Slider, Space, Span, StepIndicator, Switch, Table, Tabs, Tag, Td, Textarea, Th, ToggleButton, Tooltip, Tr, Ul, default)_
=> chore: remove import of cite from @dnb/eufemia/src

packages/dnb-eufemia/src/extensions/payment-card/__tests__/__snapshots__/PaymentCard.test.js.snap, packages/dnb-eufemia/src/extensions/payment-card/style/_payment-card.scss
Doesn't seem like the following variable is used, ```--dnb-payment-shadow-figma```
=> chore: remove unused style for payment card

packages/dnb-design-system-portal/src/docs/uilib/components/accordion.md, packages/dnb-design-system-portal/src/docs/uilib/components/heading.md, packages/dnb-design-system-portal/src/docs/uilib/components/help-button.md, packages/dnb-design-system-portal/src/docs/uilib/components/skeleton.md, packages/dnb-design-system-portal/src/docs/uilib/components/tooltip.md
Removed "new" status from docs for components that are older than 1-2 years.
=> docs: update "new" status

package.json, packages/dnb-design-system-portal/src/docs/uilib/components/pagination/info.md, packages/dnb-eufemia-sandbox/stories/components/Pagination.js, packages/dnb-eufemia/src/components/pagination/Pagination.js, packages/dnb-eufemia/src/components/pagination/__tests__/Pagination.test.js, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap
Pagination (mode pagination) rendered loading spinner as content when no children was given. 
Added a test for the reported issue as well
=> fix: added export of Bar in Pagination

packages/dnb-design-system-portal/src/docs/contribute/getting-started.md, packages/dnb-eufemia/src/components/Timeline.js
Added more specific commands for testing in the contribution guide section of the docs.
As mentioned by Tobias in [#eufemia-web-team](https://dnb-it.slack.com/archives/G01RK37BMR8/p1642764388006000).
=> docs: more specific testing commands in contribution guide

packages/dnb-eufemia/src/components/tag/__tests__/Tag.test.tsx
Removes "Tag group required"-messages from tests.
Example of what's removed:
=> fix(Tag): remove tag group warnings in tests

packages/dnb-design-system-portal/src/shared/tags/Tabbar.js
With approval from UX, this PR removes the space below tabs. This is okay since every tab content has a title with enough spacing.
=> docs: remove double spacing below tabs

packages/dnb-design-system-portal/src/shared/menu/SearchBar.js, packages/dnb-eufemia/src/fragments/drawer-list/DrawerListProvider.js, packages/dnb-eufemia/src/fragments/drawer-list/__tests__/DrawerList.test.js
This PR ensures the DrawerList will "reset" global attributes is has set during its open event.
=> fix(DrawerList): ensure DrawerList is unsetting its global attributes on unmount

packages/dnb-design-system-portal/src/docs/uilib/elements/code.md, packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap, packages/dnb-eufemia/src/style/elements/code.scss
This PR fixes both some outdated docs about the font usage and ensures there will be a scroll-bar when not enough space is left to show the content inside the `<code>` element.
=> fix syntax highlighting

packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js, packages/dnb-eufemia/src/shared/__tests__/helpers.test.js, packages/dnb-eufemia/src/shared/helpers.js
=> chore: make Eufemia "warn" console log better recognizable

.github/workflows/verify.yml, package.json, packages/dnb-design-system-portal/cypress/plugins/index.js, packages/dnb-design-system-portal/gatsby-node.js, packages/dnb-design-system-portal/package.json, packages/dnb-design-system-portal/scripts/deploy.js, packages/dnb-design-system-portal/scripts/version.js, packages/dnb-design-system-portal/src/core/PortalStylesAndProviders.js, packages/dnb-design-system-portal/src/uilib/search/searchHelpers.js, packages/dnb-eufemia/package.json, packages/dnb-eufemia/scripts/prepub/commitToBranch.js, tools/repo-utils/node-utils.js, tools/repo-utils/node-utils.test.js, tools/repo-utils/package.json, yarn.lock
This PR fixes a GitHub Actions change, where they lately changes the CI env variable from being a boolean to a string. This is not based on research, but from own tests.
We change with this PR to our own check.
=> chore(repo-utils): add repo-utils to check CI instead of external dependency

packages/dnb-eufemia/src/components/step-indicator/StepIndicatorTriggerButton.js, packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.js.snap, packages/dnb-eufemia/src/shared/AnimateHeight.js, packages/dnb-eufemia/src/shared/__tests__/AnimateHeight.test.js
This PR fixes an issue as described like so:
> The findings where that Chromium loads and runs the the JS earlier than the styles. So the button has initially 33px (no styling) and changes almost frame by frame down to 27px during the rendering phase, before the styles pops in place – but that was too late, much later than the didMount event, so the component did use and set the lower height.
The fix is basically, that we ensure, the element gets an of `height: auto` when the from/to are the same values. This way, we let chrome do its thing, but only care about animation, when the values are not equal.
=> fix(StepIndicator): fix height animation issue when CSS is loaded too slow

packages/dnb-eufemia/src/components/avatar/Avatar.tsx, packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx, packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx, packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx, packages/dnb-eufemia/src/components/info-card/InfoCard.tsx, packages/dnb-eufemia/src/components/tag/TagGroup.tsx, packages/dnb-eufemia/src/components/timeline/Timeline.tsx, packages/dnb-eufemia/src/components/timeline/TimelineItem.tsx
This PR changes our new components to use ES6-functions. We tend to add new components based on these files, so we might apply them now if we want to keep it this way.
This might just be a personal preference, 
so please feel free to decline this PR.
=> chore: es6 functions in new components

packages/dnb-design-system-portal/src/docs/contribute/getting-started.md, packages/dnb-eufemia/src/components/avatar/Avatar.tsx, packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx, packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx, packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx, packages/dnb-eufemia/src/components/button/Button.d.ts, packages/dnb-eufemia/src/components/info-card/InfoCard.tsx, packages/dnb-eufemia/src/components/tag/Tag.tsx, packages/dnb-eufemia/src/components/tag/TagGroup.tsx, packages/dnb-eufemia/src/components/timeline/Timeline.tsx, packages/dnb-eufemia/src/components/timeline/TimelineItem.tsx, packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js, packages/dnb-eufemia/src/shared/hooks/__tests__/usePropsWithContext.test.ts, packages/dnb-eufemia/src/shared/hooks/index.ts, packages/dnb-eufemia/src/shared/hooks/usePropsWithContext.ts
This PR is all about better TS support.
The new hook `usePropsWithContext` replaces `extendPropsWithContext` and returns the type given as the first property. This ensures the new object returned functions with the wanted type. 
As an example, the `Tag.tsx ` did use a not typed variant of unstyled – it was valid because we got back `any`.
EDIT: This PR relies on PR #1235
=> feat: add usePropsWithContext hook for hook based components

.yarnrc.yml, packages/dnb-design-system-portal/package.json, yarn.lock
Gatsby Cloud now supports Yarn v2 (and with that, it should support v3 as well)
Based on this feedback: https://gatsby.canny.io/gatsby-cloud/p/support-yarn-2-and-pnp-api
Background:
Because Gatsby Cloud did run its own install command, with with flags, which got removed in yarn v2 and v3 - so the install command could not get executed.
To overcome this, I created a plugin, that removed all install flags. But with this PR we remove this plugin.
=> chore: remove yarn-plugin-ignore-install-options

packages/dnb-design-system-portal/package.json, packages/dnb-design-system-portal/tsconfig.json, packages/dnb-eufemia/src/style/stylis.d.ts, packages/dnb-eufemia/tsconfig.json, yarn.lock
Also remove unneeded tsconfig settings, like:
- Creating declaration files
- Creating source maps
Just because we only use tsc with --noEmit
=> fix: add type definitions to stylis plugin

packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx, packages/dnb-eufemia/src/components/avatar/__tests__/Avatar.test.tsx
Reason for wanting to change from string to React.ReactNode is because we often pass in translations in pm-netbank, like `<FormattedMessage>`, etc.
=> fix: label of avatar group to be react node

packages/dnb-eufemia/src/components/tag/TagGroup.tsx, packages/dnb-eufemia/src/components/tag/__tests__/Tag.test.tsx
Reason for wanting to change from string to React.ReactNode is because we often pass in translations in pm-netbank, like `<FormattedMessage>`, etc.
=> fix: label of tag group to be react node

packages/dnb-eufemia/src/components/info-card/InfoCard.tsx, packages/dnb-eufemia/src/components/info-card/__tests__/InfoCard.test.tsx
Reason for wanting to change from string to React.ReactNode is because we often pass in translations in pm-netbank, like `<FormattedMessage>`, etc.
=> fix(InfoCard): change text props to React.ReactNode

packages/dnb-design-system-portal/src/docs/uilib/components/section/properties.md
Looks like `signal-orange` is a deprecated `style_type` for `Section`.
=> docs: remove signal-orange from Section

packages/dnb-design-system-portal/src/docs/uilib/components/fragments.md, packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.js
This commit fixes an issue where automatic ordering gets messed up. By using the same logic as before, it works fine after increasing the increment starting number.
Also, I think fragments can still be at the bottom. Any thoughts on that?
=> docs: fix menu order in side-menu

.drone.yml, packages/dnb-design-system-portal/gatsby-node.js, packages/dnb-design-system-portal/package.json, packages/dnb-design-system-portal/scripts/deploy.js, packages/dnb-design-system-portal/scripts/version.js, packages/dnb-design-system-portal/src/shared/parts/Layout.js, packages/dnb-eufemia/package.json, packages/dnb-eufemia/scripts/release/getNextReleaseVersion.js
closes #1060
This PR will include the release version in the footer of the portal. It will only display a version if the current branch is one of the release branches.
Else it will display `Not released` (I'm glad for better ideas there 😀)
It will look like this:
=> chore(Portal): include publish version in portal footer

.github/workflows/release.yml
This commit ensures we release first, and then deploy the portal. In case the release is not successful – we abort and can retry. Its easier to manually deploy the portal at its own via the portal branch.
=> chore(Release): switch order of portal deploy with release action

packages/dnb-design-system-portal/src/docs/uilib/components/tag/properties.md
Remove unused/unsupported `data`-prop from `TagGroup`-properties.
=> docs: remove data from TagGroup properties

.yarnrc.yml, packages/dnb-design-system-portal/package.json, yarn.lock
From the logs of this PR #1262 it looks like Gatsby has just reverted the support of yarn v3 (probably temporarily)
=> chore: revert #1237

packages/dnb-eufemia/src/components/number-format/NumberUtils.d.ts, packages/dnb-eufemia/src/components/number-format/NumberUtils.js, packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts
More details about the issue [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1643204645078400)
=> fix(NumberUtils): "replace" did not exists on IE11 

packages/dnb-design-system-portal/gatsby-browser.js, packages/dnb-design-system-portal/gatsby-node.js
Use the recommended [migration method](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#process-is-not-defined) for this Webpack 5 polyfill.
=> chore: move process polyfill to Webpack config as it is recommended

packages/dnb-eufemia/src/core/jest/jestPuppeteerEnvironment.js, packages/dnb-eufemia/src/core/jest/jestPuppeteerTeardown.js
The retry feature we lately added seems to work as expected.
But when there are re-try attempts, our jest-screenshot dependency creates a report. This report gets not removed and during the global teardown event, we then commit the reports to a new branch.
With this commit, we check put the name of a test in a cache, and remove it on success. At the end we then have hopefully an empty list, and will not commit the reports.
=> chore: enhance false-positive visual test reports

packages/dnb-eufemia/src/shared/component-helper.js
Fixes a reported issue that appears after Modal is closed.
[CSB](https://codesandbox.io/s/eufemia-modal-ie11-bug-r8upy?file=/src/App.tsx) to test the PR version on.
Edit: Here's a [deploy](https://tujoworker.github.io/csb-wj4vx/) to test in IE11
=> fix(Modal): make revalidation after Modal close work on IE11

packages/dnb-eufemia/src/components/modal/ModalContent.tsx, packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx
This omits the modal root from getting
aria-hidden="true" added to it, which
removes the modal from the accessibility tree
The modal root component got `aria-hidden="true"` added to it when opening the dialog, rendering the content inside not accessible in the accessibility tree.
This adds additional ignore of the modal root component in the `aria-hidden` handler logic.
I added a new test, for checking that a button outside still gets `aria-hidden="true"`, and the modal root no longer get it. However I could not get the test to work, I tried both using `document.querySelector` and `Comp.find` as seen in the tried test. As well as with and without the `{attachTo: attachToBody()}` option.
I have verified the described effect/change in Storybook, as well as when using it as a component in …
=> Fix dialog being omitted in accessability tree

packages/dnb-eufemia/src/components/progress-indicator/__tests__/__snapshots__/ProgressIndicator.test.js.snap, packages/dnb-eufemia/src/components/progress-indicator/style/themes/dnb-progress-indicator-theme-ui.scss
There is an aliasing artifact (checked on both FF and chrome) when 2 same sized svg shapes are drawn on top of one another, it's not really visible when drawing 'dark on light', but it's more so when 'light on dark'. This is somewhat of a quickfix (slightly hacky?). So there's probably a more "proper" solution by not overlapping shapes/paths of similar size, animating both the increasing light shape but also the decreasing dark shape?
I think loading indicators are some of the first things users will notice on any element / page that requires loading, and they are usually the "only thing on the page" surrounded by whitespace, and if it looks "cheap" like bucket fill in ms-paint with 'edge aliasing artifacts', then that probably leaves a negative impression :)
image below should show the …
=> fix: css change to fix aliasing artifacts for ProgressIndicator

packages/dnb-eufemia/src/shared/hooks/__tests__/usePropsWithContext.test.ts, packages/dnb-eufemia/src/shared/hooks/usePropsWithContext.ts
While default props are listed, with functional components and TS we do not need to list all anymore just to ensure that we use the context. So with this PR we use the context as long as the prop is not set.
=> fix(Internal): ensure usePropsWithContext will use context regardless

packages/dnb-design-system-portal/src/docs/contribute/getting-started.md, packages/dnb-eufemia/src/components/avatar/Avatar.tsx, packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx, packages/dnb-eufemia/src/components/info-card/InfoCard.tsx, packages/dnb-eufemia/src/components/tag/Tag.tsx
Not sure if this is something that makes things better, but at least, we do not need them anymore.
=> chore: remove unused defaults props with null as value

packages/dnb-design-system-portal/src/docs/uilib/components/avatar/properties.md, packages/dnb-eufemia/src/components/avatar/Avatar.tsx, packages/dnb-eufemia/src/components/avatar/__tests__/Avatar.test.tsx, packages/dnb-eufemia/src/components/avatar/stories/Avatar.stories.tsx
Did the same for Avatar as we did in [Tag](https://github.com/dnbexperience/eufemia/pull/1314).
=> feat(Avatar): add hasLabel to omit non-existing avatar group warning

packages/dnb-design-system-portal/src/shared/menu/Card.js, packages/dnb-design-system-portal/src/shared/menu/MainMenu.js
Fixed semantic portal menu
- Remove `button`-tags within `a`-tags (menu links).
- Moved `<H1>`-title to be a direct child of `<main>`-tag.
- Used `ul` instead of `section` in the `nav`-tag with `li`-elements.
=> fix(Portal): semantic and accesible menu

packages/dnb-eufemia/src/components/pagination/PaginationBar.tsx, packages/dnb-eufemia/src/components/pagination/PaginationCalculation.ts, packages/dnb-eufemia/src/components/pagination/__tests__/Pagination.test.js, packages/dnb-eufemia/src/components/pagination/__tests__/PaginationCalculation.test.ts, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap
During jest test runs after merge of #1322 I saw React key warnings. The reason was that page_count was undefined in some tests. This PR will ensure we do not return `[[ 1 ], [], [ undefined]]` – but rather `[[1]]` – will this be correct @dinarosv ?
=> fix(Pagination): handle unknown / undefined page_count

packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap, packages/dnb-eufemia/src/components/modal/stories/Modal.stories.tsx, packages/dnb-eufemia/src/components/modal/style/_modal.scss
This had the same cause as the previous reported issue with containerplacement left, where the default alignment was different for mode drawer in the original version. Hope and think this will fix the reported issue with the background too
=> fix(Modal): containerPlacement bug for top

.github/workflows/build-check.yml, .github/workflows/icons-lib.yml, .github/workflows/release.yml, .github/workflows/verify.yml, .github/workflows/visual-test.yml
With this fix, we can quickly invalidate all caches by changing the ENV in GitHub env settings. This is because, there is no way to invalidate the GitHub Actions cache. So this is a recommended solution.
Its only meant to use for special cases. Until now, we never did really need that. But when we need it, we need to do it quickly (most probably).
=> chore(CI): add CACHE_VERSION to invalidate GitHub Actions cache

packages/dnb-eufemia/src/components/tag/Tag.tsx, packages/dnb-eufemia/src/components/tag/__tests__/Tag.test.tsx
Allow Tag to inherit skeleton prop from context.
=> fix(Tag): Allow Tag to get skeleton prop from context

packages/dnb-design-system-portal/src/templates/mdx.js
Suffixed page titles with "| Eufemia" in the portal.
This is just a suggested change of common practice on how page titles should be.
It makes it easier to find and search through logs etc.
Used pipe instead of dash since [DNB.no](https://www.dnb.no/forside-ung) uses this pattern as well.
Feel free to ignore this PR if this is not what we want.
=> feat(Portal): Suffix page titles with "| Eufemia"

packages/dnb-eufemia/src/style/core/properties.scss, packages/dnb-eufemia/src/style/elements/typography.scss, packages/dnb-eufemia/src/style/themes/theme-eiendom/dnb-theme-eiendom.scss
By checking if an existing `@mixin` exists, we can insert custom styles and properties by defining this customization `@mixin` with custom css styles.
With this PR, all headings to use DNBMono in medium weight. Just as a POC.
=> fix(Theming): simplify the theming logic

packages/dnb-design-system-portal/src/docs/uilib/components/tag/demos.md
Fixes the following warning from the browsers console:
```
Eufemia Heading levels can only be changed by factor one! Got: 3 and had before 1 - The new level is 2 
NB: This warning was triggered by:  #
```
=> docs(Tag): Change heading levels by only one factor

packages/dnb-design-system-portal/src/docs/uilib/components/visually-hidden/demos.md
Fixes the following warning from the browsers console when running locally:
```
Eufemia Heading levels can only be changed by factor one! Got: 4 and had before 2 - The new level is 3 
NB: This warning was triggered by:  #
```
=> docs(VisuallyHidden): Change heading levels by only one factor

packages/dnb-design-system-portal/gatsby-config.js, packages/dnb-design-system-portal/gatsby-node.js, packages/dnb-design-system-portal/src/core/ChangeStyleTheme.js, packages/dnb-design-system-portal/src/core/PortalStylesAndProviders.js, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming.md, packages/dnb-design-system-portal/src/shared/menu/PortalToolsMenu.js, packages/dnb-eufemia/.gitignore, packages/dnb-eufemia/index.js, packages/gatsby-plugin-eufemia-theme-handler/.gitignore, packages/gatsby-plugin-eufemia-theme-handler/LICENSE, packages/gatsby-plugin-eufemia-theme-handler/README.md, packages/gatsby-plugin-eufemia-theme-handler/collectThemes.js, packages/gatsby-plugin-eufemia-theme-handler/gatsby-browser.js, packages/gatsby-plugin-eufemia-theme-handler/gatsby-node.js, packages/gatsby-plugin-eufemia-theme-handler/gatsby-ssr.js, packages/gatsby-plugin-eufemia-theme-handler/index.js, packages/gatsby-plugin-eufemia-theme-handler/inlineScriptDev.js, packages/gatsby-plugin-eufemia-theme-handler/inlineScriptProd.js, packages/gatsby-plugin-eufemia-theme-handler/package.json, packages/gatsby-plugin-eufemia-theme-handler/themeHandler.js, yarn.lock
This PR changes how the portal imports theme styles. Everything is handled via Webpack, where we split out theme CSS files into separate packages and load them as soon as the user selects a different theme. But all logic is separated in a Gatsby Plugin.
Using a different theme is possible today already. This PR is all about letting the user or the app change a theme. 
This solution does not lower the LH score 👍
Future tasks
- This Gatsby plugin can easily be used by applications as well. We may a release of that NPM package.
- Create visual tests for other brand themes. It should be pretty straight forward, as we now can load a certain theme CSS via `https://eufemia.dnb.no/?dnb-theme=ui`
Only Eufemia Portal related; What should we call the default Eufemia DNB theme? In code its called …
=> feat(Theme): create theme handler Gatsby Plugin

packages/dnb-design-system-portal/src/docs/uilib/components/tag/properties.md, packages/dnb-eufemia/src/components/tag/TagGroup.tsx, packages/dnb-eufemia/src/components/tag/__tests__/Tag.test.tsx
This PR just adds the property and type for skeleton to the Tag.Group, so that it will be easier/possible to use the component with the skeleton prop. The functionality is/was already in place, take a look at https://eufemia.dnb.no/uilib/components/tag and add the skeleton property to one of the demos/examples.
```
<Tag.Group skeleton label="tags">
<Tag />
</Tag.Group>
```
=> fix(Tag): Allow Tag.Group to set skeleton prop

packages/dnb-design-system-portal/src/docs/uilib/components/avatar/properties.md, packages/dnb-eufemia/src/components/avatar/Avatar.tsx, packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx, packages/dnb-eufemia/src/components/avatar/__tests__/Avatar.test.tsx
This PR just adds the property and type for skeleton to the Avatar.Group, so that it will be easier/possible to use the component with the skeleton prop. The functionality is/was already in place, take a look at https://eufemia.dnb.no/uilib/components/avatar and add the skeleton property to one of the demos/examples.
```
<Avatar.Group skeleton label="label">
<Avatar>A</Avatar>
</Avatar.Group>
```
=> fix(Avatar): Allow Avatar.Group to set skeleton prop

packages/dnb-design-system-portal/src/docs/uilib/elements/anchor.md, packages/dnb-design-system-portal/src/docs/uilib/elements/blockquote.md, packages/dnb-design-system-portal/src/docs/uilib/elements/code.md, packages/dnb-design-system-portal/src/docs/uilib/elements/horizontal-rule.md, packages/dnb-design-system-portal/src/docs/uilib/elements/image.md, packages/dnb-design-system-portal/src/docs/uilib/elements/lists.md, packages/dnb-design-system-portal/src/docs/uilib/elements/not-supported.md, packages/dnb-design-system-portal/src/docs/uilib/elements/tables.md, packages/dnb-design-system-portal/src/docs/uilib/elements/unstyled.md
Fixes the following warning from the browsers console when running locally:
```
Eufemia Can not decrease to heading level 1! Had before 2 - The new level is 2 
NB: This warning was triggered by:  #
```
=> docs(HTML Elements): Improve heading levels

packages/dnb-design-system-portal/src/shared/parts/ListSummaryFromPages.js
Fixes the following warning from the browsers console when running locally:
```
Eufemia Can not decrease to heading level 1! Had before 2 - The new level is 2 
NB: This warning was triggered by:  #
```
=> docs: improve headers in list summary from pages

packages/dnb-design-system-portal/src/docs/uilib/components/visually-hidden/properties.md, packages/dnb-eufemia/src/components/visually-hidden/VisuallyHidden.tsx, packages/dnb-eufemia/src/components/visually-hidden/__tests__/VisuallyHidden.test.tsx, packages/dnb-eufemia/src/shared/__tests__/helpers.test.js, packages/dnb-eufemia/src/shared/helpers.js
I think, because `VisuallyHidden` will mostly be used for text messages primarily, we should use span as the default element. Typically when used inside a paragraph, we have to use a span, and not a div. Now, it also can be used inside a heading too.
=> fix(VisuallyHidden): use span as default element so it can be used inside paragraphs

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/button/Button.js, packages/dnb-eufemia/src/components/button/__tests__/Button.test.js, packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.js.snap, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/global-error/__tests__/__snapshots__/GlobalError.test.js.snap, packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.js.snap, packages/dnb-eufemia/src/components/help-button/__tests__/__snapshots__/HelpButton.test.js.snap, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.js.snap, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/InputPassword.test.js.snap, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap, packages/dnb-eufemia/src/components/skeleton/figures/Article.js, packages/dnb-eufemia/src/components/skeleton/figures/Circle.js, packages/dnb-eufemia/src/components/skeleton/figures/Product.js, packages/dnb-eufemia/src/components/skeleton/figures/Table.js, packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.js.snap, packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.js.snap, packages/dnb-eufemia/src/components/tabs/__tests__/__snapshots__/Tabs.test.js.snap, packages/dnb-eufemia/src/components/timeline/TimelineItem.tsx, packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.js.snap, packages/dnb-eufemia/src/shared/AlignmentHelper.js
As this alignment helper only is of visual interest, we want it to hide from the accessibility tree. NVDA & Firefox did report it. None of the other screen reader & browsers did. But we should anyway remove it.
=> fix: remove alignment helper from a11y tree

packages/dnb-design-system-portal/src/docs/uilib/elements.md, packages/dnb-design-system-portal/src/docs/uilib/elements/not-supported.md, packages/dnb-design-system-portal/src/docs/uilib/elements/unstyled.md
This PR removes docs for the specific html elements from the html elements overview doc, as the elements are already linked to in the docs, and have their own doc/page.
In my opinion, this will make the html elements overview doc a bit cleaner, as it has quite a lot of text [today](https://eufemia.dnb.no/uilib/elements), scroll scroll 📜
=> docs(HTML Elements): Removes docs for elements in HTML elements overview docs

packages/dnb-design-system-portal/src/shared/menu/Card.js
Removes the list bullet visual appearing in Card in the portal.
See the bug here:
=> docs: hide visual <li> bullet appearing in card

packages/dnb-eufemia/scripts/prebuild/commitToBranch.js
After the security update of simple-git to its latest version, we get this warning during  visual test runs:
```bash
simple-git has supported promises / async await since version 2.6.0.
Importing from 'simple-git/promise' has been deprecated and will be
removed by July 2022.
```
This PR makes this requested change.
=> chore: remove /promise from simple-git import

packages/dnb-eufemia/src/components/skeleton/Skeleton.d.ts, packages/dnb-eufemia/src/components/skeleton/Skeleton.js
Fixes the following warning when running `yarn build:types`:
```
✖ The property "aria_busy" is not defined in PropTypes!
Component: Skeleton
File: ./src/components/skeleton/Skeleton.js
✖ The property "aria_ready" is not defined in PropTypes!
Component: Skeleton
File: ./src/components/skeleton/Skeleton.js
```
=> fix(Skeleton): Missing properties in PropTypes

packages/dnb-eufemia/package.json, yarn.lock
Until we actually support v18 of React – we need to declare its peer dependency to v17 as of now.
=> fix: declare v17 as Eufemias peer dependency

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.js.snap, packages/dnb-eufemia/src/fragments/drawer-list/DrawerListProvider.js, packages/dnb-eufemia/src/fragments/drawer-list/__tests__/__snapshots__/DrawerList.test.js.snap
Fixes the following warning when running `yarn build:types`:
```
✖ The property "enable_body_lock" is not defined in PropTypes!
Component: Autocomplete
File: ./src/components/autocomplete/Autocomplete.js
✖ The property "min_height" is not defined in PropTypes!
Component: Autocomplete
File: ./src/components/autocomplete/Autocomplete.js
✖ The property "page_offset" is not defined in PropTypes!
Component: Autocomplete
File: ./src/components/autocomplete/Autocomplete.js
✖ The property "observer_element" is not defined in PropTypes!
Component: Autocomplete
File: ./src/components/autocomplete/Autocomplete.js
```
=> fix(Autocomplete): Missing properties in PropTypes

packages/dnb-eufemia/src/core/jest/jestSetup.js
Just a suggestion, as we are not supposed to "shallow test".
_Do not shallow test, but test components like a user would interact (use mount or render to also test their children)._ - https://eufemia.dnb.no/uilib/usage/best-practices/for-testing#integration-tests
=> chore: unexposes enzyme's shallow

yarn.lock
Fixes the following warning when running `yarn lint`:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
=> chore: updates caniuse-lite

packages/dnb-design-system-portal/src/shared/menu/PortalToolsMenu.js, packages/dnb-eufemia/src/components/help-button/HelpButtonInstance.js, packages/dnb-eufemia/src/components/help-button/__tests__/HelpButton.test.js
This PR fixes an issue where the internally used `HelpButton`, via a Modal/Drawer/Dialog did not get a aria-label - when used with icon only.
We also update the usage of the same in the Portal.
=> fix(HelpButton): ensure Drawer/Dialog/Modal trigger button gets a label

CONTRIBUTING.md, README.md, packages/dnb-design-system-portal/src/docs/contribute.md
Instead of navigating to https://eufemia.dnb.no/uilib/development which redirects to https://eufemia.dnb.no/contribute, this PR just navigates directly to https://eufemia.dnb.no/contribute
=> docs: navigate to /contribute instead of /uilib/development

packages/dnb-eufemia/src/components/button/Button.d.ts, packages/dnb-eufemia/src/components/modal/parts/CloseButton.tsx, packages/dnb-eufemia/src/components/modal/stories/Modal.stories.tsx, packages/dnb-eufemia/src/components/modal/types.ts, packages/dnb-eufemia/src/shared/interfaces.tsx
This PR fixes issues like this:
It should be possible to extend it like this:
```tsx
declare module 'react' {
interface HTMLAttributes<T> extends React.HTMLAttributes<T> {
[property: `data-${string}`]: string
}
}
```
While `tsc --noEmit` does work fine, VSCode does not like it. 
Therefore, we create a custom type `DataPropTypes` and extend `triggerAttributes` and `closeButtonAttributes` with it.
```tsx
[property: `data-${string}`]: string
```
This 👆 is supported after TS v4.4 via [Symbol and Template String Pattern Index Signatures](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#symbol-and-template-string-pattern-index-signatures)
=> fix(Modal): fix data-testid usage in object defined props

packages/dnb-eufemia/src/components/avatar/Avatar.tsx, packages/dnb-eufemia/src/components/avatar/__tests__/Avatar.test.tsx, packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx, packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx, packages/dnb-eufemia/src/components/info-card/__tests__/InfoCard.test.tsx, packages/dnb-eufemia/src/components/tag/Tag.tsx, packages/dnb-eufemia/src/components/tag/__tests__/Tag.test.tsx, packages/dnb-eufemia/src/components/timeline/Timeline.tsx, packages/dnb-eufemia/src/components/timeline/__tests__/Timeline.test.tsx
Some components did not "remove" the spacing props when set. They just got added as HTML attributes. But when e.g. `space={{ }}` or `top={true}` was used, React throws an error warning. 
With that PR we add some tests to verify the feature.
=> Remove invalid spacing attributes

packages/dnb-eufemia/src/shared/AnimateHeight.js, packages/dnb-eufemia/src/shared/__tests__/AnimateHeight.test.js
This PR fixes an issue when animating from `auto` (open) to `0px` (closed) – but the user triggers the animation one more time (while the animation is running), we started again from `0px`, which lead to a "flicker".
Effects:
- Accordion
- GlobalStatus
- FormStatus
- StepIndicator
- Soon Table (responsive)
**Fix**
https://user-images.githubusercontent.com/1501870/172583539-2d6b27cf-8f81-480f-a355-e0e32decb22a.mov
**Current**
https://user-images.githubusercontent.com/1501870/172583627-8c0a8bd5-b09e-4e8a-8009-3a655da21e55.mov
=> fix(HeightAnimation): ensure quick state changes to react without animating from start to finish

packages/dnb-design-system-portal/src/shared/tags/CodeBlock.js
This PR will fix the diff we have between SSR and browser rendered code syntax wrapping behavior.
We use `react-live` and they use `pre-wrap` so code syntax gets wrapped to a newline, when space is missing.
but during SSR, their styles get not applied in v3 (we should maybe also fix that and make a PR – when we have time).
But more important, we "could change how we like to have it. Because its very normal to just show a scrollbar instead.
I personally like better the wrapping for our use case (dirty code snippets/examples).
But the reason why I like that better, is because when we have "long text" in the examples, they add a really long scrollbar.
But the question is still; **Should we change the behavior and use a scrollbar?** (in contrast what `react-live` sets as their default). …
=> chore(Portal): get SSR consistent code syntax (highlighting) wrapping behaviour

.github/workflows/icons-lib.yml, .github/workflows/visual-test.yml, packages/dnb-design-system-portal/gatsby-config.js, packages/dnb-design-system-portal/package.json, packages/dnb-design-system-portal/src/docs/contribute/faq.md, packages/dnb-eufemia/src/core/jest/jestPuppeteerSetup.js
Omit image processing when creating a build for visual tests.
This step takes several minutes: `Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 345.638s` but we do not test images (I think).
=> chore(CI): speed up build time when making build for visual tests

.github/workflows/visual-test.yml
We can "possible" break visual tests because do not force branches to be rebased from main (up to date) before merge. 
We may try – for a while – to have run them on the `main` branch. And if they fail, we may press the button to re-run. Even, they should work ok, as they to "re-run" each test up to a couple of times, if they fail.
=> chore(CI): run visual tests on main branch

.github/workflows/visual-test.yml, packages/dnb-design-system-portal/package.json
I have hopes that this can at least shape off some minutes.
With this PR we build the portal on Linux and test with macOS. 
What is the reason behind this? macOS is very much slower in Github Actions, so we now use it for the only one reason – testing visually.
=> chore(CI): refactor visual test run

packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/modal/ModalContent.tsx, packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap
Reported by @sivran via Slack:
> Could we ignore the onMouseUp event when releasing the mouse outside the modal?
It’s an issue when e.g. selecting text inside an input field and releasing the mouse outside the modal by accident.
https://user-images.githubusercontent.com/1501870/173918168-63f2125a-d0f6-475a-9c42-b63093bfc901.mov
=> fix(Dialog): fix Modal backdrop / overlay false-positive click issue while e.g. selecting

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.js.snap, packages/dnb-eufemia/src/components/input/style/_input.scss
This change should not influence Firefox or Chromium based browser, but enhance Safari (Webkit based browsers).
It fixes an issue occurred in PR #1467
=> fix(Input): enhance vertical centering for Safari 

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.md, packages/dnb-design-system-portal/src/docs/uilib/components/timeline/Examples.js, packages/dnb-design-system-portal/src/docs/uilib/components/timeline/info.md, packages/dnb-design-system-portal/src/docs/uilib/components/timeline/properties.md, packages/dnb-eufemia/src/components/timeline/TimelineItem.tsx, packages/dnb-eufemia/src/components/timeline/__tests__/Timeline.test.tsx, packages/dnb-eufemia/src/components/timeline/__tests__/__snapshots__/Timeline.test.tsx.snap, packages/dnb-eufemia/src/components/timeline/style/_timeline.scss, packages/dnb-eufemia/src/components/timeline/style/themes/dnb-timeline-theme-ui.scss
Rename name/dare-props in`Timeline`-component:
- `name` is changed to `title` in TimelineItem
- `date` is changed to `subtitle` in TimelineItem
=> feat(Timeline): rename name to title & date to subtitle with backwards compatibility

packages/dnb-eufemia/src/components/date-picker/DatePickerInput.js, packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.js
Adding an id prop to the DatePicker component breaks incrementing / decrementing the date inputs using the arrow keys.
Thanks @sivran for reporting 🙏
[Re-prod](https://codesandbox.io/s/smoosh-water-o94piq?file=/src/App.tsx)
The fix:
```diff
- .match(/[0-9]-([start|end]+)-/)[1]
+ .match(/-([start|end]+)-/)[1]
```
We also wrap this whole code block in a try catch because it contains DOM interaction.
=> fix(DatePicker): make keyboard usage in input not throw

packages/dnb-design-system-portal/src/docs/uilib/components/avatar.md, packages/dnb-design-system-portal/src/docs/uilib/components/breadcrumb.md, packages/dnb-design-system-portal/src/docs/uilib/components/info-card.md, packages/dnb-design-system-portal/src/docs/uilib/components/tag.md, packages/dnb-design-system-portal/src/docs/uilib/components/timeline.md
Removed '`new`' status for components older than 6 months, including 
`InfoCard`, `Avatar`, `Breadcrumb`, `Timeline`, `Tag`.
=> docs: Remove 'new' status for components older than 6 months

packages/dnb-eufemia/src/components/timeline/TimelineItem.tsx
Added stretch to `FormStatus` used as `infoMessage`  in `TimelineItem` to match the design.
From [Figma](https://www.figma.com/file/cdtwQD8IJ7pTeE45U148r1/Eufemia---Web?node-id=19553%3A7463):
=> feat(Timeline): add fullwidth to info message

packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/colors.md
This PR fixes the following "example usage" in colors docs.
https://eufemia.dnb.no/uilib/usage/customisation/colors/#example-usage
=> docs: fix example usage of color docs

packages/dnb-design-system-portal/src/docs/uilib/usage/best-practices/for-javascript.md
This PR fixes a dead link to "Where to put React State" chart.
See "this chart" link here: https://eufemia.dnb.no/uilib/usage/best-practices/for-javascript/#handling-of-react-state
=> docs: fix link to React State chart

packages/dnb-eufemia/src/shared/helpers/__tests__/withCamelCaseProps.test.tsx, packages/dnb-eufemia/src/shared/helpers/withCamelCaseProps.tsx
This PR fixes an issue where components, supporting temporary snake_case and camelCase props would run componentDidMount twice, given they are a class component (effects for now only Modal).
=> fix(Internal): avoid running componentDidMount twice

packages/dnb-eufemia/src/components/dialog/__tests__/Dialog.test.tsx, packages/dnb-eufemia/src/components/drawer/DrawerContent.tsx, packages/dnb-eufemia/src/components/drawer/__tests__/Drawer.test.tsx, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx
The Drawer component had a missing ref property (`ref={context?.scrollRef}`), so the body scroll lock did not work. The added tests do verify this now.
=> fix(Drawer): ensure it removes scroll possibility when opened

packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.js, packages/dnb-design-system-portal/src/shared/parts/Layout.js
How is was on a page reload or first visit with scrull url:
The the left sidebar/white column is now gone with this PR.
=> chore(Portal): ensure fullscreen on page reload or first visit with fullscreen url

packages/dnb-design-system-portal/src/docs/contribute/getting-started.md, packages/dnb-eufemia/src/components/form-row/FormRow.js, packages/dnb-eufemia/src/components/form-row/FormRowHelpers.tsx, packages/dnb-eufemia/src/components/slider/Slider.tsx, packages/dnb-eufemia/src/shared/Context.tsx, packages/dnb-eufemia/src/shared/helpers/__tests__/filterValidProps.test.tsx, packages/dnb-eufemia/src/shared/helpers/filterValidProps.tsx
- Fix failing screenshot/visual test
- Make Slider support FormRow again
- Write docs about how
- Add filterValidProps helper function (for "internal" usage as of now)
- Add includeValidProps to FormRow
=> chore(Slider): add back support for FormRow

packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/dialog/style/themes/dnb-dialog-theme-ui.scss, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/stories/Drawer.stories.tsx, packages/dnb-eufemia/src/components/drawer/style/_drawer.scss, packages/dnb-eufemia/src/components/drawer/style/themes/dnb-drawer-theme-ui.scss, packages/dnb-eufemia/src/components/modal/ModalContent.tsx, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap, packages/dnb-eufemia/src/components/modal/style/_modal.scss, packages/dnb-eufemia/src/components/modal/style/themes/dnb-modal-theme-ui.scss
Reported in this [thread](https://dnb-it.slack.com/archives/CMXABCHEY/p1660052015576469).
There was a pseudo-element that cause in Safari Desktop a wired scroll effect when selecting text and dragging the mouse to the right side. That pseudo-element seems to not be used, as there where not other visible styles attached to it (whooot? yes 🫣) so we remove it for now. It may be some helper for scrolling or something. But it should then be declared as so.
=> fix(Drawer): fix Safari text selection + drag/scroll issue

packages/dnb-eufemia/src/shared/helpers/__tests__/withSnakeCaseProps.test.tsx, packages/dnb-eufemia/src/shared/helpers/withSnakeCaseProps.tsx
This can be used to re-write components to camelCase, but provide snake_case backwards compatibility.
=> chore(withSnakeCaseProps): add camelCase to snake_case converter

packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/style/_drawer.scss, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap, packages/dnb-eufemia/src/components/modal/style/_modal.scss
Reported [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1661162150422519?thread_ts=1660052015.576469&cid=CMXABCHEY) 🐛
Here is a [demo build](https://eufemia-fixdrawerstickyheader.gtsb.io/uilib/components/drawer/demos/#drawer-with-custom-content).
It only happens in Safari Desktop (v15). And its a Safari bug. But this PR provides a fix for it.
When scrolling down, and selecting text from left to right, the content of the drawer, moves to the left.
The shadow of the header bar, which is again in a pseudo-element, makes the content moving to the left. If we remove the `overflow: hidden` also a Safari scroll-bar (horizontal) will show up.
We can avoid that the pseudo-element is placed "outside of the view" to the right, and use rather a negative margin with a padding to get the correct …
=> fix(Drawer): fix possible Safari selection causing selection scroll (horizontal) issue

packages/dnb-eufemia/src/components/slider/SliderThumb.tsx, packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx, packages/dnb-eufemia/src/components/slider/hooks/useSliderEvents.tsx, packages/dnb-eufemia/src/components/slider/types.ts
When pressing a second time on a thumb, after it has changed position, the internal index was not updated.
Bug:
https://user-images.githubusercontent.com/1501870/186253079-4fae245f-430d-411a-b1bb-bc9610dc196a.mov
Fix:
https://user-images.githubusercontent.com/1501870/186253105-4df1e666-33f8-48de-8198-73955c2a9dc9.mov
=> fix(Slider): (multi-thumbs) ensure correct index is set when thumb positions switches

packages/dnb-eufemia/src/components/slider/SliderProvider.tsx, packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx
To verify this, a test both for single number and multi numbers is added.
=> fix(Slider): prevent onChange being called with same value

packages/dnb-eufemia/src/components/slider/SliderHelpers.tsx, packages/dnb-eufemia/src/components/slider/SliderInstance.tsx, packages/dnb-eufemia/src/components/slider/SliderProvider.tsx, packages/dnb-eufemia/src/components/slider/SliderThumb.tsx, packages/dnb-eufemia/src/components/slider/SliderTrack.tsx, packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.tsx.snap, packages/dnb-eufemia/src/components/slider/hooks/useSliderEvents.tsx, packages/dnb-eufemia/src/components/slider/stories/Slider.stories.tsx, packages/dnb-eufemia/src/components/slider/style/_slider.scss
Sorry to spam with yet another Slider PR. 
This time, we remove the CSS reverse usage, because, if we want a Tooltip inlined, it gets reversed too. So now we only used numbers to reverse the behavior. Also to note, if `vertical` is true, we use actually reverse internally. So its not only for the `reverse` property. 
Here is a [CSB](https://codesandbox.io/s/eufemia-slider-reversed-xfuwmq) and a [demo to test out](https://xfuwmq.csb.app/).
=> fix(Slider): use numbers instead of css reverse when reversing slider

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.js, packages/dnb-eufemia/src/fragments/drawer-list/__tests__/DrawerList.test.js, packages/dnb-eufemia/src/fragments/drawer-list/__tests__/DrawerListTestMocks.js
Reported in this [Slack Thread](https://dnb-it.slack.com/archives/CMXABCHEY/p1656411051734679).
The not documented, and not used `min_height` inside Autocomplete, which again was forwarded to the `DrawerList`, did make the calculation to be `NaN`, so it resulted in not reacting and aligning the opening direction.
The added test do fail, when `min_height: null` is defined in the default props (like before).
The test and the mocks are 100% the same, so I think its fine to share them.
You can [click on this link](https://eufemia-fixautocompletedirectionoberse.gtsb.io/uilib/components/autocomplete/#default-autocomplete) to test it out. Simply focus the Autocomplete Input and scroll up & down.
=> fix(Autocomplete): make DrawerList direction observer work

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap, packages/dnb-eufemia/src/components/input/Input.js, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.js.snap, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/InputPassword.test.js.snap, packages/dnb-eufemia/src/components/skeleton/__tests__/__snapshots__/Skeleton.test.js.snap
It has no visual or negative effect. Just something I saw in the Autocomplete component.
=> fix(Input): ensure dnb-input--null class will not be set

packages/dnb-eufemia/src/components/pagination/Pagination.js, packages/dnb-eufemia/src/components/pagination/PaginationInfinity.js, packages/dnb-eufemia/src/components/pagination/PaginationProvider.js, packages/dnb-eufemia/src/components/pagination/__tests__/Pagination.test.js, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap
Reprod [CSB](https://codesandbox.io/s/paginationtablemarker-12fno?file=/package.json)
=> fix(PaginationInfinity): ensure the load button does not appear when current_page decreases

packages/dnb-design-system-portal/src/docs/uilib/components/tooltip/properties.md
Saw we had an example using the prop, `animate_position`, in https://eufemia.dnb.no/uilib/components/tooltip/#tooltip-with-position-animation
Thought it could be nice to add the property to the list of properties, and a small explanation of what it is.
=> docs(Tooltip): add docs for animate_position prop

packages/dnb-design-system-portal/src/docs/uilib/helpers.md, packages/dnb-design-system-portal/src/docs/uilib/helpers/Examples.js, packages/dnb-design-system-portal/src/docs/uilib/helpers/hooks.md, packages/dnb-eufemia/src/shared/AnimateHeight.js, packages/dnb-eufemia/src/shared/__tests__/useHeightAnimation.test.tsx, packages/dnb-eufemia/src/shared/useHeightAnimation.tsx
=> feat(useHeightAnimation): add hook to make height (auto) animations easy

packages/dnb-eufemia/src/shared/component-helper.js, packages/dnb-eufemia/src/shared/helpers.js, packages/dnb-eufemia/src/shared/stories/EventEmitter.stories.tsx
Just to have things clean and one directional.
This is in relation to PR #1568
=> chore(useEventEmitter): move import from "helpers" to "component-helper"

packages/dnb-design-system-portal/src/docs/uilib/components/avatar/Examples.js, packages/dnb-eufemia/src/components/avatar/__tests__/__snapshots__/Avatar.test.tsx.snap, packages/dnb-eufemia/src/components/avatar/style/themes/dnb-avatar-theme-ui.scss
Due to SVG path changes, the [card icon](https://github.com/dnbexperience/eufemia/pull/1575/files#diff-eac78f1448dd7a3bd40fe11a60945a1412cc91bc75027e8ad08aebefeec994f8) can not get colored with `fill` color anymore:
By default, the Icon component does inherit colors, so we may rather relay on that. The only thing left (with a negative result) is the Logo component. This PR #1578 will fix our tests.
=> fix(Avatar): don't overwrite SVG color

packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/events.md, packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/info.md, packages/dnb-eufemia/src/components/breadcrumb/stories/Breadcrumb.stories.tsx, packages/dnb-eufemia/src/components/height-animation/HeightAnimation.tsx, packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimation.test.tsx, packages/dnb-eufemia/src/components/height-animation/stories/HeightAnimation.stories.tsx, packages/dnb-eufemia/src/components/height-animation/style/_height-animation.scss, packages/dnb-eufemia/src/components/height-animation/useHeightAnimation.tsx, packages/dnb-eufemia/src/shared/AnimateHeight.ts
This PR is a small adjustment in order to adjust the height automatically when its opened and the content changes.
While nested content will disappear immediately (by React), we make the height animation smooth, especially for the content below.
[Preview](https://eufemia-featheightanimationtransitions.gtsb.io/uilib/components/height-animation/demos/#heightanimation).
Some thoughts: Here we enter a grey-zone for when this will be needed and useful. There are may other ways to solve the whole animation stagey. Like make a copy of effected DOM elements and use these for the animation, especially during disappearance.
=> feat(HeightAnimation): adjust height with animation when content changes

packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/dialog/style/_dialog.scss, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap, packages/dnb-eufemia/src/components/modal/style/_modal.scss
Here is a reprod [CSB](https://codesandbox.io/s/eufemia-modal-fullscreen-safari-bug-3sv139?file=/src/App.tsx). 
Run [this here](https://3sv139.csb.app) in Safari Desktop, click on the full-screen button, even without playing the video:
You see this here, instead of the full-screen video:
This is because of the CSS animation and the `forwards` usage. But happily, we do not need in on the "show" animation, because, that's anyway our "default". So we can remove it. Full-screen video works now fine without it.
=> fix(Modal): Safari Desktop fullscreen video issue

packages/dnb-eufemia/src/components/accordion/__tests__/__snapshots__/Accordion.test.js.snap, packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.js, packages/dnb-eufemia/src/components/avatar/__tests__/Avatar.test.tsx, packages/dnb-eufemia/src/components/badge/__tests__/Badge.test.tsx, packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx, packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.js.snap, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.js, packages/dnb-eufemia/src/components/global-error/__tests__/__snapshots__/GlobalError.test.js.snap, packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.js.snap, packages/dnb-eufemia/src/components/help-button/__tests__/HelpButton.test.tsx, packages/dnb-eufemia/src/components/icon-primary/__tests__/__snapshots__/IconPrimary.test.js.snap, packages/dnb-eufemia/src/components/icon/Icon.js, packages/dnb-eufemia/src/components/info-card/__tests__/InfoCard.test.tsx, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.js.snap, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/InputPassword.test.js.snap, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap, packages/dnb-eufemia/src/components/pagination/__tests__/Pagination.test.js, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap, packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.js.snap, packages/dnb-eufemia/src/components/tabs/__tests__/__snapshots__/Tabs.test.js.snap, packages/dnb-eufemia/src/components/tag/Tag.tsx, packages/dnb-eufemia/src/components/tag/__tests__/Tag.test.tsx, packages/dnb-eufemia/src/components/timeline/__tests__/Timeline.test.tsx, packages/dnb-eufemia/src/shared/locales/en-GB.js, packages/dnb-eufemia/src/shared/locales/nb-NO.js
This PR renames the property `data-test-id` to  `data-testid`, so that we can use the `ByTestId` query from [Testing Library](https://testing-library.com/docs/queries/bytestid/).
The suggested improvement has come as a result of this discussion.
https://github.com/dnbexperience/eufemia/pull/1581#discussion_r980069352
=> chore(Icon): replace data-test-id with data-testid

packages/dnb-eufemia/package.json
Not sure if this is something that makes things better. But we can safe potentially save some time, if it fails early.
=> chore(CI): bail on first failing visual test

packages/dnb-eufemia/src/core/jest/jestPuppeteerEnvironment.js, packages/dnb-eufemia/src/core/jest/jestPuppeteerTeardown.js
I have seen it a lot. When a visual test first fails, it creates a bunch of additional failed "retry" snapshots. Even when they succeed after some retries. But when one fails, we get these snapshots in the report as well.
This PR removes the "retry" snapshots.
Tested locally:
=> chore(CI): remove retry snapshots

packages/dnb-eufemia/src/components/tooltip/Tooltip.tsx
Remove context.FormRow) because the Tooltip does not support any FormRow props.
=> fix(Tooltip): remove unused FormRow integration

packages/dnb-eufemia/src/components/slider/Slider.tsx, packages/dnb-eufemia/src/components/slider/SliderProvider.tsx, packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx, packages/dnb-eufemia/src/components/slider/types.ts, packages/dnb-eufemia/src/components/tooltip/Tooltip.tsx, packages/dnb-eufemia/src/components/tooltip/types.ts, packages/dnb-eufemia/src/shared/Context.tsx
When we define `React.HTMLProps<HTMLElement>` to a component – because we allow forwarding HTML attributes to a HTML element, we interfere with the `lang` attribute, because both the `GetTranslationProps` type and the types of HTMLElement's have defined a lang attribute.
=> chore(Types): make lang not interfere with HTMLProps

packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap, packages/dnb-eufemia/src/components/slider/SliderThumb.tsx, packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx, packages/dnb-eufemia/src/components/tooltip/Tooltip.tsx, packages/dnb-eufemia/src/components/tooltip/TooltipContainer.tsx, packages/dnb-eufemia/src/components/tooltip/TooltipHelpers.tsx, packages/dnb-eufemia/src/components/tooltip/TooltipPortal.tsx, packages/dnb-eufemia/src/components/tooltip/TooltipWithEvents.tsx, packages/dnb-eufemia/src/components/tooltip/__tests__/Tooltip.test.tsx
Enhance usage of portal, so we not use `createPortal` and `render`.
This fixes an issue where `mouseOver` and `mouseOut` was not given the wanted/same result:
https://user-images.githubusercontent.com/1501870/193398634-55d2b1ca-1bbd-45a7-92f4-5affd5c40a67.mov
I can imagine that this issue  #1411 can be related.
=> fix(Tooltip): fix React Portal handling

packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx, packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx, packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbMultiple.tsx, packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx
When a Breadcrumb was declared like so:
```jsx
<Breadcrumb>
<Breadcrumb.Item
text="Page item 1"
/>
<Breadcrumb.Item
text="Page item 2"
/>
</Breadcrumb>
```
https://user-images.githubusercontent.com/1501870/193920026-7900d0ce-95fb-46fa-bf91-cde6e67434c1.mov
The animation did not work nicely then. Why? We do not know the count of each item.
[CSB](https://codesandbox.io/s/eufemia-breadcrumb-animation-issue-thsgsm?file=/src/App.tsx)
This PR ensures we always know the number of each item during the each re-render phase.
=> fix(Breadcrumb): make animation work properly when declared as JSX

packages/dnb-design-system-portal/src/docs/uilib/components/tooltip/properties.md, packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap, packages/dnb-eufemia/src/components/slider/SliderThumb.tsx, packages/dnb-eufemia/src/components/slider/SliderTrack.tsx, packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx, packages/dnb-eufemia/src/components/slider/hooks/useSliderEvents.tsx, packages/dnb-eufemia/src/components/tooltip/Tooltip.tsx, packages/dnb-eufemia/src/components/tooltip/TooltipContainer.tsx, packages/dnb-eufemia/src/components/tooltip/TooltipHelpers.tsx, packages/dnb-eufemia/src/components/tooltip/TooltipPortal.tsx, packages/dnb-eufemia/src/components/tooltip/TooltipWithEvents.tsx, packages/dnb-eufemia/src/components/tooltip/__tests__/Tooltip.test.tsx, packages/dnb-eufemia/src/components/tooltip/stories/Tooltip.stories.tsx, packages/dnb-eufemia/src/components/tooltip/types.ts, packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js, packages/dnb-eufemia/src/shared/component-helper.js
Sorry for the many Tooltip changes. The reason is that I want to optimize it as much as possible, before stripping out parts and make a new/shared component. 
This PR makes the `skipPortal` act as the one with the portal, but just inlines the Tooltip HTML under the component.
=> fix(Tooltip): make skipPortal properly inline and accessible to screen readers

packages/dnb-design-system-portal/src/docs/uilib/components/badge.md, packages/dnb-design-system-portal/src/docs/uilib/components/breadcrumb.md, packages/dnb-design-system-portal/src/docs/uilib/components/help-button.md, packages/dnb-design-system-portal/src/docs/uilib/components/logo.md, packages/dnb-design-system-portal/src/docs/uilib/components/number-format.md, packages/dnb-design-system-portal/src/docs/uilib/components/pagination/infinity-scroller.md, packages/dnb-design-system-portal/src/docs/uilib/components/switch.md, packages/dnb-design-system-portal/src/docs/uilib/components/table.md, packages/dnb-design-system-portal/src/docs/uilib/components/tabs.md, packages/dnb-design-system-portal/src/docs/uilib/components/tag.md, packages/dnb-design-system-portal/src/docs/uilib/components/timeline.md, packages/dnb-design-system-portal/src/docs/uilib/components/tooltip.md, packages/dnb-design-system-portal/src/shared/parts/ListSummaryFromPages.js
This PR makes a few improvements in the following page https://eufemia.dnb.no/uilib/components/:
- Adds missing descriptions to components.
- Edits a few descriptions for components that had poor description.
- Sorts the components/mdx's by their title. 
I think it's better than what it is today, but would be even better if the order would be the same(and shared), using levels like for fragments, as in the sidebar menu. Not sure how easy/quick that would be to do, and it's also not very important 😹 
For comparison: [existing](https://eufemia.dnb.no/uilib/components/) vs. [changes introduced in this PR](https://eufemia-docsadddescriptiontoallcompone.gtsb.io/uilib/components/)
=> docs(Components): add description to all component docs

packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/demos.md, packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/properties.md, packages/dnb-eufemia/src/components/height-animation/HeightAnimation.tsx, packages/dnb-eufemia/src/components/height-animation/style/_height-animation.scss
- add showOverflow property
- And basic auto resizing example
=> feat(HeightAnimation): add showOverflow property

packages/dnb-eufemia/src/components/icon/Icon.js, packages/dnb-eufemia/src/components/icon/__tests__/Icon.test.js
The changes I made in https://github.com/dnbexperience/eufemia/pull/1583 make it pointless to pass a value for `data-testid`to the Icon component, as we always overwrite the `data-testid`.
For example, the following code will end with a `data-testid` that will have the value `question icon`:
`<Icon icon={question} data-testid="custom-data-testid" />,` but in this scenario I would want it to be `custom-data-testid`.
In general, I think I made a a slight mistake with #1583 and that we shouldn't override the value of `data-testid` when provided.
=> fix(Icon): fix override of data-testid property when provided

packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/demos.md, packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/info.md, packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/properties.md, packages/dnb-eufemia/src/components/height-animation/HeightAnimation.tsx, packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimation.test.tsx, packages/dnb-eufemia/src/components/height-animation/__tests__/useHeightAnimation.test.tsx, packages/dnb-eufemia/src/components/height-animation/useHeightAnimation.tsx
I rethought the purpose of this component and think now that this component will probably mostly be used as a "height change" component, and not always from nothing to auto. 
When someone needs the first render to be nothing/0 then he anyway will send in `false` on the first render cycle. And then change it when needed.
When we have open by default, we do not need to define it anymore to use this component for only a height animation.
=> feat(HeightAnimation): make the view open by default

packages/dnb-eufemia/src/components/pagination/PaginationBar.tsx, packages/dnb-eufemia/src/components/pagination/__tests__/Pagination.test.js
This PR brings back the lost translation support once the bar got extracted as a stand-alone component.
=> fix(Pagination): fix locale support

packages/dnb-design-system-portal/src/docs/uilib/usage/layout/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/usage/layout/media-queries.md, packages/dnb-eufemia/package.json, packages/dnb-eufemia/src/shared/MediaQuery.tsx, packages/dnb-eufemia/src/shared/MediaQueryUtils.ts, packages/dnb-eufemia/src/shared/__tests__/MediaQueryUtils.test.tsx, packages/dnb-eufemia/src/shared/__tests__/useMedia.test.tsx, packages/dnb-eufemia/src/shared/index.js, packages/dnb-eufemia/src/shared/stories/MediaQuery.stories.tsx, packages/dnb-eufemia/src/shared/useMedia.tsx, yarn.lock
This PR adds a new React Hook that is based on the already existing internals of the existing [`useMediaQuery`](https://eufemia.dnb.no/uilib/usage/layout/media-queries/#usemediaquery-hook-usage) React Hook.
The new `useMedia` hooks is a fixed and simplified version of it. 
Before you would have to do this:
```jsx
const isSmall = useMediaQuery({ when: { max: 'small' } })
```
While with this hook, you can do this:
```jsx
const { isSmall, isMedium, isLarge } = useMedia()
```
In v10 of Eufemia the breakpoints will be changed and aligned in this PR #1373 – if you want to use this hook once released, and with v9 – then you may want to define the internally used breakpoints by yourselves.
**NB:** It should be done only temporary, because DNB should align on set of breakpoints to best UX and …
=> feat(useMedia): add React Hook to handle Eufemia layout breakpoints

packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbMultiple.tsx, packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx, packages/dnb-eufemia/src/components/breadcrumb/stories/Breadcrumb.stories.tsx
After the following [change](https://github.com/dnbexperience/eufemia/pull/1605/files#diff-105824c101ceb4b6537e4898deff813846530866c5e7a1040807ba39a7f07d75R47), where we now use React.cloneElement, the following code snippet would result in an error:
```
<Breadcrumb>
<Breadcrumb.Item />
<Breadcrumb.Item />
{null}
</Breadcrumb>
```
The error:
`React.cloneElement(...): The argument must be a React element, but you passed null.`
The suggested fix is just to remove/filter out not valid React elements. before trying to clone them.
This should fix it when passing children, but should we add support for this when passing `null` in `data` as well? 
Or is it just normal(not expected by the consumer) to not be able to pass null in this situation 🤔 
```
<Breadcrumb data={[ { text: "A" }, { text: "B" …
```
=> fix(Breadcrumb): support null as children

.github/workflows/build-check.yml, packages/dnb-eufemia/.eslintrc, packages/dnb-eufemia/scripts/postbuild/__tests__/postbuild.test.js, packages/dnb-eufemia/scripts/postbuild/getNextReleaseVersion.js, packages/dnb-eufemia/scripts/tools/cliTools.js
To prevent import path that are invalid in the final build we add:
- eslint rule
- postbuild test
Both are verified to work as expected:
=> chore(build): ensure that importing from src is not used inside /src directory

packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx, packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbMultiple.tsx, packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx, packages/dnb-eufemia/src/components/breadcrumb/stories/Breadcrumb.stories.tsx
Types and code did not support passing a single child as children to Breadcrumb component.
When only passing a single breadcrumb.item as children the type would report a problem:
Also, when only passing a single breadcrumb.item as children, the filter I added [here](https://github.com/dnbexperience/eufemia/pull/1661/files#diff-105824c101ceb4b6537e4898deff813846530866c5e7a1040807ba39a7f07d75R47) will make the code break, as an object can't do "filter".
This PR should fix these two issues.
=> fix(Breadcrumb): support a single child

packages/dnb-eufemia/src/components/table/TableTr.tsx
In light of https://github.com/dnbexperience/eufemia/pull/1668, I was looking for other scenarios where our types should also support a single react element, and not only an array/list of react elements.
=> fix(Table Tr): support a single child

.github/workflows/build-check.yml, .github/workflows/codeql-analysis.yml, .github/workflows/icons-lib.yml, .github/workflows/release.yml, .github/workflows/verify.yml, .github/workflows/visual-test.yml, package.json
This is nice, small improvement. This way, we define what Node.js version is used in just one single place.
Node.js version will now be used from Volta settings: https://github.com/actions/setup-node/releases/tag/v3.5.0
=> chore(CI): upgrade GitHub Actions

packages/dnb-design-system-portal/src/docs/uilib/components/section/properties.md, packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap, packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.js.snap, packages/dnb-eufemia/src/components/section/Section.tsx, packages/dnb-eufemia/src/components/section/__tests__/__snapshots__/Section.test.tsx.snap, packages/dnb-eufemia/src/components/section/style/_section.scss
Because we refer to the [spacing table](https://eufemia.dnb.no/uilib/usage/layout/spacing/#spacing-helpers), it should be supported as well.
=> fix(Section): add official support for x-large and xx-large spacing

packages/dnb-design-system-portal/src/docs/uilib/components/upload/properties.md, packages/dnb-eufemia/src/components/upload/UploadFileInput.tsx, packages/dnb-eufemia/src/components/upload/UploadVerify.tsx, packages/dnb-eufemia/src/components/upload/__tests__/Upload.test.tsx, packages/dnb-eufemia/src/components/upload/__tests__/UploadFileInput.test.tsx, packages/dnb-eufemia/src/components/upload/types.ts
This feature is mostly to prevent potential failures done by devs. Also, the `input` component does this already handle for us. Lets say, this `<input type="file" accept".jpg" />` will make `jpeg` files "select-able".
But we also want the same behavior on the drag&drop feature.
=> feat(Upload): accept jpeg when only jpg is defined

.github/workflows/build-check.yml, .github/workflows/release.yml, .github/workflows/verify.yml, packages/dnb-design-system-portal/src/docs/contribute/deploy.md, packages/dnb-eufemia/package.json
Make it possible to release versions to the `next` NPM tag. Its very the same as beta and alpha. So we may have a discussion on what should run of tests and if this version "info" should be pushed back to GitHub, like here: https://github.com/dnbexperience/eufemia/releases/tag/v9.35.0
=> chore(release): make "next" releases possible

.github/workflows/release.yml
The GitHub Action `workflow_run` does run when one of the listed workflows completes. But we also want to restrict this event to only run on certain branches.
=> chore(CI): prevent "dead" runs

.github/workflows/build-check.yml
Yes, it works without having `persist-credentials` enabled:
https://github.com/dnbexperience/eufemia/actions/runs/3345217778/jobs/5540466406
So I think we should revert this setting as it was before.
=> chore(CI): remove not needed setting on checkout

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.md, packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/Examples.js, packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/demos.md, packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/info.md, packages/dnb-eufemia/src/components/space/Space.tsx, packages/dnb-eufemia/src/components/space/SpacingUtils.ts, packages/dnb-eufemia/src/components/space/__tests__/SpacingUtils.test.tsx
I think it could be good to have this listed in the change logs, because we have found examples in prod where this is not used. So when the user presses the back button, they will be relocated to another page, instead to the previews step.
=> fix(StepIndicator): add example on how to use it with a router (browser location)

.github/workflows/release.yml, packages/dnb-eufemia/package.json
Something is not quite right. We follow the docs from semantic-release with the existing setup, but still, the next version got released under NPM next dist-tag, but without a suffix of `-next` – and also, the git tag did not get it.
So, for now, I think, we should mark it as a pre-release instead and find a way of not publish any release notes in the GitHub release section. But this has to be done in a separate PR.
Also, running the verify tests before release, is not optimal with the current setup, because it runs regardless, and not in band. So I think we want to remove `workflow_run`. And rather include them in the jobs directly.
Attaching also some screenshots:
=> chore(Release): make "next" tag to a pre-release

packages/dnb-design-system-portal/src/docs/uilib/components/upload/Examples.tsx
Replaces `checkedonChange` with `on_change`.
Reason for doing so is because the example did not work, and I got the following error in the console:
`Warning: React does not recognize the `checkedonChange` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `checkedonchange` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`
=> docs(Upload): Upload loading state example

packages/dnb-eufemia/src/components/accordion/__tests__/__snapshots__/Accordion.test.js.snap, packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.js.snap, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.js.snap, packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator-v1.test.js.snap, packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.js.snap, packages/dnb-eufemia/src/components/tag/__tests__/__snapshots__/Tag.test.tsx.snap, packages/dnb-eufemia/src/components/timeline/__tests__/__snapshots__/Timeline.test.tsx.snap, packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.js.snap, packages/dnb-eufemia/src/style/core/utilities.scss
The `@media not all and (min-resolution: 0.001dpcm)` does not work with Safari v16 anymore. It's falsy. But the rest still works, so we can invert what we have in `IS_SAFARI_IOS`. I tested it and it works fine.
=> fix: add support to IS_SAFARI_DESKTOP for Safari v16 on macOS

packages/dnb-design-system-portal/src/docs/uilib/components/table/Examples.tsx, packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap, packages/dnb-eufemia/src/components/table/stories/Table.stories.tsx, packages/dnb-eufemia/src/components/table/style/themes/dnb-table-theme-ui.scss
Because we start counting the tr inside `thead` we did not get the same when using "no" modifier. This PR aligns both to start on `<tr>` inside a table header row.
=> fix(Table): align odd/even modifiers with CSS nth

packages/dnb-design-system-portal/src/docs/uilib/typography/heading.md, packages/dnb-design-system-portal/src/docs/uilib/typography/paragraph.md
This PR aims to make heading and paragraph more searchable.
It could be nice to get to https://eufemia.dnb.no/uilib/typography/heading/ and/or https://eufemia.dnb.no/uilib/typography/paragraph/ after searching.
Especially for Paragraph, which I've sometimes struggled to find documentation and examples for.
Could/should I also or instead create a page for Paragraph under https://eufemia.dnb.no/uilib/elements/ ?
=> chore(Docs): make heading and paragraph more searchable

packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.js.snap, packages/dnb-eufemia/src/components/global-error/__tests__/__snapshots__/GlobalError.test.js.snap, packages/dnb-eufemia/src/elements/Anchor.tsx, packages/dnb-eufemia/src/elements/__tests__/Anchor.test.tsx
This way, its possible to use the anchor, without `React.forwardRef` – can be of interest when making its own "wrapper" component.
=> fix(Anchor): export types as AnchorAllProps and original instance

packages/dnb-eufemia/src/components/form-row/FormRowHelpers.tsx, packages/dnb-eufemia/src/shared/Context.tsx, packages/dnb-eufemia/src/shared/Provider.tsx, packages/dnb-eufemia/src/shared/__tests__/Provider.test.tsx, packages/dnb-eufemia/src/shared/__tests__/useTranslation.test.tsx
This fixes also an issue; when the root context changes locale, it did not update its nested contexts, because we stored them in a state.
Here is a [reprod](https://codesandbox.io/s/eufemia-table-context-locale-2nbgkp) that shows the issue. When the locale changes in the "root" context, it did not update its nested contexts with that change.
=> fix(Provider): rewrite to functional component

packages/dnb-design-system-portal/src/docs/uilib/components/upload/info.md, packages/dnb-eufemia/src/components/upload/Upload.tsx, packages/dnb-eufemia/src/components/upload/UploadDropzone.tsx, packages/dnb-eufemia/src/components/upload/__tests__/UploadDropzone.test.tsx, packages/dnb-eufemia/src/components/upload/useUpload.ts
I think its better to make this not optional. 
But then the question is, should only the first support it? 
If yes, then we probably want a way to support via a property.
Or should it be possible to disable?
But probably, its fine as of now. Having several upload components on the page is probably something that not should happen.
=> feat(Upload): support files dropped on the document body

tools/babel-plugin-react-live/babelPluginReactLive.js
`babel-loader` fails if;
```jsx
const StyledDiv = styled.div`
color: red;
`
```
is used.
=> chore(ReactLive): make it possible to use styled components

packages/dnb-design-system-portal/.eslintrc, packages/dnb-design-system-portal/package.json, packages/dnb-design-system-portal/src/docs/uilib/components/table/Examples.tsx, packages/dnb-design-system-portal/src/shared/tags/AutoLinkHeader.tsx, packages/dnb-design-system-portal/src/shared/tags/CodeBlock.tsx, packages/dnb-design-system-portal/src/shared/tags/ComponentBox.tsx, packages/dnb-eufemia/package.json, yarn.lock
With that change, unused vars will fail also in the portal package. 
Maybe, at a later time, we should move such logic to a lower lever (root level). I guess its supported now days (It was not 5 years ago).
=> chore(eslint): add support for tsx in portal package

packages/dnb-design-system-portal/src/docs/uilib/components/form-row/Examples.js, packages/dnb-design-system-portal/src/docs/uilib/typography.md, packages/dnb-design-system-portal/src/docs/uilib/typography/Examples.tsx, packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap, packages/dnb-eufemia/src/components/table/style/_table.scss, packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap, packages/dnb-eufemia/src/style/elements/typography.scss
Make this change to ensure, inherited typography is handled in one place. E.g. in case there will be bold support later.
Also, move general Typography listings to the Examples files.
=> chore(Typography): move table typography

packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.module.scss, packages/dnb-design-system-portal/src/shared/parts/Layout.module.scss
Currently, the [fullscreen mode ](https://eufemia.dnb.no/uilib/components/table/?fullscreen) does not hide the left padding.
This PR should fix that.
=> chore(Portal): fix fullscreen view

packages/dnb-design-system-portal/src/shared/menu/ToggleGrid.tsx, packages/dnb-eufemia/src/components/height-animation/useHeightAnimation.tsx
React warns about the usage of `useLayoutEffect` when React renders on the server (SSR).
This behavior can be enabled with the `FAST_DEV` flag in gatsby-config.
One "quick" fix is to use useEffect on the server, which again does nothing there.
The React "team" has [some options](https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85) to that "problem". We basically use option 1, with this approach.
Any other suggestions?
PS: I tried to create a test. But invalidating both the document or the window object (`delete globalThis.window`) makes the testing lib not rendering the component or hook.
=> fix(HeightAnimation): avoid usage of useLayoutEffect during SSR

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.md, packages/dnb-design-system-portal/src/docs/uilib/helpers/Examples.js, packages/dnb-design-system-portal/src/docs/uilib/helpers/classes.md, packages/dnb-eufemia/src/style/core/helper-classes/helper-classes.scss, packages/dnb-eufemia/src/style/core/utilities.scss
- deprecate `.dnb-not-sr-only` as it is not of interest in a React/JavaScript driven app world. We rather should remove the original class, than adding a new one.
- deprecate `.dnb-sr-only--inline` as it does not give a real additional value. We should rather change the CSS, when `.dnb-sr-only` would "break" something.
=> fix:  deprecate `.dnb-not-sr-only` and `.dnb-sr-only--inline`

packages/dnb-eufemia/src/components/number-format/NumberFormat.js, packages/dnb-eufemia/src/components/number-format/__tests__/__snapshots__/NumberFormat.test.js.snap, packages/dnb-eufemia/src/components/number-format/stories/NumberFormat.stories.js
I can't find any reasons anymore why not just use `dnb-sr-only`. Its the only place also, when `--inline` was used.
=> fix(NumberFormat): use `dnb-sr-only` instead of `dnb-sr-only--inline`

packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/dnb-eufemia/src/components/drawer/style/_drawer.scss, packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap
=> fix(Drawer): ensure nav bar is aligned to left when content is wider than Drawer

.github/dependabot.yml, packages/dnb-design-system-portal/.ncurc.json, packages/dnb-design-system-portal/package.json, packages/dnb-design-system-portal/src/docs/uilib/components/tabs/Examples.js, packages/dnb-design-system-portal/src/docs/uilib/components/tabs/demos.md, yarn.lock
We had only one example using `react-router-dom`. We also did link to a CSB with an example. So I think we should remove this example and dependency.
=> chore(react-router): remove this deps including example

.github/workflows/codeql-analysis.yml
We need to do this in order to keep this working. Here are the migration guides: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
=> chore(repo): update codeql-action to v2

packages/dnb-design-system-portal/src/docs/uilib/components/table/properties.md, packages/dnb-eufemia/src/components/table/TableTh.tsx, packages/dnb-eufemia/src/components/table/__tests__/TableTh.test.tsx
Add `aria-sort` to be handled by default. More info [about aria-sort](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort).
=> feat(Th): include by default aria-sort for assistive technology

packages/dnb-design-system-portal/tsconfig.json, packages/dnb-eufemia/tsconfig.json
After a macOS re-installation; VSCode complains about global variables, like document. A quick search on the internet, tells me we miss "dom" in `compilerOptions/lib`. 
Any thoughts about this?
=> chore: add "dom" to TypeScript libs

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap, packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.js.snap, packages/dnb-eufemia/src/components/input/style/_input.scss
This PR hides the "password reveal" button in Microsoft Edge.
Here's a screenshot of how it looked when both our internal password reveal button, and the default one in Microsoft Edge was displayed simultaneously:
=> fix(InputPassword): hide password reveal in Edge

packages/dnb-eufemia/src/shared/__tests__/helpers.test.js, packages/dnb-eufemia/src/shared/helpers.js
This is a documented helper class. 
But when there was not an element, `scrollTo` was still called. Which has negative effects on default browser location hash handling.
=> fix(scrollToLocationHashId): omit calling scrollTo when element is not found

packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.module.scss
Now that we do not need to support IE, we can use scroll-padding-top to compensate for our sticky header.
This is useful, when a location hash is used to scroll to a certain element with an ID. Does not effect our heading hash handling, there we already deal with a offset (padding).
Also, we do not need (neither should) to set a fixed height to the header. The given padding should be enough.
=> chore(Portal): add scroll-padding-top to compensate for sticky header

packages/dnb-design-system-portal/src/docs/uilib/components/table/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/components/table/demos.md, packages/dnb-design-system-portal/src/docs/uilib/components/table/info.md, packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap, packages/dnb-eufemia/src/components/table/__tests__/useHandleSortState.test.tsx, packages/dnb-eufemia/src/components/table/index.js, packages/dnb-eufemia/src/components/table/stories/Table.stories.tsx, packages/dnb-eufemia/src/components/table/style/_table-header-buttons.scss, packages/dnb-eufemia/src/components/table/useHandleSortState.tsx
This PR adds a little React Hook that could be very handy when dealing with three stage sorting, which should be naturally the default behavior.
But we also ensure that the `Th.SortButton` actually reacts correctly as well. This is handled by CSS. Also, for the CSS states, [this CSB](https://codesandbox.io/s/bold-field-glyxq6) was provided.
What do you think about all the option names and the name of the React Hook?
=> feat(Table): add useHandleSortState hook

packages/dnb-eufemia/src/fragments/scroll-view/style/_scroll-view.scss
When using mousewheel or touchpad while holding the mouse over e.g. a table, you could not scroll the "body" down anymore. With this change, you can do it as expected.
I think, this should be the default behavior.
=> fix(ScrollView): ensure an ancestor scroll area (body) can still be scrolled with mouse wheel

packages/dnb-design-system-portal/src/docs/uilib/components/table/Examples.tsx, packages/dnb-eufemia/src/components/table/__tests__/useHandleSortState.test.tsx, packages/dnb-eufemia/src/components/table/stories/Table.stories.tsx, packages/dnb-eufemia/src/components/table/useHandleSortState.tsx
Based on feedback and needs, we need to change the default direction from `asc` to `off`.
=> fix(useHandleSortState): change default direction from asc to off

packages/dnb-design-system-portal/src/shared/tags/CodeBlock.module.scss, packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap, packages/dnb-eufemia/src/components/table/stories/Table.stories.tsx, packages/dnb-eufemia/src/components/table/style/_table-sticky.scss, packages/dnb-eufemia/src/components/table/style/_table-tr.scss
=> fix(Table): make sticky header work when used in combination with accordion rows

.vscode/extensions.json
Because it works even better than the previews one and shows the actual value when cursor is set on value.
=> chore: change VSCode px vs rem tooling recommendation

packages/dnb-design-system-portal/src/docs/uilib/usage/layout/spacing.md, packages/dnb-eufemia/src/components/space/SpacingUtils.ts, packages/dnb-eufemia/src/components/space/__tests__/SpacingUtils.test.tsx, packages/dnb-eufemia/src/components/space/types.ts
With some refactoring (mostly to correct Typescript types) and the addition of 9 lines of code, we get the `calc` function that outputs CSS calc/var based summary of given types.
```tsx
import { calc } from '@dnb/eufemia/components/space/SpacingUtils'
// With Styled Components
const StyledDiv = styled.div`
margin-top: ${calc('medium large')};
margin-top: ${calc('medium', 'large')};
margin-top: ${calc('1.5rem', '2rem')};
margin-top: ${calc('24px', '32px')};
`
```
All of the examples do output: `calc(var(--spacing-medium) + var(--spacing-large))`
Invalid values will be corrected to its nearest spacing type (e.g. 17px to `var(--spacing-small)`).
=> feat(Spacing): add calc helper

packages/dnb-eufemia/src/elements/Anchor.tsx, packages/dnb-eufemia/src/elements/__tests__/Anchor.test.tsx
Seems like `HTMLProps` includes more props than `HTMLAttributes`, `rel` being one of them.
Or maybe we should use `React.ComponentPropsWithoutRef<"a">`?  🤔 
https://github.com/typescript-cheatsheets/react/blob/main/docs/advanced/patterns_by_usecase.md#componentprops
=> fix(Anchor): allow rel property in TS

packages/dnb-eufemia/src/elements/__tests__/P.test.js
Changing the use of enzyme to react testing library.
Changed testing to use testing library standards and some refactoring in the process.
Ran 
`yarn test /P.test.js`
to see that test now works.
=> chore: change P.test.js to use testing library

.github/workflows/build-check.yml, .github/workflows/icons-lib.yml, .github/workflows/release.yml, .github/workflows/verify.yml, .github/workflows/visual-test.yml
Honestly, I thought we have fixed the issue by checking the "owner". But with the two new fork PRs, I clearly see we did not.
I don't think the issue is gone with that PR. But I don't know what we can do more about it either. 
The [docs](https://docs.github.com/en/actions/learn-github-actions/expressions#always) says clearly, that the step should not fail, when `always` is used. Do they not?
If we would add a env check `if: ${{ always() && secrets.SLACK_WEBHOOK }}`, then we are probably on the same page as before? What do you think? @langz 
I also wander, how we can get the [rest of the actions](https://github.com/dnbexperience/eufemia/pull/1854) to start running?
=> chore: make Slack step not fail when run from Fork

packages/dnb-eufemia/src/components/button/__tests__/Button.test.js
Changing the use of enzyme to react testing library.
Changed testing to use testing library standards and some refactoring in the process.
Run
`yarn test /Button.test.js`
to see that test now runs using testing library
=> chore: rewrite button.test.js to testing library

packages/dnb-design-system-portal/src/shared/parts/Layout.module.scss
I can't remember, why we not did set position relative after the Emotion => SCSS conversion. But right now, I can't find any negative issues having it.
This fixes an issue a few places, where the class `example-box` is used, like on this page: https://eufemia.dnb.no/uilib/getting-started/demos/
=> chore(Portal): add position relative to example-box

packages/dnb-design-system-portal/src/shared/menu/Card.js
Missed this as part of #1855.
From:
To:
=> chore(P): use className instead of style_type

packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap, packages/dnb-eufemia/src/components/table/style/_table-accordion.scss
This PR fixes a css specificity issue on medium and small tables.
Correct (medium)
Bug (medium)
=> fix(Table): correct width on medium and small accordion chevron icon cell

packages/dnb-design-system-portal/.browserslistrc, packages/dnb-design-system-portal/src/docs/uilib/usage.md, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/styling/polyfill.md, packages/dnb-eufemia/.browserslistrc, packages/dnb-eufemia/scripts/prebuild/config/postcssConfig.js
Fixes #1912
I think, we do not need `maintained node versions`. What do you think? @langz
=> fix: remove `maintained node versions` from .browserslistrc

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.md
=> docs(Table): add info about the needed CSS class in v10

packages/dnb-eufemia/src/elements/Anchor.tsx
I think we have to remove `Button`'s [inner_ref](https://github.com/dnbexperience/eufemia/blob/71f5ee3746f6381eeb72221bac013126a5ea84ad/packages/dnb-eufemia/src/components/button/Button.js#L129), as the  `inner_ref` could be passed down to `Anchor`(which as of this PR only supports `innerRef` and not `inner_ref`):  https://github.com/dnbexperience/eufemia/blob/71f5ee3746f6381eeb72221bac013126a5ea84ad/packages/dnb-eufemia/src/components/button/Button.js#L178-L182
UPDATE: I've now changed this to just improve the comment of why it's not deprecated(easy to remove) as of now. 
I don't think it's easy or better to actually remove/deprecate the `inner_ref` property, since Button is still dependent on the `inner_ref` prop as of now.
=> fix(Anchor): comments Anchor's inner_ref usage

packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx
Fixes:
```
console.error
Warning: Received the string `true` for the boolean attribute `hidden`. Although this works, it will not work as expected if you pass the string "false". Did you mean hidden={true}?
at button
at Button (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/button/Button.js:66:5)
at useContext (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/help-button/HelpButtonInstance.tsx:23:25)
at Modal (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/modal/Modal.tsx:158:5)
at Modal (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/shared/helpers/withCamelCaseProps.tsx:53:30)
at Button (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/button/Button.js:66:5)
at useState …
```
=> chore(Modal): fix test error for trigger_attributes

packages/dnb-eufemia/src/components/space/Space.tsx
Problem was that I thought `<E `in https://github.com/dnbexperience/eufemia/pull/1859/files#diff-e332dc1ea8b6e76ee4eac5052d69c902e4b58b8e849f9d33a5d384c317c8b088R45 was the same as `import E from './Element'`, but it's not. 
Hence renaming `<E>` in this file to be `<ElementDynamic>`, just to prevent confusion, though it's "not technically needed" as it can be seen by that we don't import `<E>` in this file as well.
Fixes following issue.
```
at log (src/components/space/Space.tsx:45:13)
console.error
Warning: React does not recognize the `innerRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `innerref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
at section
at …
```
=> chore(Space): fix test error innerRef on DOM elem

packages/dnb-design-system-portal/src/docs/uilib/components/input/Examples.js, packages/dnb-design-system-portal/src/docs/uilib/components/input/demos.md, packages/dnb-design-system-portal/src/docs/uilib/components/textarea/Examples.js, packages/dnb-design-system-portal/src/docs/uilib/components/textarea/demos.md
Because its not good for a11y, we should not have an example like that.
=> docs: remove examples that shows state by color only

packages/dnb-design-system-portal/src/docs/uilib/components/number-format/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/components/number-format/demos.md, packages/dnb-design-system-portal/src/docs/uilib/components/number-format/info.md
=> docs: add correct info about the `clean_copy_value` feature

packages/dnb-eufemia/src/components/badge/Badge.tsx, packages/dnb-eufemia/src/components/badge/__tests__/Badge.test.tsx
- badge
- badge-root
- badge-label
I checked in the monorepo, and it exists no occurrences of this over there 🙏
=> chore(Badge): rewrite tests w/o using data-testid

packages/dnb-eufemia/src/components/badge/Badge.tsx, packages/dnb-eufemia/src/components/badge/__tests__/Badge.test.tsx
The role `status` has mainly a "function" when it changes. But does not hurt when there. A screen reader will only read it, when the status changes. When it is used as a counter, then its actually required.
=> fix(Badge): enhance semantic / accessibility and inherit skeleton from provider

packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap, packages/dnb-eufemia/src/style/elements/lists.scss
The current approach did not work always. When the parent space where to wide, it did not wrap. The new approach does do it. 
Here is my testing case: https://codesandbox.io/s/eufemia-timeline-example-4x7u7n?file=/src/App.tsx
It should not have any impact on our existing visual tests.
Before:
After:
=> fix(Dl): ensure horizontal wrap no matter what available space

packages/dnb-design-system-portal/src/docs/uilib/usage/best-practices/for-testing.md
Adding documentation to describe why we don't promote the use of `data-testid`.
This is related to the other PRs #1820, #1821, #1822, #1824, #1825, and #1829
=> docs(Testing): info about not using data-testid

packages/dnb-design-system-portal/src/docs/uilib/components/fragments/scroll-view/properties.md, packages/dnb-eufemia/src/components/table/TableScrollView.tsx, packages/dnb-eufemia/src/components/table/__tests__/TableScrollView.test.tsx, packages/dnb-eufemia/src/fragments/scroll-view/ScrollView.tsx, packages/dnb-eufemia/src/fragments/scroll-view/__tests__/ScrollView.test.tsx, packages/dnb-eufemia/src/fragments/scroll-view/__tests__/__mocks__/ResizeObserver.ts
When `interactive=auto` is used, and there is a scrollbar, make the scrollview tabbable. 
The screenshot shows, that I was able to focus it:
=> feat(ScrollView): add interactive=auto to observe the content

packages/dnb-eufemia/src/components/upload/Upload.tsx, packages/dnb-eufemia/src/components/upload/UploadFileInput.tsx, packages/dnb-eufemia/src/components/upload/UploadFileList.tsx, packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx, packages/dnb-eufemia/src/components/upload/UploadInfo.tsx, packages/dnb-eufemia/src/components/upload/__tests__/Upload.test.tsx, packages/dnb-eufemia/src/components/upload/__tests__/UploadFileInput.test.tsx, packages/dnb-eufemia/src/components/upload/__tests__/UploadFileListCell.test.tsx
- upload
- upload-file-input
- upload-file-input-button
- upload-file-input-input
- upload-file-list
- upload-file-list-cell
- upload-delete-button
- upload-progress-indicator
- upload-file-anchor
- upload-subtitle
- upload-warning
- upload-title
- upload-text
- upload-accepted-formats
- upload-file-size
- upload-file-amount-limit
I checked in the monorepo, and it exists no occurrences of this over there 🎊
=> chore(Upload): rewrite tests w/o using data-testid

packages/dnb-eufemia/src/components/upload/UploadFileInput.tsx, packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx, packages/dnb-eufemia/src/components/upload/UploadInfo.tsx, packages/dnb-eufemia/src/components/upload/UploadVerify.tsx, packages/dnb-eufemia/src/components/upload/__tests__/Upload.test.tsx, packages/dnb-eufemia/src/components/upload/__tests__/UploadFileInput.test.tsx, packages/dnb-eufemia/src/components/upload/__tests__/UploadFileListCell.test.tsx, packages/dnb-eufemia/src/components/upload/__tests__/UploadVerify.test.tsx
This PR is based on #1824
Before, we did mix file extension and file mime type:
Now it uses what ever is defined in the `acceptedFileTypes={['txt']}`:
Now it uses what ever is defined in the `acceptedFileTypes={['text/plain']}`:
=> fix(Upload): fix handling of file types in combination with file extension

packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.js
Adds a little bit of margin between the badge and the scrollbar in our menu,
From:
To:
=> chore(Portal): adds margin to right of badge in portal menu

packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx, packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx, packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbMultiple.tsx, packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx
- breadcrumb-nav
- breadcrumb-item
- breadcrumb-item-text
- breadcrumb-collapse
I checked in the monorepo, and it exists many many occurrences of this(queryByTestId('breadcrumb')) over there  😱 🙀
=> chore(Breadcrumb): rewrite tests w/o data-testid

packages/dnb-eufemia/src/components/tag/Tag.tsx, packages/dnb-eufemia/src/components/tag/TagGroup.tsx, packages/dnb-eufemia/src/components/tag/__tests__/Tag.test.tsx
- tag
- tag-group
- tag-group-label
I checked in the monorepo, and it exists only a few occurrences of this over there, and have already opened a PR for it 🙏
=> chore(Tag): rewrite tests w/o using data-testid

packages/dnb-eufemia/src/components/avatar/Avatar.tsx, packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx, packages/dnb-eufemia/src/components/avatar/__tests__/Avatar.test.tsx
- avatar
- avatar-text
- avatar-label
- avatar-group
- avatar-group-label
- elements-left
Will have to check if any of the `data-testid`'s is referenced to from any apps in the monorepo.
I checked, and it exists a lot of occurrences of these `data-testid`'s over there 😢
=> chore(Avatar): rewrite tests w/o using data-testid

packages/dnb-design-system-portal/gatsby-node.js, packages/dnb-design-system-portal/src/shared/parts/ListSummaryFromPages.js
This fixes an issue where summary of docs did not get listed in v10.
=> chore: fix MDX pre v2 issue with usage of contentFilePath

packages/dnb-design-system-portal/src/docs/uilib/components/upload/Examples.tsx
Fixes a small issue, that I believe was introduced in https://github.com/dnbexperience/eufemia/pull/1996
https://github.com/dnbexperience/eufemia/actions/runs/4242957091/jobs/7375099425
```
Run yarn workspace @dnb/eufemia test:types && yarn workspace dnb-design-system-portal test:types
Error: src/docs/uilib/components/upload/Examples.tsx(202,28): error TS2339: Property 'checked' does not exist on type 'FormEvent<HTMLElement>'.
Error: Process completed with exit code 2.
```
=> chore(Upload): Fix TS error in example

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.md, packages/dnb-eufemia/src/components/timeline/Timeline.tsx, packages/dnb-eufemia/src/components/timeline/TimelineItem.tsx, packages/dnb-eufemia/src/components/timeline/__tests__/Timeline.test.tsx
- timeline
- timeline-item-label-icon
- timeline-item-label-title
- timeline-item-content-subtitle
- timeline-item-content-info
- timeline-item
I checked in the monorepo, and it exists only a few occurrences of this over there, will have to change there as well.
=> chore(Timeline): rewrite tests w/o data-testid

packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.js
Just trying to minimize this from happening:
I also think people understand what WIP means, so I would say it's safe to use the term, or if they don't know, it's a quick Google search.
=> chore(Docs): Badge work in progress -> wip

packages/dnb-eufemia/src/components/drawer/__tests__/Drawer.test.tsx
This is the same behavior as in this PR #2012 – now happening in the Drawer component. So we fix it the same way.
=> chore(Drawer): avoid  SSR error of useLayoutEffect in Jest tests

.github/workflows/build-check.yml, .github/workflows/e2e.yml, .github/workflows/icons-lib.yml, .github/workflows/release.yml, .github/workflows/verify.yml
Here are [the docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) about the `continue-on-error: true` command.
=> chore(CI): continue on Slack error

packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.module.scss
Not sure if this is the best fix for #1989, as I see it was suggested to "fix it in the component itself" - https://github.com/dnbexperience/eufemia/issues/1989#issuecomment-1428450070
To me, it seems like this started happening when adding `text-decoration: underline` in https://github.com/dnbexperience/eufemia/pull/1966/files#diff-f0adfb69cb45eb94b8016448bc17488f3e2ba81514c694b5ce0f34f4e245bc56, hence now I only try to add it to the first span/text of the anchor.
How it will look when hovering now:
Fixes #1989
=> portal: remove underline when hover badge in menu

packages/dnb-design-system-portal/src/docs/contribute/getting-started/making-changes.mdx
Because it's actually not valid and needed to import these into SASS. They are import by the core package anyway and will not give any value in the SASS world. now that we do not need to use a postcss to support IE11 fallbacks.
=> docs: remove `properties.scss` import from docs

package.json
When a new dev uses a different version, he will quickly get a failure message when trying to run Node/yarn install.
Should we mention the change somewhere?
=> chore: require Node.js v18 for the repo

packages/dnb-eufemia/src/components/tabs/__tests__/__snapshots__/Tabs.test.tsx.snap, packages/dnb-eufemia/src/components/textarea/__tests__/__snapshots__/Textarea.test.js.snap, packages/dnb-eufemia/src/fragments/drawer-list/__tests__/__snapshots__/DrawerList.test.js.snap, packages/dnb-eufemia/src/fragments/scroll-view/style/themes/dnb-scroll-view-theme-ui.scss, packages/dnb-eufemia/src/style/core/utilities.scss
With this change, we:
- make it themeable.
- enhance on FF the textarea resize grabber.
we still are on the smaller side on blink/chromium/webkit.
- enable buttons on FF Windows + remove the wired color when grabbing the scrollbar thumb.
Today's fun-fact – if we would not have defined our own style – this is how a scrollbar looks in Windows 11:
=> fix: enhance scrollbar appearance

packages/dnb-eufemia/src/components/accordion/Accordion.d.ts, packages/dnb-eufemia/src/components/accordion/AccordionHeader.d.ts, packages/dnb-eufemia/src/components/accordion/AccordionProvider.d.ts, packages/dnb-eufemia/src/components/autocomplete/Autocomplete.d.ts, packages/dnb-eufemia/src/components/button/Button.d.ts, packages/dnb-eufemia/src/components/dropdown/Dropdown.d.ts, packages/dnb-eufemia/src/components/form-status/FormStatus.d.ts, packages/dnb-eufemia/src/components/global-status/GlobalStatus.d.ts, packages/dnb-eufemia/src/components/input-masked/InputMasked.d.ts, packages/dnb-eufemia/src/components/input/Input.d.ts, packages/dnb-eufemia/src/components/toggle-button/ToggleButton.d.ts
These components all use some kind of icon, but some use `IconPrimary` as they pass the props to the Button component(which uses `IconPrimary`),  and others use `Icon` directly in their component.
As of now, I've referred to the correct types from either `IconPrimary` or `Icon`, for the given property, but could/should it only be one `Icon` type, or does it make sense to have both `IconPrimary` and `Icon`?
=> chore(TypeScript): type icons

packages/dnb-design-system-portal/src/docs/uilib/components/form-row/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/components/space/info.mdx, packages/dnb-eufemia/src/components/info-card/InfoCard.tsx, packages/dnb-eufemia/src/components/space/SpacingUtils.ts, packages/dnb-eufemia/src/components/space/__tests__/SpacingUtils.test.ts, packages/dnb-eufemia/src/components/space/stories/Space.stories.tsx, packages/dnb-eufemia/src/components/space/types.ts
This is just a suggestion up for discussion, and not up for merging as of right now.
In this PR, I've just experimented with typing the `SpaceType` for users(and ourselves) to more easily know which values they can enter, and for us internally to name the the types to match https://eufemia.dnb.no/uilib/components/space/#value-format
The biggest motivation is to get rid of `string` from `export type SpaceType = string | boolean | number`, and replace it with actual values/combinations, as it would help weed out all potential non correct string values("0", "10", wrongly spelled types, etc) that's been used, and also adding intellisense.
I also think when/if we introduce types here, that someone who really understands everything that's going in `SpacingUtils.ts` would have to make sure we …
=> chore(Space): type space types

packages/dnb-design-system-portal/src/core/PortalLayout.tsx
The page did scroll to top when other page assets where loaded on hover (e.g. hover in the sidebar menu). But that was just a side-effect of this issue.
=> chore(Portal): fix layout re-render issue

.github/workflows/e2e.yml, .github/workflows/icons-lib.yml
[This](https://github.com/dnbexperience/eufemia/actions/runs/4402679787/jobs/7710112359) is an issue we can't do much about it. It looks like the GitHub Action we use, uses an GitHub API for checking if its ready to go. But there is a rate limit. Its a [known issue](h).
For nor we can try to increase the interval from 3 sec to 10 sec.
=> chore(CI): API rate limit exceeded for installation ID 15060380

packages/dnb-eufemia/src/components/step-indicator/StepIndicator.d.ts, packages/dnb-eufemia/src/components/step-indicator/StepIndicatorItem.d.ts
This PR:
- Tries to reuse the `StepIndicatorItemProps` as a potential type in `StepIndicator`'s `data` prop.
- Removes some undocumented and what I believe is faulty props for the `StepIndicator` which seems to actually belong to `StepIndicatorItem`: `title`, `is_current`, `inactive`, `disabled`, `status`, `status_state`, `on_render` (not sure how/why they was being generated for the StepIndicator though 🤔 )
=> chore(TypeScript): use StepIndicatorItem in StepIndicator

packages/dnb-design-system-portal/src/docs/contribute/style-guides/theming.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming.mdx
Also, refactor docs on how to consume a theme.
Here are some preview:
- Consuming: https://deploy-preview-2097--eufemia.netlify.app/uilib/usage/customisation/theming/
- Maintaining: https://deploy-preview-2097--eufemia.netlify.app/contribute/style-guides/theming/
=> docs: add docs about how to maintain theming

packages/dnb-design-system-portal/src/docs/brand/development.mdx, packages/dnb-design-system-portal/src/docs/brand/development/import-styles.mdx, packages/dnb-design-system-portal/src/docs/contribute.mdx, packages/dnb-design-system-portal/src/docs/contribute/contact.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/deal-with-brand.mdx
Added a draft for the main documentation for "How to deal with the brand". Still not entirely sure where the most optimal home for it would be, so this is still subject to change, and open to better suggestions 😄
As of now it's place under "usage" in the "uilib" portal. The choice was between there or in the "brand" portal, but I'm not sure if either of those are the right choice either 😅
=> docs: crate main doc for how to deal with brand

packages/dnb-eufemia/src/components/accordion/AccordionProvider.js, packages/dnb-eufemia/src/components/button/Button.js, packages/dnb-eufemia/src/components/checkbox/__tests__/Checkbox.test.tsx, packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx, packages/dnb-eufemia/src/components/form-status/__tests__/FormStatus.test.tsx, packages/dnb-eufemia/src/components/help-button/HelpButtonInstance.tsx, packages/dnb-eufemia/src/components/icon-primary/IconPrimary.js, packages/dnb-eufemia/src/components/icon/Icon.js, packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx, packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap, packages/dnb-eufemia/src/components/input/__tests__/Input.test.tsx, packages/dnb-eufemia/src/components/input/__tests__/InputPassword.test.tsx, packages/dnb-eufemia/src/components/logo/Logo.js, packages/dnb-eufemia/src/components/modal/Modal.tsx, packages/dnb-eufemia/src/components/pagination/Pagination.js, packages/dnb-eufemia/src/components/progress-indicator/ProgressIndicator.js, packages/dnb-eufemia/src/components/radio/__tests__/Radio.test.tsx, packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx, packages/dnb-eufemia/src/components/step-indicator/StepIndicatorContext.js, packages/dnb-eufemia/src/components/switch/__tests__/Switch.test.tsx, packages/dnb-eufemia/src/components/textarea/__tests__/Textarea.test.tsx, packages/dnb-eufemia/src/components/toggle-button/__tests__/ToggleButton.test.tsx, packages/dnb-eufemia/src/fragments/drawer-list/DrawerList.js
- To cover the changes in PR #2103 
- This PR is based on PR #2105
=> chore: add FormRow tests

packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.js, packages/dnb-eufemia/src/components/checkbox/__tests__/Checkbox.test.tsx, packages/dnb-eufemia/src/components/form-label/__tests__/FormLabel.test.tsx, packages/dnb-eufemia/src/components/radio/__tests__/Radio.test.tsx, packages/dnb-eufemia/src/components/switch/__tests__/Switch.test.tsx, packages/dnb-eufemia/src/components/toggle-button/__tests__/ToggleButton.test.tsx
I have forgotten to add some tests in PR #2106
=> chore: add additional FormRow tests

packages/dnb-design-system-portal/package.json, packages/dnb-design-system-portal/src/core/PortalProviders.tsx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/styling/polyfill.mdx, yarn.lock
Also, remove it from our Portal as we do not need to support IE11 anymore.
We may wait to delete the docs entirely. When doing so, we should remove the plugin as well. That's a breaking change. 
I create a task for it.
=> docs: remove docs about CSS vars polyfills

packages/dnb-design-system-portal/package.json, yarn.lock
closes #2172
Its fixed in this PR https://github.com/dnbexperience/babel-plugin-react-live/pull/5
=> chore(docs): remove unnecessary fragment in code examples

.github/workflows/build-check.yml, .github/workflows/codeql-analysis.yml, .github/workflows/e2e.yml, .github/workflows/icons-lib.yml, .github/workflows/verify.yml
I think we should try that for now. Because it does most of the time not make sense to continue runs when somethings in the branch changes. I have see that other CI environments, like Gatsby Cloud, do the same.
=> chore: cancel CI runs on new git pushes

packages/dnb-eufemia/src/components/toggle-button/ToggleButton.js, packages/dnb-eufemia/src/components/toggle-button/__tests__/ToggleButton.test.tsx
Quick fix as it seems like the `onClickHandler` expect an object with a property `event`.
Fixes #1696
=> fix(ToggleButton): fixes error when pressing enter

yarn.lock
When running yarn start I would the following warnings. This PR should fix it.
```
warn Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
warn Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
=> chore: update caniuse-lite

packages/dnb-design-system-portal/src/docs/uilib/components/pagination/properties.mdx, packages/dnb-eufemia/scripts/prebuild/tasks/generateTypes.js
- Omit warning about the missing properties during build.
- Remove unused import.
=> chore: some tiny docs/build improvements/fixes

tools/react-live-ssr/index.js
The motivation behind this change is that I find it difficult to navigate our demos and pages when tabbing.
A lot of times, I as a Eufemia developer, test tabbing and tab order of different components, and when tabbing between demos or back and forth, I get stuck in an "infinite loop" when encountering a LiveEditor where tabbing results in indentation, which I have to "click myself out of"(video from v9):
https://user-images.githubusercontent.com/1359205/232060030-cc4235d3-7196-4be5-81f7-2020b0cc8063.mov
This PR removes the indenting when tabbing, when the LiveEditor is in focus(video with changes suggested in this PR):
https://user-images.githubusercontent.com/1359205/232060287-d6e90609-2a7c-415e-ae1d-8db43dc0888e.mov
I did consider removing tabbing to focus the LiveEditor(tabIndex="-1") …
=> chore(LiveEditor): remove indenting when tabbing

packages/dnb-design-system-portal/src/docs/contribute/first-contribution/before-started.mdx, packages/dnb-design-system-portal/src/docs/contribute/getting-started/making-changes.mdx, packages/dnb-design-system-portal/src/docs/uilib/elements.mdx, packages/dnb-design-system-portal/src/docs/uilib/elements/anchor.mdx, packages/dnb-design-system-portal/src/docs/uilib/elements/heading.mdx, packages/dnb-design-system-portal/src/docs/uilib/elements/image.mdx, packages/dnb-design-system-portal/src/docs/uilib/elements/lists.mdx, packages/dnb-design-system-portal/src/docs/uilib/elements/paragraph.mdx, packages/dnb-design-system-portal/src/docs/uilib/intro/12-usage-of-components-elements.mdx, packages/dnb-design-system-portal/src/docs/uilib/typography.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/styling.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/first-steps/react.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/first-steps/the-basics.mdx
This PR is far from completed, and is just a starting point for now 🏃‍♂️ 
To wait for:
- Making sure all components(previously known as elements) is exported from root `'@dnb/eufemia'`.
TODO:
- Double-check more docs, looking for references to `/elements`.
- Update internal links to from `/uilib/elements/tables` to like `/uilib/components/tables` ?
=> docs: remove docs about importing from /elements

packages/gatsby-plugin-eufemia-theme-handler/gatsby-node.js
=> chore: avoid CLI logs where we get several of the same brands

packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.screenshot.test.ts, packages/dnb-eufemia/src/components/form-row/__tests__/FormRow.screenshot.test.ts, packages/dnb-eufemia/src/elements/anchor/__tests__/Anchor.screenshot.test.ts
Remove !isCi check from screenshot tests, as the new testing setup with playwright and firefox may have invalidated the need for it.
=> chore: remove !isCi check from screenshot tests

packages/dnb-design-system-portal/src/core/PortalProviders.tsx, packages/dnb-design-system-portal/src/docs/brand/development.mdx, packages/dnb-design-system-portal/src/docs/brand/development/import-styles.mdx, packages/dnb-eufemia/src/shared/Theme.tsx, packages/dnb-eufemia/src/style/core/scopes.scss, packages/dnb-eufemia/src/style/themes/theme-sbanken/customisations.scss, packages/dnb-eufemia/src/style/themes/theme-sbanken/sbanken-theme-basis.scss, packages/dnb-eufemia/src/style/themes/theme-sbanken/theme-mapping.scss, packages/gatsby-plugin-eufemia-theme-handler/themeHandler.js
The idea behind this is that it will make theming more flexible.
Right now we only make a wrapper for custom properties, and not for style properties (component themes).
In the file `themeHandler.js` we add a "fix" so the theme does switch properly (It works fine with React v18, but its more work to switch over to v18, as there are TypeScript issues related to Context popping up as well).
=> chore: put sb properties inside a theme wrapper

packages/dnb-design-system-portal/gatsby-node.js, packages/dnb-design-system-portal/src/core/PortalStylesAndProviders.js, packages/dnb-design-system-portal/src/uilib/search/searchHelpers.js, tools/repo-utils/node-utils.js
In prod vi target the "dev" index. This PR changes the target to be "prod".
The problem was that process.env.CI could not picket up in fornt-end code. We now use the define plugin from Webpack, to do so.
Closes #2253
=> chore(Portal): fix Algolia search

packages/dnb-design-system-portal/src/docs/uilib/demos/eufemia-demo/form-demo-01.js
I could not see the issues anymore. I guess there was an issue with our CSS setup, which has been resolve in that case.
Closes #2174
This PR fixes this issue:
---
---
=> chore: fix demo example

packages/dnb-eufemia/src/components/date-picker/DatePickerAddon.js, packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
A proposal that fixes this [this issue](https://github.com/dnbexperience/eufemia/issues/2189) where the toggle buttons gave a confusing false impression of multi-select functionality. The toggle buttons have been swapped out with secondary buttons
https://user-images.githubusercontent.com/25927156/234867012-47e603f4-42d8-4cce-8006-17792e68352b.mov
=> fix(DatePicker): shortcut buttons

packages/dnb-design-system-portal/src/docs/brand/development.mdx, packages/dnb-design-system-portal/src/docs/contribute/style-guides/documentation.mdx, packages/dnb-design-system-portal/src/shared/tags/FilterByTheme.tsx, packages/dnb-design-system-portal/src/shared/tags/index.js
With that, we can show demos/text based on the choose theme. So we can put e.g. this in a MDX file, without importing it:
```mdx
<FilterByTheme name="sbanken">
Text and Demos
</FilterByTheme>
... more shared stuff
```
What component name would you else recommend? (instead of `FilterTheme`)
=> chore(Portal): add FilterByTheme as a global component

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js, packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
The intention is to release this fix in v9.
The tests are added in PR #2269 to avoid git conflicts.
=> fix(InputMasked): on custom mask – avoid interaction stall after focus

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js, packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js, packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx
Add as `chore` as we release the original in v9 with PR #2270
=> chore(InputMasked): on custom mask – avoid interaction stall after focus

packages/dnb-eufemia/src/components/date-picker/DatePickerFooter.js
A proposal to fix [this issue](https://github.com/dnbexperience/eufemia/issues/2268) where the old padding of 0.5rem applied by the `.dnb-button--icon-position-left ` has disappeared for whatever reason. 
Closes #2268
At the moment solved by adding a `right` prop to the buttons with a value of 0.5rem
=> fix(Datepicker): reset and cancel button gap

packages/dnb-design-system-portal/src/docs/uilib/components/skip-content.mdx
Hiding the "Events" tab, as it doesn't exist/have any content.
=> docs(SkipContent): hide Events tab

packages/dnb-eufemia/scripts/tools/cliTools.js
During the release of a beta, we get a [git error](https://github.com/dnbexperience/eufemia/actions/runs/4892791322/jobs/8734965454) on the postbuild step. This PR disables the limit. That results that the test takes about a minute locally. But we don't run this locally normally, and it only happens now that we have so many file changes from the v10 branch.
=> chore: disable diff limit on postbuild test

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/Examples.tsx, packages/dnb-eufemia/src/components/date-picker/DatePickerAddon.js, packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap, packages/dnb-eufemia/src/components/date-picker/style/dnb-date-picker.scss
Make it so that the DatePicker addon container controls the shortcut button spacing, instead of using the spacing props on the buttons themselves
Before:
_All rights reserved @langz_
After:
=> chore(DatePicker): fix datepicker shortcut buttons spacing

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.d.ts
This is just a proposal to solve the typescript error shown in the image below
It might be to correct way to solve this, or it might not need to be solve at all. But I feel that this approach is more specific than using ` Record<string, unknown>`.
`
React.MutableRefObject<HTMLInputElement | undefined>` vs ` Record<string, unknown>`.
=> chore(Autocomplete): update autocompleteinputref type

packages/dnb-eufemia/src/shared/VisibilityByTheme.tsx, packages/gatsby-plugin-eufemia-theme-handler/themeHandler.tsx
This fixes temporarily an React hydration issue seen in PR #2318 and #2319
=> chore: fix VisibilityByTheme React hydration issue

packages/dnb-eufemia/src/components/toggle-button/ToggleButton.d.ts
Continuation of https://github.com/dnbexperience/eufemia/pull/2315/files
Based on what's done in https://github.com/dnbexperience/eufemia/pull/2315/files, I believe the import statement in this file should be `Button` and not `button`. Not 100% sure though.
Or maybe it should be `button/Button`? 🤔
=> chore: fix button types in import from /components/Button

.github/ISSUE_TEMPLATE/bug.md, packages/dnb-eufemia/scripts/prebuild/tasks/__tests__/makeReleaseVersion.test.ts, packages/dnb-eufemia/src/shared/Eufemia.js
With that we can with that log what version of the package is imported:
```js
const { version } = require('@dnb/eufemia/shared/Eufemia')
console.log('Eufemia version:', version)
```
=> feat: expose package version to Node.js

packages/dnb-eufemia/src/shared/VisibilityByTheme.tsx
Right now we get a React warning during development about using useEffect in an unmounted component. 
This PR should fix this.
=> chore: run React hydration fix only on prod build

packages/dnb-design-system-portal/src/docs/uilib/components/anchor/properties.mdx, packages/dnb-design-system-portal/src/shared/tags/Anchor.tsx, packages/dnb-eufemia/src/components/anchor/Anchor.tsx, packages/dnb-eufemia/src/components/anchor/__tests__/AnchorScroll.test.tsx
This PR/RFC is regarding Anchor animated scrolling.
Chromium/Blink based browser to not support smooth scrolling by default. And on macOS/iOS it's not supported at all.
The Eufemia Portal did have code that makes it possible to get this feature. Its a relative small fix. And most of the code has existed as a Portal anchor link for several years already. 
The question is, should we get this in to the Anchor component? I guess yes. But then, how?
**Opt-in**
But this feature may be interesting for projects as well. But we may debate if it should not be available via a prop, be imported and spread to all anchors via a context.
**Opt-out**
On the other hand, it may be interesting to have this as an opt-out feature, as it solves and issue most are not aware of.
Closes #2286
=> feat(Anchor): add `scrollToHash` feature

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/help-button/properties.mdx, packages/dnb-eufemia/src/components/help-button/HelpButton.tsx, packages/dnb-eufemia/src/components/help-button/__tests__/HelpButton.test.tsx, packages/dnb-eufemia/src/components/help-button/stories/HelpButton.stories.tsx
BREAKING CHANGE:
HelpButton has two props which where removed: `modal_props` or `modal_content`.
=> feat(HelpButton): remove `modal_props` in favour of `render`

packages/dnb-design-system-portal/src/docs/quickguide-designer/colors-table.mdx, packages/dnb-design-system-portal/src/docs/quickguide-designer/colors.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/colors.mdx
Added color table for Sbanken and tweaked documentation slightly. Used `<VisibilityByTheme>` to switch table and docs by theme.
=> docs: Add Sbanken color table and -documentation

packages/dnb-design-system-portal/src/docs/uilib/components/help-button/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/components/help-button/properties.mdx
Reason why I like this, is only because of TypeScript. So that if we change HelpButton or render prop in the future, it's easier to find necessary changes in our docs.
=> chore(HelpButton): make render example ts

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap, packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap, packages/dnb-eufemia/src/components/form-status/FormStatus.js, packages/dnb-eufemia/src/components/form-status/__tests__/__snapshots__/FormStatus.test.tsx.snap, packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.tsx.snap
Reported as such in the CLI when running the tests:
> Warning: React does not recognize the `globalStatus` prop on a DOM element.
=> chore(FormStatus): remove globalStauts prop from HTML attributes

packages/dnb-design-system-portal/src/core/ChangeStyleTheme.tsx, packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/dnb-ui-lib/v7.2-info.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming/theme.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming/theme/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming/theme/demos.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming/theme/info.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming/theme/properties.mdx, packages/dnb-design-system-portal/src/shared/menu/PortalToolsMenu.js, packages/dnb-eufemia/src/shared/Theme.tsx, packages/dnb-eufemia/src/shared/__tests__/Theme.test.tsx
+ docs(Theme): create dedicated pages
+ Rename `colorMapping` to `propMapping` because we may map other properties as well
=> feat(Theme): add `darkMode` and `contrastMode` props

packages/dnb-design-system-portal/package.json, yarn.lock
This fixes an issue where `console.log(e)` got additional code from Babel, which executed a runtime exception.
Related [PR](https://github.com/dnbexperience/babel-plugin-react-live/pull/6/files).
=> chore(Portal): upgrade to latest React Live Plugin

packages/dnb-design-system-portal/package.json, yarn.lock
More info about the fix: https://github.com/dnbexperience/babel-plugin-react-live/commit/8bba66668921b3ad92b5abe83f7ca7b6ff5937c8
=> chore: upgrade dep to avoid console ninja injection when used without ESLint comment

packages/dnb-design-system-portal/cypress/e2e/themeSwitch.cy.ts, packages/dnb-design-system-portal/gatsby-config.js, packages/dnb-eufemia/src/components/button/__tests__/Button.screenshot.test.ts, packages/gatsby-plugin-eufemia-theme-handler/inlineScriptProd.mjs, packages/gatsby-plugin-eufemia-theme-handler/themeHandler.tsx
This effects only the prod build. From what I'v seen during the period we had this enabled– loading the needed CSS via a file, delays other resources and gives us a much worse UX. For sure, only on the first couple of seconds. So I suggest to rather load a little more CSS, when switching the theme.
Update: Looks like the tests would have to be updated as well.
=> chore(Portal): load the DNB UI theme as embedded CSS

packages/dnb-eufemia/src/components/progress-indicator/__tests__/ProgressIndicator.test.tsx
Not sure how to replace the following "snapshot tests" yet, so I've waited with replacing these:
```
it('have to match snapshot', () => {
const Comp = mount(
<Component {...props} type="circular" progress={50} />
)
expect(toJson(Comp)).toMatchSnapshot()
})
```
We'll probably change all of these in all our tests once we figure out how to do it.
=> chore(ProgressIndicator): rewrite tests @testing-library/react

packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap, packages/dnb-eufemia/src/components/radio/__tests__/__snapshots__/Radio.test.js.snap, packages/dnb-eufemia/src/components/radio/style/_radio.scss, packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.js.snap
When Radio.Group has props vertical and layout_direction: column long labels causes the radio button to be unaligend. This is caused by width getting shrunk to avoid text overflowing.
Setting `flex-shrink: 0` on `dnb-radio__shell` will prevent the radio buttons width getting shrunk.
=> fix(Radio): prevent radio button from shrinking

packages/dnb-eufemia/jest.config.screenshots.js, packages/dnb-eufemia/src/core/jest/jestSetupScreenshots.js
Proposal solution for giving developers more time to inspect screenshot tests in the browser window, when not running the tests in headless
=> chore: add configurable timeout for screenshot tests that are not headless

packages/dnb-eufemia/scripts/figma/FigmaAPI.js, packages/dnb-eufemia/scripts/figma/helpers/docHelpers.js, packages/dnb-eufemia/scripts/figma/resetIcons.js, packages/dnb-eufemia/scripts/figma/tasks/assetsExtractors.js, packages/dnb-eufemia/scripts/lib/error.ts, packages/dnb-eufemia/scripts/prebuild/generateTypes.js, packages/dnb-eufemia/scripts/prebuild/index.js, packages/dnb-eufemia/scripts/prebuild/tasks/prepareTemplates.js, packages/dnb-eufemia/scripts/prebuild/tasks/styleFactory.ts, packages/dnb-eufemia/scripts/prebuild/tasks/themeFactory.ts, packages/dnb-eufemia/src/components/icon/Icon.js
- Don't use `new` when we expect a string, as it does not work with TS.
- So go purely with a function, I think is just as  fine.
=> chore: make ErrorHandler work with TypeScript

packages/dnb-eufemia/src/components/checkbox/__tests__/Checkbox.test.tsx, packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx, packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.tsx, packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap, packages/dnb-eufemia/src/components/form-label/__tests__/FormLabel.test.tsx, packages/dnb-eufemia/src/components/form-row/__tests__/FormRow.test.tsx, packages/dnb-eufemia/src/components/form-set/__tests__/FormSet.test.tsx, packages/dnb-eufemia/src/components/form-status/__tests__/FormStatus.test.tsx, packages/dnb-eufemia/src/components/global-status/__tests__/GlobalStatus.test.tsx, packages/dnb-eufemia/src/components/icon-primary/__tests__/IconPrimary.test.tsx, packages/dnb-eufemia/src/components/icon/__tests__/Icon.test.tsx, packages/dnb-eufemia/src/components/input/__tests__/Input.test.tsx, packages/dnb-eufemia/src/components/input/__tests__/InputPassword.test.tsx, packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx, packages/dnb-eufemia/src/components/pagination/__tests__/Pagination.test.tsx, packages/dnb-eufemia/src/components/progress-indicator/__tests__/ProgressIndicator.test.tsx, packages/dnb-eufemia/src/components/skeleton/__tests__/Skeleton.test.tsx, packages/dnb-eufemia/src/components/step-indicator/__tests__/StepIndicator.test.tsx, packages/dnb-eufemia/src/components/switch/__tests__/Switch.test.tsx, packages/dnb-eufemia/src/components/tabs/__tests__/Tabs.test.tsx, packages/dnb-eufemia/src/components/toggle-button/__tests__/ToggleButton.test.tsx, packages/dnb-eufemia/src/extensions/payment-card/__tests__/PaymentCard.test.tsx, packages/dnb-eufemia/src/fragments/drawer-list/__tests__/DrawerList.test.tsx, packages/dnb-eufemia/src/fragments/drawer-list/__tests__/__snapshots__/DrawerList.test.tsx.snap
I've gotten two failed ARIA tests, even though all I changed was from mount to render:
- [Dropdown](https://github.com/dnbexperience/eufemia/actions/runs/5214548393/jobs/9410953143?pr=2453#step:9:78)
- [DrawerList](https://github.com/dnbexperience/eufemia/actions/runs/5214548393/jobs/9410953143?pr=2453#step:9:124)
Will probably have to look into these, and how/why they now fail.
What's your initial thought @tujoworker?
I think I'll .skip them for now, so that I can continue with other work, and then open a new PR where I enable them again 🙏
=> chore: rewrite axe tests @testing-library/react

packages/dnb-design-system-portal/cypress/e2e/typography.cy.ts, packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/font-families.mdx, packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/font-weights.mdx, packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/typographic-elements.mdx, packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/typographic-rules.mdx, packages/dnb-design-system-portal/src/shared/parts/PortalStyle.scss
Added documentation for Sbanken typography and fixed a few bugs and inconsistencies for the line-height docs in all themes, and involuntary markup changes caused by line breaks done by prettier.
=> chore: correct Sbanken typography docs

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx, packages/dnb-eufemia/src/components/form-status/stories/FormStatus.stories.tsx
First time reported in Slack: https://dnb-it.slack.com/archives/CMXABCHEY/p1686124109235509
Using `status_props={{ stretch: true }}` in a Autocomplete which uses suffix results in a not fully stretched form status message.
Today, we calculate some kind of `maxWidth` for the `FormStatus`, based on ["the "linked mother"".](https://github.com/dnbexperience/eufemia/blob/f435633c73bb8d9e57c6663d8207fb95e0de00dc/packages/dnb-eufemia/src/components/form-status/FormStatus.js#L308)
For the `Autocomplete` with a `FormStatus`, it always uses the width of the `<input/>` to calculate the max width of the `FormStatus` which is applied in the `style` prop. 
This usually works perfectly fine, as the `<input/>` used/rendered in `Autocomplete` is "usually" as wide as the parent`Autocomplete` itself. …
=> fix(Autocomplete): fix stretched form status when using suffix

packages/dnb-eufemia/scripts/prebuild/tasks/__tests__/convertSvgToJsx.test.tsx
I've had the following errors when running tests locally for quite some time.
Fixes the following errors when running these tests locally:
=> chore(convertSvgToJsx): fixes errors running ES6 to ES5 conversion

packages/dnb-eufemia/src/components/step-indicator/StepIndicatorSidebar.d.ts, packages/dnb-eufemia/src/components/step-indicator/__tests__/StepIndicator.test.tsx
Fixes the following ts error:
```
Warning: Failed prop type: The prop `sidebar_id` is marked as required in `StepIndicatorProvider`, but its value is `undefined`.
at StepIndicatorProvider (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/step-indicator/StepIndicatorContext.js:103:5)
at StepIndicatorSidebar (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/step-indicator/StepIndicatorSidebar.js:19:71)
at children (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/shared/Provider.tsx:26:11)
```
Screenshot:
=> chore: fixes ts error in stepindicator test

packages/dnb-eufemia/src/components/anchor/style/themes/dnb-anchor-theme-sbanken.scss
Some small changes to increase compatability between anchor themes, reducing css specificity of some sbanken theme rules so they don@t override others. Mainly to make things compatible with eufemia theming in [style/eufemia-site-sbanken-theme](https://github.com/dnbexperience/eufemia/tree/style/eufemia-site-sbanken-theme)
=> chore(Anchor): better theme compatability

.github/workflows/codeql-analysis.yml
Based on info from this PR #2456 action run.
=> chore(ci): run CodeQL on PRs when branch is dependabot

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/demos.mdx
Not sure why this example said "disabled".
As the example code did not render a disabled DatePicker 🤔 👱‍♂️
=> docs(DatePicker): removes disabled from example description

packages/dnb-eufemia/src/shared/index.tsx
Exported `ThemeNames` type so that it's included in the Eufemia package.
=> chore: export ThemeNames type

.github/workflows/e2e.yml
Ensure we actually run the "postbuild" step on the main (and e.g. v10) branch only. This corrects the code as it was intended to be, because we need to check against a string, and not a boolean.
With that change, we should safe about 2.5 min on normal PR branches.
Also, we run the "postbuild" step in the **Verify** action anyway.
=> chore(CI): fix postbuild run in e2e action

packages/dnb-design-system-portal/src/shared/tags/AutoLinkHeader.module.scss
After the change of this PR:
Before:
=> chore(Portal): correct heading hash anchor padding

packages/dnb-eufemia/src/components/height-animation/HeightAnimationInstance.ts
A few of the `GlobalStatus` stories was breaking due to `null` values in `HeightAnimationInstance`.
Errors received when running the stories:
=> chore: fixes breaking globalstatus stories

packages/dnb-design-system-portal/src/docs/contribute/style-guides/documentation.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming/theme/info.mdx
=> docs: add docs on how to link to a specific theme

.github/workflows/e2e.yml
It looks like we need more time to wait for the artifacts to be uploaded.
=> chore: increase build timeouts

packages/dnb-eufemia/src/extensions/payment-card/stories/PaymentCard.stories.tsx
Redundant as all the alternatives is defined in the type itself, so I don't want to keep updating this when the type/enum gets updated.
=> chore(Storybook): redundant comment in PaymentCard story

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v11-info.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/section/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/components/section/demos.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/section/deprecated.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/section/properties.mdx, packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap, packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.tsx.snap, packages/dnb-eufemia/src/components/section/Section.tsx, packages/dnb-eufemia/src/components/section/__tests__/Section.screenshot.test.ts, packages/dnb-eufemia/src/components/section/__tests__/__snapshots__/Section.test.tsx.snap, packages/dnb-eufemia/src/components/section/style/dnb-section.scss, packages/dnb-eufemia/src/components/section/style/themes/dnb-section-theme-ui.scss, packages/dnb-eufemia/src/components/skip-content/__tests__/__snapshots__/SkipContent.test.tsx.snap
This is an addition to PR #2582
It's not given that this approach is the best solution. So let me know if we should change something about it or if there is a better approach.
=> docs(Section): move deprecated styles into a seperate docs page

packages/dnb-eufemia/src/extensions/forms/Layout/style/dnb-card.scss
=> fix(Forms): align card border

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber.tsx
At least from my tests, its much easier to find e.g. Switzerland with `41`.
=> fix(Forms): make PhoneNumber country code searchable by numbers

packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js, packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx, packages/dnb-eufemia/src/components/input/__tests__/Input.test.tsx
It should behave the same as a normal input.
But when given `<InputMasked value={null} placeholder="should be visible" />` the placeholder was not visible. While it is visible in a normal Input.
=> fix(InputMasked): ensure a value with null does not remove the placeholder

packages/dnb-eufemia/src/components/timeline/TimelineItem.tsx, packages/dnb-eufemia/src/components/timeline/__tests__/Timeline.test.tsx, packages/dnb-eufemia/src/components/timeline/stories/Timeline.stories.tsx
Previously it was not possible/difficult to update the state of a component inside a `subtitle` from another component inside a `subtitle`. This was fixed by extracting out all the internally declared components inside the `TimeLineItem`, making them their own standalone components inside the `TimeLineItem` file
=> fix(TimeLine): make it possible to update state of subtitle from another subtitle

packages/dnb-design-system-portal/src/docs/uilib/components/form-set.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/fragments/scroll-view.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/height-animation.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/help-button.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/pagination/infinity-scroller.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/skip-content.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/space.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/visually-hidden.mdx, packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.tsx
Several Eufemia components only exist to provide functionality, and does not need theming. This PR marks those components as Sbanken-ready. Below is a complete list.
- FormSet
- ScrollView (under Fragments)
- HeightAnimation
- HelpButton
- InfinityScroller (under Pagination)
- SkipContent
- Space
- VisuallyHidden
=> chore(Portal): Mark various components as Sbanken-ready

packages/dnb-eufemia/src/components/drawer/__tests__/Drawer.test.tsx, packages/dnb-eufemia/src/components/modal/parts/ModalHeaderBar.tsx
I'm actually not sure why we had this check to prevent it from rendering. Sadly, there was no comment in the code. Also, I can not find any tests proving this behavior. So in worst case, we "break" a layout by adding an additional spacing on top. 
If there is a need to prevent that, we should accommodate that with a more logical approach.
=> fix(Drawer): render Drawer.Navigation when hideCloseButton is true

packages/dnb-eufemia/src/elements/typography/style/themes/dnb-typography-theme-sbanken.scss
Sbanken heading font has a ligature that shows the logo on the word "Sbanken", this should be removed.
Currrent:
New:
=> feat(Heading): remove font ligatures for sbanken headings

packages/dnb-design-system-portal/src/docs/uilib/components/dialog/demos.mdx, packages/dnb-design-system-portal/src/docs/uilib/components/dialog/info.mdx
Changed `Dialog.Actions` to `Dialog.Action` in the docs.
=> docs(Dialog): Dialog.Actions to Dialog.Action

packages/dnb-design-system-portal/gatsby-config.js, packages/dnb-design-system-portal/gatsby-node.js, packages/dnb-design-system-portal/src/docs/contribute/first-contribution/before-started.mdx, packages/dnb-design-system-portal/src/e2e/pageNavigation.spec.ts
This PR:
- adds the possibility to start the portal with only some pages e.g.: `filter=/button yarn start`
- and it speeds up our e2e and visual tests by simply not building some docs pages.
The CI speed improvement is for sure only in the "build" step. There we safe 50% of the duration. We go from 16 min to 8 min. Also because the bundle is smaller, the upload and the download process of the artifacts is faster.
=> chore(Portal): add env variable "filter=/component-name" for faster dev builds

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap, packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.tsx.snap, packages/dnb-eufemia/src/components/progress-indicator/__tests__/__snapshots__/ProgressIndicator.test.tsx.snap, packages/dnb-eufemia/src/components/progress-indicator/style/dnb-progress-indicator.scss
Re-prod: https://codesandbox.io/s/busy-haibt-fwyzqg?file=/src/App.js
Because of the `position: absolute` used in the `svg` elements. When using special app CSS like `text-align: center`, we need to ensure the position gets not influenced/changed.
=> fix(ProgressIndicator): ensure correct positioning inside its boundary

packages/dnb-eufemia/src/components/modal/ModalContent.tsx
When debugging/using the Modal, I often get the following error/warning in the console:
```
Eufemia TypeError: Cannot read properties of null (reading 'focus')
at ModalContent.tsx:259:1
```
This PR tries to safeguard the usage of .focus(), so that we don't see the error/warning all the time
=> chore(Modal): safeguarding focusing element

packages/dnb-design-system-portal/src/shared/tags/CodeBlock.tsx
My console is full of warnings when running the portal(yarn start) locally:
I believe the reason for this is because label doesn't connect to one of the follow elements(as the code/live editor doesn't use any of these elements):
`Elements that can be associated with a <label> element include <button>, <input> (except for type="hidden"), <meter>, <output>, <progress>, <select> and <textarea>.` - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
=> chore: removes label of code editor

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/advanced-blocks/StepsLayout/NextButton/properties.mdx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/advanced-blocks/StepsLayout/PreviousButton/properties.mdx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/DataContext/SubmitButton/properties.mdx
I was not able to find any reference to these properties in any of our tests or actual source code, so I think it's safe to remove from the docs 🙏
=> chore(Forms): remove data-testid from components

.github/workflows/e2e.yml, .github/workflows/icons-lib.yml
Our `action-wait-for-check` did not wait anymore. So build did fail right away. To overcome this, we can simply upgrade the the latest version.
More info about the GitHub API change: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore(CI): ensure e2e to wait before build is finished

packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbMultiple.tsx
... when same text is used in two items.
=> fix(Breadcrumb): avoid React warning about duplication of key

.gitignore, packages/dnb-design-system-portal/src/e2e/fullscreen.spec.ts, packages/dnb-design-system-portal/src/e2e/responsiveness.spec.ts, packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.js, packages/dnb-design-system-portal/src/shared/parts/PortalStyle.scss, packages/dnb-design-system-portal/src/shared/tags/Anchor.tsx, packages/dnb-design-system-portal/src/shared/tags/Intro.tsx, packages/dnb-design-system-portal/src/shared/tags/Tabbar.tsx, packages/dnb-design-system-portal/src/shared/tags/Transition.ts
- Add [View Transition](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) support. Works only on chromium based browsers. Is a show-case for other DNB projects. The portal does not need such improvements I would argue. 
- Some more link usage alignment to be able to call the `startViewTransition`  APIon just two places.
=> docs(Portal): add View Transition

packages/dnb-eufemia/src/core/jest/jestPuppeteerEnvironment.js, packages/dnb-eufemia/src/core/jest/jestSetupScreenshots.js
Probably, after we switched from puppeteer to playwright (PR #1945), our retry mechanism did not work as it should anymore. So retries did nothing more than making a new screenshot.
With this PR, we refresh the page during the retry moment. I hope this will help to make visual tests fail less.
=> chore(CI): makes visual tests less flaky 

packages/dnb-design-system-portal/src/docs/uilib/extensions/payment-card.mdx, packages/dnb-design-system-portal/src/docs/uilib/extensions/payment-card/helpers.mdx
This PR adds the `formatCardNumber` to our docs in the portal.
Here's a quick link to test/look at the new docs for `formatCardNumber` in the deploy preview:
https://eufemia-git-docs-add-docs-about-the-format-card-580b8c-eufemia.vercel.app/uilib/extensions/payment-card/helpers/
=> docs(PaymentCard): adds docs for formatCardNumber function

packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.d.ts
Firstly, I just wanted to correctly export the type for `getCardData`, which I did by doing `export const getCardData :` instead of `export const getCardData =`. 
Then after correctly exporting the type, we got a few type errors in our Examples and stories, related to `cardDesign`, hence updating the type for this.
=> fix(PaymentCard): correctly export type for getCardData function

packages/dnb-design-system-portal/package.json, yarn.lock
With [this release](https://github.com/dnbexperience/gatsby-plugin-eufemia-theme-handler/pull/14).
=> chore(Portal): remove commons for appearing in the build logs

.github/workflows/e2e.yml
Just because, we have the time. And with that, we run one stripped build for the visual tests (to save total time) and one full build for the playwright e2e tests. Witch is a perfect match.
=> chore(CI): make a full build for the playwright e2e tests

packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.d.ts, packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js, packages/dnb-eufemia/src/extensions/payment-card/__tests__/PaymentCard.test.tsx
Before this PR the function `formatCardNumber` would return excess/surrounding space around the result(formatted card number).
Like: `formatCardNumber('************1337')` would result in `' **** **** **** 1337 '`.
After this PR, the same function will result in `'**** **** **** 1337'`.
=> fix(PaymentCard): removes excess space when formatting card number

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/demos.mdx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/properties.mdx, packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity.tsx
Not 100% sure which commit decoration I should use(chore vs. feat), I would normally use feat, but since this is under the "beta flag" 🤔 ....
=> chore(PostalCodeAndCity): adds support for help prop

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/demos.mdx, packages/dnb-eufemia/src/components/date-picker/DatePickerInput.js, packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
Fixes the following "possible improvement" from Chrome's console:
```
No label associated with a form field
A <label> isn't associated with a form field.
To fix this issue, nest the <input> in the <label> or provide a for attribute on the <label> that matches a form field id.
```
=> chore(DatePicker): fix no label associated with a form field

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/ArraySelection/info.mdx
1. We don't need to link to the same page as the user is in.
2. I don't think there exists a Value.ArraySelection hence me just removing the link, instead of changing it to link to "Value.ArraySelection".
=> docs(ArraySelection): removes redundant/circular link

packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx, packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useDataValue.test.ts, packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
When a custom component was build using `useDataValue` without calling focus and blur callbacks, like if forgotten during development, or for interfaces where it is not possible (like based on one time clicks), validation was performed, but the error was never displayed because the hook was waiting for a blur event to actually return the error. Fix: If focus has not been called before a change callback, assume the events are not being used so show the error message as long as the value is invalid (unless `continuousValidation` is false). I added tests for this in a separate test file for the `useDataValue` hook since the existing field compoinents like `Field.String actually call focus/blur.
=> fix(forms): Handle error display when no focus and blur events is called

packages/dnb-eufemia/src/elements/typography/Lead.tsx, packages/dnb-eufemia/src/elements/typography/__tests__/Lead.test.tsx
The `Lead` component  can now receive a `className` prop without losing its own `.dnb.p--lead` class. Adding custom classes or using styled components should now work as expected.
=> fix(Lead): can now accept className prop without losing styling

.github/workflows/e2e.yml
Right now, it looks like all of our [CI runs do fail](https://github.com/dnbexperience/eufemia/actions/runs/6497006953/job/17650511962?pr=2746). 
The reason is a new Firefox binary released, which gets downloaded during the deps install – but the new version gets not installed after the download. This PR fixes the issue. 
All failing PR's needs then a rebase.
=> chore(CI): fix Firefox binary install issue

packages/dnb-eufemia/src/components/step-indicator/StepIndicatorContext.tsx, packages/dnb-eufemia/src/components/step-indicator/__tests__/StepIndicator.test.tsx
It looks like the StepIndicator does not react to changes in the `is_current` data property
=> fix(StepIndicator): react on changes to `is_current` data property

packages/dnb-eufemia/src/extensions/forms/Form/Handler/Handler.tsx
So we are able to use `<form>` element attributes, such as `action`.
=> chore(Forms): fix types for Form.Handler

packages/dnb-eufemia/src/components/form-label/FormLabel.d.ts, packages/dnb-eufemia/src/components/form-row/FormRow.d.ts, packages/dnb-eufemia/src/components/form-set/FormSet.d.ts, packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.d.ts
- Update outdate docs linking; FormRow and FormSet where moved and do not have the same path, as the component, so they can not be found. But I think thats fine as they are deprecated.
- Correct PaymentCard types as they fail during the docs update routine. We still have a valid syntax and it works fine with TypeScript.
=> chore: various local build related updates

packages/dnb-design-system-portal/src/docs/uilib/layout/media-queries.mdx, packages/dnb-eufemia/src/shared/__tests__/useMedia.test.tsx, packages/dnb-eufemia/src/shared/useMedia.tsx
To avoid rehydration disturbance. The return values like `isSmall` will now always be false to start with. 
This should not be a breaking change, because on the client, it results as before.
I have not tested this hook IRL. Maybe someone can do that for me?
=> fix(useMedia): enhance SSR support by setting state during component mount

packages/dnb-design-system-portal/src/docs/uilib/helpers.mdx, packages/dnb-design-system-portal/src/docs/uilib/helpers/classes.mdx, packages/dnb-design-system-portal/src/docs/uilib/helpers/functions.mdx, packages/dnb-design-system-portal/src/docs/uilib/helpers/sass.mdx, packages/dnb-design-system-portal/src/docs/uilib/helpers/tools.mdx, packages/dnb-eufemia/src/style/core/utilities.scss
* Adds global or parameter customization for mixins `allAbove()` and `allBelow()` 
Will only works for the app's own stylesheets, won't retroactively affect imported Eufemia components.
```scss
@import '@dnb/eufemia/style/core/utilities.scss';
// allAbove() and allBelow() will subtract -10em from the size
$breakpoint-offset: -10em;
// the sizes 'medium' and 'large' for allAbove() and allBelow() are changed.
$breakpoints: map-merge(
$breakpints,
(
'medium': 40em,
'large': 90em,
)
);
```
```scss
@import '@dnb/eufemia/style/core/utilities.scss';
@include allAbove($size: small, $offset: 10em) {
// adds 10em to $size
}
```
=> feat(breakpoints): media query mixin offset options

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Boolean/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Boolean/demos.mdx, packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
Before, passing no value defaulted to the `valueOff` option in `Field.Toggle`, leading to the same in `Field.Button` (false option being chosen). Now, no buttons is selected when value is undefined.
=> fix(forms): Support undefined in toggle and button fields

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/FieldBlock/properties.mdx, packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx, packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx
This makes it possible to "force" FieldBlock to act as a "fieldset" with a legend, instead of label.
I'm not sure about the property name. Is there any better alternative?
=> fix(FieldBlock): add asFieldset property to force use fieldset/legend

packages/dnb-eufemia/src/components/upload/Upload.tsx, packages/dnb-eufemia/src/components/upload/__tests__/Upload.test.tsx, packages/dnb-eufemia/src/shared/locales/en-GB.js, packages/dnb-eufemia/src/shared/locales/nb-NO.js
This PR adds singular texts/translations (file instead of files, etc) in the Upload component, when the `filesAmountLimit` is 1.
The changes can be seen and tested here: https://eufemia-git-feat-provide-singular-texts-in-uploa-6743ea-eufemia.vercel.app/uilib/components/upload/demos/#upload-single-filefixed-amount-of-files
From:
To:
=> feat(Upload): singular texts when uploading single file

packages/dnb-eufemia/src/extensions/forms/Field/Boolean/__tests__/Boolean.test.tsx, packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
Because of accessibility reasons, we should always use ToggleButtons when toggling a state. From a screen reader perspective – but also how the CSS behaves while toggling.
New:
Old:
=> fix(forms): enhance accessibility by using toggle buttons

.github/workflows/e2e.yml
Because it taks way too long, and we almost never use it. In most cases we should be able to easily reproduce the CI behavior locally.
=> chore(CI): remove upload artefact on e2e tests

packages/dnb-eufemia/src/components/toggle-button/ToggleButton.d.ts, packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx, packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx, packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
Like PR #2781 – but this time for Selection.
=> fix(forms): Selection accessibility enhancement by using toggle buttons

packages/dnb-design-system-portal/src/docs/design-system/changelog/info-about-releases.mdx, packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases.mdx, packages/dnb-design-system-portal/src/docs/uilib/info/about-watching-releases.mdx, packages/dnb-design-system-portal/src/docs/uilib/usage/first-steps.mdx, packages/dnb-design-system-portal/src/shared/tags/index.tsx
From:
To:
Related component changes in PR to make it work for the Sbanken theme: https://github.com/dnbexperience/eufemia/pull/2797
=> docs: display anchors with icons using Anchor's icon prop

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js, packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx, packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx
Ensure that when setting `decimalSymbol={undefined}` the default behavior still works, which is e.g. using a coma or dot, based on the given locale.
=> fix(NumberMask): as_number should default to locally given decimalSymbol

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v11-info.mdx, packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx, packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx, packages/dnb-eufemia/src/components/breadcrumb/stories/Breadcrumb.stories.tsx, packages/dnb-eufemia/src/components/button/Button.d.ts
I believe/hope this should fix the reported issue here: https://github.com/dnbexperience/eufemia/pull/2676/files#r1368576095
=> fix(Breadcrumb): Pass rest props to item when not interactive

packages/dnb-eufemia/src/components/flex/Flex.tsx, packages/dnb-eufemia/src/components/grid/Grid.ts, packages/dnb-eufemia/src/components/grid/index.ts, packages/dnb-eufemia/src/components/grid/stories/Grid.stories.tsx
https://dnb-it.slack.com/archives/CMXABCHEY/p1698744253915779
Fixes the following error in TS, when trying to import and use Flex.X like `Flex.Container`:
`Property 'Container' does not exist on type 'typeof import("<my_path>/node_modules/@dnb/eufemia/components/flex/Flex")'.`
Reprod [CSB](https://codesandbox.io/s/eufemia-grid-jchqg7?file=/src/App.tsx).
=> fix(TypeScript): fix Grid and Flex export

packages/dnb-eufemia/src/components/section/__tests__/__snapshots__/Section.test.tsx.snap, packages/dnb-eufemia/src/components/section/style/themes/dnb-section-theme-sbanken.scss, packages/dnb-eufemia/src/components/section/style/themes/dnb-section-theme-ui.scss
Whit this PR we do miss out of a valid fallback, when an invalid `style_type` was given (regarding the issue in the Portal Tools on the Sbanken brand theme).
```
<Section style_type="invalid">
will be white now, instead of black
</Section>
```
=> chore(Section): ensure invalid style_type has still a valid fallback

packages/dnb-design-system-portal/src/docs/uilib/extensions/payment-card/properties.mdx
I did a quick analysis, trying to figure out if `card_number` actually is optional(as the docs says) or required.
But it looks to me as `card_number` is actually required from the code's point of view:
- https://github.com/dnbexperience/eufemia/blob/main/packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js#L63
- https://github.com/dnbexperience/eufemia/blob/main/packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.d.ts#L88
=> docs(PaymentCard): sets card_number as required

packages/dnb-eufemia/src/components/button/Button.d.ts, packages/dnb-eufemia/src/components/button/stories/Button.stories.tsx
This is just a "quick fix", making it possible in TypeScript to send `Link` of react-router-dom as a value to the `element` prop.
This possibility was removed as part of https://github.com/dnbexperience/eufemia/commit/e030657cd362c42fbb8af79aa11ef4115f511b9e
I'm not 100% sure about this fix(as I've just reverted(added back `any`) from this https://github.com/dnbexperience/eufemia/commit/e030657cd362c42fbb8af79aa11ef4115f511b9e#diff-ece10293b585707067686d660cf459378b2027585fc414e1263e9694b0ed0be2L38
First reported here: https://dnb-it.slack.com/archives/CMXABCHEY/p1699274667145269
I think/hope we could release this as part of v10.11.1(or v10.12.0?), as the reporters are eager for a fix 🙏 
Seems like the "problem" was introduced in v10.10.0, should we also try making a release v10.10.1 for …
=> fix(Button): element's type supports Link of react-router-dom

packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap, packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
Proposal to fix the incorrect input hover effects when hovering over the `legend` element  the `.dnb-input__shell` focus-within trigger, caused by the `fakeBorder`-mixin applying a `inset` to the `box-shadow` style.
Before:
After:
=> fix(MultiInputMask): incorrect legend hover and focus within effect

packages/dnb-eufemia/src/fragments/drawer-list/__tests__/DrawerList.test.tsx
Adds a test to test the following line of code: https://github.com/dnbexperience/eufemia/blob/1cd6be4fdd39c9424365e2d9b394ecf0e34d2740/packages/dnb-eufemia/src/fragments/drawer-list/DrawerListProvider.js#L1266
=> chore: add on_change test when for selecting selected item

packages/dnb-design-system-portal/src/docs/quickguide-designer/naming-conventions.mdx, packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/font-families.mdx, packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/font-weights.mdx, packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/line-height.mdx, packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/typographic-elements.mdx, packages/dnb-design-system-portal/src/docs/uilib/typography/Examples.tsx, packages/dnb-design-system-portal/src/shared/parts/TypographyBox.tsx, packages/dnb-design-system-portal/src/shared/tags/index.tsx
When running `/quickguide-designer/fonts/#font-weights` [locally](http://localhost:8000/quickguide-designer/fonts/#font-weights), I get the following errors:
```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
at p
at ElementInstance
```
What's happening is that `\n` somehow gets inserted when a prettier formats a `<p>`, leading to the content being wrapped in a `<p>`, so that we get `<p>`'s inside of `<p>`'s.
Here's a link to a related issue: https://github.com/storybookjs/storybook/issues/18921 
If this would only lead to the console error pasted above, it all would be fine, but in some scenarios when wrapping a `p` in a `p`, the visual result is actually different(so what's displayed in the docs is actually not what we want), compare the …
=> docs: fix font docs

packages/dnb-eufemia/package.json, yarn.lock
When typechecking an app or library in a monorepo that uses Eufemia, typechecking can fail in certain scenarios, even if all packages uses the same version of Eufemia.
Example:
app-1 uses:
@dnb/eufemia 10.9.0
react 18.2.0
@types/react 18.2.37
app-2 uses:
@dnb/eufemia 10.9.0
react 17.0.2
@types/react 17.0.70
The use of multiple React versions works fine, since Eufemia has peer dependency on react, so this is linked correctly per app.
But since Eufemia does not define a peerDependency on @types/react, the type information for Typescript can resolve to the wrong @types/react package, which can cause issues when the code is typechecked (during builds, tests or pure typechecking).
----
I have made a fairly simple monorepo reproduction repo here: …
=> fix: typescript react type resolution in monorepos

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx, packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
Added a test for the issue https://github.com/dnbexperience/eufemia/issues/2850
Not 100% sure about the actual fix yet 🤔 
If someone else has a clue, please give it a go, and add a commit to this branch 🙇 
---
Update:
- This PR relies on PR #2863
- Fixes #2862 and #2850
=> fix(PhoneNumber): ensure correct selection of value

packages/dnb-design-system-portal/src/docs/uilib/components/autocomplete/methods.mdx, packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js, packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx, packages/dnb-eufemia/src/components/autocomplete/stories/Autocomplete.stories.tsx
Added a test for the issue https://github.com/dnbexperience/eufemia/issues/2847
Not 100% sure about the actual fix yet 🤔
If someone else has a clue, please give it a go, and add a commit to this branch 🙇
---
- [CSB](https://codesandbox.io/s/hardcore-worker-x5nrv7?file=/src/App.tsx) with a reproduction.
- Will fix #2847
=> fix(Autocomplete): ensure on_change is firered during dataset update

packages/dnb-eufemia/babel.config.js, packages/dnb-eufemia/package.json, packages/dnb-eufemia/rollup.config.js, packages/dnb-eufemia/scripts/postbuild/__tests__/postbuild.test.ts, yarn.lock
We have received several request to add a ["use client"](https://react.dev/reference/react/use-client) directive on top of each React component file that uses client side only React APIs.
The reason is because Next.js takes in use a beta version of React to make RSC work (which is not OK in my opinion – its a super aggressive move 😣).
To make a first move on this from our side, I think we should automate this. And one way to do so, is to use Babel.js – because we use it in our tool-chain.
There is already a very well written and tested plugin, written by Kyle Tsang I suggest to try out.
👉 [babel-plugin-transform-next-use-client](https://github.com/kyletsang/babel-plugin-transform-next-use-client)
This must be the first time we take in use a dependency with 0 GitHub stars. If it turns out …
=> feat: add "use client" to components that use client side only React APIs (support for RSC)

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx, packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx, packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/stories/PhoneNumber.stories.tsx
The change: When the user changes the countryCode value – without making a "selection" – and then the input blurs, it will show the current selected value. This way, it will not be possible to "clear" a country code or add a custom. 
But that also requires us to deliver all possible available codes. The error rate will be way lower for sure. Now, its more like a Dropdown, but with fee text search ability.
Here's [a demo](https://eufemia-git-feat-phone-number-keep-value-eufemia.vercel.app/uilib/extensions/forms/feature-fields/PhoneNumber/demos/).
=> fix(PhoneNumber): keep selected countryCode value on blur

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/properties.mdx
Fixes https://github.com/dnbexperience/eufemia/issues/2884
Turns out that `PostalCodeAndCity` does not inherit `FieldProps` but rather `FieldBlockProps`, hence, it never inherits/extends the `DataValueReadWriteComponentProps` and therefore the `DataValueReadWriteComponentProps` should not be listed in the docs for `PostalCodeAndCity`.
=> docs(PostalCodeAndCity): remove unsupported props

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/data-value-readwrite-properties.mdx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/properties.mdx, packages/dnb-design-system-portal/src/shared/tags/Table.tsx
This way we can simply list props that are not supported for various reasons:
```mdx
<DataValueReadwriteProperties
type="string"
omit={[
'layout',
'label',
'labelDescription',
'labelSecondary',
'emptyValue',
]}
/>
```
=> docs(PhoneNumber): remove unsupported props

packages/dnb-eufemia/src/components/card/stories/Card.stories.tsx
Adds card stories, using fields from forms extension.
THOUGHTS:
Seems like my stories is not working as expected as of right now, as I'm doing:
```
<Card stack> 
<>
...component1
...component2
</>
</Card>
```
And must rather do the following for it to work:
```
<Card stack> 
...component1
...component2
</Card>
```
Should/could the first example with React fragment(`<></>`) work?
--------------------------------------------------------------------------------
Added one more commit where I duplicate it, instead of sharing it, to make it work/look as expected.
=> chore: adds Card stories

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/FieldBlock/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/FieldBlock/demos.mdx, packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx, packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlockContext.test.tsx, packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts, packages/dnb-eufemia/src/shared/locales/en-GB.js, packages/dnb-eufemia/src/shared/locales/nb-NO.js
FieldBlock did not receive errors from initial renders of inner field components, only after change callbacks to the value. Fixed, added example in portal and unit test.
=> fix(forms): Field block error handling

packages/dnb-design-system-portal/src/docs/contribute/getting-started/making-changes.mdx, packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js, packages/dnb-eufemia/src/components/button/Button.js, packages/dnb-eufemia/src/components/checkbox/Checkbox.js, packages/dnb-eufemia/src/components/date-picker/DatePicker.js, packages/dnb-eufemia/src/components/dropdown/Dropdown.js, packages/dnb-eufemia/src/components/form-label/FormLabel.tsx, packages/dnb-eufemia/src/components/input-masked/InputMasked.js, packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx, packages/dnb-eufemia/src/components/input/Input.js, packages/dnb-eufemia/src/components/input/InputPassword.js, packages/dnb-eufemia/src/components/radio/Radio.js, packages/dnb-eufemia/src/components/radio/RadioGroup.js, packages/dnb-eufemia/src/components/slider/Slider.tsx, packages/dnb-eufemia/src/components/switch/Switch.js, packages/dnb-eufemia/src/components/tag/Tag.tsx, packages/dnb-eufemia/src/components/textarea/Textarea.js, packages/dnb-eufemia/src/components/toggle-button/ToggleButton.js, packages/dnb-eufemia/src/components/toggle-button/ToggleButtonGroup.js, packages/dnb-eufemia/src/components/upload/Upload.tsx, packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx, packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx
Fixes #2893
[Reprod](https://codesandbox.io/s/jolly-blackburn-32p58l?file=/src/App.tsx)
=> fix(FieldBlock): enhance fieldset/legend detection

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx, packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts, packages/dnb-eufemia/src/extensions/forms/types.ts, packages/dnb-eufemia/src/extensions/forms/utils/ajv.ts
Errors based on schema validation in the Provider did not get values injected when providing custom error messages. This is now handeled by adding validation values to the error object (when validated in the Provider) and injecting them in the target field component with their specific error messages. With test to ensure it works as intended.
=> fix(forms): Improved message value replacements

packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx, packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx
It was meant to be a DX improvement. But it turns out, its not a valid message to give, as its actually sometimes a requirement to send in `forId` along with two or more form element children. So the warning was false.
=> chore: remove FieldBlock forId warning

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/properties.mdx, packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/PostalCodeAndCity.tsx, packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/style/dnb-postal-code-and-city.scss
Because, width is supported by FieldBlock anyway, we don't need this additional implementation.
=> chore(forms): refactor width implementation

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts, packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx, packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx, packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx, packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlockContext.ts, packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
Two issues fixed (with tests to verify):
1. `DataContext.Provider` did not show error messages correctly after clicking submit because the internal state for the status of showing all messages was changed from `useState` to `useRef` without triggering a forced update. Since there was no tests checking the display of error messages after clicking submit through the context, this was not found during the change in a previous PR.
2. Fields without a `path` did not trigger the process of error handling in `DataContext.Provider` becuse `useDataValue` only told the context about the error if it had a `path` to identify the source (the data value consumer field component). A fallback identifier of a unique id is now used if path is missing, with a test to verify.
=> fix(forms): Fix data context provider path and error state handling

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/info.mdx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/properties.mdx, packages/dnb-eufemia/src/components/autocomplete/Autocomplete.d.ts, packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx, packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx, packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/stories/PhoneNumber.stories.tsx, packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts, packages/dnb-eufemia/src/extensions/forms/types.ts
- With this change, we only return country code when a phone number exists (`onChange`). This effects also the `onFocus` and `onBlur` event. Else `emptyValue` is returned.
=> fix(PhoneNumber): return country code only when a number is given

packages/dnb-design-system-portal/src/docs/contribute/faq.mdx
I'm suggesting to remove this section, as I believe/think it's outdated.
We could perhaps change/update some other information on this page as well?
I guess somethings are outdated.
https://eufemia.dnb.no/contribute/faq/
=> docs(FAQ): removes stylelint as dependency issue

packages/dnb-eufemia/src/icons/dnb/icons-meta.json, packages/dnb-eufemia/src/icons/icons-meta.json
Just a suggestion, as `recieve` is "not a word".
But this is perhaps "breaking"? in a sense if `recieve` was used to get the hand_money icon previously.
I quickly searched through the monorepo, and could not find any occurrences of `recieve`.
Also, not 100% sure which commit decorator to use(fix, chore, feat)...
=> chore(Icon): removes tag recieve for hand_money

packages/dnb-eufemia/src/components/anchor/__tests__/Anchor.test.tsx, packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx, packages/dnb-eufemia/src/components/button/__tests__/Button.test.tsx, packages/dnb-eufemia/src/components/checkbox/Checkbox.js, packages/dnb-eufemia/src/components/checkbox/__tests__/Checkbox.test.tsx, packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.tsx, packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx, packages/dnb-eufemia/src/components/input/__tests__/Input.test.tsx, packages/dnb-eufemia/src/components/radio/Radio.js, packages/dnb-eufemia/src/components/radio/__tests__/Radio.test.tsx, packages/dnb-eufemia/src/components/switch/Switch.js, packages/dnb-eufemia/src/components/switch/__tests__/Switch.test.tsx, packages/dnb-eufemia/src/components/textarea/Textarea.js, packages/dnb-eufemia/src/components/textarea/__tests__/Textarea.test.tsx
Add test for `ref` as `function` for various input components
=> feat: add support for functional refs to various form components

packages/dnb-eufemia/src/components/date-picker/DatePicker.js, packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx, packages/dnb-eufemia/src/components/date-picker/stories/DatePicker.stories.tsx
`mask_placeholder` shows `dd.mm.yyyy` and not `dd/mm/yyyy` which is the expected result, when setting locale to be `en-GB`.
[Slack thread](https://dnb-it.slack.com/archives/CMXABCHEY/p1701329166313829)
[CSB reproducing the issue](https://codesandbox.io/p/sandbox/optimistic-bassi-gsn7hw)
Expected result in the [CSB](https://codesandbox.io/p/sandbox/optimistic-bassi-gsn7hw) would be that the `mask_placeholder` should be `dd/mm/yyyy` as seen when [wrapping the DatePicker in an Eufemia Provider](https://codesandbox.io/p/sandbox/vigorous-williamson-km4rc7?file=%2Fsrc%2FApp.tsx).
=> fix(DatePicker): renders mask_placeholder from locale w/o provider

packages/dnb-eufemia/src/core/jest/jestSetupScreenshots.js
The custom `headlessTimeout` did not work the way it was implemented. Also, moving the wait action upwards makes more sense.
=> chore: fix wait on non-headless local visual tests

packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js
Forgot to add it as part of https://github.com/dnbexperience/eufemia/pull/2934
Thanks to @tujoworker for figuring it out 🧙
=> chore(PaymentCard): adds unknown to proptypes

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/Examples.tsx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/demos.mdx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/info.mdx, packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/properties.mdx, packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx, packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx, packages/dnb-eufemia/src/extensions/forms/constants/countries.ts
```tsx
<Field.PhoneNumber
label="Label text"
countries="Scandinavia"
/>
```
=> feat(PhoneNumber): add filter for showing e.g. only Scandinavia countries

packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap, packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.tsx.snap, packages/dnb-eufemia/src/components/toggle-button/style/dnb-toggle-button.scss, packages/dnb-eufemia/src/components/toggle-button/style/themes/dnb-toggle-button-theme-ui.scss
To fix the issue on failing e2e tests on the main branch, like below;
/7ccb7ab2-7463-41d4-8143-ee9f896e1de7)
we should remove an left-over style that did influence the Sbanken styles with a higher specificity.
Why did this only happen on the main branch? Because the CSS is only there completely bundled, which creates some times a different CSS specificity.
Here is a [test-run](https://github.com/dnbexperience/eufemia/actions/runs/7091720735/job/19301471826) with the fix. The branch name starts (`startsWith(github.ref, 'refs/heads/main')`) with `main`, therefore it will run like the main branch.
=> chore(ToggleButton): remove left-over to fix Sbanken styling issue

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/Examples.tsx
`bar` is actually not a "real value" that works with/in the [SelectCountry component](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/SelectCountry/demos).
fixes https://github.com/dnbexperience/eufemia/issues/2988
=> docs(SelectCountry): replace bar as value in examples
