packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/properties.mdx
packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx
packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap
packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.tsx.snap
packages/dnb-eufemia/src/components/input/style/dnb-input.scss
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/__tests__/SelectCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/stories/SelectCountry.stories.tsx
packages/dnb-eufemia/src/extensions/forms/constants/countries.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts

With that change we support browser auto-fill and much quicker UX search ability. Also, users can search in both/all locales at the same time.
Fixes #2993

feat(SelectCountry): use autocomplete instead of dropdown

---

packages/dnb-design-system-portal/src/docs/uilib/components/badge.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/dialog.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/drawer.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/height-animation.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/number-format.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/skip-content.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/table.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/upload.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/visually-hidden.mdx

This PR removes `new` status from components older than 10 months(based on git blame).
The only component left with `new` status now is the Layout component.

chore: removes new status from components older than 10 months

---

packages/dnb-eufemia/src/components/form-label/FormLabel.tsx
packages/dnb-eufemia/src/components/form-label/__tests__/FormLabel.test.tsx
packages/dnb-eufemia/src/shared/helpers/__tests__/filterValidProps.test.tsx
packages/dnb-eufemia/src/shared/helpers/__tests__/withCamelCaseProps.test.tsx
packages/dnb-eufemia/src/shared/helpers/__tests__/withSnakeCaseProps.test.tsx
packages/dnb-eufemia/src/shared/helpers/filterValidProps.tsx
packages/dnb-eufemia/src/shared/helpers/withCamelCaseProps.tsx
packages/dnb-eufemia/src/shared/helpers/withSnakeCaseProps.tsx

the new `labelDirection` that is suppose to replace the old `label_direction` prop seems to be missing from FormLabel.
Or is it meant to be replaced by the `vertical`? 🤔

chore(FormLabel): add support for labelDirection via shared Provider

---

packages/dnb-eufemia/src/extensions/forms/constants/countries.ts

Adding the Faroe Island and Greenland to the Nordic group in the country code dropdown as they are part of the nordics, as stated by the [nordic council](https://www.norden.org/en/information/facts-about-nordic-countries)

fix(forms): add Faroe islands and Greenland to Nordics in countrylist

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/fields/ListBaseInputComponents.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/fields/ListBaseSelectionComponents.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/fields/ListBaseToggleComponents.tsx

Fixes/removes the following warning:
```
Eufemia Heading levels can only be changed by factor one! Got: 4 and had before 2 - The new level is 3 
NB: This warning was triggered by:  #String
```
Also improves the looks of the heading levels used.
Screenshot from [main](https://eufemia.dnb.no/uilib/extensions/forms/fields/#categorized-base-components)(where you can see the the heading levels are different):
Screenshot after the fix(having the same heading levels):

chore(Forms): improve heading levels

---

packages/dnb-eufemia/src/components/textarea/__tests__/__snapshots__/Textarea.test.tsx.snap
packages/dnb-eufemia/src/components/textarea/style/dnb-textarea.scss

Fixes https://github.com/dnbexperience/eufemia/issues/3044
Changed the textarea-suffix to use margin instead of padding for spacing. Also adjusted the value to be the same as input_suffix, `0.5rem'
Before: 
After:

fix(Textarea): suffix spacing

---

packages/dnb-eufemia/src/components/anchor/__tests__/__snapshots__/Anchor.test.tsx.snap
packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap
packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.tsx.snap
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap
packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
packages/dnb-eufemia/src/components/global-error/__tests__/__snapshots__/GlobalError.test.tsx.snap
packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.tsx.snap
packages/dnb-eufemia/src/components/help-button/__tests__/__snapshots__/HelpButton.test.tsx.snap
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap
packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.tsx.snap
packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap
packages/dnb-eufemia/src/components/number-format/__tests__/__snapshots__/NumberFormat.test.tsx.snap
packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
packages/dnb-eufemia/src/components/skip-content/__tests__/__snapshots__/SkipContent.test.tsx.snap
packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.tsx.snap
packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.tsx.snap
packages/dnb-eufemia/src/components/tag/__tests__/__snapshots__/Tag.test.tsx.snap
packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.tsx.snap
packages/dnb-eufemia/src/components/tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap
packages/dnb-eufemia/src/components/tooltip/style/dnb-tooltip.scss
packages/dnb-eufemia/src/components/upload/__tests__/__snapshots__/Upload.test.tsx.snap

Fixes https://github.com/dnbexperience/eufemia/issues/2982
Adds `text-align: center` to center align short texts
Before:
After:

fix(Tooltip): text alignment for short text

---

packages/dnb-design-system-portal/src/docs/uilib/components/input-masked/info.mdx
packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
packages/dnb-eufemia/src/components/input-masked/TextMask.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap
packages/dnb-eufemia/src/components/input-masked/stories/InputMasked.stories.tsx
packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
packages/dnb-eufemia/src/components/input-masked/text-mask/InputModeNumber.ts
packages/dnb-eufemia/src/components/input-masked/text-mask/createTextMaskInputElement.js

For iOS we use a custom trick (me and Joakim found during a peer prog session).
This should solve #3097

feat(InputMasked): enhance inputMode for better support of showing correct soft keyboards

---

packages/dnb-design-system-portal/package.json
yarn.lock

This fixes an issue, where theme styles where not loaded when changed (after some changes).
Here is the [fix PR](https://github.com/dnbexperience/gatsby-plugin-eufemia-theme-handler/pull/27).

chore(Portal): upgrade to latest theme handler

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/events.mdx

proposal for this enhancement https://github.com/dnbexperience/eufemia/issues/3036
Not sure if its the best way to to do it, but I put the documentation for the argument value below the event handler table, to prevent having to cram in the description of the value itself at the end of each table row.

docs(Field.PhoneNumber): document event handlers argument value

---

packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.js
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Solves https://github.com/dnbexperience/eufemia/issues/2935
Before:
[Before CSB](https://codesandbox.io/p/sandbox/reverent-voice-w4vrcc?file=%2Fsrc%2FApp.tsx%3A1%2C37)
After:
[After CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-j6s8zk)

fix(DatePicker): make sure calendar shows correct date on date prop update

---

packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.tsx.snap
packages/dnb-eufemia/src/components/section/__tests__/__snapshots__/Section.test.tsx.snap
packages/dnb-eufemia/src/components/section/style/dnb-section.scss
packages/dnb-eufemia/src/components/skip-content/__tests__/__snapshots__/SkipContent.test.tsx.snap

- We do that by adding a needed negative z-index.
- Move both the outline and the shadow in the same pseudo element for better flexibility.

fix(Section): ensure overlay is behind content

---

packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useDataValue.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts

If the form is submitted without filling out any any fields, I expect errors messages to be displayed and form submission to be prevented if the form is invalid.
I've not tested if this affects other validation rules, but at least it fails when using the `required` property.

fix(Field.String): validated empty value when required

---

packages/dnb-eufemia/src/extensions/forms/Field/Expiry/Expiry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/__tests__/Expiry.test.tsx

This PR doesn't actually fix anything, it just adds tests for scenarios I believe the Expiry field should handle in the same manner. But sometimes when value has a non existing month as a value, it returns different values, and I believe it should/could return the same:
Here are a few examples:
- value `0000` results in `0m / 00`
- value `1300` results in `1m / 00`
- value `9900` results in `mm / 00`
- etc etc.
So, consider this an issue, which includes a few tests 🤷‍♂️

fix(Field.Expiry): should handle values of non existing months

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/events.mdx
packages/dnb-eufemia/src/components/date-picker/DatePicker.d.ts
packages/dnb-eufemia/src/components/date-picker/DatePicker.js
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.js
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Proposal to add onBlur event prop for the `DatePicker`
This could be solve by either hooking the onBlur event to the `fieldset` wrapping the inputs, or adding it to the existing internal `DatePickerInput` `onBlur` handler. 
I went with the latter approach, as adding it to the `fieldset` would requrie adding a check for if the `InputButton` is being clicked to abort the onBlur event, preventing the onBlur from firing every time the user clicks the `InputButton`

chore(DatePicker): add onBlur event

---

packages/dnb-eufemia/src/components/date-picker/DatePickerCalc.js
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

`minDate` would be disabled was set to be `new Date()`, since the `isAfter` function that does the comparison to determine of the date should disabled in the calendar, also compares time. The calendar `date` param passed down to the `isDisabledCalc` has time set to `00:00:00` meaning that `date` is after `minDate` if its set to `new Date()` since `minDate` can have a time of `16:57:13`
Before:
After:

fix(DatePicker): fix bug where minDate set to today is disabled

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/Examples.tsx
packages/dnb-eufemia/src/components/date-picker/DatePicker.d.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.js
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Adds a return object for the onBlur event, to make it possible to extract the date for the event object.

fix(DatePicker): add return object for onBlur

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx

Because the corresponding HTML element does not exists in the DOM when not opened.

fix(Autocomplete): only set aria-controls attribute when expanded

---

packages/dnb-eufemia/src/components/input-masked/__tests__/MultiInputMask.test.tsx
packages/dnb-eufemia/src/components/input-masked/hooks/useHandleCursorPosition.ts

This PR will change the behavior when a user users the keyboard keys on a `MultiInputMask` input. When a selection is made, it should not navigate to the next field.
Its related to this issue #3191 – even `MultiInputMask` did not have that issue – it now enhance its appearance even more.
Before it jumps to the next input field:
https://github.com/dnbexperience/eufemia/assets/1501870/049d8ead-2197-4f6c-a14d-e1b026f154a5
After it does stay on the same input field:
https://github.com/dnbexperience/eufemia/assets/1501870/af8d0030-6c84-43d5-b6a8-43430cc930c0

fix(MultiInputMask): enhance handling of right, left and backspace key usage

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx

If you are tabbing into an `InputMasked` field which is partially filled and then uses your keyboard to un-select it by clicking your right arrow key, your input is ignored.
**Steps to reproduce:**
1. Partially fill an InputMasked field
2. Tab out of the field (Click <kbd>Tab</kbd>)
3. Tab back to the field (Click <kbd>Shift</kbd>+<kbd>Tab</kbd>)
4. Unselect by moving the cursor to the end of the text (Click <kbd>Right Arrow</kbd>)
5. Trying to continue filling out the value is ignored
**Work around:**
Set the `show_guide` property to `false`

fix(InputMasked): correct cursor position when navigating using keyboard

---

packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/stories/FieldBlock.stories.tsx

Fixes #2979
The issue:
* The label was a sub-component defined inside FieldBlock
* Therefore a new label was initialized every time FieldBlock was re-rendered
* FieldBlock re-renders on input blur (once the user has "activated" the input by making a change)
* If you blur the input by clicking the label, the FieldBlock re-renders, removes the label before handling the click, and initializes a new label that was never clicked
By memoizing the label sub-component, it now re-renders, instead of being re-initialized.

fix(FieldBlock): label can be clicked after focusing input

---

packages/dnb-eufemia/src/components/dropdown/Dropdown.js
packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.tsx

proposal to fix https://github.com/dnbexperience/eufemia/issues/2981
This solution makes the `Dropdown` close regardless if the suffix is a button or not. So if the `suffix` is just plane text, it will close the `Dropdown` if clicked. Should we perhaps add logic that checks if the trigger is a `button` or not before deciding to close, or is that unnecessary?

chore(Dropdown): close on suffix click

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Visibility.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Visibility/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Visibility/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Visibility/__tests__/Visibility.test.tsx

Thank you @kimroen for the [CSB](https://codesandbox.io/p/sandbox/laughing-bash-f2d5zm) reprod. 👌

fix(Visibility): add support for being used in Flex.Container

---

packages/dnb-eufemia/src/components/textarea/__tests__/__snapshots__/Textarea.test.tsx.snap
packages/dnb-eufemia/src/components/textarea/style/dnb-textarea.scss
packages/dnb-eufemia/src/style/core/utilities.scss

fix(Textarea): ensure correct height based on rows for Firefox browser

---

packages/dnb-design-system-portal/src/docs/uilib/components/input/demos.mdx
packages/dnb-eufemia/src/components/input/Input.js
packages/dnb-eufemia/src/components/input/__tests__/Input.test.tsx

When an input is used inside a Dialog/Modal/Drawer, the escape key should only close the modal. Key clear button is still available for keyboard users by tabbing to the clear button.

fix(Input): should not clear input value with escape key

---

packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/__tests__/ArraySelection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/Expiry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/__tests__/Expiry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/__tests__/SelectCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/__tests__/Toggle.test.tsx

Fixes #2958
The `hasError` prop is used to tell "regular" input components that they have an error

fix(Field): show error state without error object if parent FieldBlock has error

---

packages/dnb-eufemia/src/fragments/drawer-list/DrawerListHelpers.js
packages/dnb-eufemia/src/fragments/drawer-list/__tests__/DrawerList.test.tsx

closes https://github.com/dnbexperience/eufemia/issues/3199
Issue caused by the the function updating selected items using the `original_data` to find and set the selected item. This causes a issue since `original_data` does not update on `props.data` change.

fix(DrawerList): update original data when data prop changes

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/hooks/__tests__/useData.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/hooks/useData.tsx
packages/dnb-eufemia/src/shared/helpers/__tests__/useSharedState.test.ts
packages/dnb-eufemia/src/shared/helpers/useSharedState.tsx

When the initial value was given in the Form.Handler, it never got set in useData. Now we have several test cases for this too. This change needed some more rewrite of the internal structure. Also, we move from state to ref in the useData hook.

chore(useData): enhance flexibility

---

packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx
packages/dnb-eufemia/src/components/input-masked/__tests__/MultiInputMask.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/Expiry.tsx

So we can forward `labelDescription` in this PR #3251.

chore(Expiry): make Expiry FieldBlock compatible

---

packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx
packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbMultiple.tsx
packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx
packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/dnb-eufemia/src/components/breadcrumb/style/dnb-breadcrumb.scss

This PR #2762 was originally merged into #2671 – and was with that never merged into main.

fix(Breadcrumb): fix rehydration disturbance

---

packages/dnb-eufemia/src/components/number-format/NumberUtils.d.ts

The function `format` only returns an object if the option `returnAria` was passed in as `true`, but TypeScript doesn’t know this.
With this change, we’re making an overload for the function that only returns the object in the right situation. This way, the caller doesn’t need to check the returned value before being able to use it as a string (or number).
The `formatReturnType` type is now unused, but given it's been exported I opted to not remove it as that might be considered a breaking change.
You can consider this more of a suggestion than a request though, I'm not sure what your policy or testing setup is like for type changes :)

feat(NumberUtils.format): Only return object if returnAria: true

---

packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx

Before:
https://github.com/dnbexperience/eufemia/assets/25927156/4f33a2ee-784f-413f-aa9a-73648998df76
After:
https://github.com/dnbexperience/eufemia/assets/25927156/8cc71bdd-6103-4c2a-abcc-41d3355906c9
No tests at the moment, as testing was made difficult due to all the elements having a width of 0 in the jest-dom
using the `useMediaQuery` to only collapse the `BreadcrumbMultiple` on screen change does not seem to cause hydration issues.

chore(Breadcrumb): make small screen BreadcrumbMultiple collapse when resizing to medium screen

---

packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.js
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Up until now, the return object for the different `DatePicker` events did not included the corrected date value of `correct_invalid_date` was true.

fix(DatePicker): make return object have corrected value

---

packages/dnb-design-system-portal/src/docs/uilib/components/info-card/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/info-card/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/info-card/properties.mdx
packages/dnb-eufemia/src/components/info-card/InfoCard.tsx
packages/dnb-eufemia/src/components/info-card/__tests__/InfoCard.test.tsx
packages/dnb-eufemia/src/components/info-card/__tests__/__snapshots__/InfoCard.test.tsx.snap
packages/dnb-eufemia/src/components/info-card/style/dnb-info-card.scss

Added optional `dropShadow`-prop to `InfoCard`-component.

feat(InfoCard): add optional dropShadow-prop

---

packages/dnb-eufemia/src/extensions/forms/Field/Boolean/__tests__/Boolean.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/stories/Boolean.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/__tests__/Toggle.test.tsx

fix(Field.Boolean): make it possible to reset the value by providing `undefined`

---

packages/dnb-design-system-portal/src/docs/uilib/components/slider/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/slider/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/slider/properties.mdx
packages/dnb-eufemia/src/components/slider/Slider.tsx
packages/dnb-eufemia/src/components/slider/SliderInstance.tsx
packages/dnb-eufemia/src/components/slider/SliderMarker.tsx
packages/dnb-eufemia/src/components/slider/SliderProvider.tsx
packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx
packages/dnb-eufemia/src/components/slider/stories/Slider.stories.tsx
packages/dnb-eufemia/src/components/slider/types.ts

This way, the JavaScript code will not be exposed in app bundles, if they don't use the marker.

chore(Slider): refactor to not include the marker by default (slider extension)

---

packages/dnb-design-system-portal/src/docs/uilib/helpers/functions.mdx
packages/dnb-eufemia/src/shared/__tests__/helpers.test.js
packages/dnb-eufemia/src/shared/helpers.js
packages/dnb-eufemia/src/shared/helpers/__tests__/debounce.test.ts
packages/dnb-eufemia/src/shared/helpers/debounce.ts

From before, Eufemia helpers offers a `debounce` method. We expand on it and add async/await support.

feat(debounceAsync): add async debounce function support

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap
packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
packages/dnb-eufemia/src/components/progress-indicator/ProgressIndicator.js
packages/dnb-eufemia/src/components/progress-indicator/ProgressIndicatorCircular.js
packages/dnb-eufemia/src/components/progress-indicator/ProgressIndicatorLinear.js
packages/dnb-eufemia/src/components/progress-indicator/__tests__/ProgressIndicator.test.tsx
packages/dnb-eufemia/src/components/progress-indicator/__tests__/__snapshots__/ProgressIndicator.test.tsx.snap
packages/dnb-eufemia/src/components/progress-indicator/stories/ProgressIndicator.stories.tsx
packages/dnb-eufemia/src/components/progress-indicator/style/dnb-progress-indicator.scss

fix(ProgressIndicator): align label spacing when size is `small` and use span instead of divs to support inline elements

---

packages/dnb-eufemia/src/components/height-animation/HeightAnimationInstance.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimationInstance.test.ts
packages/dnb-eufemia/src/components/height-animation/stories/HeightAnimation.stories.tsx
packages/dnb-eufemia/src/components/height-animation/useHeightAnimation.tsx

By using `position: absolute` on the first pain styles, we got a wrong height calculation.

fix(HeightAnimation): enhance calculation of height

---

packages/dnb-design-system-portal/package.json
packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/components/input/Input.d.ts
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
packages/dnb-eufemia/src/shared/helpers/withCamelCaseProps.tsx
yarn.lock

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1708946072052039). Thank you @kimroen ⭐

feat(TypeScript): upgrade internal TypeScript version with a few alignments

---

packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx

Mostly to ensure we don't get flaky tests any more. With that change we lower the amount of re-renders also.

chore(Breadcrumb): internal refactor

---

packages/dnb-design-system-portal/src/docs/quickguide-designer/spatial-system.mdx

the previous owner of pxtoem might have sold the domain, as the link as of today takes you to an online casino 🎰 which has nothing to do with px nor em.

chore(Docs): remove deprecated pxtoem

---

packages/dnb-eufemia/src/extensions/forms/FieldBlock/style/dnb-field-block.scss

This created issues on some fields:
This was not released, we don't use a fix decorator.

chore(FieldBlock): remove hover border

---

packages/dnb-design-system-portal/src/docs/uilib/components/table/Examples.tsx
packages/dnb-eufemia/src/components/table/TableTr.tsx

`children` prop should rarely, if ever, be checked using typescript typing. It has limited effect, and is more likely to cause issues than not.

fix(Table): fix type error when using array of elements

---

packages/dnb-eufemia/src/shared/helpers/__tests__/runCssVersionMismatchWarning.test.ts
packages/dnb-eufemia/src/shared/helpers/runCssVersionMismatchWarning.ts

Regarding feature #3371 – this PR will ensure to always show a warning.

fix: show error in console when Eufemia CSS and JS versions do not match

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/getData/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/getData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/useData/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/useData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/ProviderDocs.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/useData.test.tsx

This lets a dev also check against the internal error. But other internal states may be more interesting. Bot we at least "document that the possibility".

feat(forms): add internal field state to `filterData` as a fourth parameter

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/useFieldProps/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/quick-start.mdx
packages/dnb-eufemia/src/extensions/forms/Field/String/String.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/stories/String.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/DataValueDocs.ts
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

This new transformer API is a declarative addition that can be used on every field, regardless if the field internals already use one of the other transformers, such as `toInput` and `fromInput`.
These two transformers are meant to be used form the field consumer, and not internally in fields.
```tsx
const transformIn = (value) => {
return value?.toUpperCase()
}
const transformOut = (value) => {
return value?.toLowerCase()
}
render(
<Form.Handler onChange={console.log}>
<Field.String
path="/myField"
transformIn={transformIn}
transformOut={transformOut}
/>
)
```

feat(forms): add `transformIn` and `transformOut` to fields for value transformation

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx

Adds a testcase showing a problem that happens with decimal handling and values being updated from outside the `InputMasked` component. This can be seen [in this codesandbox](https://codesandbox.io/p/sandbox/shy-grass-tdynr7?file=%2Fsrc%2FApp.tsx%3A25%2C13) - entering "20.00" in the top textbox results in "2000." in the InputMasked field.
@tujoworker then swooped in and fixed the issue by skipping the custom handling of decimals for the local copy of the value if the passed-in value has a decimal separator.
---
Adding the async call to `userEvent.type` seems to break some other unrelated tests - not quite sure what's up with that.

fix(InputMasked): ensure decimal value update does format correctly 

---

packages/dnb-design-system-portal/src/docs/uilib/components/autocomplete/info.mdx
packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx

Fixes #3355
There is a big potential downside to our ability to avoid potential performance issues when going forward with the implementation as is.
Because the data prop changes, we need to check if it has changed and update the search index. But not all devs will memorise the given data – and if that is not the case, each re-render will set a new search index, regardless if it has changed or not.
At the moment (late Sunday evening) I can't come up with a smart solution of mitigate that potential downside.
Any suggestions?
And thank you again for the fantastic reproduction and issue description: https://codesandbox.io/p/sandbox/confident-vaughan-ty4tz4?file=%2Fsrc%2FApp.tsx

fix(Autocomplete): use current value to filter changed data

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.d.ts
packages/dnb-eufemia/src/components/date-picker/DatePicker.d.ts
packages/dnb-eufemia/src/components/dropdown/Dropdown.d.ts
packages/dnb-eufemia/src/components/form-row/FormRow.d.ts
packages/dnb-eufemia/src/components/form-set/FormSet.d.ts
packages/dnb-eufemia/src/components/form-status/FormStatus.d.ts
packages/dnb-eufemia/src/components/input-masked/InputMasked.d.ts
packages/dnb-eufemia/src/components/input/Input.d.ts
packages/dnb-eufemia/src/components/radio/RadioGroup.d.ts
packages/dnb-eufemia/src/components/textarea/Textarea.d.ts
packages/dnb-eufemia/src/components/toggle-button/ToggleButton.d.ts
packages/dnb-eufemia/src/components/toggle-button/ToggleButtonGroup.d.ts

Didn't make the change for Checkbox to save myself the conflict

fix(FormLabel): remove undeclared `FormLabelText` type

---

packages/dnb-eufemia/src/extensions/forms/constants/locales/en-US.ts

Ref this [discussion](https://dnb-it.slack.com/archives/CMXABCHEY/p1709559880531129).
Adding the missing full stops for `OrganizationNumber` `en-US`. The other full stops has thankfully been added in an earlier PR 🔥

fix(OrganizationNumber): add missing full stop for `en-US` error messages

---

packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/FieldBoundaryContext.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/FieldBoundaryProvider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/__tests__/FieldBoundaryProvider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/AnimatedContainer/ElementBlock.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/AnimatedContainer/__tests__/ElementBlock.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/IterateElementContext.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

This way we can re-use the field boundary logic in other parts.

chore: refactor to internal field boundary

---

packages/dnb-design-system-portal/src/docs/contribute.mdx
packages/dnb-design-system-portal/src/docs/contribute/first-contribution.mdx
packages/dnb-design-system-portal/src/docs/contribute/rules.mdx
packages/dnb-design-system-portal/src/docs/contribute/style-guides/issues.mdx

- Ground rules: Reporting issues title was a bit misleading, changing it and moving the sandbox starter to more relevant place
- Update React docs link to their new docs pages

docs(contribution guide): update title and move sandbox starter

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/info.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/Handler.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/types.ts

Make this possible (again):
This type test fails when not met:

fix(forms): (TypeScript) ensure `data` type is inherited in onSubmit

---

packages/dnb-eufemia/src/components/height-animation/HeightAnimationInstance.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimationInstance.test.ts

Why it effects radio buttons: The `name` attribute is used to create a "group". But when a new element gets added, that has the same `name`, it conflicts with the existing group, and removes the checked state of the current checked radio button, as there is a second "checked" one.

fix(HeightAnimation): ensure Radio buttons persist their state

---

packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx

> 'Form.Visibility' cannot be used as a JSX component.

fix(forms): fix wrong TypeScript JSX return type

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx

In order to be able to filter data based in field props, this PR keeps unmounted field props in memory during step changes.

fix(forms): keep field props in memory during Wizard step change

---

packages/dnb-eufemia/src/components/height-animation/HeightAnimationInstance.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimationInstance.test.ts

To avoid flickering when text is auto wrapped due to a small screen width.

fix(HeightAnimation): set width during height calculation

---

packages/dnb-eufemia/src/components/anchor/Anchor.tsx
packages/dnb-eufemia/src/components/anchor/__tests__/Anchor.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx

fix(Anchor): add TypeScript (strict) support for react-router-dom Link used as `element`

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Since we don't remove props anymore, we don't need to merge and deal with syncing them. This allows us to speed up the performance by not merging them with existing props.

chore(forms): enhance field props performance

---

packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

This is an enhancement of this PR #3571 and feature. This way, nested "required" declarations are supported: 
```js
const schema: JSONSchema = {
type: 'object',
properties: {
myObject: {
type: 'object',
properties: {
myField: {
type: 'string',
},
},
required: ['myField'],
},
},
}
```

chore(useFieldProps): add support for nested schema required declaration

---

packages/dnb-design-system-portal/src/docs/uilib/helpers/functions.mdx
packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx
packages/dnb-eufemia/src/fragments/drawer-list/DrawerListHelpers.js
packages/dnb-eufemia/src/shared/component-helper.js

fix(Autocomplete): fix issue where `React.Element` would not render when used as `selected_value` 

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx

It can be tested in [this example](https://eufemia-git-fix-set-focus-after-submit-eufemia.vercel.app/uilib/extensions/forms/Form/demos/#in-combination-with-a-submitbutton) vs the [existing one](https://eufemia.dnb.no/uilib/extensions/forms/Form/demos/#in-combination-with-a-submitbutton).

fix(forms): set focus back on existing element after async submission

---

packages/dnb-design-system-portal/src/docs/uilib/layout/media-queries.mdx

To make it more clear when media query breakpoints do break, we can add info in pixels, as it is more accurate.
Here is [the preview](https://eufemia-git-docs-breakpoint-clarification-eufemia.vercel.app/uilib/layout/media-queries/#breakpoint-ranges).

docs: add more details about media query breakpoint ranges

---

packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/ArraySelection.tsx

If the project is using "exactOptionalPropertyTypes": true in tsconfig, then this component will not work unless you explicitly say it can be undefined in the type.
I'm not sure how to test this change, since changing the tsconfig flag will break everything else. So I didn't include a test.

fix(ArraySelection): make explicit type of value can be undefined

---

packages/dnb-eufemia/src/fragments/drawer-list/DrawerListHelpers.js

Related to https://github.com/dnbexperience/eufemia/pull/3606
It looks like bundled code still tries to call the function based on testing with the previous fix

fix(DrawerList): prevent call attempt for word if not function

---

packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx

Fixes issue #3623 
This change handles when selectedKey is not present on data object passed in handleDropdownChange.
Before:
https://github.com/dnbexperience/eufemia/assets/16835802/338c0de3-0d6e-4c72-9572-02602a223806
After:
https://github.com/dnbexperience/eufemia/assets/16835802/9be79163-cc50-46b0-8cd2-0230a938d2e6

fix(Field.Selection) handle emptying the input field

---

packages/dnb-eufemia/src/components/table/TableContainer.tsx
packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap
packages/dnb-eufemia/src/components/table/style/table-container.scss

fix(TableContainer): take full width when inside `Card`

---

packages/dnb-eufemia/src/components/skip-content/__tests__/SkipContent.test.tsx

This is just a first attempt, where I've moved the expect statements inside of the waitForU(seems to be a recurring pattern in SkipContent.text.tsx), not sure if it's fixing anything yet.
I've opened two PRs(https://github.com/dnbexperience/eufemia/pull/3656 & https://github.com/dnbexperience/eufemia/pull/3653), both builds([3656](https://github.com/dnbexperience/eufemia/actions/runs/9380814489/job/25828660556) & [3653](https://github.com/dnbexperience/eufemia/actions/runs/9380686070/job/25828253882)) failing with:
```
FAIL src/components/skip-content/__tests__/SkipContent.test.tsx
● SkipContent.Return › should show button and set focus on content element
expect(element).not.toBeInTheDocument()
expected document not to contain element, found <button class="dnb-button dnb-button--secondary …
```

chore(SkipContent): improve failing test

---

packages/dnb-design-system-portal/src/docs/uilib/helpers/functions.mdx

Improves upon the following warning in the console:
`Heading levels can only be changed by factor one! Got: 3 and had before 1 - The new level is 2 NB: This warning was triggered by:  #isTrue`

chore(Component Helpers): improves heading levels

---

packages/dnb-design-system-portal/src/docs/uilib/components/table/demos.mdx

Improves upon the following console warning:
```
Heading levels can only be changed by factor one! Got: 5 and had before 3 - The new level is 4 
NB: This warning was triggered by:  #Expand a single container
```

chore(Table): improve heading levels

---

packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/styling/consume-styles.mdx

Fixes the following console warning:
`Can not decrease to heading level 1! Had before 2 - The new level is 2 NB: This warning was triggered by:  #Select a theme`

docs: fix heading levels

---

packages/dnb-design-system-portal/src/docs/quickguide-designer/colors/ColorTable.tsx

Fixes the following error in the console when running locally, http://localhost:8000/uilib/usage/customisation/colors/
`Warning: Each child in a list should have a unique "key" prop.`

chore: adds color as unique key to tr in ColorTable

---

packages/dnb-eufemia/src/components/logo/Logo.tsx
packages/dnb-eufemia/src/components/logo/__tests__/Logo.test.tsx

The size prop was broken in earlier refactor to ts (#3611). This fix makes it backwards compatible.

chore(Logo): fix size prop in logo

---

packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

> Cannot access 'errorMessagesRef' before initialization

fix(forms): solve issue when schema is used in Wizard

---

packages/dnb-design-system-portal/src/docs/uilib/components/logo/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/logo/demos.mdx

Motivation comes from the latest changes done in Logo, where `size="auto"` was removed from the example, etc. 
Hence I feel these "example names" better reflect the actual examples now.

chore(Logo): rename inherit examples

---

packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.tsx
packages/dnb-eufemia/src/style/themes/theme-sbanken/globals.scss
packages/dnb-eufemia/src/style/themes/theme-ui/globals.scss

Before: 
After:
Because Chromium does not support CSS custom properties in `::selection`.

fix: add support for ::selection color for Chromium based browsers

---

packages/dnb-design-system-portal/src/docs/uilib/components/tabs/demos.mdx

Fixed the title of `Tabs` _breakout_ example introduced in #3384.

docs(Tabs): fix the title of Tabs breakout example

---

packages/dnb-eufemia/src/components/step-indicator/StepIndicatorContext.tsx
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorItem.tsx
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorModal.tsx
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorSidebar.tsx
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorTriggerButton.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx

Fixes #3685
Here is the same example as mentioned in the issue: https://eufemia-git-fix-wizard-step-title-eufemia.vercel.app/uilib/extensions/forms/Wizard/#intro-example

fix(StepIndicator): avoid re-assigning functions that can cause titles to be not in sync

---

packages/dnb-eufemia/src/components/icon/__tests__/Icon.test.tsx

chore(Icon): adds test for when icon provided is FC using hooks

---

packages/dnb-design-system-portal/src/docs/uilib/components/tabs/properties.mdx
packages/dnb-eufemia/src/components/tabs/TabsDocs.ts

I feel that the [properties docs of tabs](https://eufemia.dnb.no/uilib/components/tabs/properties/#key) is not very readable because of how the `data` property's `type` is formatted.
This is just a suggestion, but instead of changing the values of the type property(as I've done in the PR here) we should probably change the styling or so, to accomplish the same. Perhaps the `PropertiesTable` is the correct place to change? 🤔 
From:
To:

docs(Tabs): improve property docs

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx

before:
https://github.com/dnbexperience/eufemia/assets/25927156/5154f5bc-66e2-4880-945d-519219467e77
after:
https://github.com/dnbexperience/eufemia/assets/25927156/2b84e42c-38e7-4593-a54f-2c8051336104

fix(Autocomplete): make inputValue update on data prop changes

---

packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/__tests__/useNextRouter.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/__tests__/useQueryLocator.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/__tests__/useReachRouter.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/__tests__/useReactRouter.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/useNextRouter.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/useQueryLocator.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/useReachRouter.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/useReactRouter.tsx

fix(forms): ensure useReactRouter to handle initial data given by url

---

packages/dnb-design-system-portal/src/docs/uilib/layout/grid/visual-tests/Examples.tsx

docs: update grid layout example without responsive sidebar

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Date/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Value/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Date/DateDocs.ts
packages/dnb-eufemia/src/extensions/forms/Value/Date/__tests__/Date.test.tsx

Add support for 'variant' prop with 'long' or 'short' values, and 'locale'
Fixes #3711

fix(forms): use corrct date formatting for Value.Date

---

packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js
packages/dnb-eufemia/src/shared/component-helper.js

The test does fail when using the regexp version:
Reprod: https://codesandbox.io/p/sandbox/eufemia-js-ios16-issue-gz77wm?file=%2Fsrc%2FApp.js%3A7%2C5

fix(toCapitalized): remove lookbehind regular expression in order to support iOS Safari <v16 

---

packages/dnb-eufemia/src/components/accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
packages/dnb-eufemia/src/components/accordion/style/themes/dnb-accordion-theme-ui.scss

closes https://github.com/dnbexperience/eufemia/issues/3641
Before:
After:

fix(Accordion): add missing bottom border on hover

---

packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/events.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/properties.mdx
packages/dnb-eufemia/src/components/height-animation/HeightAnimation.tsx
packages/dnb-eufemia/src/components/height-animation/HeightAnimationDocs.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimation.test.tsx
packages/dnb-eufemia/src/components/height-animation/useHeightAnimation.tsx

This feature is to make it possible to use `HeightAnimation` as a child inside a container using CSS row-gap, without the "jump" when the HeightAnimation gets display: none when hidden.

feat(HeightAnimation): add property `compensateForGap`

---

packages/dnb-eufemia/src/components/height-animation/useHeightAnimation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/VisibilityDocs.ts

feat(forms): add property compensateForGap to Visibility

---

packages/dnb-eufemia/src/extensions/payment-card/utils/cardProducts.js

- changed SBanken to Sbanken
- added proper brand name for Sbanken: 'Sbanken – et konsept fra DNB'

fix(PaymentCard): change SBanken to Sbanken

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/Examples.tsx

Seems like the `percent` property was forgotten when making the demo/example, in the following commit https://github.com/dnbexperience/eufemia/commit/cb89fa406b837b972677d6764c9ac36dbf7d8a0b

docs(Field.Number): fix `percent` demo/example

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Section/EditContainer/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Section/ViewContainer/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/EditContainer/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/RemoveButton/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/ViewContainer/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/EditToolbarTools.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/ViewContainer/ViewToolbarTools.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/ViewContainer/__tests__/ViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/EditToolbarTools.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditToolbarTools.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/RemoveButton/RemoveButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/RemoveButton/__tests__/RemoveButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Toolbar/__tests__/Toolbar.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/ViewToolbarTools.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/__tests__/ViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/__tests__/ViewToolbarTools.test.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

Motivation comes from the following Slack thread: https://dnb-it.slack.com/archives/CMXABCHEY/p1720189333537279
This PR removes the `Section` translation, which was previously used in `Iterate.EditContainer`, `Iterate.ViewContainer`, `Section.EditContainer`, `Section.ViewContainer` and `RemoveButton`. 
`Section` translation has now rather been split into the following separate translations: 
- `IterateEditContainer`
- `IterateViewContainer`
- `SectionEditContainer`
- `SectionViewContainer`
- `RemoveButton`
This PR also adds docs for the translation props of:
- `Iterate.EditContainer`
- `Iterate.ViewContainer`
- `Section.EditContainer`
- `Section.ViewContainer`
- `RemoveButton`

feat(Forms): translations EditContainer, ViewContainer, RemoveButton

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/NextButton.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/NextButton/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/NextButton/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/NextButton/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/NextButton/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/PreviousButton.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/PreviousButton/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/PreviousButton/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/PreviousButton/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Buttons/PreviousButton/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Step/EditButton.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Step/EditButton/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Step/EditButton/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Step/EditButton/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Wizard/EditButton/EditButton.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/EditButton/__tests__/EditButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/NextButton/NextButton.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/PreviousButton/PreviousButton.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

This PR splits the `Step` translation, into the following separate translations:
- `WizardEditButton`
- `WizardPreviousButton`
- `WizardNextButton`
This PR also adds docs for the translation props of:
- `Wizard`
- `Wizard.PreviousButton`
- `Wizard.EditButton`
- `Wizard.Step.EditButton`
I've still kept the `Step` translation with the `summaryTitle`, as it's documented in so many places so there's a high chance changing that might break something for our users.

feat(Forms.Wizard): separate translations for buttons

---

packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.tsx
packages/dnb-eufemia/src/fragments/drawer-list/DrawerList.js

I think this fixes it...
So when [there's no items selected](https://github.com/dnbexperience/eufemia/commit/8116f8d1a1844783b34aaa48c3aca0592db452ad#diff-46dbe8d13456e462d06633ec5d300715616d086a119195145ddb53b1219a4fdcR257-R261), meaning `active_item` is `-1` the `aria-activedescendant` [get the `-1` value appended](https://github.com/dnbexperience/eufemia/commit/8116f8d1a1844783b34aaa48c3aca0592db452ad#diff-46dbe8d13456e462d06633ec5d300715616d086a119195145ddb53b1219a4fdcR264)(which it shouldn't).
This results in `aria-activedescendant` value being `option-id-q1yx1378--1` when in reality it should be set to the first item, which should be `option-id-q1yx1378-0`.
So this PR basically handles when `active_item` is `-1`, then we set `aria-activedescendant` value to be first item in the …

fix(Dropdown): NVDA navigation issue when no items are selected

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Email/properties.mdx

Fixes the following "link"([Input](/uilib/components/input/properties)), https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/Email/properties/

docs(Field.Email): fix link to input docs

---

packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx

Fixed typing of `dropdownProps` and `autocompleteProps` to allow all legal props for those components.

feat(Field.Selection): allow all props for dropdown and autocomplete

---

packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.tsx

The  Github button size was slightly larger than the "more options"-menu button.
Before:
After:

chore(Portal): fix Github button size

---

packages/dnb-eufemia/src/elements/img/Img.tsx

Add support for `loading`-prop in `Img`. Mainly to be able to use native '`lazy`'-loading.

feat(Img): add support for loading-prop

---

packages/dnb-design-system-portal/src/docs/uilib/typography/font-weight.mdx

docs(Typography): improve font-weights table

---

packages/dnb-eufemia/src/components/button/Button.d.ts

This commit updates the type signature of `Button` to allow passing a
`react-router`-style `Link` in the `element` props.

fix(Button): Allow `react-router` Link as `element`

---

packages/dnb-eufemia/src/components/tabs/Tabs.js
packages/dnb-eufemia/src/components/tabs/__tests__/Tabs.test.tsx

The custom key given to Tabs data was always set to the tab title, this pr fixes that issue

fix(Tabs): make sure props data key is used if defined

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/IsolationDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx

Based on #3812
API suggestions:
- `transformOnCommit`
- `transformCommitData`
- any other suggestions?
To do:
- More examples will be added in this PR #3808

feat(forms): add `transformOnCommit` to Form.Isolation

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Currency/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Currency/CurrencyDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/__tests__/ListAllProps.test.tsx

This changes the behaviour added in [this PR](https://github.com/dnbexperience/eufemia/pull/3184) which again is based on [this issue](https://github.com/dnbexperience/eufemia/issues/3124).

fix(forms): show error when entered `Field.Currency` or `Field.Number` value exceeds maximum possible amount

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/events.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/events.mdx
packages/dnb-eufemia/src/extensions/forms/Field/FieldDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountryDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/__tests__/SelectCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

* added two ways to send `additionalArgs` to `onBlur` and `onFocus`:
* method 1: use `setHasFocus()` with new parameter `additionalArgs`, instead of `handleBlur()` and `handleFocus()`
* method 2: use new transformer `transformAdditionalArgs()` that can generate `additionalArgs` from `value`
* added `additionalArgs` to `<Field.PhoneNumber>` `onBlur` and `onFocus` using method 1
* added `additionalArgs` to `<Field.SelectCountry>` `onBlur` and `onFocus` using method 2

feat(Field.PhoneNumber, Field.SelectCountry): additional event args for onFocus and onBlur

---

packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/__tests__/FieldBoundaryProvider.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

`FieldBoundaryContext`'s `hasVisibleError` was not updated if attempting to `showError()` and there is none. If there was an error before, then any component that used `hasVisibleError` (only `Iterate.EditContainer` and `Form.Section.EditContainer` at the moment) would still think there was an error visible. 
`showError()` is run at any change whenever `continuousValidation` is used. Some components always use `continuousValidation` like `ArraySelection`.
* `hasVisibleError` is now set to `false` if there is no error when attempting to "showError"
* `showError` renamed to `revealError` to make it more clear that it does not actually mean there is an error.

feat(Form): continuousValidation did not update error state correctly

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Toggle/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

Could potentially be breaking if there's someone who manually sets BooleanField for the Field.Toggle.

feat(Forms): seperate translations for Boolean and Toggle

---

packages/dnb-eufemia/src/extensions/forms/Iterate/style/dnb-iterate.scss

fix(forms): ensure correct spacing between `Iterate.Array` items

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/Expiry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/types.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

* Added the type `FieldPropsWithExtraValue` if we need to type events with two arguments.
* The type `FieldProps` will now type events like `onChange`, `onBlur` and `onFocus` with only one argument.
* Added the type `FieldPropsGeneric` that makes no assumptions on whether events have one or two parameters
* `Field.PhoneNumber` and `Field.SelectCountry` now types their second event arguments.
Other fixes:
* fixed `Field.Expiry` missing type for empty value causing useless event type
* fixed `Iterate.Array` having types for non existing props

feat(Field): adds typing for event callbacks

---

packages/dnb-design-system-portal/tsconfig.json
packages/dnb-eufemia/tsconfig.definitions.json
packages/dnb-eufemia/tsconfig.json

In this PR #3854 we need the support of [Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat) which is supported with es2022.
I'm unsure about the relation to this PR #3860 as of now.

chore(TypeScript): set lib version from 2018 to `es2022` to support newer JavaScript APIs

---

.github/workflows/e2e.yml

It seems to me that the `Build portal` step is not slower by removing the cache. So we probably should do that so we avoid the CSS file import issues, like [here](https://github.com/dnbexperience/eufemia/actions/runs/10559105350/job/29249868805).

chore(CI): remove portal build cache

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/SelectionDocs.ts

Motivation:
The [value property of Field.Selection](https://eufemia.dnb.no/uilib/extensions/forms/base-fields/Selection/properties/) states the type is string and number, however when using variant radio or button with a value of type number it breaks.
Reason it breaks, is because the value property of [RadioButton](https://eufemia.dnb.no/uilib/components/radio/properties/) and [ToggleButton](https://eufemia.dnb.no/uilib/components/toggle-button/properties/) states it only supports string. 
Any better ways to fix/improve on this, rather than just adding a description to the docs? 🤔

docs(Selection): value should be string when variant is radio or button

---

packages/dnb-eufemia/src/extensions/forms/Field/Email/Email.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Email/__tests__/Email.test.tsx

See the tests for more details about what we now allow. In short, its not possible to have the perfect validation. Here is an [article about the challenge](https://www.abstractapi.com/guides/email-validation/email-address-pattern-validation). 
The Regex gets way larger when we try to validate IPv4 and especially IPv6. But I think we don't need a perfect validation for these, as these are exceptions anyways.

fix(Forms): enhance `Field.Email` validation pattern

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx

Quick example:
```tsx
<Field.Number
value={1}
label="With suffix (function)"
suffix={(value) => (value === 1 ? ' year' : ' years')}
/>
```

feat(Forms): add function support for the `prefix` or `suffix` props in `Field.Number`

---

packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/ChildrenWithAge.test.tsx
packages/dnb-eufemia/src/shared/Context.tsx
packages/dnb-eufemia/src/shared/__tests__/Context.test.tsx

Fixes https://github.com/dnbexperience/eufemia/issues/3818

fix(Forms): fallback to use default locale for translations when providing a non-existent locale

---

packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Move out the warning from PR #3877 in regards of this issue #3882

fix(Forms): warn on value prop usage on fields inside iterate with itemPath

---

packages/dnb-eufemia/src/components/flex/Container.tsx
packages/dnb-eufemia/src/components/flex/__tests__/Container.test.tsx
packages/dnb-eufemia/src/components/flex/utils.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/stories/Visibility.stories.tsx

Motivation comes from [this Slack thread](https://dnb-it.slack.com/archives/CMXABCHEY/p1725282736084299).
This PR basically ignores fragments in the Container, so it removes the fragment and returns its children instead.
Here's two failing CSBs, to display what the error/problem is/was:
- [Fragment as root in Card](https://codesandbox.io/p/sandbox/hidden-dew-335rcs?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [Fragment nested/inside Card](https://codesandbox.io/p/sandbox/strange-northcutt-nrdvwj?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
Here's the same CSBs using the fix of this PR:
- [Fragment as root in Card](https://codesandbox.io/p/sandbox/quizzical-lamport-cnj4kh?file=%2Fsrc%2FApp.tsx&workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [Fragment nested/inside …

fix(Flex): enhance handling of React fragments

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/constants/countries.ts

The reasoning for adding these countries is that they are required for compliance reasons for application in some of DNBs solutions.
The country list in Eufemia serves two purposes in letting users select countries and letting users select the dialing code for a country.
The country codes missing from ISO 3166 are mostly for external territories of other states.
The dialing code for some of them are certain, and are contained in the wikipedia page the country list was based on earlier.
For others the dialing code is not certain, and most likely they do not have a dialing code. These countries are mostly research bases, or otherwise not permanently inhabited.
The likelyhood of any of these countries actually being used is probably very small.
In the event that someone should want to use a …

feat(countries): Added missing countries from ISO 3166 #3894

---

packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx

Motivation from [this Slack thread](https://dnb-it.slack.com/archives/CMXABCHEY/p1725367722056839).
Importing/using `<Field.SelectCountry />` and/or `<Field.PhoneNumber />` from `import { Field } from '@dnb/eufemia/extensions/forms'` with eufemia 10.46.0 and react 17.0.2 results in the following error: `LabelDescription(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`, see [CSB](https://codesandbox.io/p/sandbox/new-cookies-82klmm?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
Here's the [same CSB with the fix in this PR](https://codesandbox.io/p/sandbox/elegant-http-2kc6y5?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd).

fix(LabelDescription): nothing was returned

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx

"Behaviour" is the British English spelling.
"Behavior" is the American English spelling.
Our code is written in en-us English, while the translation English is en-gb.
There are a couple more. One in the Accordion component (`expandBehaviour`) as a property. But this I think we should keep, as it needs to be deprecated. Feel free to make another PR 🙏

chore(Forms): Behaviour => Behavior

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/error-messages/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/stories/Number.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Slider/Slider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/DataValueDocs.ts
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useDataValue.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

This feature allows a validator for a field to connect to another data path. Changes to the data path value will be reflected in a rerender of the validator. But only if the validator is actually in use. This can be controlled with field properties, such as `validateUnchanged` etc.
**Good to know:** Why do validators not rerender on every data change? Because field A should not emit the validator of field B. It can be used for various cases, such as backend requests.
But with the new feature called `connectWithPath` you as a dev get the possibility to control this in a fine granted way.
Quick examples:
```tsx
import { Form, Field } from '@dnb/eufemia/extensions/forms'
const validator = (value, { connectWithPath }) => {
const { getValue } = connectWithPath('/myReference')
const amount = …
```

fix(Forms): provide `connectWithPath` in the change validator and onBlurValidator

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitButton/__tests__/SubmitButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitIndicator/SubmitIndicator.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitIndicator/__tests__/SubmitIndicator.test.tsx

In the submit indicator component we check if a label/text did wrap to a new line, because of too little space. In this check routine we insert/manipulate the DOM via `element.textContent`. But this check messes up with React and makes so that the given children is re-inserted, so new children/label will not be shown. 
We can fix this chancing the `key` of the element.

fix(Forms): ensure labels do update when they change (async fields)

---

packages/dnb-eufemia/src/extensions/forms/Form/SubmitIndicator/SubmitIndicator.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitIndicator/__tests__/SubmitIndicator.test.tsx

Here is a [demo](https://eufemia-git-fix-field-block-label-html-eufemia.vercel.app/uilib/extensions/forms/Form/Handler/#complex-async-autosave-example) of this feature (without HTML).
And here is a quick screen recording where the label has HTML inside:
https://github.com/user-attachments/assets/56fdc553-b78c-4b88-9de3-fb696c710c68

fix(Forms): ensure label supports HTML formatting

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/useFieldProps/info.mdx
packages/dnb-eufemia/src/extensions/forms/hooks/DataValueDocs.ts
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

Quick example: 
```tsx
const MyField = (props) => {
const myInternalValidator = useCallback(() => {
if (value === 'fail now') {
return new Error('Internal validation error')
}
}, [])
return (
<Field.String exportValidators={{ myInternalValidator }} {...props} />
)
}
const myValidator = (value, { validators: { myInternalValidator } }) => {
if (value === 'fail') {
return new Error('My error')
}
return [myInternalValidator] // optional
}
render(<MyField onBlurValidator={myValidator} />)
```

feat(Forms): make it possible to reuse and extend internal validators

---

packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming/theme/info.mdx
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.tsx

Motivation from this [Slack thread](https://dnb-it.slack.com/archives/CMXABCHEY/p1725533657841919).
The follow code:
```
const { isSbanken } = useTheme()
console.log(isSbanken)
```
Results in this error message:
`Property 'isSbanken' does not exist on type 'UseThemeReturn'.typescript(2339)`
[CSB displaying the error.](https://codesandbox.io/p/sandbox/silent-star-67jztx)
This is because of the type definition introduced in this PR https://github.com/dnbexperience/eufemia/pull/3861/files
This PR types just the `object`, and not `object | null`(which it was), since all fields in JavaScript (and in TypeScript) can have the value null or undefined? So by just typing the `object`, it could also be `null` instead of the `object`?
Here's a [CSB with the …

docs(useTheme): updates docs to match TS type definitions

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Currency/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Currency/demos.mdx

The motivation is that these two fields are very often used, and I saw a dev using the `onChange` event for throwing an error, instead of using the `valdiator` prop.

chore(Forms): add demos to showcase exclusive to Field.Currency and Field.Number

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Toolbar/demos.mdx

There's no Iterate.Count used in the example, hence we can remove the faulty text/info stating it.

chore: removes faulty description of Toolbar example

---

packages/dnb-eufemia/src/extensions/forms/constants/countries.ts

Ever since May 2022, the Norwegian Ministry of Foreign Affairs has decided to use the name "Belarus" for Belarus [(source)](https://www.regjeringen.no/no/aktuelt/hviterussland-blir-til-belarus/id2916338/). Unless DNB has made a executive decision to keep the name "Hviterussland", I say we should change it.

fix(Forms): rename "Hviterussland" to "Belarus"

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/EditContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/EditContainer/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/EditContainer/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Toolbar/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/ViewContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/ViewContainer/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/ViewContainer/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/EditContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/EditContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/ViewContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/ViewContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/Iterate.stories.tsx

Based on #3877
Quick example using the new Toolbar variant:
```tsx
<Form.Handler>
<Iterate.Array path="/countries" defaultValue={[null]}>
<Iterate.ViewContainer toolbarVariant="minimumOneItem"
>
<Value.SelectCountry
label="Land du er statsborger i"
itemPath="/"
/>
</Iterate.ViewContainer>
<Iterate.EditContainer toolbarVariant="minimumOneItem"
>
<Field.SelectCountry
label="Land du er statsborger i"
itemPath="/"
required
/>
</Iterate.EditContainer>
<Iterate.PushButton
path="/countries"
pushValue={null}
text="Legg til flere statsborgerskap"
/>
```

feat(Forms): add `toolbarVariant="minimumOneItem"` to Iterate.Toolbar for hiding buttons when there is only one item in the array

---

packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx

Today, we have a warning for when an async validator or onChange event is used, but no label is given. Because we want then show the indicator. But maybe this is not that useful? Then we can consider to remove it.
This PR enhances at least the message given to the user.

chore(Forms): enhance the not provided label warning

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Container/info.mdx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/WizardContext.ts

feat(Wizard): add `preventNavigation` callback function to `onStepChange`

---

packages/dnb-eufemia/src/components/height-animation/HeightAnimationInstance.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimationInstance.test.ts

When animating/adjusting the height for some value to 0, it did not. Also animating/adjusting from 0 to a a certain value did not work properly.
From value to 0, first the issue and then with the fix:
https://github.com/user-attachments/assets/316d7288-2a2d-4792-90e1-3d41313602a0
https://github.com/user-attachments/assets/93dc3198-0ffd-4eb3-b5de-b7e6f0d6ac76
From 0 to value, first the issue and then with the fix:
https://github.com/user-attachments/assets/ddd21697-60a8-4555-af5d-a1d3a8b6ebc0
https://github.com/user-attachments/assets/cd97dbca-8a1d-46d1-8fd8-16f7cea85b5a

fix(HeightAnimation): enhance adjusting the height to 0

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

This change should not effect any existing code. Its a pure internal change from using an array to use an object to track mounted fields.
We need such a change for a following up PR.

chore(Forms): rewrite mounted fields logic from array to object

---

packages/dnb-eufemia/src/extensions/forms/Iterate/Array/ArrayItemArea.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainerDocs.ts

`PushContainer` can use the prop `variant` to change between outline or no outline surrounding the contents.
The prop has not been exposed in the prop type, and using it will result in a typescript error even though it functionally works.

fix(PushContainer): Add missing variant type

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/FieldBoundaryContext.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/FieldBoundaryProvider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/__tests__/FieldBoundaryProvider.test.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/Iterate.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

This PR adds the "visible error" logic to the field boundary. 
Before it just inherited it from the global data context, which could lead in worst case to error disturbance, similar to what [happened here](https://github.com/dnbexperience/eufemia/pull/3938).

fix(Forms): enhance container boundary error handling

---

packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/DoneButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/RemoveButton/RemoveButton.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/__tests__/ListAllProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/__snapshots__/ChildrenWithAge.test.tsx.snap

When `required` was set on the Form.Handler, this code;
```tsx
<Form.Handler required>
<Iterate.Array path="/myList">
<Iterate.ViewContainer>ViewContainer</Iterate.ViewContainer>
<Iterate.EditContainer>EditContainer</Iterate.EditContainer>
<Iterate.PushButton path="/myList" pushValue={{}} />
```
did result in this;
... when pressing the done button.
This happened because the remove button did use the hook `useFieldProps` which is meant to be used by fields. So it suddenly did validate as required.

fix(Forms): remove unwanted Iterate.EditContainer error confirmation when using required on Form.Handler

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/info.mdx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/OpenButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx

Quick example:
```tsx
<Form.Handler>
<Iterate.Array path="/myList">...</Iterate.Array>
<Iterate.PushContainer
path="/myList"
title="New item title"
openButton={
<Iterate.PushContainer.OpenButton text="Add no. {nextItemNo}" />
}
showOpenButtonWhen={(list) => list.length > 0}
>
<Field.Name.Last itemPath="/name" />
</Iterate.PushContainer>
```

feat(Forms): add `{nextItemNo}` support to Iterate.PushContainer open button

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/info.mdx

This is a witch, we don't like witches 🧙‍♀️ 
Not sure if the sentence I updated makes sense seen up against the [regex](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/PhoneNumber/#norwegian-mobile-numbers) it should describe.

chore: minor spelling improvement witch -> any

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/ChildrenWithAge.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/ChildrenWithAge/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/ChildrenWithAge/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/ChildrenWithAge/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/ChildrenWithAge/properties.mdx
packages/dnb-design-system-portal/src/shared/parts/TranslationsTable.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/ChildrenWithAge.screenshot.test.ts

chore: split out ChildrenWithAge into its own docs

---

packages/dnb-design-system-portal/src/docs/uilib/components/input/info.mdx

Fixes this incorrect markdown link on the [input component page](https://eufemia.dnb.no/uilib/components/input/#accessibility):

docs: fix markdown link to text counter component

---

packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

This can be experienced e.g. in the ChildrenWithAge block rendered in React.StrictMode. Then non of the default values are selected.

fix(Forms): ensure `defaultValue` works in React.StrictMode

---

packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.module.scss
packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.tsx

I guess the code/styling in this PR could be made better.
The reason for me going with the current approach(hiding/showing two different home buttons based on screen size) is because of the existing approach(as of today) does not work, because a "icon button with hidden text(display:none) still styles/acts as it is text there, as the node is still rendered".
Resulting in the "strange icon" we see today in the "From example", and this:
From:
To:

chore: improve home button on small devices

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/ChildrenWithAge/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/ChildrenWithAge.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/ChildrenWithAgeDocs.ts
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/ChildrenWithAge.test.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/stories/ChildrenWithAge.stories.tsx

Instead of resetting the amount of children, this PR removes it, so the default value applies when switching back again.

fix(Forms): enhance reset routine of ChildrenWithAge block

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SelectCountry/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/__tests__/SelectCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/stories/SelectCountry.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/Log.tsx
packages/dnb-eufemia/src/extensions/forms/constants/countries.ts

Based on PR #3974
Here is a [demo](https://eufemia-git-fix-select-country-transform-eufemia.vercel.app/uilib/extensions/forms/feature-fields/SelectCountry/#transformin-and-transformout).

fix(Forms): add support for `transformIn` and `transformOut` to Field.SelectCountry

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

In PR #3975 (not released at this point of time), we added a new `transformOut` function to the `useFieldProps` hook. This function is with that also called when the field is initialized (and there is a path and Form.Handler). It can be used to transform the value before it is stored in the data context. However, this function, when changing the value in the context, it will re-render and with that, try to do the same again, but we had no check for this case, so it can/will result in an infinite loop.
By double checking if the data context value did change since last time, we can avoid this infinite loop.
The provided tests would fail with an infinite loop without the fix.

chore(Forms): fix initial `transformOut` call

---

packages/dnb-design-system-portal/src/docs/uilib/helpers/sass.mdx
packages/dnb-design-system-portal/src/docs/uilib/layout/media-queries.mdx
packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.module.scss
packages/dnb-eufemia/src/components/accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap
packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
packages/dnb-eufemia/src/components/form-row/__tests__/__snapshots__/FormRow.test.tsx.snap
packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.tsx.snap
packages/dnb-eufemia/src/components/section/__tests__/__snapshots__/Section.test.tsx.snap
packages/dnb-eufemia/src/components/skip-content/__tests__/__snapshots__/SkipContent.test.tsx.snap
packages/dnb-eufemia/src/components/space/__tests__/__snapshots__/Space.test.tsx.snap
packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.tsx.snap
packages/dnb-eufemia/src/fragments/drawer-list/__tests__/__snapshots__/DrawerList.test.tsx.snap
packages/dnb-eufemia/src/shared/MediaQueryUtils.ts
packages/dnb-eufemia/src/shared/__tests__/MediaQuery.test.tsx
packages/dnb-eufemia/src/shared/__tests__/MediaQueryUtils.test.tsx
packages/dnb-eufemia/src/shared/__tests__/useMedia.test.tsx
packages/dnb-eufemia/src/shared/__tests__/useMediaQuery.test.tsx
packages/dnb-eufemia/src/style/core/utilities.scss
packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap

The `1px` overlap-avoidance between media queries created a  `0.999...px` gap between mixin media queries. That is visible if user zooms in. This PR changes that to `0.1px` so you would have to zoom in more than 1000% in order to get a gap.
1. `'small'` breakpoint `40em = 640px
3. `allBelow('small')` `0px to 640px` is narrower than `640.5px`
4. `allAbove('small')` `641px to infinity` is wider than `640.5px`
5. Changing `allAbove('small')` to `640.1px to infinity` includes `640.5px`
* changed overlap-avoidance from `1px` to `0.1px` in both SASS mixins and react hooks.
* updated documentation for "SASS and Mixins" and "Media Queries and Breakpints" to make it clearer that we do not include the minimum breakpoint in our intervals.
* fixed Portal Home button breakpoint off by 1 px
* fixed a …

feat(SASS mixins): media queries mixins now uses 0.1px instead of 1px to avoid overlap

---

packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/ViewContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/__tests__/ViewContainer.test.tsx

Fixes #3999
(I/we forgot the add the backwards compatibility in the second container 🫣)

fix(Forms): ensure `itemNr` still works in the Iterate.ViewContainer

---

packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/useData.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useData.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/Iterate.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx

As reported here https://dnb-it.slack.com/archives/C07JEJVSHJR/p1727258016481019
TODO:

fix(Forms): `Form.useData` should not throw error when used in Wizard

---

packages/dnb-design-system-portal/src/docs/uilib/layout/space.mdx

properties tab doesn't display when visiting https://eufemia-git-main-eufemia.vercel.app/uilib/layout/space/
But it does show when visiting https://eufemia-git-main-eufemia.vercel.app/uilib/layout/space/demos/
Should be able to see the tab when visiting both urls.
Seems to work now, see the deploy preview:
https://eufemia-git-chore-fixes-properties-tab-which-ran-c6430a-eufemia.vercel.app/uilib/layout/space/
https://eufemia-git-chore-fixes-properties-tab-which-ran-c6430a-eufemia.vercel.app/uilib/layout/space/demos

chore: fixes Space's properties tab

---

packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/usePath.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/usePath.ts

Its an edge case, but when using an array iterator with a `/` slash only to target an array, fields could end up using `//0/something` as the path.

chore(Forms): clean paths properly when only slash is given as iteratePath

---

packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/extensions/forms/DataContext/At/At.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/stories/Provider.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Indeterminate/useDependencePaths.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/Handler.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/Section.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/useVisibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/getData.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useData.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Count/Count.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/GenerateSchema.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/ListAllProps.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useExternalValue.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts
packages/dnb-eufemia/src/extensions/forms/utils/ajv.ts
packages/dnb-eufemia/src/extensions/forms/utils/index.ts
packages/dnb-eufemia/src/extensions/forms/utils/json-pointer.ts
packages/dnb-eufemia/src/extensions/forms/utils/json-pointer/__tests__/json-pointer.test.ts
packages/dnb-eufemia/src/extensions/forms/utils/json-pointer/export.ts
packages/dnb-eufemia/src/extensions/forms/utils/json-pointer/json-pointer.ts
packages/dnb-eufemia/src/shared/Context.tsx
yarn.lock

I believe this is the right step for now because the dependency we’re using is written in CJS and doesn't treeshake unused parts. Since we rely on this pointer in the default Eufemia Context, reducing its footprint is my main motivation.
By using the native `foreach` method and the export approach in this PR, we can ship smaller bundle (maybe 20%). In the future, we may consider submitting a PR to the original dependency to address this issue directly.
PR no. 4000

feat(Forms): implement TypeScript version of `json-pointer`

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Currency/properties.mdx
packages/dnb-eufemia/src/components/number-format/NumberFormatDocs.ts
packages/dnb-eufemia/src/extensions/forms/Value/Currency/CurrencyDocs.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Number/NumberDocs.tsx

Follow-up to https://github.com/dnbexperience/eufemia/pull/4008#discussion_r1776864819
As of now docs looks like the following([deploy preview](https://eufemia-dnb-design-system-portal.vercel.app/uilib/extensions/forms/Value/Currency/properties/) of release [v10.51](https://github.com/dnbexperience/eufemia/pull/4012)):
This PR will change it to be looking like this([deploy preview](https://eufemia-git-docs-improve-value-currency-docs-eufemia.vercel.app/uilib/extensions/forms/Value/Currency/properties/) this PR).
TODO:

docs(Value.Currency): improve documented properties

---

packages/dnb-eufemia/src/extensions/forms/Form/data-context/useData.tsx

Not sure if it was intentionally done or not, but in PR https://github.com/dnbexperience/eufemia/pull/4000.
https://github.com/dnbexperience/eufemia/pull/4000/files#diff-140a134e6c50d8779c0d649217f3bf668c632db66fdb1d8e41f1405b330ecaa1R40
By using `unknown` makes it so that all consumers will have to type their expected value, like `getValue('/a') as string` to prevent a TS error. Of course it could potentially be "fixed" on consumer side to reduce the "strictness" or so. Just fixing this now, and then we can have a discussion about this after the vacation break.

fix(Form.UseData): getValue returns any instead of unknown

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap
packages/dnb-eufemia/src/components/dropdown/Dropdown.js
packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
packages/dnb-eufemia/src/components/dropdown/style/dnb-dropdown.scss

Proposal on how to solve the alignment issue
Before:
After:

fix(Dropdown): align tertiary dropdown triangle icon with button

---

packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx

closes [this issue](https://github.com/dnbexperience/eufemia/issues/3840)
Before:
https://github.com/user-attachments/assets/4629c16f-111e-47a5-85d2-3e6ed66fb003
After:
https://github.com/user-attachments/assets/f7419a58-a0ea-4430-9eb9-461c7298968e

fix(Field.Selection): prevent `radio` re-render onClick to enable keyboard navigation

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/__tests__/SelectCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/stories/String.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts
packages/dnb-eufemia/src/extensions/forms/utils/ajv.ts
packages/dnb-eufemia/src/extensions/forms/utils/json-pointer/json-pointer.ts

Fixes #3997
Until now, the "out" transformed value was used inside useFidldProps. But when transforming out to an object, validation can not be performed anymore. So this PR transforms the object "in" again internally, so validation can be performed.

fix(Forms): support validation when using object based `transformOut` and `transformIn` on fields

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks.mdx

Reason why it feels beta to me, is because it's so many frequent changes to the design and layout of the only existing block we have, ChildrenWithAge. They even have a new design now, that we'll have to implement, so just want to mark it as beta for now.

chore: adds beta badge to blocks in menu

---

packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fixes #4067
I could not find any relation with `pattern` actually.

fix(Forms): show error on every value change when using exported validators

---

packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

- Relies on #4068
- Fixes #4066
At least hope it will fix it. 
**NB:** When using this code:
```tsx
<Field.OrganizationNumber
onBlurValidator={myValidator}
validateInitially
/>
```
it will not show the error. This is simply because internally we check if there is a value/pattern that matches. And only if it matches, the validator will run.
Therefore this particular field needs a `value` or `defaultValue` to run a validator, not matter if it is an `onBlurValidator` or not.
```tsx
<Field.OrganizationNumber
onBlurValidator={myValidator}
validateInitially
defaultValue="123 331 231"
/>
```

fix(Forms): ensure `onBlurValidator` gets called when `validateInitially` is true

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumber.test.tsx

Just to align with validation of organization number https://github.com/dnbexperience/eufemia/pull/3976

fix(NationalIdentityNumber): use `onBlurValidator` instead of `validator`

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/info.mdx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumberDocs.tsx

Dependent on https://github.com/dnbexperience/eufemia/pull/3982

docs(NationalIdentityNumber): add docs about validation

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/VisibilityDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/useVisibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/stories/Visibility.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/useVisibility.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

As of now, the Visibility does only react on data content, but not on validation.
This PR is an attempt to add support for showing something based on the validation result by another field:
```tsx
<Form.Visibility
visibleWhen={{
path: '/foo',
isValid: true,
}}
>
<Value.Name.First path="/foo" />
</Form.Visibility>
```
Here is [a demo](https://eufemia-git-feat-visibility-validate-eufemia.vercel.app/uilib/extensions/forms/Form/Visibility/#show-children-when-field-has-no-errors-validation).
To avoid hiding/showing its content during e.g. typing, it will wait until the field has blurred.
E.g. the name field does validate negatively when a space is added after a name. During typing are we going then from false to true to false several times.
This blur behavior could for sure be omitted with a …

feat(Forms): add `isValid` to Form.Visibility for showing content based on the validation of a field

---

packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/OrganizationNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/__tests__/OrganizationNumber.test.tsx

Fixes the following error message( Cannot read properties of undefined (reading 'length')), when using validateInitially like so:
`<Field.OrganizationNumber validateInitially />`

chore(Field.OrganizationNumber): fixes error when validateInitially

---

packages/dnb-eufemia/src/extensions/forms/Form/SubmitConfirmation/SubmitConfirmation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitConfirmation/__tests__/SubmitConfirmation.test.tsx
packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js
packages/dnb-eufemia/src/shared/component-helper.js

fix(Forms): add support for `Form.SubmitConfirmation` inside Wizard

---

packages/dnb-eufemia/jest.d.ts
packages/dnb-eufemia/src/core/jest/jestSetup.js
packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/OrganizationNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/__tests__/OrganizationNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx

Fixes #4073
The reason for the outcome in the issue is that the internal pattern is prioritized over the custom validator. But we probably don't need the pattern. So this PR removes is.
Also, I think when first utilizing the `expectNever`, we rather should add a Jest matcher.

feat(Forms): remove internal pattern from `Field.OrganizationNumber` in favor of the internal validator

---

packages/dnb-eufemia/src/components/form-status/FormStatus.d.ts
packages/dnb-eufemia/src/components/icon/Icon.tsx

Fixes https://github.com/dnbexperience/eufemia/issues/4083
Here's a CSB, to validate that the fix works, https://codesandbox.io/p/sandbox/eager-perlman-yr96sy?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd

fix(Icon): icon property typing should accept FormStatus icons

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Step/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Step/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/info.mdx
packages/dnb-eufemia/src/extensions/forms/Wizard/Buttons/Buttons.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/WizardContext.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Step/Step.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/useStep.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/stories/Wizard.stories.tsx

Quick example:
```tsx
<Wizard.Container
onStepChange={(index, mode, args) => {
console.log('onStepChange', index, mode, args.id) // 👈 here we get the "id"
}}
>
<Wizard.Step
title="Step A"
id="step-a" // 👈 here we add an "id"
activeWhen={{ path: '/activeSteps', hasValue: 'group-1' }}
>
content
</Wizard.Step>
<Wizard.Container
```

feat(Forms): add support for `id` for when using dynamic steps with `activeWhen`

---

packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/OrganizationNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/__tests__/OrganizationNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-US.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

I think this makes more sense for the component, as we don't use pattern internally by default, but we do support validator by default

chore(Field.OrganizationNumber): changes translation from errorPattern to errorOrgNo

---

packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

I think this required translation(`Du må fylle inn et fødselsnummer.`) is more in line with the required translation of organization number(`Du må fylle inn et organisasjonsnummer.`)

chore(Field.NationalIdentityNumber): updates required translation

---

packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumberDocs.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumber.test.tsx

Let's say if user wants to use validator instead of onBlurValidator, then he should be able to disable the default `onBlurValidator`.

chore(Field.NationalIdentityNumber): disable default onBlurValidator using `false`

---

packages/dnb-eufemia/.eslintrc
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useData.tsx

We had a spot that was using `window.structuredClone` instead of the polyfill from `@ungap/structured-clone` that is used everywhere else.
Fixed that spot, and added a rule to eslint to make sure we don't forget in the future.
Note that I don't make any judgement on whether we should be using this or not here, just enforcing consistency.
With this linting rule in place:

fix(Forms): Fix use of unpolyfilled structuredClone in useData hook

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumberAdultValidator.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/stories/NationalIdentityNumber.stories.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

PR adds `createAgeValidator`.
Give the feature a test in this [CSB(outdated](https://codesandbox.io/p/sandbox/xenodochial-ardinghelli-ph6w2k?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd) or in the [new CSB](https://codesandbox.io/p/sandbox/pensive-heisenberg-kcj484?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd), or in the [pr preview](https://eufemia-git-feat-is-adult-validator-eufemia.vercel.app/uilib/extensions/forms/feature-fields/NationalIdentityNumber/demos/#extend-validation-with-adult-validator).
To dos:

feat(Forms): add `createMinimumAgeValidator` to Field.NationalIdentityNumber make a customizable `adultValidator`

---

packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fix(Forms): don't call internal `exportValidators` when they not are exported as an array

---

packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx

- Link for [more info](https://dnb-it.slack.com/archives/CMXABCHEY/p1728383158013599).
- Link to a [CSB](https://codesandbox.io/p/sandbox/selectcountry-locale-issue-cj7d3k?file=/src/App.tsx:11,1&workspaceId=9ef62a18-9e27-4ef9-bc06-7cacaacfab66) that uses React v17, but sadly it does not crash there.

fix(Forms): ensure Field.SelectCountry has a fallback locale (nb-NO)

---

packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/__tests__/ArraySelection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useExternalValue.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fix(Forms): ensure `emptyValue` is set in the data context when defined

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumberMinimumAgeValidator.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/OrganizationNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/__tests__/OrganizationNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-US.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

I've made two CSBs for comparison, and to validate that I've not broken anything.
Based on my testing, it works as expected, as small little enhancement 👍 
[How it works before this PR](https://codesandbox.io/p/sandbox/headless-bird-yt7tcz?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
[How it works in this PR](https://codesandbox.io/p/sandbox/friendly-bash-gwcgml?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)

chore: adds length validator messages

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useTranslation.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useTranslation/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useTranslation/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useTranslation/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/localization.mdx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useTranslation.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useTranslation.tsx
packages/dnb-eufemia/src/shared/Context.tsx
packages/dnb-eufemia/src/shared/__tests__/useTranslation.test.tsx
packages/dnb-eufemia/src/shared/useTranslation.tsx

This PR relies on #4121 as of now.
This lets form components consume the internal translations as well as extending the translations with your own strings: 
```tsx
import { Form } from '@dnb/eufemia/extensions/forms'
const myTranslations = {
'en-GB': {
Custom: {
translation: 'My translation with a {myKey}',
},
},
}
function MyComponent() {
const { Custom, formatMessage } = Form.useTranslation<myTranslations>()
// Use it directly
const str1 = formatMessage(Custom.translation, {
myKey: 'value!',
})
// Or use it with a key
const str2 = formatMessage('Field.errorRequired', {
myKey: 'value!',
})
return <>MyComponent</>
}
<Form.Handler locale="en-GB" translations={myTranslations}>
<MyComponent />
```

feat(Forms): add `Form.useTranslation` hook

---

packages/dnb-eufemia/src/core/jest/jestSetup.js
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Slider/Slider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/__tests__/Section.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

- Shorten the message.
- Avoid showing the warning in our logs.
- Avoid showing the warning when not needed.
- Use `spyOnEufemiaWarn` in other tests as well.
The origin of this PR:

chore: enhance multiple path warning

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useTranslation/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/localization.mdx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useTranslation.test.tsx
packages/dnb-eufemia/src/shared/__tests__/useTranslation.test.tsx
packages/dnb-eufemia/src/shared/useTranslation.tsx

This PR is based on #4121 and #4123
Quick example:
```tsx
const myTranslations = {
'en-GB': {
'stringWithLinebreaks':
'My custom string with a {br}line-break',
},
}
const MyComponent = () => {
const t = useTranslation()
// Render line-breaks
const jsxOutput = t.renderMessage(t.stringWithLinebreaks)
return <>{jsxOutput}</>
}
<Provider translations={myTranslations} locale="en-GB">
<MyComponent />
</Provider>
```

feat: add `renderMessage` to useTranslation hook for line-break support

---

packages/dnb-eufemia/src/extensions/forms/hooks/useTranslation.tsx
packages/dnb-eufemia/src/shared/__tests__/useTranslation.test.tsx
packages/dnb-eufemia/src/shared/useTranslation.tsx

The reason is to avoid re-renders or maximum callstack problems.
The test does fail without the changes:

chore(useTranslation): ensure `formatMessage` and `renderMessage` have the same instance after rerender

---

packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/ArraySelection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/__tests__/ArraySelection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/stories/ArraySelection.stories.tsx

With the use of JSON Schema and ajv's validation, `ArraySelection` supports setting `minItems` and `maxItems` to control how many items the user can select. The validation error message types are however not exposed, thus TypeScript won't let you override them.

feat(Forms): add support for `minItems`/`maxItems` error messages to Field.ArraySelection

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/PostalCodeAndCity.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/PostalCodeAndCityDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/__tests__/PostalCodeAndCity.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/stories/PostalCodeAndCity.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Value/PostalCodeAndCity/PostalCodeAndCity.tsx
packages/dnb-eufemia/src/shared/defaults.ts

feat(Forms): add `country` prop to Field.PostalCodeAndCity to support other countries than Norway

---

packages/dnb-design-system-portal/src/docs/uilib/helpers/classes.mdx
packages/dnb-design-system-portal/src/docs/uilib/helpers/functions.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/component-properties.mdx

Fixes a few links in the following page: https://eufemia.dnb.no/uilib/helpers/functions/#topascalcase
Which would link/redirect to a non-existing page:

chore: fixes faulty links to /contribute/naming

---

.github/workflows/verify.yml

I have had issues where the verify step has run for several hours. This timeout will fix such issues.

chore(CI): set timeout on the verify GitHub Action

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Currency/__tests__/Currency.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx

This PR makes it so that the user can't enter any decimals while doing:
`<Field.Currency decimalLimit={0} />`

fix(Field.Number): `decimalLimit={0}` when `currency` should work

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/about-fields.mdx

docs: add documentation about `emptyValue`

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Fixes #4074
With an exception for when `onChange` or `validator` is async. Then we still want to show the `onBlurValidator`.
**An example**
We have a slow `onChange` event. 
- The user types.
- `onChange` fires and is ongoing while the user types more.
- Before `onChange` has finished, the user blurs the field.
- The `onBlurValidator` fails.
- We show the error coming from the `onBlurValidator`.

fix(Forms): only run onBlurValidator when no other errors are present

---

packages/dnb-eufemia/src/extensions/forms/constants/countries.ts

To have a more common approach to country names across DNB I wanted to update some of the country names in Eufemia which is different from what the KycProfileV2 API provides. I had a discussion with the KycProfileV2 API owner and we reached an agreement regarding which country names they should provide.
This way we avoid having different entities in DnB supplying their own version of country names.
Please let me know if some of these country names are not in accordance with your views and we could have a discussion :)

fix(Forms): updates country names in SelectCountry

---

packages/dnb-eufemia/src/components/number-format/NumberUtils.js
packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts

In this PR, not providing a valid currency when providing value `null` will result in `"null"`. 
And when not providing a valid currency when providing value `undefined` will result in `"undefined"`.  
I don't think it's optimal, but I think it's good enough, as I believe this is an edge-case.
Initially, I would want it to result in the same as using default currency(when not providing a valid one).
Which is `NOK 0.00`.
But to figure out that you have not provided a valid currency, one would have to check up against all valid currencies(https://en.wikipedia.org/wiki/ISO_4217), which is too much job 😅 
I guess we could just return `0` if value is `null` or `undefined`, and then don't care about the other options/properties? 🤔

fix(NumberFormat): should not throw exception when providing an invalid currency

---

packages/dnb-eufemia/src/extensions/forms/Tools/Log.tsx

This fixes an issue occurring in this example: https://eufemia.dnb.no/uilib/extensions/forms/Iterate/Array/#minium-one-item

chore(Portal): fix Tools.Log exception in portal example (Iterate.Array)

---

packages/dnb-eufemia/src/extensions/forms/Form/Handler/stories/FormHandler.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Even the simple scenario `<Field.Number />` can result in:
```
Error: Infinity loop detected and stopped.
at useFieldProps (http://localhost:8002/src_extensions_forms_Form_index_ts.iframe.bundle.js:6112:11)
at NumberComponent (http://localhost:8002/src_extensions_forms_index_ts.iframe.bundle.js:1878:49)
```
Not sure what the cause is, I just randomly type random values, then remove them all(using command + A -> backspace) before entering new random values:
https://github.com/user-attachments/assets/7168d150-0119-4f21-9894-281d6e7982fb
Here's one where I only enter 1 and backspace * repeat:
https://github.com/user-attachments/assets/9c641c5a-9b70-4d8d-bda1-e4ba9b75a9fc

chore: remove leftover infinity loop test code

---

packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/EditContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/EditContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/EditToolbarTools.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/ViewContainer/ViewContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/ViewContainer/ViewContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Section/ViewContainer/ViewToolbarTools.tsx

This allows to listen on the Toolbar button events:
```tsx
<Form.Section>
<Form.Section.EditContainer onDone={onDone} onCancel={onCancel}>
<Field.Name required path="/name" />
</Form.Section.EditContainer>
<Form.Section.ViewContainer onEdit={onEdit}>
<Value.Name path="/name" />
</Form.Section.ViewContainer>
</Form.Section>
```

feat(Forms): add `onDone`, `onCancel` and `onEdit` to Form.Section containers

---

packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx

Updates a test description from https://github.com/dnbexperience/eufemia/pull/4184 for when `autoComplete` is set to `true`. The one for `false` is right below this test.

chore: fix inverted test description for autoComplete property

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields.mdx
packages/dnb-design-system-portal/src/shared/menu/MainMenu.js

Currently on ultra wide monitors or if you have zoom set to  =< 67%, the cards on https://eufemia.dnb.no/ will not be aligned properly to the search bar.
This was a quick fix I found, but I am not an UX/UI expert so let me know if this breaks some accessibility rules :)  
Not centered:
Centered correctly:

refactor: center cards on ultra-wide monitors and fix capitalization typo

---

packages/dnb-eufemia/src/components/upload/Upload.tsx
packages/dnb-eufemia/src/components/upload/UploadDropzone.tsx
packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
packages/dnb-eufemia/src/components/upload/UploadVerify.tsx
packages/dnb-eufemia/src/components/upload/__tests__/useUpload.test.tsx
packages/dnb-eufemia/src/components/upload/types.ts
packages/dnb-eufemia/src/components/upload/useUpload.ts
packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx

More info [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1730734655581989).

fix(Upload): fix `UploadFile` type to include `id` as required

---

packages/dnb-eufemia/src/components/number-format/NumberUtils.js
packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx

fix(Forms): ensure `Field.Number` with `percent` and without a value renders correctly

---

packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/form-row/__tests__/__snapshots__/FormRow.test.tsx.snap
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap
packages/dnb-eufemia/src/components/radio/__tests__/__snapshots__/Radio.test.tsx.snap
packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.tsx.snap
packages/dnb-eufemia/src/extensions/forms/FieldBlock/style/dnb-field-block.scss
packages/dnb-eufemia/src/style/core/utilities.scss

For fields/components that uses a `fieldset` the `gap` spacing did not apply properly:
---
I'm not 100% sure why we not did always make the margin check. But it should actually not effect other styles, as we now check if a spacing class is applied or not.
When this is in main, we may add an example to #4225

fix: ensure components having `fieldset` inside still can use spacing

---

packages/dnb-eufemia/src/components/anchor/Anchor.tsx
packages/dnb-eufemia/src/components/anchor/__tests__/Anchor.test.tsx
packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx

I think it should be possible to remove(not display launch icon) when an anchor has target '_blank'.
It also makes the Anchor more usable, as that's the only reason why it was not used in Upload, and rather an `<a>` with class `'dnb-anchor'` was used.

chore(Anchor): make it possible to remove launch icon

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/ArraySelection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/BankAccountNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Boolean/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Currency/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Date/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Email/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Name/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/NationalIdentityNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Number/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/OrganizationNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/PhoneNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/PostalCodeAndCity/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SelectCountry/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Selection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/String/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/ValueBlock.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/ValueBlock/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/ValueBlock/stories/ValueBlock.stories.tsx
packages/dnb-eufemia/src/extensions/forms/ValueBlock/style/dnb-value-block.scss

fix(Forms): remove extra space from Value.* components with `inline` property

---

packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/SummaryList.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/SummaryListContext.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/__tests__/SummaryList.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/__tests__/useVerifyChildren.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/useVerifyChildren.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useValueProps.ts

More info [here](https://dnb-it.slack.com/archives/C07JEJVSHJR/p1730882739880279?thread_ts=1730737161.151109&cid=C07JEJVSHJR).
It verifies that only allowed children are passed. 
It does this by comparing the amount of given children components vs the amount of the actual wanted components (verified via a context call). 
When there are more other children than the wanted ones, we show a warning ⚠️ 
I'm not sure if there are smarter ways to do that. But as of now, I think this may work.

fix(Forms): console log a warning when Value.SummaryList gets an invalid child

---

packages/dnb-eufemia/src/elements/ElementDocs.ts
packages/dnb-eufemia/src/elements/lists/Dl.tsx
packages/dnb-eufemia/src/elements/lists/DlDocs.ts
packages/dnb-eufemia/src/elements/lists/Li.tsx
packages/dnb-eufemia/src/elements/lists/Ol.tsx
packages/dnb-eufemia/src/elements/lists/OlDocs.ts
packages/dnb-eufemia/src/elements/lists/Ul.tsx
packages/dnb-eufemia/src/elements/lists/UlDocs.ts

As of today the following elements DL, UL, OL [say they have support](https://eufemia.dnb.no/uilib/elements/lists/properties/#ol-properties) for skeleton and skeletonMethod, but they don't as they internally in the component/element set skeleton to false(`skeleton=false`).
This PR removes docs and type support for skeleton(as it is not actually supported) in:
- Dl
- Ul
- Ol

chore: updates docs and types for lists who dont support skeleton

---

packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1731326666796919).

fix(Forms): render given elements to `warning` and `info` properties

---

packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts

Removes the following unnecessary logs:
```
console.log
Eufemia RangeError: Invalid currency code : non-valid value
at Intl.NumberFormat (<anonymous>)
at NumberFormat (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/number-format/NumberUtils.js:1171:25)
at formatToParts (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/number-format/NumberUtils.js:551:16)
at formatNumber (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/number-format/NumberUtils.js:243:15)
at Object.<anonymous> (/Users/anderslangseth/dev/eufemia/packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts:113:18)
at Promise.then.completed (/Users/anderslangseth/dev/eufemia/node_modules/jest-config/node_modules/jest-circus/build/utils.js:298: …
```

chore: reduces unnecessary logs in NumberUtils test

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Appearance/info.mdx

This is not correct/finished.
The motivation behind this change is that when reading the [description](https://eufemia.dnb.no/uilib/extensions/forms/Form/Appearance/info/#description), I don't easily understand which Field.X-components I can use or not with the `Form.Appearance`.
The description doesn't use commonly known names in the forms world as base fields or feature fields, etc, but it rather says  `provides theming of sizes of input fields, including Autocomplete and Dropdown`, thoughts:
- What's input fields?
- Why do we mention the base Eufemia component Autocomplete, instead of the Field equivalent?
- Why do we mention the base Eufemia component Dropdown, instead of the Field equivalent?

chore: improves wording in appearance

---

packages/dnb-eufemia/src/components/date-picker/DatePickerCalc.ts
packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx

I don't think this PR fixes anything, but rather highlights some kind of type mismatch or casting gone wrong in `Field.Date` component, as it comes a lot of string values with value `"undefined"` and `"null"` to the function.
It aims to fix all the console.logs when running `yarn test packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx` in `main` branch:
```
console.log
Eufemia convertStringToDate got invalid date: undefined
at log (src/shared/helpers.js:407:15)
console.log
Eufemia convertStringToDate got invalid date: undefined
at log (src/shared/helpers.js:407:15)
console.log
Eufemia convertStringToDate got invalid date: undefined
at log (src/shared/helpers.js:407:15)
console.log
Eufemia convertStringToDate got invalid date: undefined
at log …
```

chore: reduces unnecessary logs in Field.Date tests

---

packages/dnb-design-system-portal/src/docs/uilib/components/upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/info.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx

Add support for asynchronously processing/handling files so a virus checker can be used with the Field.Upload component.

feat(Forms): add `asyncFileHandler` to Field.Upload to support async file handling during upload

---

packages/dnb-eufemia/src/extensions/forms/Field/Upload/UploadDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx

Adds missing `asyncFileHandler` property from docs and adds test for mixed `asyncFileHandler`handler results

chore(Field.Upload): adds asyncFileHandler test

---

packages/dnb-design-system-portal/src/docs/uilib/components/upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/info.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/UploadDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/stories/Upload.stories.tsx

This PR:
- Renames `asyncFileHandler` -> `fileHandler`.
- Adds support for sync function in `fileHandler`.
- Adds test with error messages and sync function.
- Adds example of sync function.
- Updates examples and docs to match the new fileHandler which can have both a sync and async function.

feat(Field.Upload): adds support for async and sync fn in `fileHandler`

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Section/demos.mdx

Fixes #4308 (not really, it is fixed in v10.57 already) – but I want a heading so we can "link it" easier.

chore(Forms): add heading to basic Form.Section example

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/stories/Upload.stories.tsx

Because a `path` is defined, we can omit the `data` property from Tools.Log, as it will use the data context.

chore(Foms): simplify upload example outupt

---

.github/workflows/e2e.yml
.github/workflows/icons-lib.yml
.github/workflows/verify.yml
.github/workflows/visual-regression.yml

... except when opening a PR from main to release etc.
With that change, we lower the amount of unnecessary runs.

ci: only run GitHub Actions on git commits

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/getData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/setData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useSnapshot/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useValidation/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Container/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/location-hooks/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/useStep/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/ProviderDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Element/__tests__/Element.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/useData.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/clearData.ts
packages/dnb-eufemia/src/extensions/forms/Form/data-context/getData.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useData.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useValidation.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataContext.tsx
packages/dnb-eufemia/src/shared/helpers/__tests__/useSharedState.test.ts
packages/dnb-eufemia/src/shared/helpers/useSharedState.tsx

This feature allows developers to use a function or a React Context as the reference instead of a string-based ID. This can be useful for ensuring a safe local scope, especially when multiple form handlers are present.
```tsx
const myReference= () => null
const MyField = () => {
const { data } = Form.useData(myReference)
return data.foo
} 
render(
<>
<Form.Handler id={myReference}>
...
<MyField />
</>
)
```

feat(Forms): add support for using a function references instead of a string based id

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/RemoveButton/info.mdx
packages/dnb-eufemia/src/components/dialog/parts/DialogAction.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/ArrayItemArea.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/RemoveButton/RemoveButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/RemoveButton/RemoveButtonDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/RemoveButton/__tests__/RemoveButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

Based on #4329
Here is a PR [Preview](https://eufemia-git-feat-forms-confirm-remove-eufemia.vercel.app/uilib/extensions/forms/Iterate/Array/demos/#customize-the-view-and-edit-containers).

feat(Forms): add `showConfirmDialog` to Iterate.RemoveButton

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/all-features.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Element/Element.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Element/__tests__/Element.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/Handler.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitButton/SubmitButton.tsx

This change allows devs to use the data context in a more flexible way:
Before:
```tsx
<App>
<AppRelatedThings>
<Form.Handler> 👈 Data context, form element and status message
...
</AppRelatedThings>
</App>
```
After:
```tsx
<App>
<Form.Handler decoupleForm> 👈 Data context
<AppRelatedThings>
<Form.Element> 👈 form element and status message
...
</Form.Element>
</AppRelatedThings>
</App>
```

feat(Forms): introduce `decoupleForm` prop to Form.Handler

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/info.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/Form/Handler/Handler.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx

Fixes a missing commit for PR #4332

chore: rename `decoupleFormElement` to `decoupleForm`

---

packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx

When using `sessionStorageId` on `Form.Handler` alongside `Field.Upload` with a specified path, file data is stored. However, during serialization, Blob information is not preserved in session storage. As a result, reading this data causes `Field.Upload` to throw an exception.
This PR ensures invalid files are not rendered, preventing such errors.
In the future, we could explore storing Blobs in IndexedDB, but that would require a more extensive effort.

fix(forms): add `sessionStorageId` support to Field.Upload with empty file list rendering

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/DataContext/Provider/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Isolation/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Isolation/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Provider/FieldProvider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/Handler.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/stories/Isolation.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/Section.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/PushContainer.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/ListAllProps.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/__tests__/ListAllProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useSnapshot.tsx
packages/dnb-eufemia/src/extensions/forms/types.ts
packages/dnb-eufemia/src/extensions/forms/utils/json-pointer/json-pointer.ts

The main change is that we go from:
```tsx
type JsonObject = any
```
to
```tsx
type JsonObject = Record<string | number, unknown> | Array<unknown>
```
and enhance the TypeScript support docs for the "Getting Started" section the `Form.Handler` and `Form.Isolation` docs.
To disable types you can do so by:
```tsx
<Form.Handler<any>>
...
```
or
```tsx
const { data } = Form.useData<any>()
```

feat(Forms): enhance typing and add docs on how to deal with TypeScript types

---

packages/dnb-eufemia/src/components/date-picker/DatePickerContext.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerFooter.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/hooks/useDates.ts
packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx

Should hopefully fix the issue described [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1732031524606929)
Neither of us were able to recreate the issue in csb, so testing this manually might be a challenge
This also improves input deletion behaviour when the dates are prop controlled
Before:
https://github.com/user-attachments/assets/2331ac62-e758-44aa-8a93-fcd042a7fc6e
After:
https://github.com/user-attachments/assets/6c3aa9a3-1d01-415e-8028-6626d42b0e3c

fix(DatePicker): make sure the picker and input only reacts to the props that have changed

---

packages/dnb-eufemia/src/components/form-label/FormLabel.tsx

I think it makes sense to add the and statement: https://github.com/dnbexperience/eufemia/pull/4354/files#diff-f476207b8a837f2c0dea83ca374c5d383bcd895b0f6f10e033e12d7c0a7a3f84R142
As all following code in the if statement is dependent on that `ref.current` is existing.
Fixes https://github.com/dnbexperience/eufemia/issues/4352

fix(FormLabel): unhandled runtime error, elem is null

---

packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/VisibilityDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx

We forward the props to HeightAnimation, so we just need the types and the docs to make this work.
Maybe we should call it `onVisible`? But on the other hand, it's meant to be used only when `animate` is set to true.

feat(Forms): add `onVisible` property to Form.Visibility

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility/events.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility/properties.mdx
packages/dnb-eufemia/src/components/height-animation/HeightAnimationDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/VisibilityDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx

I think we should use `onVisible` for both the animated and non-animated state change. Here is the related PR #4350
While `onAnimationEnd` should be used to determine if the animated has "ended". Pretty much like HeightAnimation works.

feat(Forms): add `onAnimationEnd` property to Form.Visibility

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/shared/helpers/__tests__/useSharedState.test.ts
packages/dnb-eufemia/src/shared/helpers/useSharedState.tsx

The reason behind this is that I saw a negative side-effect in PR #4357 when it comes to the initial render, where we don't want an animation, but it did animate.

fix(Forms): avoid unnecessary rerenders in Form.Handler

---

packages/dnb-design-system-portal/gatsby-node.js
packages/dnb-design-system-portal/playwright.config.ts
packages/dnb-design-system-portal/src/docs/contribute/getting-started/make-and-run-tests.mdx
packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/typographic-rules.mdx
packages/dnb-design-system-portal/src/docs/uilib/typography.mdx
packages/dnb-eufemia/playwright.config.ts
packages/dnb-eufemia/src/__tests__/e2e/Fonts.e2e.spec.ts
packages/dnb-eufemia/src/__tests__/e2e/Typography.e2e.spec.ts

- Change `playwright.config.ts` so it runs locally on post 8000.
- Copy fonts folder in /public directory so it can be used by third party apps without getting hashed.
- Document the hosted fonts on [this page](https://eufemia-git-feat-font-cdn-eufemia.vercel.app/uilib/typography/) (could not find a better place, any better ideas out there?).
- Added a e2e test to verify the fonts are located properly.
- Moved `Typography.e2e.spec.ts` from the Portal workspace to the Eufemia Workspace, because I think it's the correct place.

feat: host fonts in the public directory

---

packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/stories/Upload.stories.tsx

From:
https://github.com/user-attachments/assets/3fdc65d0-691e-44b0-bd9b-e97c1d359393
To:
https://github.com/user-attachments/assets/c27a0977-8553-4348-a1ee-4d0aaa6524b5

fix(Field.Upload): handling of multiple async file uploads

---

packages/dnb-design-system-portal/src/docs/uilib/components/upload/Examples.tsx

Better to duplicate, as it makes it easier to read the code examples.
Previously, one would read `useMockFiles(setFiles, { errorMessage: 'This is no real file!' })` in the example code, but not be able to see what `useMockFiles` would do.

chore(Upload): improves readability in examples

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Upload.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Upload/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Upload/events.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Upload/properties.mdx
packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Upload/UploadDocs.ts
packages/dnb-eufemia/src/extensions/forms/Value/Upload/__tests__/Upload.test.tsx

This only adds the "sync" onFileClick event.
Not support for async yet.
Not really sure how the loading state of a Value.Upload with async onFileClick would look 🤔 
Can be demoed here:
https://eufemia-git-feat-upload-value-on-file-click-eufemia.vercel.app/uilib/extensions/forms/Value/Upload/demos/#using-onfileclick

feat(Value.Upload): add `onFileClick` event

---

packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Upload/Upload.tsx

Removes the warning:
```
Eufemia Icon required: A Tertiary Button requires an icon to be WCAG compliant in most cases, because variant tertiary has no underline.
(Override this warning using icon={false}, or consider using one of the other variants) 
```

chore(Upload): fix test warning

---

packages/dnb-eufemia/src/components/dropdown/stories/Dropdown.stories.tsx
packages/dnb-eufemia/src/fragments/drawer-list/DrawerList.d.ts

Fixes the following error when using an `interface` for the `data` property:
```
No overload matches this call.
Overload 1 of 2, '(props: DropdownAllProps | Readonly<DropdownAllProps>): Dropdown', gave the following error.
Type 'MyInterface[]' is not assignable to type 'DrawerListData'.
Type 'MyInterface[]' is not assignable to type 'DrawerListDataArray'.
Type 'MyInterface' is not assignable to type 'DrawerListDataArrayItem'.
Type 'MyInterface' is not assignable to type 'DrawerListDataArrayObject'.
Index signature for type 'string' is missing in type 'MyInterface'.
Overload 2 of 2, '(props: DropdownAllProps, context: any): Dropdown', gave the following error.
Type 'MyInterface[]' is not assignable to type 'DrawerListData'.ts(2769)
```
If I would use a `type` instead of an `interface` it …

fix(Dropdown): correct 'data' type to support interface-based types

---

packages/dnb-eufemia/src/components/upload/UploadDocs.ts

`id` property is [required](https://github.com/dnbexperience/eufemia/blob/ee948ede2201b8bcc489e49874be400187809c85/packages/dnb-eufemia/src/components/upload/types.ts#L19), so makes sense to document it.

docs(Upload): add `id` property

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx

Link to PR build: https://eufemia-git-chore-forms-housekeeping-eufemia.vercel.app/uilib/extensions/forms/getting-started/#quick-start

chore(Forms): enhance Getting Started examples

---

packages/dnb-eufemia/src/shared/helpers/__tests__/useSharedState.test.ts
packages/dnb-eufemia/src/shared/helpers/useSharedState.tsx

When using `useWeakSharedState` it will clean up data when each subscriber has unmounted (when using `id` to sync components with each other).
The term "Weak" is inherited from [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap).

chore: add `useWeakSharedState` for internal use

---

packages/dnb-eufemia/src/components/slider/SliderHelpers.tsx
packages/dnb-eufemia/src/components/slider/SliderProvider.tsx
packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx

PR build with the relevant/reported [example](https://eufemia-git-fix-slider-step-min-max-eufemia.vercel.app/uilib/extensions/forms/feature-fields/more-fields/Slider/#sync-with-input).

fix(Slider): ensure `min` and `max` value is respected when `step` doesn't fit exactly

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SelectCountry/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/__tests__/SelectCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/stories/SelectCountry.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/stories/String.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/stories/Upload.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useValueProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useValueProps.ts

fix(Forms): enhance transformIn and transformOut to support changed array and object instances

---

packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/dnb-eufemia/src/components/drawer/style/dnb-drawer.scss

I don't think this has any effect, as `auto` was a non-valid value. Here are the [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width).

chore(Drawer): use `none` instead of `auto` for min and max width

---

packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx

The main reason was due to a missing `await`. My bad.
It did [fail here](https://github.com/dnbexperience/eufemia/actions/runs/12377018356/job/34554639319?pr=4414).

chore(Visibility): fix flaky test

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx
packages/dnb-eufemia/src/components/autocomplete/stories/Autocomplete.stories.tsx

fixes https://github.com/dnbexperience/eufemia/issues/4293
As of now, I've just added support for the characters ÆØÅ, not sure if there's other non-alphanumeric characters we should support, and perhaps improve the regex to something better than just`\wÆØÅæøå`.
[Original CSB from the issue](https://codesandbox.io/p/sandbox/stoic-feather-8ymh7s)
[CSB with the fix](https://codesandbox.io/p/sandbox/relaxed-paper-gyxyf8?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE) using commit https://github.com/dnbexperience/eufemia/pull/4419/commits/aa28f0c632f1baf57ff2b234157f88ebbe49c043
[CSB with the fix](https://codesandbox.io/p/sandbox/flamboyant-feistel-klw9c2?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE) using commit https://github.com/dnbexperience/eufemia/pull/4419/commits/2334c879516dd658db048778439e4efbb9f62cd …

fix(Autocomplete): support query with unicodes when using `search_numbers`

---

packages/dnb-eufemia/src/components/upload/UploadFileListLink.tsx

fix(Forms): correct font-size of non-clickable Field.Upload item

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/info.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/stories/Upload.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useExternalValue.ts

In this PR #4339 we did not render the stored files.
This time, we do support rendering the file names stored in the session storage. The test dedicated to session storage got aligned.

fix(Forms): add support for `sessionStorageId` in Field.Upload

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedDocs.ts
packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx
packages/dnb-eufemia/src/components/input-masked/stories/InputMasked.stories.tsx

This PR aims to make InputMasked work without providing any props.
Reason why it should work without providing any props, is because all its props is optional.
Defaults to using number mask, as a mask is required.
fixes https://github.com/dnbexperience/eufemia/issues/3134

fix(InputMasked): should work without any properties

---

packages/dnb-design-system-portal/src/shared/tags/TabBar.tsx
packages/dnb-eufemia/src/components/tabs/Tabs.d.ts
packages/dnb-eufemia/src/components/tabs/Tabs.js

fixes https://github.com/dnbexperience/eufemia/issues/3116
Removes `use_hash` which was an internally used property(but was not used anywhere), which was not publicly documented.
Added a new internal property `onOpenTabNavigationFn ` to be able to use Gatsby `navigate` when user presses the next and prev buttons in Tabs:

chore(TabBar): fix navigation on next and prev button click

---

packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/form-row/__tests__/__snapshots__/FormRow.test.tsx.snap
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap
packages/dnb-eufemia/src/components/radio/__tests__/__snapshots__/Radio.test.tsx.snap
packages/dnb-eufemia/src/components/space/__tests__/__snapshots__/Space.test.tsx.snap
packages/dnb-eufemia/src/components/space/style/dnb-space.scss
packages/dnb-eufemia/src/components/space/style/space-mixins.scss
packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.tsx.snap
packages/dnb-eufemia/src/elements/blockquote/style/blockquote-mixins.scss
packages/dnb-eufemia/src/elements/code/style/code-mixins.scss
packages/dnb-eufemia/src/elements/hr/style/hr-mixins.scss
packages/dnb-eufemia/src/elements/img/style/img-mixins.scss
packages/dnb-eufemia/src/elements/lists/style/lists-mixins.scss
packages/dnb-eufemia/src/elements/typography/style/typography-mixins.scss
packages/dnb-eufemia/src/style/core/utilities.scss
packages/dnb-eufemia/src/style/dnb-ui-forms.scss
packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap

This PR changes basically all margin resets with a better check. More info [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1736775869816959).
So this reset:
```scss
&:not([class*='dnb-space']) {
margin: 0;
}
```
Is now like this:
```scss
@include spaceReset();
```
Which again checks for all directions:
```scss
&:not([class*='space__top']) {
margin-top: 0;
}
etc...
```

fix(Spacing): ensure HTML elements like h1 use always a spacing reset

---

packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx

Previously, if a required field was placed inside a PushContainer with `bubbleValidation`, it prevented the Wizard from advancing—even when the container was inactive (not opened). This change ensures that the inactive PushContainer no longer blocks navigation, allowing users to proceed to the next step as intended.
Fixes #4460

feat(Forms): fix inactive `Iterate.PushContainer` blocking Wizard navigation when `bubbleValidation` is true

---

packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/ValueBlock/ValueBlock.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useExternalValue.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useExternalValue.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/hooks/usePath.ts

Because the "element" is a legacy term we moved away from.

chore: rename internal context (`IterateElementContext` to `IterateItemContext`)

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/Examples.tsx
packages/dnb-eufemia/src/components/date-picker/DatePicker.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerDocs.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerPortal.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/date-picker/style/dnb-date-picker.scss
packages/dnb-eufemia/src/components/date-picker/style/themes/dnb-date-picker-theme-ui.scss
packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js
packages/dnb-eufemia/src/shared/component-helper.js

feat(DatePicker): render calendar in a react portal

---

packages/dnb-eufemia/src/components/height-animation/HeightAnimationInstance.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimation.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

The animation is slowed down to 4s in order to see the issue. 
Keep an eye on the container edge, just below the "Velg land" field.
The outer height animation sets a "fixed" height, even only the inner content height gets updated. The fix is to tell all "outer" height animations to not animated (keep the auto height), when an "inner" height gets changed.
Before:
https://github.com/user-attachments/assets/5c53d017-c344-4a4f-8179-75908df7e3aa
After:
https://github.com/user-attachments/assets/84229310-1b39-4790-b5d4-a7c70ba1f6da

fix(HeightAnimation): ensure height does not lock during animation when nested

---

packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/CancelButton.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/__tests__/CancelButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/CancelButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/CancelButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditAndViewContainer.test.tsx

This is a behavior change which concern was reported [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1731317705952689). 
I agree that its confusing that a cancel button not can be used, when an error is present. 
We do handle still errors during submit. The container will even switch to the edit mode when the submit button gets pressed.

feat(Forms): ensure Form.Iterate and Form.Section containers close when cancel button is pressed

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SummaryList/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SummaryList/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/VisibilityContext.ts
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/__tests__/SummaryList.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/stories/SummaryList.stories.tsx
packages/dnb-eufemia/src/extensions/forms/ValueBlock/ValueBlock.tsx
packages/dnb-eufemia/src/extensions/forms/ValueBlock/__tests__/ValueBlock.test.tsx
packages/dnb-eufemia/src/extensions/forms/ValueBlock/style/dnb-value-block.scss
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/__snapshots__/ChildrenWithAge.test.tsx.snap

To maintain the semantic structure of the `dl` element, the `Form.Visibility` component animates the content of the `dl` element instead of wrapping it in a div element.
- More info [here](https://dnb-it.slack.com/archives/C07JEJVSHJR/p1737450029241429).
- [Example](https://eufemia-git-fix-forms-summary-list-visibility-animation-eufemia.vercel.app/uilib/extensions/forms/Value/SummaryList/#with-animated-visibility)

fix(Forms): add animation support to Form.Visibility when used inside Value.SummaryList

---

packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/FieldBoundaryProvider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/__tests__/FieldBoundaryProvider.test.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

As an addition to #4470
With it, we add support for using a `FieldBlock` around `Iterate.Array`.

chore(Forms): enhance `required` prop support (before release) for when used in Iterate.Array

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

Waiting for the actual feature to be completed before merging this 🙏

chore: add nested iterate in iterate to changelog

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/SelectionDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/stories/Selection.stories.tsx

This is only for the Dropdown and Autocomplete.
[Demo](https://eufemia-git-feat-forms-selection-transform-eufemia.vercel.app/uilib/extensions/forms/base-fields/Selection/#dropdown-with-a-transformed-selection-text).

feat(Forms): add `transformSelection` to Field.Selection

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/Examples.tsx

Removes ReferenceError: Tools is not defined in https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/more-fields/Upload/demos/#session-storage-support

chore: ReferenceError: Tools is not defined

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/DoneButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/IterateItemContext.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/PushButton/PushButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushButton/PushButtonDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/PushButton/__tests__/PushButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainerContext.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/EditButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/hooks/index.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/hooks/useItemPath.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/Iterate.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/utils/json-pointer/__tests__/json-pointer.test.ts
packages/dnb-eufemia/src/extensions/forms/utils/json-pointer/json-pointer.ts

Closes #4417
Here is a [working example](https://eufemia-git-feat-iterate-push-container-item-path-eufemia.vercel.app/uilib/extensions/forms/Iterate/demos/#nested-iterate-with-pushcontainer) based on the issue reprod from @andlbrei .

feat(Forms): add `itemPath` property support to `Iterate.PushButton` and `Iterate.PushContainer`

---

packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/stories/Upload.stories.tsx

fixes https://github.com/dnbexperience/eufemia/issues/4495
[CSB](https://codesandbox.io/p/sandbox/fileupload-validation-on-async-upload-forked-r2r4kd?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE)

fix(Field.Upload): prevent `fileHandler` to run when it is validation errors 

---

packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/DataValueWritePropsDocs.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

To be used in #4469 and requested [here](https://dnb-it.slack.com/archives/C04NL73S2Q5/p1737652409110949).

feat(Forms): add support for arrays with errors for `onChangeValidator` and `onBlurValidator`

---

packages/dnb-eufemia/src/extensions/forms/Field/Option/Option.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Option/__tests__/Option.test.tsx

I don't see that the `Field.Option` code is actually used at all 🤔 
It's only the types that's used, as the actual JSX code that `Field.Option` had before this PR would never be ran, it would just be overridden in `Field.Selection` and `Field.ArraySelection`. And as it says in [docs](https://eufemia.dnb.no/uilib/extensions/forms/base-fields/Option/#description): _Field.Option is a pseudo-component that is used by parent components to configure options. It has no use on its own._

chore(Field.Option): remove unused code

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/info.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx

- This is kind of a following up on #4510
- More info [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1738314903619959?thread_ts=1736345187.215229&cid=CMXABCHEY).
**Note:**
When using `transformData` with Iterate.Array, then it is important to exclude the entry from being transformed, because that is probably not what you want. You can do it with a type check or with a `path` !== 'myArray':

fix(Forms): ensure `transformData` contains `displayValue` from fields inside Iterate

---

.github/workflows/icons-lib.yml
.github/workflows/visual-regression.yml
packages/dnb-design-system-portal/package.json
packages/dnb-eufemia/package.json
packages/dnb-eufemia/scripts/prebuild/tasks/makeReleaseVersion.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimation.test.tsx
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimationUtils.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx

This PR includes all the changes from #4522 so far. I will rebase the PR when merged.
Since snapshots are updated on the CI, we had to switch the runner from Linux to macOS and execute everything in one step. This led to slower Jest test execution, requiring adjustments to multiple tests and an increased timeout from 5 to 10 seconds.

chore(Icons): automatically update test snapshots on CI for convenience

---

packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/useValidation.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useValidation.tsx

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1738590820694909).

fix(Forms): ensure `setFieldStatus` by useValidation does not throw when used without id

---

packages/dnb-design-system-portal/src/docs/uilib/components/modal/event-table.mdx
packages/dnb-eufemia/src/components/dialog/__tests__/Dialog.test.tsx
packages/dnb-eufemia/src/components/drawer/__tests__/Drawer.test.tsx
packages/dnb-eufemia/src/components/modal/Modal.tsx
packages/dnb-eufemia/src/components/modal/ModalContent.tsx
packages/dnb-eufemia/src/components/modal/ModalRoot.tsx
packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx
packages/dnb-eufemia/src/components/modal/types.ts

- Also add `handler` to `triggeredBy` when the `close` method is called.
- Improve the documentation of the `triggeredBy` property.
- More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1738574258572699?thread_ts=1738072824.587899&cid=CMXABCHEY) about the approach.
- Thank you Ahmet for the [good reprod](https://codesandbox.io/p/sandbox/connectwithpath-forked-h2wr7p). 🫶

fix(Dialog): prevent `onClose` event from firing in StrictMode when opening a new dialog

---

packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/useVisibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/useVisibility.tsx

fix(Forms): ensure `pathDefined` on Form.Visibility does not render when value is `undefined`

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/info.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/__tests__/ArraySelection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/__tests__/Boolean.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Currency/__tests__/Currency.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/__tests__/Expiry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/__tests__/SelectCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Slider/__tests__/Slider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/__tests__/Toggle.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1738852150610279?thread_ts=1736345187.215229&cid=CMXABCHEY).
A following up on #4526

fix(Forms): only execute `transformData` from fields with a path and not Iterate

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/useFieldProps/info.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/__tests__/ArraySelection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/__tests__/Expiry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Name/__tests__/Name.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Slider/__tests__/Slider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/__tests__/Toggle.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/__tests__/Section.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/DataValueWritePropsDocs.ts
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

With this change, these evens can receive the given field properties as `{ props }`. This is needed in an upcoming PR in relation to #4344.

feat(Forms): provide `{ props }` to the second `onChange`, `onFocus` and `onBlur` event parameter

---

packages/dnb-eufemia/src/components/date-picker/DatePickerCalc.ts
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Fixes [this bug](https://dnb-it.slack.com/archives/CMXABCHEY/p1738399061145199)

fix(DatePicker): compare `date` and `maxDate` at same time of day so `is_valid_end_date` is `true` when `date` and `maxDate` are the same date

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/info.mdx
packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/PostalCodeAndCityDocs.ts
packages/dnb-eufemia/src/extensions/forms/Value/PostalCodeAndCity/PostalCodeAndCityDocs.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts

Motivation is just to continue using postal code instead of postcode.
We already have most occurrences of postal code, hence continuing that trend...

chore: postcode -> postal code

---

packages/dnb-eufemia/src/style/core/reset.scss

fix(ePlatform): adjust ul list style and wrapper style (`max-width` and `padding`)

---

packages/dnb-eufemia/src/extensions/forms/Field/Expiry/Expiry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/__tests__/Expiry.test.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

This PR removes the the strict input control behaviour from the month field, and adds validation and built in error messaging, to make the component be in line with the [new](https://github.com/dnbexperience/eufemia/pull/4508) `Field.Date` behaviour.

feat(Field.Expiry): add month and year validation

---

packages/dnb-eufemia/src/components/date-picker/DatePicker.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx

Fixes this [issue](https://dnb-it.slack.com/archives/CMXABCHEY/p1739954634005029?thread_ts=1738679460.852019&cid=CMXABCHEY)

fix(DatePicker): portal will properly unmount when 'onShow' and 'onHide' callbacks are used to set a state

---

packages/dnb-eufemia/src/components/date-picker/DatePicker.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Fixes this [issue](https://dnb-it.slack.com/archives/CMXABCHEY/p1740128157820069).
Removes redundant `removeOutsideClickHandler` from `useEffect` since `hidePicker`already handles that.

fix(DatePicker): `opened` prop listener `useEffect` no longer removes on outside click detector

---

packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx

The regular expression extracted `"raa"` instead of `"start"` from the ID `"id-raa-start-month"`. This only happened when a certain number of tests were run, likely because React dynamically generated the ID in those cases. All other IDs worked as expected.  
Debugging this took a few hours, during which I refactored some code. I believe the changes make it more readable now.

chore(DatePicker): fix failing tests

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v11-info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/getData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Container/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Container/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/ProviderDocs.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/types.ts

> You can use the `onSubmitRequest` prop on the [Form.Handler](/uilib/extensions/forms/Form/Handler/) to get visible errors before the form is submitted.
```tsx
const onSubmitRequest: OnSubmitRequest = ({ errors }) => {
errors.forEach(({ path, value, label, error }) => {
// Do something with the error
console.log(label, error.message)
})
}
```

feat(Forms): return existing errors in `onSubmitRequest` before Form.Handler submit or Wizard step change

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Container/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Container/demos.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/ProviderDocs.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/types.ts

This is an addition to #4625.
I don’t think we should run the code to generate the errors with all the info unless it’s really necessary. That’s why I suggest using a function. Not that it would have a big performance impact, but still.

chore: return `getErrors` function in `onSubmitRequest` instead of errors

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Name/info.mdx

I don't think this docs/info is correct, as we don't have a field named `Field.SummaryList`, and it doesn't make sense to use `Value.SummaryList` in the example either, so changing to `Form.Handler` instead.

docs(Name): remove Field.SummaryList from example

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/events.mdx
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/hooks/useDates.ts

Adding invalid dates, typed in by user, to the return object, to make it possible to validate if the given date is invalid. As of today, the date is set to null of the date is invalid, making it impossible to tell if the date is null because the input field is empty, or if the date is invalid

feat(DatePicker): add invalid dates to return object

---

packages/dnb-eufemia/src/components/step-indicator/StepIndicator.tsx
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorContext.tsx
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorTriggerButton.tsx

We need this prop in order to be able to show an error status on the Wizard when the screen has a small width. Its used internally only. And may even be removed in v3 of the StepIndicator.

chore(StepIndicator): add `triggerButtonProps` for internal Wizard use to show a state on the trigger button when in small view

---

packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fix(Forms): hide `info`, `warning` or `error` prop when `undefined` is given to a Field

---

packages/dnb-design-system-portal/src/docs/uilib/components/info-card/properties.mdx

These events are already listed under [events](https://eufemia.dnb.no/uilib/components/info-card/events/), so removing them from [properties](https://eufemia.dnb.no/uilib/components/info-card/properties/).

docs(InfoCard): remove events from properties

---

packages/dnb-design-system-portal/src/docs/uilib/components/height-animation/events.mdx

This is how it looks today: https://eufemia.dnb.no/uilib/components/height-animation/events/

docs(HeightAnimation): remove properties heading from events doc

---

packages/dnb-design-system-portal/src/docs/uilib/components/dialog/prop-table.mdx

As of now, we have 2x "Properties"-heading in the Dialog properties docs, https://eufemia.dnb.no/uilib/components/dialog/properties/

docs(Dialog): removes double properties heading

---

packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

As concluded in a team meeting, we should remove the input control, and allow users to type in whatever numbers they want, to prevent confusion, especially for vision impaired users. 
`Field.Date` will with [this PR](https://github.com/dnbexperience/eufemia/pull/4508) warn users if they have typed an invalid date

fix(DatePicker): remove input validation (use Field.Date for included validation)

---

packages/dnb-eufemia/src/components/number-format/NumberUtils.js
packages/dnb-eufemia/src/components/number-format/__tests__/NumberFormat.test.tsx

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1741254690495009).

fix(NumberFormat): ensure -0 is displayed as 0

---

packages/dnb-design-system-portal/.browserslistrc
packages/dnb-design-system-portal/gatsby-config.js
packages/dnb-design-system-portal/package.json
packages/dnb-design-system-portal/src/docs/contribute/faq.mdx
packages/dnb-design-system-portal/src/docs/uilib/assets/SupportedBrowsers.tsx
packages/dnb-design-system-portal/src/docs/uilib/usage.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/styling/polyfill.mdx
packages/dnb-eufemia/.browserslistrc
packages/dnb-eufemia/package.json
packages/dnb-eufemia/scripts/prebuild/config/postcssConfig.js
yarn.lock

My research so far is:
There is a difference in the output. But its minimal. Basically, every file (over 400) have some more imports such as this:
```js
import "core-js/modules/web.dom-collections.iterator.js";
```
Also, we may add a list of the supported browsers in a human readable table/list. Here is a PR that would make that possible: https://github.com/dnbexperience/browserslist-config

feat: use @dnb/browserslist-config for when creating the bundle

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx
packages/dnb-eufemia/src/components/input/Input.js
packages/dnb-eufemia/src/components/input/__tests__/Input.test.tsx
packages/dnb-eufemia/src/components/radio/__tests__/Radio.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/__tests__/Section.test.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/__tests__/GenerateSchema.test.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/__tests__/ListAllProps.test.tsx

Removing the `value` attribute from the HTML output, as best practice nowdays is to avoid updating it dynamically.  
Getting the `value` via the attribute was **never documented**, so this should be safe to remove.

fix(Input): remove value attribute (⚠️ Use element.value instead in e.g. tests)

---

packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts

`Field.Date` does not support `date` property, but uses `value` instead.
Hence removing `date` property from the properties docs of `Field.Date` :)

docs(Field.Date): remove `date` property

---

packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx

Looks like prettier did some formatting one save too 😅 The only real change was putting all the `DatePicker` prop related tests inside a describe clause 🙏

chore(Field.Date): group `DatePicker` prop tests inside a describe

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Examples.tsx

Reason for adding is that it's nice to have a help button example incorporated in the [value docs](https://eufemia.dnb.no/uilib/extensions/forms/Value/) as well.

docs(Value): add help button to example

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/properties.mdx
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/hooks/useInvalidDates.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts

We have decided to go for removing the strict input control (will be done in a separate pr), and allow for user to input invalid dates, and extending the `returnObject` to contain the invalid dates, so we can allow for error messaging when an invalid date is given. This is to make the component less confusing for users, and it will remove code complexity on our side. `Field.Date` will be updated to show error messages by default when an invalid date is given, and invalid dates will be corrected to closes valid date, only when `correctInvalidDates` is enabled.
relies on groundwork from https://github.com/dnbexperience/eufemia/pull/4469
also relies on invalid date properties from https://github.com/dnbexperience/eufemia/pull/4637
now also relies on …

feat(Field.Date): show error messages on invalid date

---

packages/dnb-eufemia/src/components/number-format/NumberUtils.js
packages/dnb-eufemia/src/components/number-format/__tests__/NumberFormat.test.tsx
packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts

fix(NumberFormat): render properly when `sv-SE` locale is given

---

packages/dnb-design-system-portal/src/shared/menu/PortalToolsMenu.tsx

docs: add link to localization docs in portal tools menu

---

packages/dnb-eufemia/src/extensions/forms/Field/Currency/__tests__/Currency.test.tsx

Not too important, but just a nice-to-have test, as I assume a lot of applications should use the autocomplete value [transaction-amount](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#transaction-amount), especially in PM, etc.
I've added docs for this `transaction-amount` in https://github.com/dnbexperience/eufemia/pull/4770

chore(Field.Currency): add autoComplete transaction-amount test

---

packages/dnb-eufemia/src/extensions/forms/Wizard/Container/DisplaySteps.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/IterateOverSteps.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/WizardContext.ts

Same as #4751 – just to the StepIndicator trigger button – e.g. when on small screens.

fix(Forms): don't show Wizard step error on small screens for the same step

---

packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/stories/SelectCountry.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/constants/countries.ts

Or perhaps this is "too breaking", possibly requiring our users to import and use the type `CountryISO`?

feat(Field.SelectCountry): enhance value type

---

packages/dnb-eufemia/src/components/number-format/NumberUtils.js
packages/dnb-eufemia/src/components/number-format/__tests__/NumberFormat.test.tsx

Related PR #4691 and [more details](https://dnb-it.slack.com/archives/CMXABCHEY/p1742463244250749?thread_ts=1741254690.495009&cid=CMXABCHEY).

fix(NumberFormat): ensure -0 is displayed as 0 when formatted as currency

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Number/stories/Number.stories.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/stories/FieldBlock.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1742375173085389
Fixes https://github.com/dnbexperience/eufemia/issues/4771
CSB of the issue: https://codesandbox.io/p/sandbox/eloquent-tharp-z9pck9
For now, I've just added a stor, but not sure if that's too helpful as I don't believe the TypeScript settings in this repo is strict enough to catch/display the same errors as in the [CSB of the issue](https://codesandbox.io/p/sandbox/eloquent-tharp-z9pck9).

fix(Forms): enhance typing for `FieldBlock` and `useFieldProps`

---

packages/dnb-eufemia/src/components/anchor/__tests__/AnchorScroll.test.tsx

Swallowing these logs:
```
PASS  src/components/anchor/__tests__/AnchorScroll.test.tsx (6.433 s)
● Console
console.log
Eufemia "scrollToHashHandler" is deprecated.
at log (src/shared/helpers.js:407:15)
console.log
Eufemia "scrollToHashHandler" is deprecated.
at log (src/shared/helpers.js:407:15)
console.log
Eufemia "scrollToHashHandler" is deprecated.
at log (src/shared/helpers.js:407:15)
console.log
Eufemia "scrollToHashHandler" is deprecated.
at log (src/shared/helpers.js:407:15)
console.log
Eufemia "scrollToHashHandler" is deprecated.
at log (src/shared/helpers.js:407:15)
console.log
Eufemia "scrollToHashHandler" is deprecated.
at log (src/shared/helpers.js:407:15)
console.log
Eufemia "scrollToHashHandler" is deprecated.
at log (src/shared/helpers.js:407:15)
```

chore(Anchor): swallow deprecated scrollToHashHandler test logs

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String/Examples.tsx

I tested the added example and found an issue when selecting the text. The updated example takes care of when selecting an area in the input field before typing.

docs: update `onInput` example (prevent typing of invalid characters)

---

packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js
packages/dnb-eufemia/src/shared/component-helper.js

I get the following error:
```
Eufemia TypeError: Cannot use 'in' operator to search for 'current' in undefined
at DetectOutsideClickClass.checkOutsideClick (component-helper.js:558:1)
at DetectOutsideClickClass.handleClickOutside
```
when visiting https://eufemia.dnb.no/uilib/components/fragments/scroll-view/ locally http://localhost:8000/uilib/components/fragments/scroll-view/

chore: Eufemia TypeError: Cannot use 'in' operator to search for 'current' in undefined

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/useFieldProps/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/useValueProps/info.mdx

Improves the warning:
```
Eufemia Cannot decrease to heading level 1! Had before 2 - The new level is 2 
NB: This warning was triggered by:  #Description
```

chore: Cannot decrease to heading level 1

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCurrency/AvailableCurrenciesTable.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCurrency/assets/AvailableCurrenciesTable.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCurrency/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCurrency/properties.mdx

Can be demoed here: https://eufemia-git-docs-add-list-of-currencies-in-props-eufemia.vercel.app/uilib/extensions/forms/feature-fields/SelectCurrency/properties/#list-of-available-currencies

docs(Field.SelectCurrency): display list of available currencies

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/FieldBoundaryProvider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlockContext.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/useVisibility.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/useCollectStepsData.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/types.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useValueProps.ts

We use maps a couple of places in Eufemia Forms. Maps in general can be faster, but are mostly less memory hungry. So I think some of our internals can and should be rewritten.

chore(Forms): refactor object to use maps

---

packages/dnb-eufemia/src/components/upload/UploadFileList.tsx
packages/dnb-eufemia/src/components/upload/__tests__/testHelpers.ts
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/stories/Upload.stories.tsx

When async removing a file that has the same file name as an other file, both files displays as loading/removing, and only 1 file is removed. 
The expected result when clicking remove for file x is that only file x is loading/removing and only file x is removed.
CSB of the problem: https://codesandbox.io/p/devbox/exciting-pike-td395f
Video of the problem:
https://github.com/user-attachments/assets/549bccac-d856-4b48-a924-6104d592e666
CSB with the fix in this PR: https://codesandbox.io/p/devbox/sad-antonelli-dkdmtp?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE
Sidenote: As of today, it's allowed with files of the same file name, that's not in our code classified as an "existing file".
These are the conditions that needs to be met for it to be an "existing file": …

fix(Field.Upload): async removal of file with same file name as other file

---

packages/dnb-design-system-portal/src/docs/uilib/components/upload/Examples.tsx

Improves so that we don't render the uploaded file/image infinitely many times, demo [here](https://eufemia.dnb.no/uilib/components/upload/demos/#useupload-react-hook):
https://github.com/user-attachments/assets/292f3046-7841-4e3e-a476-c9a7a18c7c08
Should only display the image once, and not infinitely many times.

chore(Upload): improve  example

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/demos.mdx

This PR now just adds the `ChangeLocale` dropdown in the `Field.Date` docs.
TODO:
Here's a video from main branch when changing locale in DatePicker (expected behavior):
https://github.com/user-attachments/assets/c9fa9398-3a3f-4da6-abf6-889ab43dd72a
Here's a video from main branch when changing locale in Field.Date (unexpected behavior):
https://github.com/user-attachments/assets/7f1ddabd-4269-4aa0-b3b1-9cf40480c554

chore(Field.Date): improve localization in docs

---

packages/dnb-eufemia/src/components/date-picker/DatePickerAddon.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerCalendar.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerContext.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/hooks/useViews.ts

Fixes  [this issue](https://dnb.enterprise.slack.com/archives/CMXABCHEY/p1742391247076779?thread_ts=1742391247.076779&cid=CMXABCHEY)

fix(DatePicker): update calendar views based on input value when `range` is `true`

---

packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx
packages/dnb-eufemia/src/components/avatar/__tests__/Avatar.test.tsx

Fixes so setting `size`, `variant`, `color`, `backgroundColor` when single Avatar as child should work.
As of today, this does not work:
```
<Avatar.Group label="tags" variant="secondary">
<Avatar>A</Avatar>
</Avatar.Group>
```
This will now work after this fix 🙏

fix(Avatar.Group): forward `size`, `variant`, `color`, `backgroundColor` to single child

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1743427503988359).

fix(Forms): prevent form submit when `error` prop is set on a `Field.*`

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMaskedUtils.test.ts
packages/dnb-eufemia/src/extensions/forms/Field/Currency/__tests__/Currency.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Currency/stories/Currency.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx

This issue only occurred when the suffix changed while typing. In that case, the cursor was placed at the end because the lengths no longer matched the initially provided value.
We now send in the current/latest suffix, and the cursor position is set correctly.
In this video; the issue is shown all the way at the end of the video, where the cursor gets placed at the end.
https://github.com/user-attachments/assets/aee4df3c-3394-4b40-a653-0083b13e1ca1

fix(InputMasked): ensure correct cursor position when suffix changes during typing

---

packages/dnb-eufemia/src/components/date-picker/DatePickerContext.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.tsx
packages/dnb-eufemia/src/components/date-picker/hooks/useDates.ts

Moves the value `hasHadValidDate` variable to `DatePickerInput` since it's the only component that actually uses it. No need for it to live in the context and `useDates` hook

chore(DatePicker): move `hasHadValidDate` to `DatePickerInput`

---

packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/hooks/useDates.ts

Fixes [this issue](https://dnb-it.slack.com/archives/CMXABCHEY/p1744105593951939)

fix(DatePicker): display correct dates when props are updated with `useLayoutEffect`

---

packages/dnb-eufemia/src/components/date-picker/DatePickerFooter.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/hooks/useDates.ts
packages/dnb-eufemia/src/components/date-picker/hooks/useInputDates.ts

Fixes this [issue](https://dnb-it.slack.com/archives/CMXABCHEY/p1744105593951939) by removing the `useEffect`/`useLayoutEffect` that updates the input date values
Related to https://github.com/dnbexperience/eufemia/pull/4945 and https://github.com/dnbexperience/eufemia/pull/4937
[CSB reprod ](https://codesandbox.io/p/sandbox/inspiring-water-cqtxc8)with the original issue, using this build

fix(DatePicker): display correct dates when props are updated with `useLayoutEffect` in `React.StrictMode` 

---

packages/dnb-design-system-portal/package.json
yarn.lock

I have not tested if it actually works. I think we need to test a "build" and not a dev start.

chore(Portal): add support for ${...} and \${...} in string literals

---

packages/dnb-eufemia/src/components/step-indicator/StepIndicatorItem.tsx
packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.tsx.snap
packages/dnb-eufemia/src/components/step-indicator/style/dnb-step-indicator.scss
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx

[CSB of the issue](https://codesandbox.io/p/devbox/frosty-hertz-vnxfsp?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE):
[How it should look](https://codesandbox.io/p/sandbox/laughing-darkness-788lz8)
[CSB of the fix](https://codesandbox.io/p/devbox/smoosh-worker-rs5ncc?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE):

fix(StepIndicator): font size of step items

---

packages/dnb-eufemia/src/components/step-indicator/StepIndicatorTriggerButton.tsx
packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.tsx.snap
packages/dnb-eufemia/src/components/step-indicator/style/dnb-step-indicator.scss

Example: https://eufemia-git-feat-step-indicator-chevron-transition-eufemia.vercel.app/uilib/components/step-indicator/demos/#stepindicator-in-static-mode
Before:
https://github.com/user-attachments/assets/20ae29aa-33ce-4e1d-a4a2-efcafcf48dab
After:
https://github.com/user-attachments/assets/d2df8875-6b9d-4d55-b794-2d4f8cf8912a

feat(StepIndicator): animate chevron on expand/collapse

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SelectCurrency/info.mdx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCountry/__tests__/SelectCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCurrency/SelectCurrency.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCurrency/__tests__/SelectCurrency.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCurrency/__tests__/useCurrency.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCurrency/useCurrency.ts

When providing a not valid/supported iso code as `value`, the provided value will be displayed instead of the component breaking/failing.

fix(Value.SelectCurrency): handle invalid iso code values

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SelectCountry/info.mdx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCountry/__tests__/SelectCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCountry/__tests__/useCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCountry/useCountry.ts

When providing a not valid/supported iso code as `value`, the provided value will be displayed instead of the component breaking/failing.
fixes https://github.com/dnbexperience/eufemia/issues/4991

fix(Value.SelectCountry): handle invalid iso code values

---

packages/dnb-eufemia/src/components/date-picker/DatePickerCalendar.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Fixes [this](https://dnb-asa.atlassian.net/jira/software/c/projects/EDS/boards/734?assignee=712020%3A11a274b8-3b2a-4c7f-9968-07cf788ff7dd&selectedIssue=EDS-730) and [this](https://dnb-asa.atlassian.net/jira/software/c/projects/EDS/boards/734?assignee=712020%3A11a274b8-3b2a-4c7f-9968-07cf788ff7dd&selectedIssue=EDS-279).
Line 308 caused the date object to mutate to the previous valid date, when navigating backwards with the keyboard.
https://github.com/user-attachments/assets/b533c424-81c6-4fce-b8a8-a92f7c859e92
https://github.com/user-attachments/assets/4821f4ad-3053-4da3-9e4f-dafd94b7690e

fix(DatePicker): prevent selection of invalid dates when navigating the calendar with arrow keys

---

packages/dnb-design-system-portal/src/docs/uilib/components/copy-on-click/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/copy-on-click/demos.mdx
packages/dnb-eufemia/src/components/copy-on-click/CopyOnClick.tsx
packages/dnb-eufemia/src/components/copy-on-click/__tests__/CopyOnClick.test.tsx
packages/dnb-eufemia/src/components/copy-on-click/style/dnb-copy-on-click.scss
packages/dnb-eufemia/src/core/jest/jestSetup.js

- Feature nr. 1 of [this post](https://dnb-it.slack.com/archives/CMXABCHEY/p1745580508874319?thread_ts=1745578322.405229&cid=CMXABCHEY).
- PR [Preview](https://eufemia-git-fix-copyonclick-textcontent-eufemia.vercel.app/uilib/components/copy-on-click/demos/#copy-text-content).
- We could almost always just relay on using `.textContent` instead of trying to get the content of children. Any thoughts?

fix(CopyOnClick): copy `textContent` when given children is empty

---

packages/dnb-eufemia/src/components/height-animation/HeightAnimationInstance.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimation.test.tsx

This PR reverts the fix introduced here #4493 
With this we ensure it always "end" animations properly. I have seen too often that this causes issues. 
In future we rather can and should use only CSS solutions like [`interpolate-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/interpolate-size) with [`calc-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc-size).

fix(HeightAnimation): always end animation properly when animation has finished

---

packages/dnb-eufemia/src/components/radio/Radio.js
packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx

This fix has a relation to #4584

fix(Selection): support `undefined` value from data context

---

packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlockDocs.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

We already have a visual test for `labelSize="medium"`, this PR just enables this feature to be used in fields directly.

feat(Forms): add support for `labelSize` to all Field.*

---

packages/dnb-eufemia/src/components/date-picker/DatePickerCalendar.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerContext.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerRange.tsx
packages/dnb-eufemia/src/components/date-picker/hooks/useDates.ts
packages/dnb-eufemia/src/components/date-picker/hooks/useHoverDate.ts

Motivated by https://github.com/dnbexperience/eufemia/pull/5021 as the `onHoverDay` keeps updating the other dates, making it impossible to keep track of the previous selected dates without adding a lot of extra code.

chore(DatePicker): separate `onHoverDay` from `useDate` to prevent unnecessary date updates

---

packages/dnb-eufemia/src/extensions/forms/Field/Number/style/dnb-number.scss
packages/dnb-eufemia/src/extensions/forms/FieldBlock/style/dnb-field-block.scss

On a certain screen width, a large FieldBlock will overflow. It "can" and probably will cut over Field.String in the default width.
With the issue:
With this PR, the large size will adjust it to a lower width, so it will not overflow:

fix(Forms): ensure fields do not overflow in width on a certain screen size

---

packages/dnb-eufemia/src/components/date-picker/DatePickerCalc.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePickerCalc.test.ts

Relates to #4886
You can test it here: https://eufemia-git-feat-date-picker-copy-eufemia.vercel.app/uilib/extensions/forms/feature-fields/Date/ by copy&pasting from one field to another.

feat(DatePicker): copy whole formatted date when coping from input field

---

packages/dnb-eufemia/src/components/toggle-button/ToggleButton.js
packages/dnb-eufemia/src/components/toggle-button/__tests__/ToggleButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/stories/Selection.stories.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1746520226276669
The fix does so [Field.Selection variant button](https://eufemia.dnb.no/uilib/extensions/forms/base-fields/Selection/demos/#toggle-buttons):
- ToggleButton has `role="radio"`
- ToggleButton.Group has`role="radiogroup"`
- ToggleButton component when role radio sets `aria-checked` instead of `aria-pressed`
I think role radio is correct as one can only select one of these toggle buttons / items, read https://www.w3.org/TR/wai-aria/#radio
Fixes https://github.com/dnbexperience/eufemia/issues/3241

fix(Forms): support `required` in Field.Selection with `button` variant

---

packages/dnb-eufemia/src/components/modal/ModalDocs.ts

I don't think it was done with purpose to deprecate these props in this PR https://github.com/dnbexperience/eufemia/pull/1190, and commit 
https://github.com/dnbexperience/eufemia/commit/ebe8e6a597c87885c081fcdfd76339780e90befc#diff-f1c94bc3bf35a0cb7181e56dab45c760dfa612539ab3fcd8c903e3c76b6b9f6e
It's been over 3 years since the docs was set to `deprecated/optional`, and the props have not been deprecated since.
There's also no comments in the actual code about deprecation of these props, or that these props should be deprecated.
Props written in snake_case(`close_title`, `hide_close_button`, `spacing`) is also not deprecated here https://github.com/dnbexperience/eufemia/blob/0c4ef059e5ff9af51ad7393290aaa7184c0da1c0/packages/dnb-eufemia/src/components/modal/types.ts

docs(Modal): `closeTitle`, `hideCloseButton`, `spacing` is not deprecated

---

packages/dnb-eufemia/src/components/toggle-button/ToggleButton.js
packages/dnb-eufemia/src/components/toggle-button/__tests__/ToggleButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/__tests__/Boolean.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/__tests__/Toggle.test.tsx

Here's demo for variant [button](https://eufemia-git-fix-toggle-a11y-issues-variant-buttons-eufemia.vercel.app/uilib/extensions/forms/base-fields/Toggle/demos/#buttons) and variant [checkbox-button](https://eufemia-git-fix-toggle-a11y-issues-eufemia.vercel.app/uilib/extensions/forms/base-fields/Toggle/demos/#checkbox-button). They behave like checkboxes, therefore I've set the role to `checkbox`.

fix(Forms): support `required` in Field.Toggle with `button` & `checkbox-button` variant

---

packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/ArraySelection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/__tests__/ArraySelection.test.tsx

Builds on top of https://github.com/dnbexperience/eufemia/pull/5104
Variant [button](https://eufemia-git-fix-array-selection-a11y-issues-eufemia.vercel.app/uilib/extensions/forms/base-fields/ArraySelection/demos/#button-variant) and [checkbox-button](https://eufemia-git-fix-array-selection-a11y-issues-eufemia.vercel.app/uilib/extensions/forms/base-fields/ArraySelection/demos/#button-with-checkbox-variant) behaves like checboxes, hence setting role to `checkbox`

fix(Forms): support `required` in Field.ArraySelection with `button` & `checkbox-button` variant

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Boolean/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Boolean/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Boolean/events.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Toggle/events.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/Boolean.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/BooleanDocs.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/__tests__/Boolean.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/ToggleDocs.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/__tests__/Toggle.test.tsx

fix(Field.Toggle, Field.Boolean): add support for `preventDefault` in onClick for `checkbox` variant

---

packages/dnb-eufemia/src/components/heading/HeadingHelpers.ts
packages/dnb-eufemia/src/components/heading/__tests__/Heading.test.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1743769418111539
CSB: https://codesandbox.io/p/devbox/value-padding-forked-5lrp2k
I do not think we should warn about this, as I believe:
```
<Heading>heading</Heading>
<Heading increase>subheading</Heading>
``` 
should result in h1 and h2 which it does, but without warnings.
I do think the reason why we log the warning today, is because we automatically change the second heading to be a h2 in the snippet:
```
<Heading>heading</Heading>
<Heading>subheading</Heading>
``` 
So hence, our code tries/thinks the following code will increase the heading level to h3 of the second heading which is already made into a h3:
```
<Heading>heading</Heading>
<Heading increase>subheading</Heading>
``` 
I think the code perhaps could be simplified or …

fix(Heading): warning when increasing heading to be `h2` when previous sibling is `h1`

---

packages/dnb-eufemia/src/components/dropdown/Dropdown.js
packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.tsx

fixes this [issue](https://dnb-it.slack.com/archives/CMXABCHEY/p1747217419048679)

fix(Dropdown): fix `React.ReactNode` support for `title` prop

---

packages/dnb-eufemia/src/extensions/forms/hooks/useSnapshot.tsx

It looks like #5129 did introduce a issue during portal build.

chore(Form.useSnapshot): add safeguard when using hook

---

packages/dnb-eufemia/src/extensions/forms/Field/Boolean/Boolean.tsx

Seems like these props was introduced in https://github.com/dnbexperience/eufemia/pull/3513/files#diff-de62b4ab2ab5f16d0a602679528ed1dff658f08f79dcab55310c59b0d70a6abd
I don't fully understand why `Field.Boolean` has to have props related to `Field.Indeterminate`. Hence suggesting to remove it, or at least discuss it 😅

chore(Field.Boolean): remove Indeterminate props

---

packages/dnb-design-system-portal/src/docs/uilib/components/country-flag/properties.mdx

When thinking about it, it's sort of misleading as the list of available/supported countries is not actually determined from `import countries from '../../extensions/forms/constants/countries'` but rather all the ISO codes listed here: packages/dnb-eufemia/assets/flags/1x1

docs(CountryFlag): list available countries

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx

This PR ensures that `filterData` runs on every internal data context path, and not only on mounted fields. This allows `filterData` to be used on predefined data as well, without a related field.

fix(Forms): run `filterData` on every data entry, not only on mounted fields

---

packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/localization.mdx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useTranslation.test.tsx
packages/dnb-eufemia/src/shared/__tests__/useTranslation.test.tsx

This PR adds some tests and enhances the tests with some info about typing.
Thank you @andlbrei 
Motivation: https://github.com/dnbexperience/eufemia/pull/5148#discussion_r2103103453

chore(useTranslation): add typing tests for using an identifier

---

packages/dnb-design-system-portal/src/core/ChangeLocale.tsx

Pretty sure we removed all other occurrences of "beta" for Swedish in our docs in a PR not many weeks ago.

chore: remove beta from Swedish

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/payment-card/helpers.mdx
packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1748941526894089
[Link to the docs saying how to import](https://eufemia.dnb.no/uilib/extensions/payment-card/helpers/#formatcardnumber):  `import { formatCardNumber } from '@dnb/eufemia/extensions/PaymentCard'`. 
But this is actually never been a valid path or import statement (take a look at this [CSB](https://codesandbox.io/p/devbox/intelligent-bas-sz6n52?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE) from where the [docs was added](https://github.com/dnbexperience/eufemia/pull/2702), it's not working), but should have been either: 
`import { formatCardNumber } from '@dnb/eufemia/extensions/payment-card/PaymentCard'`
or: `import { formatCardNumber } from '@dnb/eufemia/extensions/payment-card'`.
So this PR updates the docs for the correct …

fix(PaymentCard): export `formatCardNumber` from PaymentCard

---

packages/dnb-eufemia/src/components/accordion/Accordion.tsx
packages/dnb-eufemia/src/components/accordion/AccordionContext.ts
packages/dnb-eufemia/src/components/accordion/AccordionGroup.tsx
packages/dnb-eufemia/src/components/accordion/AccordionProviderContext.ts
packages/dnb-eufemia/src/components/accordion/AccordionStore.ts

Fixes [this issue](https://dnb-asa.atlassian.net/jira/software/c/projects/EDS/boards/734?assignee=712020%3A11a274b8-3b2a-4c7f-9968-07cf788ff7dd&selectedIssue=EDS-789) by consolidating the `expandBehaviour` and `expandBehavior` and adding a default value to the `expandBehavior` used in context, for grouped accordions used outside of an `Accordion.Group`
[Deploy Preview](https://eufemia-git-fix-accordion-unable-to-collapse-group-bug-eufemia.vercel.app/uilib/components/accordion/#customized-accordion)
[Current Docs](https://eufemia.dnb.no/uilib/components/accordion/#customized-accordion)

fix(Accordion): fix Accordion toggle behavior when not used inside an `Accordion.Group`

---

packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/__tests__/Expiry.test.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/sv-SE.ts

[Fixes](https://dnb-it.slack.com/archives/CMXABCHEY/p1748958017935249) 🙏
You should now be able to select dates in range mode, without triggering the required error message. An error message for invalid date range will also now trigger of both start date and end date inputs are empty.
[Oirginal CSB](https://codesandbox.io/p/devbox/quizzical-ritchie-td7q84?workspaceId=ws_E5ciTFghWDp59nAiN8Yqpd)
[CSB With Fix](https://codesandbox.io/p/sandbox/white-wave-sj4x3c?file=%2Fpackage.json%3A17%2C101)

fix(Field.Date): required validation with date ranges

---

packages/dnb-eufemia/scripts/prebuild/tasks/__tests__/makeReleaseVersion.test.ts
packages/dnb-eufemia/scripts/prebuild/tasks/makeReleaseVersion.ts
packages/dnb-eufemia/src/shared/Eufemia.ts
packages/dnb-eufemia/src/shared/__tests__/Eufemia.test.ts
packages/dnb-eufemia/src/shared/helpers/runCssVersionMismatchWarning.ts

Also, it should with that be possible to get a short sha. We may document that as a feature if we see that it works.
Here is a test setup: https://stackblitz.com/edit/dsuwq5hy

chore: add `Eufemia.versions` support

---

packages/dnb-eufemia/src/fragments/drawer-list/DrawerList.tsx

Add & exported `DrawerListSize`-type. This was available before 10.74.0, but removed after for some reason

fix(DrawerList): add & export DrawerListSize-type

---

packages/dnb-eufemia/scripts/postbuild/__tests__/postbuild.test.ts

A test that should verify that no files with .mjs or .cjs extensions are used, does fail.
On main we build more packages, so there it failed only on main. This will replaced #5249.

chore(CI): fix failing tests on main

---

packages/dnb-eufemia/src/components/upload/UploadDocs.ts
packages/dnb-eufemia/src/components/upload/__tests__/Upload.test.tsx

`Upload` already support `children` prop today, but it's not documented. Hence documenting it.

docs(Upload): support `children`

---

packages/dnb-eufemia/src/fragments/drawer-list/__tests__/DrawerList.test.tsx

Also, all tests where run with `skip_portal` which means the tests where run without being in a React Portal. But one of the main purposes of the `DrawerList` is to run in a Portal. Therefore the refactoring.

chore(DrawerList): add more tests

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Connectors/Bring/info.mdx

Not too important, but the url with `#supported-countries` doesn't exist.

chore(Forms): correct link to bring address api

---

packages/dnb-eufemia/src/extensions/forms/Field/Indeterminate/Indeterminate.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Indeterminate/__tests__/Indeterminate.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Indeterminate/stories/Indeterminate.stories.tsx

Deploy preview: https://eufemia-git-chore-add-axe-tests-to-fields-eufemia.vercel.app/uilib/extensions/forms/base-fields/Indeterminate/demos/

fix(Field.Indeterminate): add support for `required` property

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/Examples.tsx

The code box seems to remove the `\` from the regex masks used in the example.
Before: 
After:

chore(Field.Number): fix custom mask docs example

---

packages/dnb-eufemia/src/style/core/helper-classes/skip-link.scss

fixes: https://dnb-it.slack.com/archives/CMXABCHEY/p1753708180948019
I'm not entirely sure how/what the fix here should be, seems like the [following change](https://github.com/dnbexperience/eufemia/pull/5306/files#diff-ef3774a725c2e6dad3648a609dfe7ba96fad8c9d1d36e362575ff55f24a8eebc) in this [PR](https://github.com/dnbexperience/eufemia/pull/5306) makes it fail in release `v10.77.1`.
Could there be a bigger issue with the `[skip-isolation]` strategy?
To experience the issue, I made a CSB using [v10.77.1](https://codesandbox.io/p/devbox/keen-thunder-kt4f4l?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE) and one using [v10.77.0](https://codesandbox.io/p/devbox/inspiring-hooks-24vw4t?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE).
@tujoworker

fix: skip-link styling

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String/info.mdx

Adds documentation based on the answers in [this thread](https://dnb-it.slack.com/archives/CMXABCHEY/p1753096647186049)

docs(Field.String): add demo example using `TextCounter` together with `maxLength` property

---

packages/dnb-eufemia/src/components/number-format/style/dnb-number-format.scss
packages/dnb-eufemia/src/components/table/TableClickableHead.tsx
packages/dnb-eufemia/src/components/table/__tests__/TableAccordionMode.test.tsx
packages/dnb-eufemia/src/shared/helpers.js

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1753777131358149
By clicking the "button" which is not a button, but just an icon in the most left cell, we should always be able to expand or close the accordion.

fix(Table): allow expanding by chevron when text is selected

---

packages/dnb-design-system-portal/src/shared/parts/PortalStyle.scss

Related to #5367
This fixes a new arising issue on smaller screens by using `min-height` instead of just height:
`dvh` is useful here because on mobile browsers (like Safari or Chrome on iOS/Android) the classic vh unit can be misleading — it includes the space taken up by the browser’s address bar and navigation controls, even when they’re visible.

chore(Portal): vertically stretch the home page background

---

packages/dnb-design-system-portal/src/docs/uilib/components/aria-live/Examples.tsx
packages/dnb-eufemia/src/components/aria-live/stories/AriaLive.stories.tsx

Fixes the broken ["additions demo/example"](https://eufemia.dnb.no/uilib/components/aria-live/demos/#additions):
```
react-dom.production.min.js:106 Uncaught DataCloneError: Failed to execute 'structuredClone' on 'Window': Symbol(react.element) could not be cloned.
at index.js:20:46
at useData.tsx:115:12
at useData.tsx:135:28
at Object.on_click (eval at si (evalCode.ts:3:7), <anonymous>:22:17)
at _ (component-helper.ts:249:34)
at Button.js:86:26
at Object.Fe (react-dom.production.min.js:54:317)
at $e (react-dom.production.min.js:54:471)
at react-dom.production.min.js:55:35
at Ir (react-dom.production.min.js:105:68)
```

chore(AriaLive): improve additions demo

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx

Suggesting to remove this, as it doesn't work to provide a `Value` to a `label` of a `Value` or `Field`:
`label={<Value.String itemPath="/label" />}`
Or should it actually work?
```
<Value.String
label={<Value.String itemPath="/label" />}
itemPath="/value"
/>
```
I see that the reporter expects it to work in https://github.com/dnbexperience/eufemia/issues/4194
The example can be viewed/demoed here: https://eufemia.dnb.no/uilib/extensions/forms/Iterate/Array/#value-composition

chore: remove non-visible label in example

---

packages/dnb-eufemia/src/extensions/forms/ValueBlock/ValueBlock.tsx
packages/dnb-eufemia/src/extensions/forms/ValueBlock/__tests__/ValueBlock.test.tsx

In regards to #4194 and [this comment](https://github.com/dnbexperience/eufemia/issues/4194#issuecomment-3188760960).

fix(Forms): ensure labels from `Value.*` components can be served from a `Value.*` component itself

---

packages/dnb-design-system-portal/src/core/ChangeLocale.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/date-format/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/date-format/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/date-format/info.mdx
packages/dnb-eufemia/src/components/date-format/DateFormat.tsx
packages/dnb-eufemia/src/components/date-format/DateFormatDocs.ts
packages/dnb-eufemia/src/components/date-format/DateFormatUtils.ts
packages/dnb-eufemia/src/components/date-format/__tests__/DateFormat.test.tsx
packages/dnb-eufemia/src/components/date-format/stories/DateFormat.stories.tsx

👉 PR Preview: https://feat-dateformat-relative-tim.eufemia-e25.pages.dev/uilib/components/date-format/demos/
Originally it was speculated that we could use a [duration string](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/time#valid_datetime_values) value for the `datetime` attribute. But from testing it seems like VoiceOver does not pick up on, or reads the duration string at all.
I've tried setting it up like in [this example](https://www.jasha.eu/blogposts/2019/05/voiceover-safari-time-element.html), but the VoiceOver ignores the duration string, and reads the sentence as "It takes 47 meters to travel to the Hauge" in a broke norwegian accent (the system language i tested) instead of "It takes 47 minutter to travel to the Hauge" as the example claims it should. …

feat(DateFormat): add support for relative time (auto updated)

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap
packages/dnb-eufemia/src/components/date-format/__tests__/DateFormat.test.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap
packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.tsx.snap
packages/dnb-eufemia/src/components/input/style/dnb-input.scss
packages/dnb-eufemia/src/components/textarea/style/dnb-textarea.scss

Fixes #5217
I also tried adding a visual test for these styles. There is a way to do this via Chromium and its DevTools, but it would require a significant refactoring.
Another option would be to use a "simulation" class, but I think this approach is too fragile from a maintenance perspective and could negatively impact CSS specificity in certain cases.

fix(Input): ensure error, focus, and hover states work with autofilled content

---

packages/dnb-eufemia/src/components/tooltip/TooltipWithEvents.tsx
packages/dnb-eufemia/src/components/tooltip/__tests__/Tooltip.test.tsx

I'm not 100% sure why we have had these events. Also, no tests are failing when removing it. The most important once for such as hover, touchstart and focus we have tests. So I think its fine for now.
Here are the PR docs in case of a need: https://aa466ee5.eufemia-e25.pages.dev/uilib/components/tooltip/

fix(Tooltip): remove click event to make screen reader not read out "clickable"

---

packages/dnb-design-system-portal/package.json
packages/dnb-design-system-portal/src/docs/uilib/components/input/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/payment-card/Examples.tsx
packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/components/drawer/__tests__/Drawer.test.tsx
packages/dnb-eufemia/src/components/modal/Modal.tsx
packages/dnb-eufemia/src/components/space/SpacingUtils.ts
packages/dnb-eufemia/src/components/table/table-accordion/TableAccordionHead.tsx
packages/dnb-eufemia/src/components/tabs/__tests__/Tabs.test.tsx
packages/dnb-eufemia/src/components/tabs/stories/Tabs.stories.tsx
packages/dnb-eufemia/src/components/tooltip/TooltipPortal.tsx
packages/dnb-eufemia/src/style/themes/theme-ui/prism/dnb-prism-theme.ts
packages/eufemia-starter/package.json
yarn.lock

The issue started because running `test:types` locally was crashing TypeScript — but it didn’t happen in CI. This is probably related to the recent Node.js upgrade.
To debug the problem, I tried using a newer TypeScript version, which helped me track it down to the Drawer.test.tsx file. For now, we’re skipping type-checking of this file to avoid the crash. The error seems to be caused by TypeScript struggling with the complex type handling (camelCase vs snake_case).

chore: upgrade internal TypeScript version to latest

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx
packages/dnb-eufemia/src/fragments/drawer-list/DrawerListItem.tsx

Reverse of `aria-current` and `aria-selected` to be correct with accessibility rules.
- `aria-selected` is `true` for the selected option (the input value) and `false` for the other options.
- `aria-current` is true for the focused option (when navigating), and is removed from other option.
The use of `aria-current` is not needed by WAI-ARIA specs, but added by us for screen reader compatibility.

fix(DrawerList): swap aria-selected and aria-current

---

packages/dnb-eufemia/src/components/button/Button.js
packages/dnb-eufemia/src/components/button/__tests__/Button.test.tsx

fix(Button): remove `disabled` attribute when disabled with `href`

---

packages/dnb-eufemia/src/components/dialog/__tests__/Dialog.test.tsx
packages/dnb-eufemia/src/components/drawer/__tests__/Drawer.test.tsx
packages/dnb-eufemia/src/components/help-button/__tests__/HelpButton.test.tsx
packages/dnb-eufemia/src/components/modal/ModalContent.tsx
packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx
packages/dnb-eufemia/src/components/modal/parts/ModalHeader.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitConfirmation/__tests__/SubmitConfirmation.test.tsx
packages/dnb-eufemia/src/shared/helpers/InteractionInvalidation.ts
packages/dnb-eufemia/src/shared/helpers/__tests__/InteractionInvalidation.test.ts

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1757332666406779 and I think even https://dnb-it.slack.com/archives/CMXABCHEY/p1758017383453619
This PR:
- Ensures to set focus, even when no close button and no title was found.
- Ensures `aria-hidden` is not present in parent elements, so ctr+opt+array-key navigation works properly in VoiceOver.

fix(Dialog, Drawer): enhance screen reader support and focus management

---

packages/dnb-eufemia/package.json

Jest v30 supports extra arguments as filters. So we can remove --testNamePattern for better CLI command support.

chore(jest): remove --testPathPatterns

---

packages/dnb-design-system-portal/gatsby-node.js
packages/dnb-design-system-portal/src/shared/tags/Transition.ts

It may be the cause of such wired snapshots:
Like when ViewTransition runs – even it theoretical should not:
Or maybe a transition to fullscreen. Even I can't find it to happen.

chore: ensure no ViewTransition is enabled during visual tests

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Currency/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/String.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/ChildrenWithAge.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/utils/zod.ts

fix(Field.Number): show formatted numbers in error messages

---

packages/dnb-eufemia/src/components/tabs/TabsCustomContent.tsx

Fixes the following error from our tests:
```
console.error
Warning: CustomContent: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
```

chore(Tabs.Content): remove propType `key`

---

packages/dnb-design-system-portal/src/docs/uilib/components/autocomplete/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/dropdown/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/fragments/drawer-list/demos.mdx

@snorrekim, does these changes make sense?
I just saw the docs was referencing a `group` property, which doesn't exist, so I changes to `groups`.

chore(Dropdown, Autocomplete, DrawerList): `group` to `groups`

---

packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Just came over that this part needed a `isZodSchema` check as well. Even its an edge case.

fix(Forms): enhance schema prioritization when using Zod schema

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-format/info.mdx

Motivation: Krister did use the old import from when it was placed in the DatePicker.

docs(DateFormat): document `formatDate` helper function
