dnbexperience/eufemia

packages/dnb-design-system-portal/src/pages/uilib/typography/font-weights/usage-in-css.md
packages/dnb-design-system-portal/src/pages/uilib/usage/best-practice/styling.md
packages/dnb-ui-lib/src/components/button/Button.js
packages/dnb-ui-lib/src/components/button/__tests__/__snapshots__/Button.test.js.snap
packages/dnb-ui-lib/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
packages/dnb-ui-lib/src/components/icon/__tests__/__snapshots__/Icon.test.js.snap
packages/dnb-ui-lib/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap
packages/dnb-ui-lib/src/components/input/Input.js
packages/dnb-ui-lib/src/components/input/__tests__/Input.test.js
packages/dnb-ui-lib/src/components/input/__tests__/__snapshots__/Input.test.js.snap
packages/dnb-ui-lib/src/components/input/style/_input.scss
packages/dnb-ui-lib/src/components/input/style/themes/dnb-input-theme-ui.scss
packages/dnb-ui-lib/src/components/logo/__tests__/__snapshots__/Logo.test.js.snap
packages/dnb-ui-lib/src/components/modal/__tests__/__snapshots__/Modal.test.js.snap
packages/dnb-ui-lib/src/components/slider/__tests__/__snapshots__/Slider.test.js.snap
packages/dnb-ui-lib/src/components/switch/__tests__/__snapshots__/Switch.test.js.snap
packages/dnb-ui-lib/src/components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
packages/dnb-ui-lib/src/patterns/view-title/__tests__/__snapshots__/ViewTitle.test.js.snap
packages/dnb-ui-lib/src/style/core/dnb-style.scss
packages/dnb-ui-lib/src/style/core/properties.scss
packages/dnb-ui-lib/src/style/core/scopes.scss
packages/dnb-ui-lib/src/style/core/typography.scss
packages/dnb-ui-lib/src/style/core/utilities.scss

regarding to the placeholder, we had to define a new style. But we also made a change due to the active stated (2px border) - this has to be checked with Jens.

enhance input

---

packages/dnb-ui-lib/scripts/prepub/tasks/makeMainStyle.js
packages/dnb-ui-lib/src/components/button/__tests__/__snapshots__/Button.test.js.snap
packages/dnb-ui-lib/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
packages/dnb-ui-lib/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap
packages/dnb-ui-lib/src/components/input/__tests__/__snapshots__/Input.test.js.snap
packages/dnb-ui-lib/src/components/logo/__tests__/__snapshots__/Logo.test.js.snap
packages/dnb-ui-lib/src/components/modal/__tests__/__snapshots__/Modal.test.js.snap
packages/dnb-ui-lib/src/components/slider/__tests__/__snapshots__/Slider.test.js.snap
packages/dnb-ui-lib/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.js.snap
packages/dnb-ui-lib/src/components/switch/__tests__/__snapshots__/Switch.test.js.snap
packages/dnb-ui-lib/src/components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
packages/dnb-ui-lib/src/patterns/view-title/__tests__/__snapshots__/ViewTitle.test.js.snap
packages/dnb-ui-lib/src/style/core/scopes.scss
packages/dnb-ui-lib/src/style/dnb-ui-basis.scss
packages/dnb-ui-lib/src/style/dnb-ui-body.scss

In order to be able to have the body stiles inside a app wrapper, we have this class helper to get the body styles inside the wrapper as well without using the body
```html
<div class="dnb-app-content">My App Content</div>
```

fix style packages + add a feature

---

packages/dnb-ui-lib/src/shared/component-helper.js

- fix touch device detection regarding #e76b5ae

release of v5.8.1

---

.drone.yml

- fix missing env vars on ci release

release of v6.1.2 - take two

---

packages/dnb-ui-lib/src/components/modal/Modal.js

- fix #modal delay/timeout not getting properly cleared

release of v6.3.2

---

packages/dnb-ui-lib/src/components/accordion/Accordion.js

* feat: add #accordion (beta) component (#564)
* WIP: add files
* WIP: #accordion before prerender state
* WIP: make prerender work
* WIP: make  work
* WIP: fix IE issue
* WIP: add `remember_state` to #accordion
* WIP: fix `remember_state` to #accordion
* WIP: add first styles and make the component structure flexible
* WIP: fix #accordion component size and title / desc spacing
* WIP: enhance handling of keyboard usage and avoid selection
* WIP: skip screen shot tests
* feat: add `allow_close_all` prop
* WIP: enhance the flexibility and add container, left_component and description as well as icon right aligned
* chore: define `dark-grey` and `outline-grey`
* WIP: add styles
* WIP: fix default spacing and spacing support
* WIP: fix hover issue in #accordion header
* fix: remember …

release of v7.2-beta.2

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/info.md

Inconsistent use of DatePicker and date-picker

update docs for DatePicker component

---

packages/dnb-ui-lib/src/components/button/__tests__/Button.test.js

Testing the following logic of a Button, https://github.com/dnbexperience/eufemia/blob/a72bb99dde7b2f446173cb04357a66137a71640d/packages/dnb-ui-lib/src/components/button/Button.js#L240-L255

chore: test setting variant and size of button

---

packages/dnb-ui-lib/src/patterns/payment-card/utils/CardDesigns.js

Fixed two issues regarding the new pluss design
* Pluss has now been added to the Designs object
* Pluss card used invalid type for BankAxept but has now been changed to White
Tested with *yarn test*.

fix: used wrong type on BankAxept on pluss design

---

packages/dnb-design-system-portal/src/docs/icons.md
packages/dnb-design-system-portal/src/docs/quickguide-designer/typography/typographic-rules.md
packages/dnb-design-system-portal/src/docs/uilib/components/pagination/demos.md
packages/dnb-design-system-portal/src/docs/uilib/usage/customisation.md

Fix outdate/breaking links to repo

docs: fix links to repo

---

packages/dnb-design-system-portal/src/docs/design-system/contact.md

I think Tobias's email is incorrect, `_tobias.hoegh@dnb.no_.`
https://eufemia.dnb.no/design-system/contact

fix: change contact email for Tobias

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.md
packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v9-info.md
packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/Examples.js
packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/demos.md
packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/info.md
packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/properties.md
packages/dnb-design-system-portal/src/docs/uilib/demos/eufemia-demo/form-demo-01.js
packages/dnb-eufemia-sandbox/stories/components/StepIndicator.js
packages/dnb-eufemia/src/components/step-indicator/StepIndicator.js
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorItem.js
packages/dnb-eufemia/src/components/step-indicator/__tests__/StepIndicator.test.js
packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.js.snap
packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap
packages/dnb-eufemia/src/style/elements/code.scss

This is a first step in making the API cleaner for the future StepIndicator makeover.

fix: simplify #step-indicator API with a couple of *deprecation* warnings

---

packages/dnb-eufemia/src/components/help-button/HelpButtonInstance.js
packages/dnb-eufemia/src/components/help-button/__tests__/HelpButton.test.js

- When text is given, do not use aria-label

fix: fix #modal #help-button aria usage

---

.husky/pre-commit
packages/dnb-design-system-portal/src/docs/uilib/development.md

This PR makes lint-staged opt-in.
Read more in the docs on how to enable it (once it is released):
https://eufemia.dnb.no/uilib/development

chore: make lint-staged optional

---

packages/dnb-eufemia/src/components/accordion/AccordionContent.js
packages/dnb-eufemia/src/components/global-status/GlobalStatus.js
packages/dnb-eufemia/src/shared/AnimateHeight.js
packages/dnb-eufemia/src/shared/__tests__/AnimateHeight.test.js

- change .setElem() to .setElement()

chore: refactor AnimateHeight class

---

packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.js.snap
packages/dnb-eufemia/src/components/button/style/themes/dnb-button-theme-ui.scss
packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap
packages/dnb-eufemia/src/style/elements/_anchor-mixins.scss

Heres a CSB to showcase the new animation: https://codesandbox.io/s/eufemia-button-animation-i82x7?file=/src/App.tsx

fix: fix tertiary button animation, defined by UX

---

packages/dnb-design-system-portal/.ncurc.json
packages/dnb-design-system-portal/package.json
yarn.lock

release of v9.12.0

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap
packages/dnb-eufemia/src/components/autocomplete/style/themes/dnb-autocomplete-theme-ui.scss
packages/dnb-eufemia/src/fragments/drawer-list/__tests__/__snapshots__/DrawerList.test.js.snap
packages/dnb-eufemia/src/fragments/drawer-list/style/themes/dnb-drawer-list-theme-ui.scss

This PR fixes a color contrast issue when a DrawerList item is selected and gets focus at the same time.

fix: fix focus contrast issue when #drawer-list is selected and gets focus

---

packages/dnb-eufemia/src/components/input-masked/InputMasked.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap

This PR will add inputMode if a numeric mask is used.

fix: use numeric and decimal inputMode on InputMasked

---

CHANGELOG.md
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap
packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.js.snap
packages/dnb-eufemia/src/components/tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
packages/dnb-eufemia/src/fragments/drawer-list/__tests__/__snapshots__/DrawerList.test.js.snap
packages/dnb-eufemia/src/style/core/utilities.scss
packages/dnb-eufemia/src/style/elements/table.scss

A style change on dropshadow was requested and found in Figma:
[Eufemia Web - RFCs - Figma](https://www.figma.com/file/PomHecnAnpJJQb9HPowWSa/?node-id=6738%3A24867)
_Please let me know if I missed doing something_

fix: update dropshadow styles

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.js
packages/dnb-eufemia/src/fragments/drawer-list/DrawerList.js

fix(Autocomplete): enhance selections and event calls when autocomplete value gets removed

---

packages/dnb-design-system-portal/gatsby-node.js
packages/dnb-design-system-portal/src/shared/tags/CodeBlock.js

This PR fixes a bug where the code preview during development did not update (fast-refresh) whyle edidit – so a hard refresh was needed.

chore(Portal): fix live dev preview of code examples

---

packages/dnb-design-system-portal/src/docs/design-system/about.md

docs: remove link to deactived slack accounts

---

packages/dnb-design-system-portal/src/shared/menu/SearchBar.js
packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.js
packages/dnb-design-system-portal/src/uilib/search/searchQuery.js

This PR depends on their future PRs as well:

Enhance UX of portal search

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js

This PR fixes an issue when the initial value is 0

fix(InputMasked): change value when leading zero is 0 initially

---

packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.js

chore(Portal): fix modal z-index to be above portal header – always

---

package.json
packages/dnb-design-system-portal/src/docs/uilib/development/changes.md

This is just a staring point. We may find a better structure or even a additional page for all this info.

docs: write some more docs about creating new components

---

packages/dnb-eufemia-sandbox/.eslintrc
packages/dnb-eufemia-sandbox/package.json
yarn.lock

Looks like v8 of ESLint wants to have some config to make its job.

chore: add ESLint to sandbox

---

packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.js.snap
packages/dnb-eufemia/src/components/modal/style/_modal.scss

Closes #1104
Reprod [CSB](https://codesandbox.io/s/eufemia-modal-selection-bug-79dul?file=/src/App.tsx)

fix(Modal): text selection issue after modal has been closed

---

packages/dnb-design-system-portal/src/docs/uilib/components/pagination/Examples.js
packages/dnb-eufemia-sandbox/stories/components/Pagination.js
packages/dnb-eufemia-sandbox/stories/components/PaginationTable.js
packages/dnb-eufemia-sandbox/stories/components/PaginationTableMarker.js
packages/dnb-eufemia/src/components/pagination/Pagination.js
packages/dnb-eufemia/src/components/pagination/PaginationBar.js
packages/dnb-eufemia/src/components/pagination/PaginationInfinity.js
packages/dnb-eufemia/src/components/pagination/PaginationProvider.js
packages/dnb-eufemia/src/components/pagination/__tests__/Pagination.test.js
packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap

This PR fixes an issue where a infinity scroller was used and suddenly the top placed "load more" button did appear.
Also, added finally some tests for the infinity scroller.

fix: fix pagination indicator and load button issue

---

EUFEMIA_CHANGELOG.md

Update changelog since this is a large design change for component GlobalStatus

chore: update changelog with GlobalStatus

---

packages/dnb-design-system-portal/src/docs/uilib/components/button/info.md
packages/dnb-eufemia/src/components/button/Button.js

Closing issue #876 
Updated warning message and also added more information in the docs.

chore: Improve warning for tertiary button without icon (#876)

---

packages/dnb-design-system-portal/src/docs/contribution/types.md
packages/dnb-eufemia/scripts/prepub/tasks/generateTypes.js
packages/dnb-eufemia/scripts/prepub/tasks/generateTypes/__tests__/__mocks__/ClassComponent.js
packages/dnb-eufemia/scripts/prepub/tasks/generateTypes/__tests__/__mocks__/PrimaryComponent.js
packages/dnb-eufemia/scripts/prepub/tasks/generateTypes/__tests__/__snapshots__/babelPluginCorrectTypes.test.js.snap
packages/dnb-eufemia/scripts/prepub/tasks/generateTypes/__tests__/__snapshots__/babelPluginIncludeDocs.test.js.snap
packages/dnb-eufemia/scripts/prepub/tasks/generateTypes/__tests__/__snapshots__/babelPluginPropTypesRelations.test.js.snap
packages/dnb-eufemia/scripts/prepub/tasks/generateTypes/babelPluginPropTypesRelations.js

With this PR, its now possible to referance prop types as a static function or class property.

Enhance type generation

---

packages/dnb-eufemia-sandbox/stories/components/ToggleButton.js
packages/dnb-eufemia/src/components/toggle-button/ToggleButton.js
packages/dnb-eufemia/src/components/toggle-button/__tests__/ToggleButton.test.js

Heres a [CSB](https://codesandbox.io/s/fancy-waterfall-5n069?file=/src/App.js) that shows the issue

fix: fix re-render issue with ToggleButtons

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/dnb-ui-lib/v5-info.md
packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/dnb-ui-lib/v6-info.md
packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/dnb-ui-lib/v7-info.md
packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/dnb-ui-lib/v8-info.md
packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.md
packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v9-info.md

docs: fix typos in release notes

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap

This PR fixes an issue where the user could not enter a leading zero when a custom mask was used.

fix(InputMasked): allow leading zero when custom mask is given

---

packages/dnb-design-system-portal/src/docs/uilib/usage/layout/media-queries.md

Remove "new" status from media queries

docs: remove "new" from media queries

---

packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx
packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap

Fixed a small typo in Breadcrumb test

fix(Breadcrumb): fix typo in test files

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/regression.md
packages/dnb-design-system-portal/src/docs/contribute/first-contribution.md
packages/dnb-design-system-portal/src/docs/contribute/rules.md
packages/dnb-design-system-portal/src/docs/issue.js
packages/dnb-design-system-portal/src/docs/uilib/getting-started.md

This commit adds a way to quickly lunch the starter and create a Codesandbox by visiting 🐛 http://eufemia.dnb.no/issue (when its released)

chore: add codesandbox starter

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.js

Just to have a dedicated test for this case as well – ##1118

chore: add test regarding issue #1118

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js
packages/dnb-eufemia/src/components/input-masked/text-mask/createTextMaskInputElement.js

fix: fix InputMasked delete key usage

---

packages/dnb-design-system-portal/src/docs/uilib/components/info-card/Examples.js
packages/dnb-eufemia-sandbox/stories/components/InfoCard.js

Inspired by https://github.com/dnbexperience/eufemia/pull/1277/commits/cd8dd487fc324c23385de439234c1f6eb9afc49a

chore: move info-card to local images

---

packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap
packages/dnb-eufemia/src/components/modal/style/_modal.scss

[CSB](https://codesandbox.io/s/eufemia-modal-ie11-bug-r8upy?file=/src/App.tsx) to test the PR version on.
Before
After

fix(Modal): ensure IE11 is placing the close button to the right side

---

packages/dnb-eufemia/src/shared/helpers/__tests__/withCamelCaseProps.test.tsx
packages/dnb-eufemia/src/shared/helpers/withCamelCaseProps.tsx

Moved this into a separate PR to keep it simple. I also added a new test to verify 😃

chore: update classWithCamelCaseProps with a prop change check

---

packages/dnb-design-system-portal/src/docs/EUFEMIA_CHANGELOG.md

Updated changelog from version @9.22.0

docs: update changelog

---

.github/workflows/build-check.yml
.github/workflows/icons-lib.yml
.github/workflows/release.yml
.github/workflows/verify.yml
.github/workflows/visual-test.yml

Ensure we run the Slack action when an action fails.

chore(CI): run Slack action on failures

---

packages/dnb-eufemia/src/components/info-card/InfoCard.tsx
packages/dnb-eufemia/src/components/info-card/__tests__/__snapshots__/InfoCard.test.tsx.snap
packages/dnb-eufemia/src/components/info-card/stories/InfoCard.stories.js
packages/dnb-eufemia/src/components/info-card/style/_info-card.scss

The component did not behave proparly on smaller screens, see screenshots for before and after visuals

fix(InfoCard): issue on smaller screens

---

packages/dnb-design-system-portal/src/docs/uilib/components/dialog/info.md
packages/dnb-design-system-portal/src/docs/uilib/components/drawer/info.md

To prevent misinterpretation and errors when trying to convert from Modal to Drawer or Dialog 😊

fix(docs): add more information on converting from Modal

---

packages/dnb-design-system-portal/src/docs/uilib/components/tag/properties.md
packages/dnb-eufemia/src/components/tag/Tag.tsx
packages/dnb-eufemia/src/components/tag/__tests__/Tag.test.tsx
packages/dnb-eufemia/src/components/tag/stories/Tag.stories.tsx

For reference https://dnb-it.slack.com/archives/CMXABCHEY/p1645714272401489

feat(Tag): omit non-existing group warning with new prop: hasLabel

---

packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.js
packages/dnb-eufemia/src/fragments/drawer-list/DrawerList.js
packages/dnb-eufemia/src/fragments/drawer-list/DrawerListHelpers.js

Thank you Mateusz!
For reference: https://dnb-it.slack.com/archives/CMXABCHEY/p1645701889827709

fix(Dropdown): fix empty data entry handling

---

packages/dnb-design-system-portal/src/docs/contribute/style-guides/issues.md

Added minor corrections in style guide section.

docs: minor corrections in style guide section

---

packages/dnb-design-system-portal/src/docs/quickguide-designer.md

Fixed TOC in designers quick start guide,

docs: fix TOC in designers quick start guide

---

packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.js.snap
packages/dnb-eufemia/src/components/button/style/themes/dnb-button-theme-ui.scss

This PR makes it easier to change the sizes of the button

fix(Button): make tertiary button icon inherit button height property

---

packages/dnb-eufemia/src/components/tag/TagGroup.tsx
packages/dnb-eufemia/src/components/tag/__tests__/Tag.test.tsx
packages/dnb-eufemia/src/components/tag/stories/Tag.stories.tsx

[Reproduction codesandbox](https://codesandbox.io/s/naughty-tharp-bupbc6?file=/src/App.tsx)

fix(Tag): avoid inheriting spacing props when set on Tag.Group

---

packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx

fix(Breadcrumb): Allow Breadcrumb to get skeleton prop from context

---

packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap
packages/dnb-eufemia/src/style/elements/hr.scss

Reprod Codesandbox: https://codesandbox.io/s/quirky-feistel-6huglk?file=/src/App.tsx

fix(Hr): ensure the hr element does not causing a scrollbar

---

packages/dnb-design-system-portal/src/docs/design-system/about.md

Add Eufemia vision to the portal
✨ transparency ✨

docs: add vision statement to the portal

---

packages/dnb-eufemia/src/components/tooltip/TooltipPortal.js

This PR aims to fix two issues:
- If the main main group contains more than one tooltip, and one of them is unmounted, the portal is removed prematurely, causing an exception to be thrown.
- If the main group contains more than one tooltip and a tooltip is activated before a previously active tooltip has completed `hide_delay`, the previous tooltip sticks around as a zombie
For the first issue we keep a count of the number of tooltips in the group and only remove the group when it is empty.
For the second issue we store a copy of the timeout ref on the component and clear it on unmount. The group timeout is only cleared on render if the tooltip is not in the main group.
The tests pass, and the portal looks OK. Anything else I need to do @tujoworker?

fix(Tooltip): fix premature removal of portal and prevent zombies

---

packages/dnb-design-system-portal/src/docs/uilib/helpers/functions.md
packages/dnb-design-system-portal/src/docs/uilib/helpers/info.md
packages/dnb-eufemia/src/shared/__tests__/helpers.test.js
packages/dnb-eufemia/src/shared/helpers.js

feat(helpers): add cancel method to debounce

---

package.json
yarn.lock

Until now, Gatsby would have been effected by the resolutions as well. This PR fixes it.

chore(Storybook): ensure we only define a fixed Webpack v5 for Storybook

---

packages/dnb-design-system-portal/src/shared/menu/MainMenu.js

chore(Portal): fix logo alignment and make nav and logo better on a11y

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js
packages/dnb-eufemia/src/components/input-masked/addons/createNumberMask.js

fix(InputMasked): fix integerLimit option when used with decimals

---

packages/dnb-eufemia/src/components/dialog/Dialog.tsx
packages/dnb-eufemia/src/components/dialog/DialogContent.tsx
packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap
packages/dnb-eufemia/src/components/dialog/style/_dialog.scss
packages/dnb-eufemia/src/components/dialog/types.ts
packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/dnb-eufemia/src/components/modal/ModalContent.tsx
packages/dnb-eufemia/src/components/modal/ModalContext.tsx
packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap
packages/dnb-eufemia/src/shared/component-helper.js

This PR fixes an issue where the Dialog component did not scroll when there was content that overflows the Dialog on the Safari iOS browser.

fix(Dialog): fix Safari issue not able to scroll

---

packages/dnb-eufemia/jest.config.screenshots.js
packages/dnb-eufemia/scripts/prebuild/tasks/prepareTemplates.js

+ Collect tsx when generating index/lib files

chore: Make visual screenshot tests to work with tsx files

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/demos.md

I think `locale` is the correct prop name 🙏

docs(DatePicker): locales to locale

---

packages/dnb-eufemia/src/components/table/Table.tsx
packages/dnb-eufemia/src/components/table/TableTd.tsx
packages/dnb-eufemia/src/components/table/TableTh.tsx
packages/dnb-eufemia/src/components/table/TableTr.tsx
packages/dnb-eufemia/src/components/table/__tests__/Table.test.tsx
packages/dnb-eufemia/src/components/table/__tests__/TableStickyHeader.test.tsx
packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap
packages/dnb-eufemia/src/components/table/style/_table.scss
packages/dnb-eufemia/src/components/table/style/themes/dnb-table-theme-ui.scss

Small alignments and fixes related to PR #1422
This PR also makes things ready to support a future PR for responsive tables.

fix(Table): align HTML/CSS classes and types

---

packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap
packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap
packages/dnb-eufemia/src/components/modal/style/_modal-mixins.scss
packages/dnb-eufemia/src/components/modal/style/_modal.scss

This release includes the PR #1441

release of v9.26.1

---

packages/dnb-design-system-portal/src/docs/uilib/components/table/Examples.js
packages/dnb-design-system-portal/src/docs/uilib/components/table/info.md
packages/dnb-eufemia/src/components/table/TableStickyHeader.tsx
packages/dnb-eufemia/src/components/table/__tests__/TableStickyHeader.test.tsx
packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap
packages/dnb-eufemia/src/components/table/stories/Table.stories.tsx
packages/dnb-eufemia/src/components/table/style/_table.scss

In regards to PR #1422 this fixes some issue and makes the sticky functionally more robust.

fix(Table): simplify sticky table hook

---

packages/dnb-eufemia/src/components/input/Input.js
packages/dnb-eufemia/src/components/input/__tests__/Input.test.js

- Warn when clear button and an "icon" positioned right is used.
- Add tests

fix(Input): warn when clear button with icon is used

---

packages/dnb-design-system-portal/gatsby-config.js
packages/dnb-design-system-portal/package.json
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.js
yarn.lock

Created this Plugin to simply the usage and make it generic: https://github.com/tujoworker/gatsby-plugin-scroll-position
We also ensure that the selected menu item is in view (as we did before) but with much less code.
How it was before this PR:
https://user-images.githubusercontent.com/1501870/175283394-8bf20a24-3ccf-4d5a-b033-b0e30b431b7c.mov
How it is now:
https://user-images.githubusercontent.com/1501870/175283213-d7b32fc9-7a87-4c7d-b381-e05818a568a3.mov

chore(Portal): enhance scroll position handling for sidebar menu

---

packages/dnb-design-system-portal/package.json
yarn.lock

Released in [v1.2.x](https://github.com/tujoworker/gatsby-plugin-scroll-position/releases/tag/v1.2.0)
For more context: PR #1481

chore(Portal): add support for iOS restore scroll position 

---

packages/dnb-design-system-portal/src/docs/uilib/components/slider/demos.md
packages/dnb-eufemia/src/components/Badge.js
packages/dnb-eufemia/src/components/slider/Slider.tsx
packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx
packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.tsx.snap
packages/dnb-eufemia/src/components/slider/stories/Slider.stories.tsx
packages/dnb-eufemia/src/shared/AlignmentHelper.js
packages/dnb-eufemia/src/shared/helpers/Suffix.tsx

This PR depends on #1496 to run tests successfully.

feat(Slider): convert Slider to TypeScript

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.md

Adds info about changing prop thump_title to thumb_title in release docs

docs(Slider): rename prop thump_title to thumb_title

---

packages/dnb-eufemia/src/components/button/style/themes/dnb-button-theme-eiendom.scss
packages/dnb-eufemia/src/components/tabs/style/themes/dnb-tabs-theme-eiendom.scss
packages/dnb-eufemia/src/style/themes/theme-eiendom/dnb-theme-eiendom.scss

fix(Theme): correct DNB Eiendom state colors mint-green-50 to pistachio

---

packages/dnb-eufemia/src/components/slider/SliderInstance.tsx
packages/dnb-eufemia/src/components/slider/SliderProvider.tsx
packages/dnb-eufemia/src/components/slider/SliderThumb.tsx
packages/dnb-eufemia/src/components/slider/SliderTrack.tsx
packages/dnb-eufemia/src/components/slider/__tests__/Slider.test.tsx
packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.tsx.snap
packages/dnb-eufemia/src/components/slider/hooks/useSliderEvents.tsx
packages/dnb-eufemia/src/components/slider/style/_slider.scss
packages/dnb-eufemia/src/components/slider/types.ts

- Enhance "animate to" implementation
- Ensure pointer cursor is shown during dragging on Safari (desktop)
Slider [demos of this build](https://eufemia-fixsafariux.gtsb.io/uilib/components/slider/demos/).

fix(Slider): enhance Safari (desktop) UX

---

packages/dnb-design-system-portal/src/docs/uilib/components/tooltip/properties.md

Removes duplicate docs for the position prop

docs(Tooltip): remove duplicate docs position prop

---

packages/dnb-eufemia/src/shared/component-helper.js
packages/dnb-eufemia/src/shared/helpers/__tests__/getPreviousSibling.test.tsx
packages/dnb-eufemia/src/shared/helpers/getPreviousSibling.ts

chore(getPreviousSibling): add support for finding tagName + rewrite to TypeScript

---

packages/dnb-design-system-portal/src/docs/uilib/helpers/classes.md
packages/dnb-eufemia/src/style/core/helper-classes/helper-classes.scss

feat(Easing): expose default CSS easing with --easing-default

---

packages/dnb-design-system-portal/src/docs/uilib/components/breadcrumb/Examples.js
packages/dnb-eufemia/scripts/postbuild/__tests__/postbuild.test.js
packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx
packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbMultiple.tsx
packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/dnb-eufemia/src/components/breadcrumb/style/_breadcrumb.scss

This PR depends on #1561 
Check out the [demos](https://eufemia-featbreadcrumbanimation.gtsb.io/uilib/components/breadcrumb/demos/).

feat(Breadcrumb): add animation when in collapse mode

---

packages/dnb-eufemia/src/shared/Context.tsx

See [comment](https://github.com/dnbexperience/eufemia/pull/1581#discussion_r982246100)

chore(Context): require props in getTranslation

---

packages/dnb-eufemia/src/components/avatar/Avatar.tsx
packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx
packages/dnb-eufemia/src/components/badge/Badge.tsx
packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
packages/dnb-eufemia/src/components/button/Button.d.ts
packages/dnb-eufemia/src/components/height-animation/HeightAnimation.tsx
packages/dnb-eufemia/src/components/info-card/InfoCard.tsx
packages/dnb-eufemia/src/components/modal/Modal.tsx
packages/dnb-eufemia/src/components/section/Section.tsx
packages/dnb-eufemia/src/components/table/Table.tsx
packages/dnb-eufemia/src/components/tag/Tag.tsx
packages/dnb-eufemia/src/components/tag/TagGroup.tsx
packages/dnb-eufemia/src/components/timeline/Timeline.tsx
packages/dnb-eufemia/src/components/visually-hidden/VisuallyHidden.tsx
packages/dnb-eufemia/src/elements/Anchor.tsx
packages/dnb-eufemia/src/elements/Dd.tsx
packages/dnb-eufemia/src/elements/Dl.tsx
packages/dnb-eufemia/src/elements/Dt.tsx
packages/dnb-eufemia/src/fragments/scroll-view/ScrollView.tsx
packages/dnb-eufemia/src/shared/interfaces.tsx
packages/dnb-eufemia/src/shared/types.tsx

The changes where made in two commits. The first is small and contains the type changes. You may [check out this in isolation](https://github.com/dnbexperience/eufemia/pull/1601/commits/3e956a99ef398fc82c3ae42e9e883f7e437066cc).

fix(Interfaces): refactor /shared/interfaces and move to /shared/types

---

packages/dnb-eufemia/src/components/slider/types.ts
packages/dnb-eufemia/src/components/tooltip/types.ts

Refactor missed changes by PR #1601

chore(Types): refactor outdated types

---

packages/dnb-eufemia/src/components/form-status/FormStatus.js
packages/dnb-eufemia/src/components/global-status/GlobalStatus.js
packages/dnb-eufemia/src/components/height-animation/HeightAnimationInstance.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimation.test.tsx
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimationInstance.test.ts
packages/dnb-eufemia/src/components/height-animation/useHeightAnimation.tsx
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorItem.js
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorTriggerButton.js

Move it into the `HeightAnimation` component directory and rename it to `HeightAnimationInstance`.

chore(HeightAnimation): move the internal shared AnimateHeight class

---

packages/dnb-design-system-portal/src/docs/contribute/getting-started.md

Following up this comment: https://github.com/dnbexperience/eufemia/pull/1636#discussion_r995370817

docs(Contribution): small types enhancements

---

packages/dnb-eufemia/src/components/section/Section.tsx

fix(Section): rename AllSectionProps to SectionAllProps

---

packages/dnb-design-system-portal/src/docs/uilib/components/upload/properties.md
packages/dnb-eufemia/src/components/upload/Upload.tsx
packages/dnb-eufemia/src/components/upload/UploadContext.tsx
packages/dnb-eufemia/src/components/upload/UploadDropzone.tsx
packages/dnb-eufemia/src/components/upload/UploadFileInput.tsx
packages/dnb-eufemia/src/components/upload/UploadVerify.tsx
packages/dnb-eufemia/src/components/upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/components/upload/__tests__/UploadDropzone.test.tsx
packages/dnb-eufemia/src/components/upload/__tests__/UploadFileInput.test.tsx
packages/dnb-eufemia/src/components/upload/__tests__/UploadVerify.test.tsx
packages/dnb-eufemia/src/components/upload/__tests__/__snapshots__/Upload.test.tsx.snap
packages/dnb-eufemia/src/components/upload/style/_upload.scss
packages/dnb-eufemia/src/components/upload/style/themes/dnb-upload-theme-ui.scss
packages/dnb-eufemia/src/components/upload/types.ts
packages/dnb-eufemia/src/shared/locales/en-GB.js
packages/dnb-eufemia/src/shared/locales/nb-NO.js
packages/dnb-eufemia/src/style/themes/theme-ui/dnb-theme-ui.scss

Putting this in as a chore, because its not released yet.
This PR adds support for file drag&drop to the browser window.

chore(Upload): add drop zone

---

packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
packages/dnb-eufemia/src/components/upload/__tests__/useUpload.test.tsx
packages/dnb-eufemia/src/components/upload/useUpload.ts

Tests have to follow in a later PR.

fix(Upload): make import paths valid in released version

---

packages/dnb-eufemia/src/components/upload/Upload.tsx
packages/dnb-eufemia/src/components/upload/UploadFileInput.tsx
packages/dnb-eufemia/src/components/upload/UploadFileList.tsx
packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
packages/dnb-eufemia/src/components/upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/components/upload/__tests__/UploadFileInput.test.tsx
packages/dnb-eufemia/src/components/upload/__tests__/UploadFileListCell.test.tsx
packages/dnb-eufemia/src/components/upload/__tests__/__snapshots__/Upload.test.tsx.snap
packages/dnb-eufemia/src/components/upload/style/themes/dnb-upload-theme-ui.scss
packages/dnb-eufemia/src/components/upload/types.ts
packages/dnb-eufemia/src/components/upload/useUpload.ts

New UX changes to highlight files which where already added. Also, do not/never disable the browse files button.

feat(Upload): highlight existing files visually

---

packages/dnb-eufemia/src/shared/MediaQueryUtils.ts
packages/dnb-eufemia/src/shared/__tests__/MediaQueryUtils.test.tsx
packages/dnb-eufemia/src/shared/__tests__/useMedia.test.tsx
packages/dnb-eufemia/src/shared/__tests__/useMediaQuery.test.tsx
packages/dnb-eufemia/src/shared/useMedia.tsx
packages/dnb-eufemia/src/shared/useMediaQuery.tsx

Thanks for reporting @sivran 🙏

fix(useMediaQuery): remove warning and handle environments without breaking

---

packages/dnb-design-system-portal/src/docs/uilib/components/upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/upload/demos.md
packages/dnb-design-system-portal/src/docs/uilib/components/upload/info.md

I think, before announcement, the docs needs some more info about how we want it to be used.
Any thoughts and suggestion that can improve it further?

docs(Upload): polish the info and examples

---

packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.js
packages/dnb-eufemia/src/components/input-masked/addons/createNumberMask.js

Here is [reprod](https://codesandbox.io/s/eufemia-starter-forked-tnozky?file=/src/App.tsx:108-559) of the bug.

fix(InputMasked): fix integerLimit to work during typing

---

packages/dnb-eufemia/src/components/table/Table.tsx
packages/dnb-eufemia/src/components/table/TableContext.tsx

We need the context to add future features.

chore(Table): add internal context for "auto" handling of odd/even

---

packages/dnb-design-system-portal/src/docs/uilib/components/table/info.md
packages/dnb-eufemia/src/components/table/Table.tsx
packages/dnb-eufemia/src/components/table/TableTd.tsx
packages/dnb-eufemia/src/components/table/TableTr.tsx

I see that we need some refactoring, while working on another larger PR.

chore(Table): docs and housekeeping

---

packages/dnb-design-system-portal/src/docs/uilib/typography.md

Should be merged after #1728 and #1727

docs(Typography): remove tabs

---

.github/workflows/visual-test.yml

For details, see comment in code.

chore(Portal): run lib prebuild on main branch

---

.github/dependabot.yml

We may try to test this out. Not sure yet if it will be practical useful.

chore: add dependabot deps updater

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.js.snap
packages/dnb-eufemia/src/components/checkbox/__tests__/__snapshots__/Checkbox.test.js.snap
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap
packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
packages/dnb-eufemia/src/components/form-label/FormLabel.js
packages/dnb-eufemia/src/components/form-label/__tests__/FormLabel.test.js
packages/dnb-eufemia/src/components/form-label/__tests__/__snapshots__/FormLabel.test.js.snap
packages/dnb-eufemia/src/components/form-label/style/_form-label.scss
packages/dnb-eufemia/src/components/form-row/__tests__/__snapshots__/FormRow.test.js.snap
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.js.snap
packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.js.snap
packages/dnb-eufemia/src/components/radio/__tests__/__snapshots__/Radio.test.js.snap
packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.tsx.snap
packages/dnb-eufemia/src/components/switch/__tests__/__snapshots__/Switch.test.js.snap
packages/dnb-eufemia/src/components/textarea/__tests__/__snapshots__/Textarea.test.js.snap
packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.js.snap

fix(FormLabel): ensure sr_only prop will eliminate label height

---

packages/dnb-eufemia/src/components/table/TableContainer.tsx
packages/dnb-eufemia/src/components/table/TableScrollView.tsx
packages/dnb-eufemia/src/components/table/__tests__/TableScrollView.test.tsx

fix(Table): make Table.ScrollView accessible with keyboard navigation

---

packages/dnb-design-system-portal/src/docs/index.js
packages/dnb-design-system-portal/src/shared/parts/Layout.tsx
packages/dnb-design-system-portal/tsconfig.json

Also, rewrite Layout to TypeScript

chore(Portal): fix background color on home page

---

packages/dnb-eufemia/src/components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
packages/dnb-eufemia/src/components/textarea/__tests__/__snapshots__/Textarea.test.js.snap
packages/dnb-eufemia/src/fragments/drawer-list/__tests__/__snapshots__/DrawerList.test.js.snap
packages/dnb-eufemia/src/style/core/scopes.scss
packages/dnb-eufemia/src/style/core/utilities.scss

feat(Scrollbar): add new look to scrollbars

---

packages/dnb-design-system-portal/src/docs/uilib/components/info-card.md
packages/dnb-design-system-portal/src/docs/uilib/components/info-card/properties.md

Minor improvements to the InfoCard docs.

docs(InfoCard): Fix link to button properties

---

packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap
packages/dnb-eufemia/src/components/table/style/_table-container.scss

fix(TableContainer): align always visible scrollbar

---

packages/dnb-design-system-portal/src/docs/uilib/components/table/info.md
packages/dnb-eufemia/src/components/table/index.js
packages/dnb-eufemia/src/components/table/stories/Table.stories.tsx

This PR fixes an reported issue with the current documented import.

fix(useHandleSortState): fix import issue

---

packages/dnb-eufemia/src/elements/Ingress.js
packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap
packages/dnb-eufemia/src/style/elements/typography.scss

feat(P): remove deprecated class dnb-p--ingress

---

packages/dnb-design-system-portal/src/shared/tags/Table.js

chore(Portal): fix properties table

---

packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
packages/dnb-eufemia/src/components/upload/__tests__/UploadFileListCell.test.tsx

fix(Upload): support special file extensions like .dat

---

packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.js
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.module.scss

portal: replace current badge with our Badge component

---

packages/dnb-design-system-portal/src/docs/uilib/components/upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/upload/demos.md

Here is the [request](https://dnb-it.slack.com/archives/CMXABCHEY/p1675247149429519).

docs: add FileReader example

---

packages/dnb-design-system-portal/package.json
packages/dnb-design-system-portal/src/shared/tags/CodeBlock.tsx
packages/dnb-design-system-portal/src/shared/tags/Copy.js
yarn.lock

- I checked the logs during SSR for these props. None where used.
- Remove `react-markdown` dependency.

chore(CodeBlock): remove unused parts

---

packages/dnb-design-system-portal/src/docs/uilib/components/number-format/info.md

docs(NumberFormat): fix info docs

---

packages/dnb-design-system-portal/cypress/e2e/pageNavigation.cy.ts
packages/dnb-eufemia/src/components/dialog/__tests__/Dialog.test.tsx
packages/dnb-eufemia/src/fragments/scroll-view/ScrollView.tsx

fix(ScrollView): avoid usage of useLayoutEffect during SSR

---

packages/dnb-design-system-portal/src/docs/design-system/about.md
packages/dnb-design-system-portal/src/docs/design-system/contact.md

docs(Contact): adds Joakim as contact

---

packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.js.snap
packages/dnb-eufemia/src/components/pagination/style/themes/dnb-pagination-theme-ui.scss

Before:
https://user-images.githubusercontent.com/1501870/222097216-d2132847-e14e-4f0b-9c36-c4efec2540b3.mov
---
After:
https://user-images.githubusercontent.com/1501870/222097240-c2131176-b6e2-4f7d-9444-2a8527163578.mov

fix(Pagination): fix hover style state after click to be emerald-green

---

packages/dnb-design-system-portal/package.json
packages/gatsby-plugin-eufemia-theme-handler/collectThemes.js
packages/gatsby-plugin-eufemia-theme-handler/gatsby-node.js
packages/gatsby-plugin-eufemia-theme-handler/package.json
yarn.lock

It needs to be tested on a Windows PC:
1. git fetch
1. git switch chore/portal-windows-support
1. yarn clean && yarn start

chore: make Portal windows compatible by properly handle backslashes and newlines

---

packages/dnb-eufemia/src/style/themes/theme-sbanken/properties.scss

Added properties SCSS file for Sbanken theme

chore: add Sbanken properties

---

packages/dnb-design-system-portal/src/docs/uilib/components/input/events.mdx

docs(Input): adds on_key_down event

---

packages/dnb-eufemia/src/components/date-picker/DatePicker.d.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.d.ts
packages/dnb-eufemia/src/components/input-masked/InputMasked.d.ts

chore(TypeScript): type input_attributes & input_element

---

packages/dnb-eufemia/src/components/form-row/FormRow.d.ts
packages/dnb-eufemia/src/components/form-set/FormSet.d.ts
packages/dnb-eufemia/src/components/input-masked/InputMasked.d.ts
packages/dnb-eufemia/src/components/number-format/NumberFormat.d.ts
packages/dnb-eufemia/src/components/number-format/NumberUtils.d.ts
packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.d.ts

`locale` prop of DatePicker looks to be something else than a string: https://eufemia.dnb.no/uilib/components/date-picker/properties/#properties, hence I'm not changing that :)

chore(TypeScript): type locale

---

packages/dnb-design-system-portal/src/docs/uilib/components/form-label/properties.mdx
packages/dnb-eufemia/src/components/form-label/FormLabel.d.ts

docs(FormLabel): improve description of vertical prop

---

packages/dnb-eufemia/src/components/accordion/AccordionProvider.d.ts

On a side note, I see the file name is AccordionProvider, but the component is named AccordionGroup 🤔

chore(TypeScript): use AccordionProps in AccordionGroupProps

---

packages/dnb-design-system-portal/src/docs/uilib/usage/first-steps/react.mdx

I'm not sure if this line is true/needed anymore 🤔

docs(TypeScript): remove outdated docs

---

packages/dnb-design-system-portal/src/docs/uilib/elements/anchor.mdx

docs(Anchor): fix console warning when using class

---

packages/dnb-design-system-portal/src/docs/quickguide-designer/logos.mdx

docs(Logos): fix console warning when using class

---

packages/dnb-design-system-portal/src/docs/brand.mdx
packages/dnb-design-system-portal/src/docs/contribute.mdx
packages/dnb-design-system-portal/src/docs/uilib.mdx

docs(Front Page): minor text improvements

---

packages/dnb-eufemia/src/components/button/Button.js

The tests are covered in PR #2146 (v10)

fix(Button): support for FormRow and FormSet

---

packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.module.scss
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.tsx

new branch for this task, since the [previous one](https://github.com/dnbexperience/eufemia/pull/2120) died from rebasing

chore(SidebarMenu): fix highlighting for active items inside the SidebarMenu

---

.github/PULL_REQUEST_TEMPLATE.md

More info about it: https://githubnext.com/projects/copilot-for-pull-requests

chore: add copilot to PR template

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/Examples.tsx

https://github.com/dnbexperience/eufemia/pull/2204#discussion_r1165117173

chore(DatePicker): use globalThis in examples

---

packages/dnb-eufemia/src/style/themes/theme-ui/dnb-theme-extensions.scss

This files gets now added based on this change: #2201

chore(PaymentCard): add missing theme import

---

packages/dnb-eufemia/src/components/timeline/__tests__/Timeline.test.tsx

I'll try to run the "Verify tests and types" action a few times, to see if I'm able to reproduce the following error/failing test https://github.com/dnbexperience/eufemia/actions/runs/4487837629

chore(Timeline): fix randomly failing test

---

packages/dnb-design-system-portal/src/docs/contribute/style-guides/naming.mdx
packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.mdx
packages/dnb-design-system-portal/src/uilib/utils/slug.js

Preview of the docs: https://eufemia-a5hj9ltie-eufemia.vercel.app/uilib/about-the-lib/releases/eufemia/v10-info/

chore: update v10-info

---

packages/dnb-design-system-portal/src/docs/contribute/style-guides/theming.mdx
packages/dnb-eufemia/src/components/button/__tests__/themes/Button.eiendom.screenshot.test.ts
packages/dnb-eufemia/src/components/button/__tests__/themes/Button.sbanken.screenshot.test.ts
packages/dnb-eufemia/src/elements/typography/__tests__/themes/Typography.eiendom.screenshot.test.ts
packages/gatsby-plugin-eufemia-theme-handler/README.md
packages/gatsby-plugin-eufemia-theme-handler/inlineScriptProd.js
packages/gatsby-plugin-eufemia-theme-handler/themeHandler.js

This change is mostly to align on the change made in #2220 – but this time for the portal only.

chore(Portal): change naming from `dnb-theme` to `eufemia-theme`

---

packages/dnb-eufemia/src/elements/typography/H.tsx
packages/dnb-eufemia/src/elements/typography/P.tsx

Documenting the props for P and H elements

chore(Typography): document typography props

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap
packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.tsx.snap
packages/dnb-eufemia/src/components/button/style/dnb-button--tertiary.scss
packages/dnb-eufemia/src/components/button/style/dnb-button.scss
packages/dnb-eufemia/src/components/button/style/themes/dnb-button-theme-ui.scss
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap
packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
packages/dnb-eufemia/src/components/global-error/__tests__/__snapshots__/GlobalError.test.tsx.snap
packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.tsx.snap
packages/dnb-eufemia/src/components/help-button/__tests__/__snapshots__/HelpButton.test.tsx.snap
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap
packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.tsx.snap
packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap
packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
packages/dnb-eufemia/src/components/skip-content/__tests__/__snapshots__/SkipContent.test.tsx.snap
packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.tsx.snap
packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.tsx.snap
packages/dnb-eufemia/src/components/tag/__tests__/__snapshots__/Tag.test.tsx.snap
packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.tsx.snap
packages/dnb-eufemia/src/components/upload/__tests__/__snapshots__/Upload.test.tsx.snap

The interesting parts are in the first commit.
This can/will make it easier when theming for sb.

chore: split out sharable parts of tertiary button

---

packages/dnb-design-system-portal/src/docs/contribute/style-guides/theming.mdx
packages/dnb-design-system-portal/src/docs/uilib/intro/12-usage-of-components-elements.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/styling.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/styling/consume-styles.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming.mdx
packages/dnb-eufemia/src/style/themes/eiendom.js
packages/dnb-eufemia/src/style/themes/index.js
packages/dnb-eufemia/src/style/themes/sbanken.js
packages/dnb-eufemia/src/style/themes/ui.js

Ensure, components are imported as well, when imported via the JavaScript import.

chore: fix theming import

---

packages/dnb-eufemia/package.json
packages/dnb-eufemia/scripts/postbuild/__tests__/postbuild.test.ts
packages/dnb-eufemia/scripts/postbuild/postbuild.sh
packages/dnb-eufemia/src/style/themes/theme-sbanken/sbanken-theme-basis.scss
packages/dnb-eufemia/src/style/themes/theme-ui/ui-theme-basis.scss

Because we will run visual tests on these styles, we will ensure the existence of the import of elements in future. 
Update: I will add a postbuild test as well.

chore: ensure SB theme elements gets imported

---

packages/dnb-eufemia/src/components/date-picker/DatePicker.js
packages/dnb-eufemia/src/components/date-picker/DatePickerFooter.d.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerFooter.js
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Solves [this issue](https://github.com/dnbexperience/eufemia/issues/2190) where developers were unable to change the submit and cancel button text

fix(DatePicker): fix text prop for submit and cancel buttons

---

packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/properties.mdx

docs(StepIndicator): format Steps Parameters table

---

packages/dnb-eufemia/src/components/accordion/Accordion.d.ts
packages/dnb-eufemia/src/components/accordion/AccordionHeader.d.ts
packages/dnb-eufemia/src/components/autocomplete/Autocomplete.d.ts
packages/dnb-eufemia/src/components/dropdown/Dropdown.d.ts
packages/dnb-eufemia/src/components/help-button/HelpButton.tsx
packages/dnb-eufemia/src/components/input-masked/InputMasked.d.ts
packages/dnb-eufemia/src/components/input/Input.d.ts
packages/dnb-eufemia/src/components/modal/Modal.tsx
packages/dnb-eufemia/src/components/modal/parts/CloseButton.tsx
packages/dnb-eufemia/src/components/modal/types.ts

The problem:
Where we can solve it:
✅ How we can solve it:

chore: fix button types in import from /components/Button

---

packages/dnb-eufemia/src/components/autocomplete/stories/Autocomplete.stories.tsx
packages/dnb-eufemia/src/components/button/stories/Button.stories.tsx
packages/dnb-eufemia/src/components/checkbox/stories/Checkbox.stories.tsx
packages/dnb-eufemia/src/components/date-picker/stories/DatePicker.stories.tsx
packages/dnb-eufemia/src/components/dropdown/stories/Dropdown.stories.tsx
packages/dnb-eufemia/src/components/form-status/stories/FormStatus.stories.tsx
packages/dnb-eufemia/src/components/input/stories/Input.stories.tsx
packages/dnb-eufemia/src/components/radio/stories/Radio.stories.tsx
packages/dnb-eufemia/src/components/switch/stories/Switch.stories.tsx
packages/dnb-eufemia/src/components/textarea/stories/Textarea.stories.tsx
packages/dnb-eufemia/src/components/toggle-button/stories/ToggleButton.stories.tsx

I just wanted to try out and see if/how it works, and thought that it's okay to add it to the source code, as some sort of "dev documentation".

chore: adds stories for globalStatus prop

---

packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js

Need to do some work in regards to rewriting tests to @testing-library/react for this file, as there still exists a `mount` that I wasn't able to quickly rewrite.

chore(component-helper): rewrite tests @testing-library/react

---

packages/dnb-design-system-portal/src/docs/uilib/components/autocomplete/demos.mdx

Includes #2103 in v10, https://github.com/dnbexperience/eufemia/pull/2103/files#diff-ad1d68b9426016d8f7eb2d5555db27807b5c25540b58605a3cfd6d1a07829905R92-R95

chore: manually include #2103 in v10

---

packages/dnb-eufemia/src/fragments/drawer-list/__tests__/DrawerList.test.tsx

#2388 to `main` instead of to `v10`.

chore(DrawerList): rewrite tests @testing-library/react

---

packages/dnb-eufemia/src/components/input-masked/InputMasked.d.ts
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx
packages/dnb-eufemia/src/components/input/Input.d.ts
packages/dnb-eufemia/src/components/input/stories/Input.stories.tsx
packages/dnb-eufemia/src/fragments/drawer-list/stories/DrawerList.stories.tsx

Skipped one test:
https://github.com/dnbexperience/eufemia/pull/2442/files#r1221206383

chore(InputMasked): rewrite tests @testing-library/react

---

packages/dnb-eufemia/src/core/jest/jestSetup.js

Dependent on #2437 and #2453, and should be rebased with `main` branch after these PRs are merged to `main`.

chore(jestSetup): removes support for Enzyme in axeComponent()

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx
packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.tsx
packages/dnb-eufemia/src/fragments/drawer-list/__tests__/DrawerList.test.tsx

Continuation of #2453 & #2464
Not sure if we should fix these tests, or "skip them/ignore them" as I've done so far in this PR.

chore: enables skipped axe tests

---

packages/dnb-eufemia/src/components/input-masked/InputMasked.d.ts
packages/dnb-eufemia/src/components/input-masked/InputMasked.js
packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx
packages/dnb-eufemia/src/components/input-masked/text-mask/createTextMaskInputElement.js
packages/dnb-eufemia/src/components/input/__tests__/Input.test.tsx
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorItem.d.ts
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorTriggerButton.d.ts

Reproduction: https://codesandbox.io/s/cocky-snyder-lfgl2z

fix(InputMasked): make `inner_ref` work when provided as a function

---

packages/dnb-design-system-portal/cypress/e2e/typography.cy.ts

chore(Typography): add e2e for UI

---

packages/dnb-eufemia/src/components/heading/__tests__/Heading.test.tsx

I've skipped two tests in this PR for now, https://github.com/dnbexperience/eufemia/pull/2437/files#r1220124215 & https://github.com/dnbexperience/eufemia/pull/2437/files#r1220123777
I'm not sure how to rewrite them, now that we can't do setState, and I'm not sure what they are actually testing.
Any help and/or additional thoughts are warmly welcome 🙏

chore(Heading): rewrite tests @testing-library/react

---

package.json
packages/dnb-design-system-portal/src/docs/contribute/style-guides/theming.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/anchor.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/button.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/heading.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/logo.mdx
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.module.scss
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.tsx
packages/dnb-design-system-portal/src/shared/parts/Layout.module.scss

General sbanken colors on the Eufemia page.
Add a badge on components that are themed

chore(Portal): enhance Sbanken look and UX

---

packages/dnb-design-system-portal/cypress/e2e/pageLists.cy.ts
packages/dnb-design-system-portal/src/shared/parts/ListComponents.tsx

This will make the e2e tests run in PR https://github.com/dnbexperience/eufemia/pull/2420 when rebased.

chore(Portal): make e2e more robust

---

packages/dnb-eufemia/src/components/avatar/__tests__/Avatar.test.tsx
packages/dnb-eufemia/src/components/button/__tests__/Button.test.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/height-animation/__tests__/useHeightAnimation.test.tsx
packages/dnb-eufemia/src/components/icon/__tests__/Icon.test.tsx
packages/dnb-eufemia/src/components/table/__tests__/TableScrollView.test.tsx
packages/dnb-eufemia/src/components/table/__tests__/TableTd.test.tsx
packages/dnb-eufemia/src/components/table/__tests__/TableTh.test.tsx
packages/dnb-eufemia/src/components/table/__tests__/TableTr.test.tsx
packages/dnb-eufemia/src/components/upload/__tests__/UploadDropzone.test.tsx
packages/dnb-eufemia/src/elements/typography/__tests__/Heading.test.tsx
packages/dnb-eufemia/src/fragments/scroll-view/__tests__/ScrollView.test.tsx
packages/dnb-eufemia/src/shared/__tests__/MediaQuery.test.tsx
packages/dnb-eufemia/src/shared/__tests__/Theme.test.tsx
packages/dnb-eufemia/src/shared/__tests__/useMedia.test.tsx

My motivation for using more TS objects as props in some of our tests, is because the more ts objects we use internally, the more errors/faults we find 🙏

chore: use ts objects as props in tests

---

packages/dnb-eufemia/src/components/dialog/__tests__/Dialog.test.tsx

chore(Dialog): add tests for hideDecline and hideConfirm props

---

packages/dnb-design-system-portal/src/docs/uilib/components/number-format.mdx
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.module.scss

Small fixes to side menu after anchor refactor, added sbanken theme tag to NumberFormat.

portal: added NumberFormat sbanken tag and fixed sidemenu hover

---

packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.tsx
packages/dnb-design-system-portal/src/shared/tags/Tabbar.tsx

This PR fixes both the initial implementation from #2577 and the nice [findings](https://github.com/dnbexperience/eufemia/pull/2577#pullrequestreview-1589242588) by @langz 👌

portal: fix handling of active marked sidebar menu items

---

.github/workflows/release.yml
packages/dnb-design-system-portal/gatsby-node.js
packages/dnb-design-system-portal/src/uilib/search/searchHelpers.js
packages/dnb-eufemia/rollup.config.js
packages/dnb-eufemia/scripts/postbuild/__tests__/postbuild.test.ts
packages/dnb-eufemia/scripts/tools/cliTools.js

The issue with `isCI` resulted that we actually did not update the Algolia search indexes properly. This PR fixes this and now they are updated, because I run the code in the `portal` branch.

chore: make post-build test run on "portal" branch + fix issue with isCI

---

packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.tsx.snap
packages/dnb-eufemia/src/components/input/style/themes/dnb-input-theme-ui.scss

I think i fixed the keep_placeholder prop. Please correct me if i misunderstood something 🙏😅

fix(MaskedInput): correct keep_placeholder css selector

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String.tsx

More [info](https://dnb-it.slack.com/archives/G01RK37BMR8/p1693399952666769).

fix(MaskedInput): make cleanedValue contain leading zeroes

---

packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/__tests__/Provider.test.tsx
yarn.lock

+ add polyfill
+ add test for Provider

fix(Forms): add polyfill for structuredClone

---

packages/dnb-eufemia/src/extensions/forms/Field/String.tsx
packages/dnb-eufemia/src/extensions/forms/Field/__tests__/String.test.tsx

Fixes https://github.com/dnbexperience/eufemia/issues/2629

fix(Forms): focus InputMasked when clicking label

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v10-info.mdx

Adds info to v10 docs about https://github.com/dnbexperience/eufemia/pull/2617

docs(v10): changes to PaymentCard's height & width

---

packages/dnb-eufemia/src/components/modal/ModalContent.tsx
packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx

- CSB https://codesandbox.io/s/practical-jennings-jsnhws?file=/src/App.tsx
- Closes #2652

fix(Dialog): select whole input on focus given by focusSelector

---

packages/dnb-eufemia/src/shared/__tests__/useMedia.test.tsx
packages/dnb-eufemia/src/shared/useMedia.tsx

feat(useMedia): add new props: queries and breakpoints

---

packages/dnb-design-system-portal/gatsby-node.js
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/FieldBlock/properties.mdx
packages/dnb-design-system-portal/src/e2e/fullscreen.spec.ts
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.screenshot.test.ts
packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx

Also, revise what pages are build on CI. Make all demo pages available. So this new visual test inside /forms will succeed.

fix(FieldBlock): automate label in label detection

---

.github/workflows/codeql-analysis.yml
.github/workflows/e2e.yml
.github/workflows/icons-lib.yml
.github/workflows/release.yml
.github/workflows/verify.yml

I'm not sure if this change will actually help. I just observe in this PR #2664 that some tests did run after approval.
And I can't find any info or setting that do explain the difference between the actions.

chore: make CI run on fork PRs

---

packages/dnb-design-system-portal/gatsby-browser.tsx
packages/dnb-design-system-portal/package.json
yarn.lock

Now this code runs in the plugin. Done with [this PR](https://github.com/dnbexperience/gatsby-plugin-eufemia-theme-handler/pull/13).

chore(Portal): use scrollBehavior from theme-handler

---

packages/dnb-design-system-portal/src/docs/uilib/components/anchor/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/anchor/properties.mdx
packages/dnb-design-system-portal/src/e2e/pageLists.spec.ts
packages/dnb-design-system-portal/src/e2e/pageNavigation.spec.ts
packages/dnb-design-system-portal/src/e2e/pageScroll.spec.ts
packages/dnb-design-system-portal/src/shared/tags/Anchor.tsx
packages/dnb-design-system-portal/src/shared/tags/AutoLinkHeader.module.scss
packages/dnb-eufemia/src/components/anchor/Anchor.tsx
packages/dnb-eufemia/src/components/anchor/__tests__/AnchorScroll.test.tsx

When clicking links on [this page](https://eufemia.dnb.no/contribute/getting-started/), the target heading should get an animation. Also when refreshing the page afterwards, like so:

docs(Portal): fix anchor hash highlighting

---

.github/workflows/e2e.yml

With the changes made in this PR #2695 I missed to remove the delete-artifact job.

chore(CI): remove leftover

---

packages/dnb-design-system-portal/src/docs/uilib/intro.mdx
packages/dnb-design-system-portal/src/shared/tags/Intro.module.scss

docs(Intro): add breadcrumb for mitigate lack of orientation

---

packages/dnb-eufemia/src/components/anchor/__tests__/__snapshots__/Anchor.test.tsx.snap
packages/dnb-eufemia/src/components/anchor/style/anchor-mixins.scss
packages/dnb-eufemia/src/components/section/__tests__/__snapshots__/Section.test.tsx.snap

Is it a gutter? I'm not sure about the naming.
Keep in mind, you always need to use a unit, to null it out:
```css
--anchor-background-gutter: 0rem;
```

fix(Anchor): add --anchor-background-gutter

---

packages/dnb-design-system-portal/src/docs/uilib/components/pagination/infinity-scroller/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/pagination/infinity-scroller/info.mdx

Updated outdated links to GitHub examples for `Pagination`.

docs(Pagination): Updated links to GitHub examples

---

packages/dnb-design-system-portal/src/shared/menu/PortalToolsMenu.js
packages/dnb-design-system-portal/src/shared/menu/PortalToolsMenu.module.scss
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.tsx
packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.tsx

Avoid using JavaScript for media detection.

chore(Portal): fix rehydration disturbance

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx

Ensure to not update the state before the first component mount.

fix(Autocomplete): fix rehydration disturbance

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Element/Element.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitButton/SubmitButton.tsx

So stored autocomplete values gets reset, once the form got submitted.

feat(Form.Handler): call reset on form submit

---

packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbItem.tsx
packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbMultiple.tsx
packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx
packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/dnb-eufemia/src/components/breadcrumb/style/dnb-breadcrumb.scss

Ensure to not update the state before the first component mount.

fix(Breadcrumb): fix rehydration disturbance

---

packages/dnb-design-system-portal/src/docs/uilib/helpers/functions.mdx
packages/dnb-eufemia/src/shared/__tests__/component-helper.test.js
packages/dnb-eufemia/src/shared/component-helper.js
packages/dnb-eufemia/src/shared/helpers/__tests__/filterProps.test.ts
packages/dnb-eufemia/src/shared/helpers/filterProps.ts

chore(filterProps): rewrite to TypeScript and add function callbacks

---

packages/dnb-eufemia/src/components/global-status/GlobalStatus.js
packages/dnb-eufemia/src/components/global-status/__tests__/GlobalStatus.test.tsx
packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.tsx.snap
packages/dnb-eufemia/src/components/global-status/style/dnb-global-status.scss

This should allow <p> tags to be sendt in to the `title` prop 
More context here: https://jira.tech.dnb.no/browse/EDS-603

fix(GlobalStatus): remove paragraph tag around title to allow children paragraphs

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/DataContext/Provider/Examples.tsx

Fixes [2803](https://github.com/dnbexperience/eufemia/issues/2803)

chore: only use data or sessionStorageId

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

fix(PhoneNumber): fix spacing prop support

---

packages/dnb-design-system-portal/src/e2e/fullscreen.spec.ts

Seen here: https://github.com/dnbexperience/eufemia/actions/runs/6730382987/job/18292979827?pr=2833

chore(e2e): wait for url change during navigation

---

packages/dnb-eufemia/src/fragments/drawer-list/style/themes/dnb-drawer-list-theme-sbanken.scss

Added missing focus style for DrawerList in preparation for Sbanken theme for autocomplete.

fix(DrawerList): Add focus style for Sbanken theme

---

packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/theming/theme/info.mdx

Mostly; simplify them (I hope).

docs(Theme): enhance info about using the shared theme provider

---

packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.d.ts
packages/dnb-eufemia/src/icons/dnb/card_in_medium.tsx
packages/dnb-eufemia/src/icons/dnb/clock_medium.tsx
packages/dnb-eufemia/src/icons/dnb/hourglass.tsx
packages/dnb-eufemia/src/icons/dnb/padlock_medium.tsx

These gets updated while running `yarn build` locally. They look ok. The color change should also be fine, as it was take care in PR #2846.

chore: update build artefacts

---

packages/dnb-design-system-portal/src/docs/uilib/elements/lead.mdx
packages/dnb-design-system-portal/src/docs/uilib/elements/lead/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/elements/paragraph.mdx

Fixes https://github.com/dnbexperience/eufemia/issues/2650

docs(Lead): adds Lead to docs

---

packages/dnb-design-system-portal/src/docs/design-system/about.mdx

Added Snorre Kim, Henrik Haugberg & Ynge Sundfjord as contributors.

docs(About): add Snorre/Henrik/Ynge as contributors

---

packages/dnb-eufemia/babel.config.js
packages/dnb-eufemia/scripts/postbuild/__tests__/postbuild.test.ts

With that change we increase the number of affected files from 30 to 80.

fix: add "use client" to non hook components like the Button

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx

fix(Autocomplete): make clear button work with enter key

---

packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx

fix(Selection): correctly link id with label

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/payment-card/properties.mdx
packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.d.ts
packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js
packages/dnb-eufemia/src/extensions/payment-card/__tests__/PaymentCard.test.tsx
packages/dnb-eufemia/src/extensions/payment-card/icons/index.js
packages/dnb-eufemia/src/shared/locales/en-GB.js
packages/dnb-eufemia/src/shared/locales/nb-NO.js

This PR adds the card_status `unknown`, looking like:

feat(PaymentCard): adds card_status unknown

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/schema-validation.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/schema-validation/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/schema-validation/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/schema-validation/info.mdx

- More explanation on the Extended Features page in Forms extension
- A separate page for JSON Schema validation with general information and several examples

chore(forms): JSON Schema examples

---

packages/dnb-design-system-portal/src/docs/contribute/faq.mdx

We could perhaps change/update some other information on this page as well?
I guess somethings are outdated.
https://eufemia.dnb.no/contribute/faq/

docs(FAQ): change version of yarn to v4

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Currency/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Currency/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Currency/Currency.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Currency/__tests__/Currency.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx

[More info](https://dnb-it.slack.com/archives/CMXABCHEY/p1700752971296059) about this.

feat(Currency): add automatic locale and alignment support

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/stories/PhoneNumber.stories.tsx
packages/dnb-eufemia/src/shared/locales/en-GB.js
packages/dnb-eufemia/src/shared/locales/nb-NO.js

```tsx
<PhoneNumber required pattern="^[49]+" />
```

feat(PhoneNumber): add `pattern` property

---

yarn.lock

Its time again to run: `npx update-browserslist-db@latest`

chore: update browserslist to latest

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/OrganizationNumber/info.mdx

proposal to fix https://github.com/dnbexperience/eufemia/issues/2967

chore(OrganizationNumber): add info about value length in docs

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/info.mdx

I have not heard about the select component, so I believe it's actually the [selection component](https://eufemia.dnb.no/uilib/extensions/forms/base-fields/Selection/) it should say.

docs(Field.SelectCountry): select component -> selection component

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx

[CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-r2k9rh?file=%2Fsrc%2FApp.tsx)
Fixes https://github.com/dnbexperience/eufemia/issues/2969

chore(PhoneNumber): fix visual space when omitCountryCodeField is given

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/BankAccountNumber/info.mdx

proposal for https://github.com/dnbexperience/eufemia/issues/2973

chore(Field.BankAccountNumber): add more descriptive info to docs

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/info.mdx

proposal for https://github.com/dnbexperience/eufemia/issues/2972

chore(Field.NationalIdentityNumber): add more descriptive info

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/info.mdx

proposal for https://github.com/dnbexperience/eufemia/issues/2974

chore(Field.PostalCodeAndCity): add more descriptive information about postal code

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/info.mdx

fixes https://github.com/dnbexperience/eufemia/issues/2992

chore(SelectCountry): adds docs about return value ISO 3166-1 alpha-2

---

packages/dnb-eufemia/src/components/card/stories/Card.stories.tsx

It's nice to have when testing locally

chore: adds Field.Expiry to card stories

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

Like in PR #3023 and since they share so many things, we move the shared code into the SelectCountry component.

feat(PhoneNumber): add prioritized sort option

---

packages/dnb-design-system-portal/src/docs/uilib/components/section.mdx

Fixes/improves https://github.com/dnbexperience/eufemia/pull/3042#issuecomment-1849567294

chore: adds new status to section component

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Boolean.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Toggle.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/BankAccountNumber.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Currency.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Email.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Expiry.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/OrganizationNumber.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry.mdx

Fixes https://github.com/dnbexperience/eufemia/issues/3047
Sidebarmenu now looking like:

chore: add theme sbanken to docs for form components

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/demos.mdx

Showing how Selection-options can be created and rendered dynamically

chore(Selection): adds dynamic options example

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/ArraySelection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Toggle/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/BankAccountNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Currency/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Email/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Expiry/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/OrganizationNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumber.test.tsx

Changes based on https://github.com/dnbexperience/eufemia/pull/3058

chore(Forms): import FormError from /forms

---

packages/dnb-design-system-portal/gatsby-config.js
packages/dnb-design-system-portal/package.json
yarn.lock

This ensures correct order of theme files.

chore(Portal): update to latest theme handler

---

packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx

Solves https://github.com/dnbexperience/eufemia/issues/3029 and https://github.com/dnbexperience/eufemia/issues/3026
Before:
After:

fix(Field.Selection): make it possible to disable radio variants

---

packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/Expiry.tsx

Adds this feature proposal https://github.com/dnbexperience/eufemia/issues/3099
Tested and works on my android device, so need someone to test if it actually works on iOS 🙏

chore(Field.Expiry): make number keyboard default for mobile

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component.mdx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useDataValue.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

For data transformation, add these hooks:
- `toOutput`
- `fromExternal`
For custom control about validating the required prop:
- `validateRequired`
Also, adding docs about the `useDataValue` hook.

feat(useDataValue): add toOutput, fromExternal and validateRequired

---

packages/dnb-eufemia/src/extensions/forms/Field/Expiry/Expiry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/__tests__/Expiry.test.tsx

Proposal to fix https://github.com/dnbexperience/eufemia/issues/3130

fix(Field.Expiry): handles value as null

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/StepsLayout/StepsLayout/properties.mdx
packages/dnb-eufemia/src/extensions/forms/StepsLayout/StepsLayout.tsx
packages/dnb-eufemia/src/extensions/forms/StepsLayout/__tests__/StepsLayout.test.tsx

fixes https://github.com/dnbexperience/eufemia/issues/3132

fix(StepsLayout): mode defaults to strict

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/events.mdx

Enhancement proposal for https://github.com/dnbexperience/eufemia/issues/3035

chore(Field.SelectCountry): document event handlers argument type

---

packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx

proposal to fix https://github.com/dnbexperience/eufemia/issues/2970

fix(Field.Date): define empty value to trigger required error

---

packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/PostalCodeAndCity.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/__tests__/PostalCodeAndCity.test.tsx

solves https://github.com/dnbexperience/eufemia/issues/3090

chore(Field.PostalCodeAndCity): add mask to postal code to enforce max length of four

---

packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/PostalCodeAndCity.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/__tests__/PostalCodeAndCity.test.tsx

solves https://github.com/dnbexperience/eufemia/issues/3091

chore(Field.PostalCodeAndCity): add numeric input mode to postal code

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

solves https://github.com/dnbexperience/eufemia/issues/3091

chore(Field.PhoneNumber): add tel input mode to phone number input

---

packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumber.test.tsx

solves https://github.com/dnbexperience/eufemia/issues/3095

chore(Field.NationalIdentityNumber): add numeric input mode

---

packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/OrganizationNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/__tests__/OrganizationNumber.test.tsx

solves https://github.com/dnbexperience/eufemia/issues/3096

chore(Field.OrganizationNumber): add numeric input mode

---

packages/dnb-eufemia/src/extensions/forms/Field/BankAccountNumber/BankAccountNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/BankAccountNumber/__tests__/BankAccountNumber.test.tsx

fixes https://github.com/dnbexperience/eufemia/issues/3098

chore(Field.BankAccountNumber): add numeric keyboard

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

solves: https://github.com/dnbexperience/eufemia/issues/3052
before:
after:

fix(Field.PhoneNumber): make country code only search for country name based on chosen locale

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Element/__tests__/Element.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useDataValue.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts

fix(forms): update data context with initially given field value

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/events.mdx
packages/dnb-eufemia/src/components/date-picker/DatePicker.d.ts
packages/dnb-eufemia/src/components/date-picker/DatePicker.js
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.js
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

feat(DatePicker): add onFocus event

---

packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx

As a following up on #3160, we simplify the handling of the cursor position correction and enhance also its reliability on a mouseDown event.

fix(InputMasked): extend reliability on cursor position correction

---

packages/dnb-design-system-portal/src/docs/uilib/components/input-masked/events.mdx
packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx
packages/dnb-eufemia/src/components/input-masked/__tests__/MultiInputMask.test.tsx
packages/dnb-eufemia/src/components/input-masked/hooks/useMultiInputValues.ts
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/Expiry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/__tests__/Expiry.test.tsx

solves https://github.com/dnbexperience/eufemia/issues/3128

fix(Expiry): validation logic

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/Handler/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/stories/Provider.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Email/__tests__/Email.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
packages/dnb-eufemia/src/extensions/forms/utils/ajv.ts

fix(forms): validate schema when given data structure not matches

---

packages/dnb-eufemia/src/components/table/TableAccordion.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/String.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

closes https://github.com/dnbexperience/eufemia/issues/3309

chore(Forms): forward aria-attributes

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx
packages/dnb-eufemia/src/shared/locales/en-GB.js
packages/dnb-eufemia/src/shared/locales/nb-NO.js

closes https://github.com/dnbexperience/eufemia/issues/3270 and https://github.com/dnbexperience/eufemia/issues/2980

chore(Field.Selection): remove clear functionality

---

packages/dnb-eufemia/src/components/textarea/__tests__/__snapshots__/Textarea.test.tsx.snap
packages/dnb-eufemia/src/components/textarea/style/dnb-textarea.scss

closes https://github.com/dnbexperience/eufemia/issues/3328

fix(Textarea): make element shrink and stay inside boundaries on smaller screen sizes

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/properties.mdx

forgot to remove the `clear` property from the property table in [this pr](https://github.com/dnbexperience/eufemia/pull/3327) 🙏

chore(Field.Selection): remove `clear` from property table

---

packages/dnb-eufemia/src/shared/helpers/__tests__/isAsync.test.ts
packages/dnb-eufemia/src/shared/helpers/isAsync.ts

For now, undocumented, for internal use only.

chore(isAsync): add isAsync helper function

---

.gitignore
packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/Examples.tsx
packages/dnb-eufemia/src/components/date-picker/DatePicker.d.ts
packages/dnb-eufemia/src/components/date-picker/DatePicker.js
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.js
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.js
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Added partially typed dates to the onBur event.
Will be helpful to display proper error messages in optional date fields
This was added as an extension to the onBlur event, so it shouldn't affect anyone.

feat(DatePicker): Add partial dates

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/ListBaseFieldComponents.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/ListBasisAPIs.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/DataContext/ListDataContextComponents.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/ListFormComponents.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/SubmitIndicator.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/Visibility.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/components.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/error-messages.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/getData.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/schema-validation.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/setData.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/useData.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/useError.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Iterate.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Iterate/ListIterateComponents.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Iterate/components.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/ListAdvancedAPIs.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/StepsLayout/ListStepsLayoutComponents.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Value/ListFeatureValueComponents.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/ListFeatureFieldComponents.tsx
packages/dnb-design-system-portal/src/shared/parts/ListComponents.tsx
packages/dnb-design-system-portal/src/shared/parts/ListExtensions.tsx

docs(forms): list all sub-components and API in extended features

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/useData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/quick-start.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/stories/FormHandler.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitIndicator/SubmitIndicator.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/getData.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/useData.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/getData.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useData.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/shared/helpers/useSharedState.tsx

Thank you @kimroen for the nice idea ⭐

feat(useData): support data handling without id when nested inside Form.Handler

---

packages/dnb-eufemia/src/components/input/Input.js
packages/dnb-eufemia/src/components/textarea/Textarea.d.ts
packages/dnb-eufemia/src/components/textarea/Textarea.js
packages/dnb-eufemia/src/components/textarea/TextareaDocs.ts
packages/dnb-eufemia/src/components/textarea/__tests__/__snapshots__/Textarea.test.tsx.snap
packages/dnb-eufemia/src/components/textarea/style/dnb-textarea.scss
packages/dnb-eufemia/src/components/textarea/style/themes/dnb-textarea-theme-sbanken.scss
packages/dnb-eufemia/src/components/textarea/style/themes/dnb-textarea-theme-ui.scss
packages/dnb-eufemia/src/extensions/forms/Field/String/String.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx

feat(Textarea): add keepPlaceholder prop

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/StepsLayout/Buttons/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/StepsLayout/NextButton/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/StepsLayout/PreviousButton/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/StepsLayout/NextButton/__tests__/NextButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/StepsLayout/PreviousButton/__tests__/PrevioursButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/StepsLayout/StepsContext.ts

fix(useStep): fix possibly undefined type message

---

packages/dnb-design-system-portal/src/docs/uilib/components/checkbox/events.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/checkbox/properties.mdx
packages/dnb-eufemia/src/components/checkbox/CheckboxDocs.ts

docs(Checkbox): update to typed docs

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx

split up the test in two to fix async behaviour

chore(forms): inconsistent async tests in Forms Provider

---

packages/dnb-eufemia/src/components/global-status/style/themes/dnb-global-status-theme-sbanken.scss

fix(GlobalStatus): Symmetric horizontal padding on smaller screens (Sbanken)

---

packages/dnb-design-system-portal/src/docs/uilib/intro/09-icons.mdx

chore(docs): fix intro typo

---

packages/dnb-design-system-portal/src/docs/EUFEMIA_CHANGELOG.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms.mdx

Let's wait to merge/add this to when we feel comfortable with https://github.com/dnbexperience/eufemia/milestone/4

feat(forms): release stable version

---

packages/dnb-eufemia/src/components/height-animation/HeightAnimationInstance.ts
packages/dnb-eufemia/src/components/height-animation/__tests__/HeightAnimationInstance.test.ts
packages/dnb-eufemia/src/components/table/useTableAnimationHandler.tsx

Before
https://github.com/dnbexperience/eufemia/assets/1501870/76fe9b5b-048d-456b-b2fd-979f932392a7
Now
https://github.com/dnbexperience/eufemia/assets/1501870/cfa05073-0193-4286-87d9-3b2e484c46b3

fix(HeightAnimation): overcome flickering issue due to false height pre-calculation

---

packages/dnb-design-system-portal/src/docs/uilib/layout/flex/Examples.tsx
packages/dnb-eufemia/src/components/flex/__tests__/utils.test.tsx
packages/dnb-eufemia/src/components/flex/utils.tsx

Use existing list of valid spacing props to pick among other props.

chore(Flex): add innerSpace as a valid spacing prop when using `pickSpacingProps`

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

closes https://github.com/dnbexperience/eufemia/issues/3516
Before:
https://github.com/dnbexperience/eufemia/assets/25927156/ef000f6d-7778-45a7-a967-564549cd6144
After:
https://github.com/dnbexperience/eufemia/assets/25927156/7afaf617-c5e4-457f-8419-6f418dc83268

fix(Field.PhoneNumber): make country code show all relevant countries on click after phonenumber is entered

---

packages/dnb-eufemia/src/extensions/forms/Iterate/AnimatedContainer/ElementBlock.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/EditContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/EditContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/ViewContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/ViewContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/style/dnb-form-iterate.scss

feat(forms): add `variant` prop to Iterate ViewContainer and EditContainer

---

packages/dnb-eufemia/src/extensions/forms/Field/Composition/__tests__/Composition.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Composition/stories/Composition.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fix(forms): add schema `required` support to Field.Composition

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/VisibilityDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx

feat(forms): add filterData prop to Visibility component

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useData/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/VisibilityDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/stories/Visibility.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/useData.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useData.tsx

feat(forms): add path based `filterData` support

---

packages/dnb-eufemia/src/components/checkbox/__tests__/__snapshots__/Checkbox.test.tsx.snap
packages/dnb-eufemia/src/components/checkbox/style/dnb-checkbox.scss
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.tsx.snap

Fix issue where the check icon is always visible when disabled

fix(Checkbox): ensure correct disabled state

---

packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx

chore(Visibility): don't render when visibleWhen path not exists

---

packages/dnb-eufemia/src/shared/MediaQuery.tsx
packages/dnb-eufemia/src/shared/MediaQueryUtils.ts
packages/dnb-eufemia/src/shared/__tests__/MediaQuery.test.tsx
packages/dnb-eufemia/src/shared/__tests__/useMedia.test.tsx
packages/dnb-eufemia/src/shared/__tests__/useMediaQuery.test.tsx
packages/dnb-eufemia/src/shared/useMedia.tsx
packages/dnb-eufemia/src/shared/useMediaQuery.tsx

In this PR we ensure that break-point ranges do not overlap.

fix(Breakpoint): ensure correct breakpoint ranges when using useMedia, useMediaQuery or MediaQuery

---

packages/dnb-design-system-portal/src/docs/uilib/components/accordion/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/accordion/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/layout/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/layout/grid/container/properties.mdx
packages/dnb-eufemia/src/components/grid/Container.tsx
packages/dnb-eufemia/src/components/grid/ContainerDocs.ts
packages/dnb-eufemia/src/components/grid/style/grid-container.scss

Link to demo: https://eufemia-git-docs-accordion-colums-eufemia.vercel.app/uilib/components/accordion/demos/?fullscreen#in-two-columns

docs: add Accordion in Grid columns example

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Composite/Block/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Composite/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/schema-validation/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/all-blocks.mdx
packages/dnb-eufemia/src/extensions/forms/Composite/Block/__tests__/Block.test.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/GenerateSchema.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/ListAllProps.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/__tests__/GenerateSchema.test.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/__tests__/ListAllProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/Category/FirstBlock/FirstBlock.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/Category/FirstBlock/__tests__/FirstBlock.test.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/Category/FirstBlock/index.ts
packages/dnb-eufemia/src/extensions/forms/blocks/Category/index.ts
packages/dnb-eufemia/src/extensions/forms/blocks/index.ts

Add [this example](https://eufemia-git-chore-blocks-eufemia.vercel.app/uilib/extensions/forms/blocks/all-blocks/) to showcase the possibilities.

chore(forms): add Blocks example

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/ProviderDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/types.ts
packages/dnb-eufemia/src/extensions/forms/hooks/DataValueDocs.ts
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

feat(forms): add `defaultValue` to all fields

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v11-info.mdx

chore(Checkbox): Add Checkbox v11 changes to the info docs

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/useFieldProps/Examples.tsx
packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx
packages/dnb-eufemia/src/extensions/forms/types.ts
yarn.lock

fix(forms): enhance handling of schema TypeScript support

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx
packages/dnb-eufemia/src/components/step-indicator/StepIndicator.tsx
packages/dnb-eufemia/src/extensions/forms/Form/MainHeading/MainHeading.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubHeading/SubHeading.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Buttons/Buttons.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/WizardContext.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Step/Step.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Step/StepDocs.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Step/__tests__/Step.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/useStep.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/stories/Wizard.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/style/dnb-wizard-layout.scss

Is there any better prop name than `active`?

feat(forms): add `active` prop to Wizard.Step

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/button/Button.js
packages/dnb-eufemia/src/components/dropdown/Dropdown.js
packages/dnb-eufemia/src/components/logo/Logo.js
packages/dnb-eufemia/src/components/number-format/NumberFormat.js
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js
packages/dnb-eufemia/src/fragments/drawer-list/DrawerList.js

chore: remove rest of class done in #3634

---

packages/README.md
packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/styling/legacy-styling.js
packages/dnb-design-system-portal/src/docs/uilib/usage/first-steps/bundles.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/first-steps/module-formats.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/first-steps/react.mdx
packages/dnb-design-system-portal/src/docs/uilib/usage/first-steps/the-basics.mdx

I'm not 100% sure if we want to remove all references to [eufemia-examples repo](https://github.com/dnbexperience/eufemia-examples), so please go through the changes done in this PR and verify if we should remove or keep some of the links to the demos in [eufemia-examples repo](https://github.com/dnbexperience/eufemia-examples). 
As of now, I've removed them all.

chore: remove all references to eufemia-examples repo

---

packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/localization.mdx
packages/dnb-eufemia/src/shared/Translation.tsx
packages/dnb-eufemia/src/shared/__tests__/Translation.test.tsx
packages/dnb-eufemia/src/shared/useTranslation.tsx

Check out the docs changes in this PR for more context.

feat(Translation): add support for type-safe keys

---

packages/dnb-design-system-portal/src/docs/uilib/components/accordion/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/accordion/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/accordion/events.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/accordion/properties.mdx
packages/dnb-eufemia/src/components/accordion/Accordion.tsx
packages/dnb-eufemia/src/components/accordion/AccordionDocs.ts
packages/dnb-eufemia/src/components/accordion/AccordionGroup.tsx
packages/dnb-eufemia/src/components/accordion/AccordionProviderContext.ts
packages/dnb-eufemia/src/components/accordion/__tests__/Accordion.test.tsx

Add functionality to close all `Accordions` in a `Accordion.Group`
Based on https://github.com/dnbexperience/eufemia/pull/3666 🙏

feat(Accordion): close all `Accordions` in `Accordion.Group`

---

packages/dnb-design-system-portal/src/docs/uilib/components/accordion/Examples.tsx
packages/dnb-eufemia/src/components/accordion/Accordion.tsx
packages/dnb-eufemia/src/components/accordion/AccordionContext.ts
packages/dnb-eufemia/src/components/accordion/AccordionDocs.ts
packages/dnb-eufemia/src/components/accordion/AccordionGroup.tsx
packages/dnb-eufemia/src/components/accordion/AccordionProviderContext.ts
packages/dnb-eufemia/src/components/accordion/AccordionStore.ts
packages/dnb-eufemia/src/components/accordion/__tests__/Accordion.test.tsx

feat(Accordion): allow multiple accordions inside a group to be expanded at the same time

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/demos.mdx

Adds a demo/example to the following feature https://github.com/dnbexperience/eufemia/pull/3753

docs(Field.Number): add `allowNegative` demo/example

---

packages/dnb-eufemia/src/components/badge/Badge.tsx
packages/dnb-eufemia/src/components/badge/__tests__/Badge.test.tsx
packages/dnb-eufemia/src/components/badge/__tests__/__snapshots__/Badge.test.tsx.snap
packages/dnb-eufemia/src/components/badge/stories/Badge.stories.tsx
packages/dnb-eufemia/src/components/badge/style/dnb-badge.scss

fix(Badge): fix vertical alignment support when used inline

---

packages/dnb-design-system-portal/src/docs/uilib/typography/font-size.mdx
packages/dnb-design-system-portal/src/docs/uilib/typography/font-weight.mdx
packages/dnb-design-system-portal/src/docs/uilib/typography/line-height.mdx

chore: minor doc improvement: changed _loot_ to _look_

chore: minor doc improvement: loot -> look

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx

fix(forms): ensure Form.Isolated does merge data properly

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/IsolationDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx

feat(forms): add path prop support to Form.Isolation

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Isolation/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/clearData.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/clearData/info.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/clearData.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/clearData.ts
packages/dnb-eufemia/src/extensions/forms/Form/index.ts

feat(forms): add `Form.clearData` method to remove existing/shared data forms with an id

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/events.mdx
packages/dnb-eufemia/src/extensions/forms/Field/FieldDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumberDocs.ts
packages/dnb-eufemia/src/extensions/forms/hooks/DataValueDocs.ts

* added portal documentation for second argument of `onChange(value, additionalArgs)` event.
* added `onCountryCodeChange` and `onNumberChange` events to portal documentation
* added helper for general field event types

docs(Field.PhoneNumber): document onChange event args

---

packages/dnb-design-system-portal/package.json
packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/components/table/table-accordion/TableAccordionHead.tsx
packages/dnb-eufemia/src/components/table/table-navigation/TableNavigationHead.tsx
packages/dnb-eufemia/src/shared/helpers/isAsync.ts

For some reason we had the `--fix` flag during linting, so some issues were never coughed up.

chore: ensure ESLint runs properly on CI

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Isolation/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Option/Option.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Option/__tests__/Option.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/SelectionDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx

chore(Field.Selection): concat `dataPath` with children

---

packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fix(forms): ensure `Iterate.Array` can handle an array given in the data context

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Isolation/info.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx

Fixes #3844
The test fails with the old implementation 👍

fix(forms): make `Form.Isolation`s data flow "from outside" stricter

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Isolation/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/schema-validation/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/AnimatedContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Count/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushButton/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/RemoveButton/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Toolbar/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PostalCodeAndCity/Examples.tsx
packages/dnb-design-system-portal/src/shared/tags/ComponentBox.tsx

As suggested [here](https://github.com/dnbexperience/eufemia/pull/3841#issuecomment-2297024013)

chore: default import Iterate in ComponentBox

---

packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/useContainerDataStore.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/usePath.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
packages/dnb-eufemia/src/extensions/forms/hooks/usePath.ts

fix(forms): ensure `Section.EditContainer` cancel restores data when path is given

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/ChildrenWithAge.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/ChildrenWithAge.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/ChildrenWithAge.test.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/__snapshots__/ChildrenWithAge.test.tsx.snap

feat(Blocks.ChildrenWithAge): removes step controls in age field

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/ArraySelection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/ArraySelection/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/ArraySelection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/ArraySelectionDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/__tests__/ArraySelection.test.tsx

feat(Field.ArraySelection): add dataPath prop

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/info.mdx
packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/NationalIdentityNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/__tests__/NationalIdentityNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/NationalIdentityNumber/stories/NationalIdentityNumber.stories.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts
yarn.lock

Motivation from https://dnb-it.slack.com/archives/CMXABCHEY/p1720521252444219

feat(Forms): add validation for dnr and fnr in `Field.NationalIdentityNumber`

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/demos.mdx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/ArrayDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/types.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/IterateItemContext.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/Iterate.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Quick example:
```tsx
<Form.Handler>
<Iterate.Array
path="/items"
validator={(arrayValue) => {
if (!(arrayValue?.length > 0)) {
return new Error('You need at least one item')
}
}}
>
<Field.String itemPath="/" />
<Iterate.PushButton path="/items" pushValue="baz" />
<Form.SubmitButton />
```

feat(Forms): add `validator` support to Iterate.Array

---

packages/dnb-eufemia/src/extensions/forms/Wizard/Step/Step.tsx

Here is a [CSB](https://codesandbox.io/p/sandbox/nq8vpt?file=%2Fsrc%2FApp.tsx) that fails.

fix(Forms): Wizard.Step JSX component TypeScript fix

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushButton/info.mdx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushButton/PushButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushButton/__tests__/PushButton.test.tsx

Quick example:
```tsx
<Form.Handler>
<Iterate.Array path="/myList">
<Field.String itemPath="/" />
<Iterate.PushButton
path="/myList"
pushValue="push value"
text="Add no. {nextItemNo}"
/>
</Form.Handler>,
```

feat(Forms): add `{nextItemNo}` support to Iterate.PushButton

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SelectCountry/info.mdx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/Iterate.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCountry/__tests__/useCountry.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SelectCountry/useCountry.ts

This PR moves the logic to get a country name by iso out of the Value component to its own hook. 
- We also document it.
- And add it to an example/demo.

feat(Forms): add `useCountry` with `getCountryNameByIso` to Value.SelectCountry

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/ArraySelection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/ArraySelection/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Value/ArraySelection/ArraySelection.tsx
packages/dnb-eufemia/src/extensions/forms/Value/ArraySelection/ArraySelectionDocs.ts
packages/dnb-eufemia/src/extensions/forms/Value/ArraySelection/__tests__/ArraySelection.test.tsx

Sorry, need to fix some last minute changes 🙏

feat(Value.ArraySelection): add `variant` prop to allow for list layout

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Before:
https://github.com/user-attachments/assets/42bd6a95-0353-43ec-b445-6750f9336833
After:
https://github.com/user-attachments/assets/c64da0b0-5f01-4c29-9a74-988ca7902601
This PR will not make any change when a default data set is given:
https://github.com/user-attachments/assets/b83611ca-7840-4f82-88e3-f042eaf35f9b

fix(Forms): enhance defaultValue routine during mounting of fields

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/Examples.tsx

This reverts this [WIP commit](https://github.com/dnbexperience/eufemia/pull/3962/commits/1562f98eef92e7a6a4b89ef9406b8fb91cf22eab), which I not wanted to me merged 😄

chore: revert unwanted example changes

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SummaryList/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SummaryList/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/SummaryList.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/SummaryListContext.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/SummaryListDocs.ts
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/__tests__/SummaryList.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useValueProps.ts

Motivated by https://github.com/dnbexperience/eufemia/pull/4003

feat(Forms): add inheritLabel to Value.SummaryList

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Currency/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Currency/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Currency/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Number/properties.mdx
packages/dnb-eufemia/src/components/number-format/NumberFormatDocs.ts
packages/dnb-eufemia/src/extensions/forms/Value/Currency/CurrencyDocs.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Number/NumberDocs.tsx

Can be demoed here:
- [Currency](https://eufemia-git-chore-improve-currency-docs-eufemia.vercel.app/uilib/extensions/forms/Value/Currency/properties/)
- [Number](https://eufemia-git-chore-improve-currency-docs-eufemia.vercel.app/uilib/extensions/forms/Value/Number/properties/)

docs(Forms): improves docs for Value.Number & Value.Currency

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Date/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Date/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Date/properties.mdx
packages/dnb-eufemia/src/components/date-picker/DatePicker.d.ts
packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/stories/Date.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Value/Date/__tests__/Date.test.tsx

feat(Field.Date): add date range functionality

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

The changelog can be looked at here https://eufemia-git-chore-changelog-for-v1051-eufemia.vercel.app/uilib/extensions/forms/changelog/

chore: update changelog for v10.51

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/SummaryList/properties.mdx

Removes the text showtabs:true

chore: remove showTabs: true

---

packages/dnb-eufemia/src/components/badge/Badge.tsx
packages/dnb-eufemia/src/components/badge/__tests__/Badge.test.tsx

fixes https://github.com/dnbexperience/eufemia/issues/4047
Here's a [CSB](https://codesandbox.io/p/sandbox/boring-fog-n7vr2y?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd), using the build from this PR, where Badge doesn't re-render.

fix(Badge): prevents unwanted re-rendering

---

packages/dnb-design-system-portal/src/docs/quickguide-designer/accessibility.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/BankAccountNumber/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Expiry/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/NationalIdentityNumber/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/OrganizationNumber/info.mdx
packages/dnb-eufemia/src/components/logo/Logo.tsx
packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts

Changed norwegian to Norwegian.

chore: change norwegian to Norwegian

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/dnb-ui-lib/v4.10-info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Expiry/demos.mdx
packages/dnb-eufemia/src/components/logo/Logo.tsx
packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts

chore: change english to English

---

packages/dnb-eufemia/src/extensions/forms/Field/OrganizationNumber/OrganizationNumber.tsx

chore: adds missing validator logic based on validate

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx

Closes https://github.com/dnbexperience/eufemia/issues/4058
Before:
https://github.com/user-attachments/assets/c3551fe6-e3e5-4995-ac84-95212593331b
After:
https://github.com/user-attachments/assets/8f420888-eba2-4b9e-889f-b7c097d27cc1

fix(Autocomplete): Show whole suggestion list after item selection

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/clearData.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/clearData.ts
packages/dnb-eufemia/src/extensions/forms/Form/data-context/getData.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useData.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useValidation.tsx

fix(Forms): ensure Form.clearData works in React.StrictMode

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushButton/Examples.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/Iterate.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/Log.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

feat(Forms): add support for `defaultValue` (and `value`) for fields used in `Iterate.Array`

---

packages/dnb-eufemia/jest.config.screenshots.js
packages/dnb-eufemia/src/components/tabs/__tests__/Tabs.screenshot.test.ts
packages/dnb-eufemia/src/core/jest/setupJestScreenshot.js

Its not a 100% sure solution. But should improve the outcome I hope.

chore: make visual test for tabs less flaky

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/ArrayItemArea.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/ArrayItemArea.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/IterateItemContext.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/Iterate.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/stories/PushContainer.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/Log.tsx

fix(Forms): keep `Iterate.EditContainer` open when falsy value or empty object was given as the iterate value

---

packages/dnb-eufemia/src/extensions/forms/Form/SubmitConfirmation/SubmitConfirmation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitConfirmation/__tests__/SubmitConfirmation.test.tsx

fix(Forms): add support for Form.SubmitConfirmation inside Wizard (renderWithState)

---

packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/ChildrenWithAge.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/ChildrenWithAgeTranslations.ts
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/__snapshots__/ChildrenWithAge.test.tsx.snap

chore(ChildrenWithAge): formats daycare help text

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

Updates changelog for https://github.com/dnbexperience/eufemia/pull/4129

chore: update changelog for v10.53

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/demos.mdx

I don't think our users needs to read this 🙏

chore: removes unnecessary text

---

packages/dnb-design-system-portal/package.json
packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx
packages/dnb-eufemia/src/components/checkbox/Checkbox.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerCalendar.js
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.js
packages/dnb-eufemia/src/components/dropdown/Dropdown.js
packages/dnb-eufemia/src/components/global-status/GlobalStatus.js
packages/dnb-eufemia/src/components/input-masked/InputMaskedHooks.js
packages/dnb-eufemia/src/components/modal/ModalContent.tsx
packages/dnb-eufemia/src/components/radio/Radio.js
packages/dnb-eufemia/src/components/table/TableClickableHead.tsx
packages/dnb-eufemia/src/components/tabs/Tabs.js
packages/dnb-eufemia/src/components/toggle-button/ToggleButton.js
packages/dnb-eufemia/src/fragments/drawer-list/DrawerList.js
packages/dnb-eufemia/src/fragments/drawer-list/DrawerListProvider.js
packages/dnb-eufemia/src/shared/__tests__/keycode.test.ts
packages/dnb-eufemia/src/shared/component-helper.js
packages/dnb-eufemia/src/shared/keycode.ts
packages/dnb-eufemia/src/shared/libs/Shortcuts.js
yarn.lock

This change let's us progressively rewrite our components and tests.

feat(Keyboard navigation): add support for `key` property (useful for fire events like {ArrowDown} during tests)

---

packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap
packages/dnb-eufemia/src/components/table/style/table-accordion.scss

Remove outdated fix from [this pr](https://github.com/dnbexperience/eufemia/pull/1737)

fix(Table): fix visible hidden rows for additional expandable table rows

---

packages/dnb-eufemia/src/extensions/forms/Form/Section/__tests__/Section.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/hooks/usePath.ts

fix(Forms): fix schema validation for required paths with matching name

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/__tests__/SelectCountry.test.tsx

fix(Forms): ensure correct sorting in Field.SelectCountry

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Section/EditContainer/properties.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Section/ViewContainer/properties.mdx
packages/dnb-eufemia/src/extensions/forms/Form/Section/EditContainer/EditContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Section/ViewContainer/ViewContainerDocs.ts

chore(Docs): move event properties to it's own event section

---

packages/dnb-eufemia/src/extensions/forms/Field/PostalCodeAndCity/__tests__/PostalCodeAndCity.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts

fix(Forms): add Iterate support for Field.PostalCodeAndCity when using `country` with a path

---

packages/dnb-eufemia/src/components/country-flag/CountryFlagDocs.ts

Small follow-up to https://github.com/dnbexperience/eufemia/pull/4232

docs(CountryFlag): `iso` defaults to `NO`

---

packages/dnb-eufemia/src/style/core/reset.scss

More info [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1730900327026259?thread_ts=1728631312.108779&cid=CMXABCHEY).

fix: remove legacy `fieldset` reset

---

packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx

More info [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1731077916746649?thread_ts=1730901926.012229&cid=CMXABCHEY).
Thank you Anders for good [reprod](https://codesandbox.io/p/sandbox/blue-sun-d66ky5?file=/src/App.tsx:10,16&workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd) 💯

fix(Forms): ensure Field.Upload handles `required` logic between Wizard step changes

---

packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/SummaryList.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/__tests__/SummaryList.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/__tests__/useVerifyChildren.test.tsx
packages/dnb-eufemia/src/extensions/forms/Value/SummaryList/useVerifyChildren.ts

- Ignore Form.Visibility
- Show given props in message, so it is possible to find the source/cause of the message.

chore: enhance Value.SummaryList warning

---

.vscode/settings.json

chore: ensure VS Code uses workspace of TypeScript

---

packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx

This PR adds tests to https://github.com/dnbexperience/eufemia/pull/4281

chore(Field.Upload): adds asyncFileHandler tests

---

packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlockContext.ts
packages/dnb-eufemia/src/extensions/forms/FieldBlock/__tests__/FieldBlock.test.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/style/dnb-field-block.scss
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Issues we had with the indicator:
https://github.com/user-attachments/assets/7612f17b-ee6d-4b56-a5bc-92fcda72d07d
https://github.com/user-attachments/assets/9805423d-8ee3-4967-82ed-eb074ed0675f

fix(Forms): ensure fields inside composition share submit indicator

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/parts/async-state-return-example.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/clearData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/getData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/setData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useSnapshot/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useValidation/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Count/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Container/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/useStep/info.mdx
packages/dnb-eufemia/src/extensions/forms/Iterate/Count/Count.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/useStep.tsx

Sorry, I missed a few parts of the id reference feature introduced in #4331

chore(Forms): refactor and document missed parts of #4331

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/PhoneNumber/Examples.tsx
packages/dnb-eufemia/src/components/number-format/NumberUtils.js
packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts
packages/dnb-eufemia/src/extensions/forms/Value/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/constants/countries.ts

fix(NumberFormat): improve regex for parsing phone numbers with country codes

---

packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.module.scss
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.tsx

* Also fixed not scrolling to current page when opening menu on small screens

chore(portal): expand button no longer below scrollbar

---

packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx

From:
https://github.com/user-attachments/assets/be316407-925c-49d9-8ba7-ac09ef60635a
To: 
https://github.com/user-attachments/assets/1d217482-1fc3-4a6d-a49b-3908d315fc87

fix(Upload): handling of multiple async events

---

packages/dnb-design-system-portal/src/docs/contribute/getting-started/commit-changes.mdx
packages/dnb-design-system-portal/src/docs/contribute/style-guides/git.mdx

Read them here: https://eufemia-git-docs-git-commit-guidlines-eufemia.vercel.app/contribute/style-guides/git/

docs: add guidelines for writing commit messages to the contribution guide

---

packages/dnb-eufemia/src/components/tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/dnb-eufemia/src/components/tabs/style/dnb-tabs.scss

- [CSB](https://codesandbox.io/p/sandbox/pagination-interference-v9kd9y?file=/src/App.tsx:15,7) with the issue.
- CSB (comming) with the fixed version.

fix(Tabs): ensure cached content never takes up visual space

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

Changelog for forms in release v10.62.0 https://github.com/dnbexperience/eufemia/pull/4414

chore: add changelog for forms v10.62.0

---

packages/dnb-eufemia/src/components/date-picker/DatePicker.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.tsx

Contains typescript fixes for DatePicker

release of v10.62.2

---

packages/dnb-eufemia/src/components/upload/__tests__/UploadFileListLink.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useExternalValule.test.tsx

chore: add missing tests

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/Examples.tsx
packages/dnb-eufemia/src/components/card/Card.tsx
packages/dnb-eufemia/src/components/card/__tests__/Card.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx

fix(Card): prioritize `gap` property over `stack` spacing

---

packages/dnb-eufemia/src/extensions/forms/Form/data-context/useValidation.tsx

More [info here](https://dnb-it.slack.com/archives/CMXABCHEY/p1736248982648609).

fix(Forms): ensure `setFormError` from Form.useValidation accepts undefined or null as a value

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js

fixes https://github.com/dnbexperience/eufemia/issues/2101

fix(Autocomplete): does not fail when clicking show all button

---

packages/dnb-design-system-portal/src/html.js
packages/dnb-design-system-portal/src/shared/menu/SidebarMenu.tsx
packages/dnb-design-system-portal/src/shared/menu/StickyMenuBar.tsx
packages/dnb-design-system-portal/src/shared/tags/Img.js
packages/dnb-design-system-portal/src/shared/tags/Intro.tsx
packages/dnb-design-system-portal/src/shared/tags/Tabbar.tsx
packages/dnb-eufemia/src/components/button/Button.js
packages/dnb-eufemia/src/components/dropdown/stories/Dropdown.stories.tsx
packages/dnb-eufemia/src/components/form-row/FormRow.js
packages/dnb-eufemia/src/components/form-status/FormStatus.js
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js
packages/dnb-eufemia/src/fragments/drawer-list/DrawerList.js
packages/dnb-eufemia/src/shared/AlignmentHelper.js
tools/react-live-ssr/dist/index.js
tools/react-live-ssr/dist/index.mjs

Fixes a few warnings reported here, not all I believe:
https://github.com/dnbexperience/eufemia/issues/4145

chore: replace defaultProps in function components

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useData/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/Form/Handler/__tests__/Handler.test.tsx

docs(Forms): improve documentation on TypeScript type handling

---

packages/dnb-eufemia/src/components/accordion/Accordion.tsx

- Fixes https://github.com/dnbexperience/eufemia/issues/4145
- In relation to #4447 and #4448

chore(Accordion): replace defaultProps

---

packages/dnb-eufemia/src/components/input-masked/InputMasked.js
packages/dnb-eufemia/src/components/input-masked/InputMaskedUtils.js
packages/dnb-eufemia/src/components/input-masked/__tests__/InputMasked.test.tsx

- Fixes https://github.com/dnbexperience/eufemia/issues/4145
- In relation to #4447

fix: refactor defaultProps to ES6 default parameters

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx
packages/dnb-eufemia/src/components/autocomplete/stories/Autocomplete.stories.tsx

fixes https://github.com/dnbexperience/eufemia/issues/3419
[Here's a CSB with the fix](https://codesandbox.io/p/sandbox/great-ganguly-mgm548?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE)

fix(Autocomplete): focus issue when no valid data

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions.mdx
packages/dnb-design-system-portal/src/docs/uilib/intro/11-components-elements-extensions.mdx

Fixes https://github.com/dnbexperience/eufemia/issues/3297

docs(Extensions): extend description

---

packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/useHandleLayoutEffect.tsx

More info [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1737026599728919).

fix(Forms): ensure wizard step changes scroll so the StepIndicator is included at the top

---

packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts

More info [here](https://dnb-it.slack.com/archives/CMXABCHEY/p1737987113910259).

fix(Forms): ensure `connectWithPath` type is given

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Isolation/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Section/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Visibility/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useData/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useSnapshot/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useValidation/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/String/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/blocks/ChildrenWithAge/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/demo-cases/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/Examples.tsx
packages/dnb-design-system-portal/src/shared/tags/ComponentBox.tsx

https://github.com/dnbexperience/eufemia/pull/4503#pullrequestreview-2577452327

chore(ComponentBox): add Tools as default import

---

packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/ArraySelection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/__tests__/Boolean.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Expiry/Expiry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Slider/Slider.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/String.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Section/__tests__/Section.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/IterateItemContext.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/hooks/useItemPath.ts
packages/dnb-eufemia/src/extensions/forms/Tools/__tests__/GenerateSchema.test.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/__tests__/ListAllProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/__snapshots__/ChildrenWithAge.test.tsx.snap
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

More [info](https://dnb-it.slack.com/archives/C07JEJVSHJR/p1738066448039359?thread_ts=1730453188.996159&cid=C07JEJVSHJR).

fix(Forms): provide `displayValue` and `label` to `transformData` from fields inside Iterate

---

packages/dnb-design-system-portal/src/docs/EUFEMIA_CHANGELOG.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

changelog for https://github.com/dnbexperience/eufemia/pull/4450

chore: changelog for v10.63.0

---

packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx

chore(Forms): remove console warning during test run

---

packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/useData.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useExternalValue.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1738590820694909).

fix(Forms): ensure `update('/path', undefined)` does not show error message

---

packages/dnb-design-system-portal/src/docs/uilib/components/modal/event-table.mdx
packages/dnb-design-system-portal/src/shared/parts/PropertiesTable.tsx
packages/dnb-eufemia/src/components/dialog/__tests__/Dialog.test.tsx
packages/dnb-eufemia/src/components/drawer/__tests__/Drawer.test.tsx
packages/dnb-eufemia/src/components/modal/Modal.tsx
packages/dnb-eufemia/src/components/modal/ModalContent.tsx
packages/dnb-eufemia/src/components/modal/ModalRoot.tsx
packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx
packages/dnb-eufemia/src/components/modal/types.ts
packages/dnb-eufemia/src/elements/code/style/code-mixins.scss
packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/useData.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/__tests__/useValidation.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/data-context/useValidation.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useExternalValue.ts
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/style/elements/__tests__/__snapshots__/Elements.test.js.snap

release of v10.63.2

---

packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/useVisibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/useVisibility.tsx

Relies on https://github.com/dnbexperience/eufemia/pull/4538

fix(Forms): ensure `pathUndefined` on Form.Visibility does render when value is `undefined`

---

packages/dnb-eufemia/src/components/form-status/FormStatus.js
packages/dnb-eufemia/src/components/form-status/__tests__/FormStatus.test.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1733401959487709).

fix(FormStatus): ensure content given as `children` will be displayed in linked GlobalStatus

---

packages/dnb-design-system-portal/src/docs/uilib/layout/flex/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/layout/flex/stack.mdx
packages/dnb-design-system-portal/src/docs/uilib/layout/flex/stack/info.mdx

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1737703268584629).

docs(Flex): clarify difference between Flex.Vertical and Flex.Stack (stretching behavior)

---

packages/dnb-eufemia/src/extensions/forms/Wizard/Step/Step.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Step/__tests__/Step.test.tsx

[CSB of the problem](https://codesandbox.io/p/sandbox/focused-kare-r99q49)
[CSB with the fix](https://codesandbox.io/p/devbox/blazing-pond-hshgpp?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE)

fix(Wizard.Step): use `title` as aria-label when wrapped in `Wizard.Container`

---

packages/dnb-eufemia/src/components/textarea/Textarea.js

Motivation https://dnb-it.slack.com/archives/CMXABCHEY/p1739800350978059

fix(TextArea): ResizeObserver loop completed with undelivered notifications

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v11-info.mdx

Related to https://github.com/dnbexperience/eufemia/pull/4572

docs(v11): replace `country` with `countryCode` in `Field.PostalCodeAndCity`

---

packages/dnb-eufemia/src/extensions/forms/Field/Boolean/Boolean.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/BooleanDocs.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/__tests__/Boolean.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/ToggleDocs.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/__tests__/Toggle.test.tsx

Dependent on https://github.com/dnbexperience/eufemia/pull/4601

feat(Boolean): add `size` property

---

packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx

dependent on https://github.com/dnbexperience/eufemia/pull/4469 and https://github.com/dnbexperience/eufemia/pull/4614

feat(Field.Date) export `dateLimitValidator`

---

packages/dnb-eufemia/src/components/date-picker/DatePicker.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerAddon.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Fixes [this issue](https://dnb-it.slack.com/archives/CMXABCHEY/p1740129052576499)

fix(DatePicker): correct focus behaviour when picker has closed

---

packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx

fix(Field.Date): add missing support for `skipPortal`

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx

feat(Forms): add async Autocomplete support to Field.Selection

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Connectors/Bring/info.mdx
packages/dnb-eufemia/src/extensions/forms/Connectors/Bring/__tests__/postalCode.test.tsx
packages/dnb-eufemia/src/extensions/forms/Connectors/Bring/postalCode.ts
packages/dnb-eufemia/src/extensions/forms/Connectors/__tests__/createContext.test.ts
packages/dnb-eufemia/src/extensions/forms/Connectors/createContext.ts
packages/dnb-eufemia/src/extensions/forms/Connectors/stories/Connectors.stories.tsx
packages/dnb-eufemia/src/extensions/forms/types.ts

chore(Connector): add support for `countryCode` to handler config

---

packages/dnb-eufemia/package.json
yarn.lock

Reverts https://github.com/dnbexperience/eufemia/pull/4703

chore: revert core-js to 3.26.1

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/info.mdx
packages/dnb-eufemia/src/components/date-picker/DatePickerCalendar.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/stories/DatePicker.stories.tsx

feat(DatePicker): add support for swedish translations

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-picker/events.mdx
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/hooks/useDates.ts
packages/dnb-eufemia/src/components/date-picker/hooks/usePartialDates.ts

chore(DatePicker): refactor partial dates

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

Changelog for forms in release v10.67.0 - https://github.com/dnbexperience/eufemia/pull/4673

chore: changelog for forms v10.67.0

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

Changelog for v10.67.1 https://github.com/dnbexperience/eufemia/pull/4715

changelog for v10.67.1

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/Name/info.mdx
packages/dnb-eufemia/src/extensions/forms/Field/Name/Name.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Name/__tests__/Name.test.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1741780935099909?thread_ts=1741776399.617789&cid=CMXABCHEY

fix(Field.Name.Company): must consist of at least 3 norwegian letters

---

packages/dnb-design-system-portal/src/docs/uilib/components/dialog/Examples.tsx
packages/dnb-eufemia/src/components/dialog/stories/Dialog.stories.tsx
packages/dnb-eufemia/src/components/modal/ModalContent.tsx
packages/dnb-eufemia/src/components/modal/__tests__/Modal.test.tsx
packages/dnb-eufemia/src/shared/helpers/InteractionInvalidation.ts

- More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1741703864007019).
- Related PR #4525 and [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1738574258572699?thread_ts=1738072824.587899&cid=CMXABCHEY).

fix(Dialog, Drawer, Modal): ensure `onClose` is not called in React.StrictMode

---

packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/localization.mdx

I think we should wait to merge this PR until https://github.com/dnbexperience/eufemia/pull/4719 is merged, to prevent conflicts in https://github.com/dnbexperience/eufemia/pull/4719

chore(Localization): minor spelling improvements

---

packages/dnb-eufemia/src/extensions/forms/DataContext/FieldBoundary/__tests__/FieldBoundaryProvider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Fixing errors related to implementation of https://github.com/dnbexperience/eufemia/pull/4638

fix(Wizard.Container): not displaying error when user enters required data

---

packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx

As promised [here](https://github.com/dnbexperience/eufemia/pull/4742#issuecomment-2724005849).

chore(useFieldProps): add revealError test

---

packages/dnb-eufemia/src/shared/Translation.tsx
packages/dnb-eufemia/src/shared/__tests__/Translation.test.tsx

fix(mergeTranslations): add support for nested objects

---

packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/components/number-format/NumberUtils.js
packages/dnb-eufemia/src/components/number-format/__tests__/NumberFormat.test.tsx
packages/dnb-eufemia/src/components/number-format/__tests__/NumberUtils.test.ts
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/shared/Translation.tsx
packages/dnb-eufemia/src/shared/__tests__/Translation.test.tsx
yarn.lock

Main motivation: https://github.com/dnbexperience/eufemia/issues?q=state%3Aopen%20label%3A%22swedish%20translation%22
These are quite breaking I would say, and will prevent one from actually using the new `sv-SE` translations
Especially: 
https://github.com/dnbexperience/eufemia/issues/4753

release of v10.68.1

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/NextButton/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/NextButton/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/PreviousButton/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/PreviousButton/info.mdx

chore(Forms): refactor NextButton and PreviousButton example to not show Wizard.Provider

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js

Fixes this error that I've experienced:
https://github.com/user-attachments/assets/3e8c384b-f6bf-4e85-b718-eae3099dab7c

chore(Autocomplete): safeguard updating data

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/dnb-ui-lib/v5.8-info.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/input-masked/properties.mdx
packages/dnb-eufemia/src/components/form-status/__tests__/FormStatus.test.tsx
packages/dnb-eufemia/src/components/input/__tests__/Input.test.tsx
packages/dnb-eufemia/src/components/textarea/__tests__/Textarea.test.tsx

chore: minor spelling improvement `to to` -> `to`

---

packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1742297259375399?thread_ts=1741793180.264779&cid=CMXABCHEY).
This issue is not easy to title in the PR nor to make a good test and description. It actually is not only an Wizard issue, but just was discovered there. And probably would never have been.
Any better ideas?

fix(Forms): ensure Wizard does not show invalid error

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/info.mdx

Perhaps we should also render the actual list of countries in a table format as well?

docs(Field.SelectCountry): add link to list of countries

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component/useFieldProps/Examples.tsx

Error can be seen/demoed here: https://eufemia.dnb.no/uilib/extensions/forms/create-component/useFieldProps/demos/#demos

chore: Incorrect use of <label for=FORM_ELEMENT>

---

packages/dnb-design-system-portal/src/docs/uilib/components/global-error/properties.mdx
packages/dnb-eufemia/src/components/global-error/GlobalError.tsx
packages/dnb-eufemia/src/components/global-error/GlobalErrorDocs.ts

Can be demoed here https://eufemia-git-docs-improve-global-error-properties-docs-eufemia.vercel.app/uilib/components/global-error/properties/

docs(GlobalError): improve properties docs

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/AvailableCountriesTable.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/assets/AvailableCountriesTable.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/SelectCountry/properties.mdx

Can be demoed here: https://eufemia-git-docs-add-list-of-countries-in-props-eufemia.vercel.app/uilib/extensions/forms/feature-fields/SelectCountry/properties/#list-of-available-countries

docs(Field.SelectCountry): display list of available countries

---

packages/dnb-design-system-portal/src/docs/404.tsx

Can be demoed at https://eufemia-git-chore-localize-404-error-page-eufemia.vercel.app/404/

chore: localize 404 error page

---

packages/dnb-design-system-portal/src/docs/500.tsx

Can be demoed at https://eufemia-git-chore-localize-500-eufemia.vercel.app/500/

chore: localize 500 error page

---

packages/dnb-eufemia/src/extensions/forms/Wizard/Buttons/Buttons.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/DisplaySteps.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/IterateOverSteps.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/useCollectStepsData.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/WizardContext.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/types.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Step/Step.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Step/StepDocs.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/useStep.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/stories/Wizard.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

- Fixes #4789
- Any better suggestions to name the change log/PR?

fix(Forms): enhance Wizard Step rendering routine

---

packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/CancelButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/DoneButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushButton/__tests__/PushButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/OpenButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/EditButton.tsx

+ Added one more test to the PushContainer, which I need in another PR

chore(Forms): rename internal `Iterate.*` class names

---

packages/dnb-eufemia/src/components/tabs/Tabs.js
packages/dnb-eufemia/src/components/tabs/__tests__/Tabs.test.tsx
packages/dnb-eufemia/src/components/tabs/stories/Tabs.stories.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1743149851563079
CSB of the problem: https://codesandbox.io/p/sandbox/zealous-lumiere-nz9s8k?file=%2Fsrc%2FApp.tsx
CSB of the problem using the fix of this PR: https://codesandbox.io/p/devbox/frosty-driscoll-jxd76c?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE

fix(Tabs): conditional render Tabs.Content

---

packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/ArrayItemArea.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/EditContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/__tests__/EditAndViewContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/ViewContainer/ViewContainer.tsx

It should not change any behavior. Just logical rewrites done in #4812

chore(Forms): housekeeping of Containers and Visibility

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/Visibility.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/VisibilityContext.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/DisplaySteps.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/useCollectStepsData.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/WizardContext.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/types.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/EditButton/__tests__/EditButton.screenshot.test.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Step/Step.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

- Based on #4811
- Fixes #4804

fix(Forms): remove error from Wizard menu when field gets unmounted

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

Changelog for https://github.com/dnbexperience/eufemia/pull/4800

chore: changelog for forms v10.69.1

---

packages/dnb-eufemia/src/extensions/forms/Form/Visibility/VisibilityDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/Visibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/__tests__/useVisibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Visibility/useVisibility.tsx

fix(Forms): ensure `hasValue` runs in Form.Visibility when path is missing

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v11-info.mdx
packages/dnb-eufemia/src/components/pagination/Pagination.d.ts
packages/dnb-eufemia/src/components/pagination/Pagination.js
packages/dnb-eufemia/src/components/pagination/PaginationDocs.ts
packages/dnb-eufemia/src/components/pagination/PaginationProvider.js

fixes https://github.com/dnbexperience/eufemia/issues/4868

feat(Pagination): rename `place_maker_before_content` to `place_marker_before_content`

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fix(Forms): correctly report error during Wizard step navigation with async event handler or field validator

---

packages/dnb-eufemia/src/components/avatar/__tests__/Avatar.test.tsx

Failing test on main: https://github.com/dnbexperience/eufemia/actions/runs/14261313297/job/39973342015?pr=4869

chore(Avatar): remove test duplication

---

packages/dnb-eufemia/src/components/avatar/Avatar.tsx
packages/dnb-eufemia/src/components/section/Section.tsx
packages/dnb-eufemia/src/shared/helpers.js

Not entirely sure if this is the best place to put it 🤔 
For now I moved it to `packages/dnb-eufemia/src/shared/helpers.js`

chore: share `getColor` function

---

packages/dnb-design-system-portal/src/docs/uilib/components/heading/info.mdx

chore(Heading): remove todo from docs

---

packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Test is made with the motivation from: https://dnb-it.slack.com/archives/CMXABCHEY/p1744105593951939

chore(DatePicker): add test for updating `minDate` value

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/PhoneNumber/events.mdx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumberDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1744110850287729) and [PR preview](https://eufemia-git-feat-forms-phone-number-iso-eufemia.vercel.app/uilib/extensions/forms/feature-fields/PhoneNumber).

feat(Forms): add `iso` (country) to additional args in PhoneNumber field

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/ProviderDocs.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlock.tsx
packages/dnb-eufemia/src/extensions/forms/FieldBlock/FieldBlockContext.ts
packages/dnb-eufemia/src/extensions/forms/hooks/DataValueWritePropsDocs.ts
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/types.ts
packages/dnb-eufemia/src/extensions/forms/utils/FormError.ts

More [info](https://dnb-it.slack.com/archives/CMXABCHEY/p1743427503988359).

feat(Forms): add support for string and JSX format to Field.* `error` prop and validators

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

Forms changelog for https://github.com/dnbexperience/eufemia/pull/4933

chore(changelog): forms v10.71.0

---

packages/dnb-design-system-portal/src/docs/uilib/components/drawer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/fragments/drawer-list/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/global-status/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/progress-indicator/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/step-indicator/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/components/upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Connectors/Bring/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/Handler/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Form/useData/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/AnimatedContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Value/Upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/Container/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Selection/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/getting-started.mdx
packages/dnb-eufemia/src/extensions/forms/utils/FormError.ts

Adjustments:
- https://github.com/dnbexperience/eufemia/pull/4928#discussion_r2039668388
- https://github.com/dnbexperience/eufemia/pull/4928#discussion_r2039674507
- Try to use template literals with variables in examples.

chore: housekeeping

---

packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx

Fixes failing test introduced in #4766

chore(DatePicker): fix faling test

---

packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.tsx.snap
packages/dnb-eufemia/src/components/step-indicator/style/dnb-step-indicator.scss

[CSB of the issue](https://codesandbox.io/p/devbox/frosty-hertz-vnxfsp?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE):
[How it should look](https://codesandbox.io/p/sandbox/laughing-darkness-788lz8)
[CSB of the fix](https://codesandbox.io/p/devbox/stupefied-platform-k65stg?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE):

fix(StepIndicator): align trigger button

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/demos.mdx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Fixes #4956
PR [Preview](https://eufemia-git-fix-iterate-schema-minitems-eufemia.vercel.app/uilib/extensions/forms/Iterate/Array/#minium-one-item).

fix(Forms): ensure Iterate.Array schema validation

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Context.ts
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/Field/ArraySelection/ArraySelection.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/__tests__/useFieldProps.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

chore(Forms): store emptyValue of fields in context

---

packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/useReportError.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/useReportError.ts

Its not an issue today. But we need this "refactor" with the reporting in an upcoming PR (related to #4985).

chore(Forms): ensure Form.Isolation reports error to Wizard

---

packages/dnb-design-system-portal/src/docs/icons/form-status.mdx
packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/dnb-ui-lib/v6-info.mdx
packages/dnb-eufemia/src/components/timeline/TimelineDocs.ts

Related to https://github.com/dnbexperience/eufemia/pull/5039

chore(FormStatus): improve links

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1695835256502809

fix(Field.PhoneNumber): validate field as required even if country code was given

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.d.ts
packages/dnb-eufemia/src/components/autocomplete/AutocompleteDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1743066020148259
https://github.com/user-attachments/assets/5a0d896c-9d64-4acf-8aa7-52203d1a0df2

fix(Field.PhoneNumber): select country  code input value on single click

---

packages/dnb-eufemia/src/components/upload/UploadFileList.tsx
packages/dnb-eufemia/src/components/upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/stories/Upload.stories.tsx

Motivation is that when transforming where one make a new File() the files will not be equal, hence the file will not be removed...

fix(Upload): remove file by id or file equality

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1743066020148259

fix(Field.PhoneNumber): list country code beneath country name

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/AutocompleteDocs.ts
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx
packages/dnb-eufemia/src/components/dropdown/DropdownDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Selection/Selection.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx
packages/dnb-eufemia/src/fragments/drawer-list/DrawerListDocs.ts
packages/dnb-eufemia/src/shared/helpers/__tests__/withCamelCaseProps.test.tsx
packages/dnb-eufemia/src/shared/helpers/withCamelCaseProps.tsx

To be used in https://github.com/dnbexperience/eufemia/pull/5019

chore(Field.Selection): support setting `autoComplete` for autocomplete variant

---

packages/dnb-eufemia/src/components/dropdown/Dropdown.js
packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/__tests__/Selection.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Selection/stories/Selection.stories.tsx

fix(Forms): support `required` in Field.Selection with `dropdown` variant

---

packages/dnb-design-system-portal/src/docs/uilib/about-the-lib/releases/eufemia/v11-info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushContainer/info.mdx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/useHandleStatus.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/stories/PushContainer.stories.tsx
packages/dnb-eufemia/src/extensions/forms/constants/locales/en-GB.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/nb-NO.ts
packages/dnb-eufemia/src/extensions/forms/constants/locales/sv-SE.ts

Missing a `t` in `uncommitted`.

chore(Iterate.PushContainer): preventUncommitedChanges -> preventUncommittedChanges

---

packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx

fix(Forms): ensure Form.Isolation does work within a Form.Section

---

packages/dnb-eufemia/src/components/autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap
packages/dnb-eufemia/src/components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/dnb-eufemia/src/components/button/__tests__/__snapshots__/Button.test.tsx.snap
packages/dnb-eufemia/src/components/button/style/dnb-button.scss
packages/dnb-eufemia/src/components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/dnb-eufemia/src/components/dialog/__tests__/__snapshots__/Dialog.test.tsx.snap
packages/dnb-eufemia/src/components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/dnb-eufemia/src/components/dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
packages/dnb-eufemia/src/components/global-error/__tests__/__snapshots__/GlobalError.test.tsx.snap
packages/dnb-eufemia/src/components/global-status/__tests__/__snapshots__/GlobalStatus.test.tsx.snap
packages/dnb-eufemia/src/components/help-button/__tests__/__snapshots__/HelpButton.test.tsx.snap
packages/dnb-eufemia/src/components/input-masked/__tests__/__snapshots__/InputMasked.test.tsx.snap
packages/dnb-eufemia/src/components/input/__tests__/__snapshots__/Input.test.tsx.snap
packages/dnb-eufemia/src/components/modal/__tests__/__snapshots__/Modal.test.tsx.snap
packages/dnb-eufemia/src/components/pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
packages/dnb-eufemia/src/components/skip-content/__tests__/__snapshots__/SkipContent.test.tsx.snap
packages/dnb-eufemia/src/components/slider/__tests__/__snapshots__/Slider.test.tsx.snap
packages/dnb-eufemia/src/components/step-indicator/__tests__/__snapshots__/StepIndicator.test.tsx.snap
packages/dnb-eufemia/src/components/tag/__tests__/__snapshots__/Tag.test.tsx.snap
packages/dnb-eufemia/src/components/toggle-button/__tests__/__snapshots__/ToggleButton.test.tsx.snap
packages/dnb-eufemia/src/components/upload/__tests__/__snapshots__/Upload.test.tsx.snap

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1747388437726769
Fixes it also for [Form.SubmitButton](https://eufemia.dnb.no/uilib/extensions/forms/Form/SubmitButton/)
Deploy preview: https://eufemia-git-fix-font-weight-button-type-submit-iphone-eufemia.vercel.app/uilib/extensions/forms/Form/SubmitButton/
How it looks today:
How it will look with the fix:

fix(Button): bold font weight issue when `type="submit"` on iPhone

---

packages/dnb-eufemia/src/components/date-picker/DatePicker.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerRange.tsx

To prevent confusion since it's not the same as the `DatePicker` `onChange`

chore(DatePicker): rename `onChange` for `DatePickerRange`  to `onPickerChange`

---

packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/types.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/Count/__tests__/Count.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushButton/PushButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushButton/__tests__/PushButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Visibility/__tests__/Visibility.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts
packages/dnb-eufemia/src/extensions/forms/hooks/usePath.ts

fix(Forms): add support for Iterate.Array in a Form.Section with a path

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/PushButton/info.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/RemoveButton/info.mdx
packages/dnb-eufemia/src/extensions/forms/Iterate/RemoveButton/RemoveButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/RemoveButton/__tests__/RemoveButton.test.tsx

```tsx
<Iterate.Array value={['foo', 'bar']}>
<RemoveButton text="Remove item {itemNo}" />
```

feat(Iterate.RemoveButton): add support for `itemNo`

---

packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fix(Forms): ensure Iterate.Array with `required` prop removes error in Wizard step

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Motivation: https://dnb-it.slack.com/archives/C07JEJVSHJR/p1747833979816759

fix(Forms): ensure `reduceToVisibleFields` works properly within Wizard

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx

forms changelog for https://github.com/dnbexperience/eufemia/pull/5151

chore(Forms): changelog v10.75.0

---

packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fix(Forms): ensure fields don't report errors when hidden inside Visibility

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/changelog.mdx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/ChildrenWithAge.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/ChildrenWithAge.test.tsx
packages/dnb-eufemia/src/extensions/forms/blocks/ChildrenWithAge/__tests__/__snapshots__/ChildrenWithAge.test.tsx.snap

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1747983210055469

fix(ChildrenWithAge): set 9 as maximum amount of children 

---

packages/dnb-eufemia/src/extensions/forms/Field/Upload/Upload.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/__tests__/Upload.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Upload/stories/Upload.stories.tsx

Builds on top of https://github.com/dnbexperience/eufemia/pull/5188
Labeling as a fix, since docs already says this prop is supported.

fix(Field.Upload): support disabled property

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/useStep/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/useStep/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Wizard/useStep/info.mdx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Context/WizardContext.ts
packages/dnb-eufemia/src/extensions/forms/Wizard/Step/Step.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/__tests__/useReactRouter.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/__tests__/useStep.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/hooks/useStep.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1747903983715989

fix(Forms): call every `onStepChange` assigned to Wizard.useStep

---

packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/Provider.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/__tests__/Provider.test.tsx
packages/dnb-eufemia/src/extensions/forms/DataContext/Provider/useEventListener.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/IsolatedContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/IsolationDataReference.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/useHasContentChanged.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/useDataContextSnapshot.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/useHandleStatus.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/useHasContentChanged.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/useReportError.ts
packages/dnb-eufemia/src/extensions/forms/Form/SubmitConfirmation/SubmitConfirmation.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/EditContainer/ResetButton.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainerDocs.ts
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Tools/Errors.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/PrerenderFieldPropsOfOtherSteps.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/WizardContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

fix(Forms): ensure `preventUncommittedChanges` with handler schema does not prevent Wizard navigation

---

packages/dnb-design-system-portal/src/docs/uilib/usage/best-practices.mdx

I don't think this line of code does anything.
https://eufemia.dnb.no/uilib/usage/best-practices/

chore: removes wip from Best Practices docs

---

packages/dnb-eufemia/src/components/button/Button.js
packages/dnb-eufemia/src/components/dialog/__tests__/DialogAction.test.tsx
packages/dnb-eufemia/src/components/drawer/__tests__/Drawer.test.tsx
packages/dnb-eufemia/src/components/global-status/__tests__/GlobalStatus.test.tsx
packages/dnb-eufemia/src/components/help-button/__tests__/HelpButton.test.tsx
packages/dnb-eufemia/src/components/step-indicator/__tests__/StepIndicator.test.tsx
packages/dnb-eufemia/src/components/timeline/TimelineItem.tsx
packages/dnb-eufemia/src/extensions/forms/Form/SubmitButton/__tests__/SubmitButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushButton/__tests__/PushButton.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/__tests__/WizardContainer.test.tsx
packages/dnb-eufemia/src/shared/AlignmentHelper.d.ts
packages/dnb-eufemia/src/shared/AlignmentHelper.tsx
packages/dnb-eufemia/src/style/core/helper-classes/helper-classes.scss
packages/dnb-eufemia/src/style/core/utilities.scss

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1748860637911689?thread_ts=1748854640.692369&cid=CMXABCHEY
**It does indeed fix the issue reported:**
vs

fix(Button, Input): update alignment helper to use a more widely supported zero-width character

---

packages/dnb-eufemia/src/extensions/forms/Field/Indeterminate/Indeterminate.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Indeterminate/__tests__/Indeterminate.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Indeterminate/useDependencePaths.tsx

Motivation for setting aria-controls:
https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox-mixed/

fix(Field.Indeterminate): set `aria-controls`

---

packages/dnb-design-system-portal/src/html.tsx

Tested and verified locally that the same file is actually used.

chore(Portal): rewrite html entry file

---

packages/dnb-eufemia/scripts/prebuild/tasks/__tests__/makeReleaseVersion.test.ts
packages/dnb-eufemia/scripts/prebuild/tasks/makeReleaseVersion.ts
packages/dnb-eufemia/src/shared/BuildInfo.cjs
packages/dnb-eufemia/src/shared/Eufemia.ts

Just for internal usage like in configuration files.

chore: make it possible to import the Eufemia version from CJS

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Toggle/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Toggle/demos.mdx
packages/dnb-eufemia/src/components/checkbox/Checkbox.tsx
packages/dnb-eufemia/src/components/switch/Switch.tsx
packages/dnb-eufemia/src/components/switch/SwitchDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/BooleanDocs.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Boolean/__tests__/Boolean.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/Toggle.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Toggle/__tests__/Toggle.test.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1749556336354409
Can be tested in [Toggle](https://eufemia-git-feat-add-variant-switch-eufemia.vercel.app/uilib/extensions/forms/base-fields/Toggle/demos/#switch).

feat(Forms): add variant `switch` to Field.Boolean & Field.Toggle

---

packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
packages/dnb-eufemia/src/components/breadcrumb/BreadcrumbDocs.ts
packages/dnb-eufemia/src/components/breadcrumb/__tests__/Breadcrumb.test.tsx

Solves [this ticket](https://dnb-asa.atlassian.net/jira/software/c/projects/EDS/boards/734?assignee=712020%3A11a274b8-3b2a-4c7f-9968-07cf788ff7dd&selectedIssue=EDS-737)

feat(Breadcrumbs): add `onToggle` property

---

packages/dnb-eufemia/src/components/upload/Upload.tsx

`HeightAnimation` does not support `hideOutline`

chore(Upload): fixes test warning

---

packages/dnb-eufemia/src/plugins/postcss-isolated-style-scope/plugin-scope-hash.cjs
packages/dnb-eufemia/src/plugins/postcss-isolated-style-scope/plugin-scope-hash.d.ts
packages/dnb-eufemia/src/plugins/postcss-isolated-style-scope/plugin-scope-hash.js

fix(IsolatedStyleScope): enhance typing for `getStyleScopeHash`

---

packages/dnb-eufemia/src/plugins/postcss-isolated-style-scope/scripts/__tests__/transformToESM.test.ts
packages/dnb-eufemia/src/plugins/postcss-isolated-style-scope/scripts/transformToESM.ts

Motivation: https://dnb-it.slack.com/archives/C04NL73S2Q5/p1750758202248989

fix(isolated-style-scope-plugin): ensure CJS support

---

packages/dnb-eufemia/src/components/table/__tests__/__snapshots__/Table.test.tsx.snap
packages/dnb-eufemia/src/components/table/style/table-header-buttons.scss
packages/dnb-eufemia/src/style/core/utilities.scss

StackBlitz of the issue: https://stackblitz.com/edit/1turgmyg-2x88kjyu?file=src%2FApp.tsx
StackBlitz of the fix: https://stackblitz.com/edit/1turgmyg-ckt1ypzs?file=package.json
CSB of the issue: https://codesandbox.io/p/devbox/keen-zhukovsky-xgmzgl?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE
Continuation of https://github.com/dnbexperience/eufemia/pull/5276

fix(FieldBlock): alignment helper when used in HTML v4 limited-quirks

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/Examples.tsx
packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/base-fields/Number/demos.mdx
packages/dnb-eufemia/src/components/input-masked/InputMasked.d.ts
packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Number/NumberDocs.ts
packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1752475893069009

fix(Field.Number): ensure custom mask support

---

packages/dnb-eufemia/src/components/autocomplete/AutocompleteDocs.ts

relates to https://github.com/dnbexperience/eufemia/pull/5327

chore(Autocomplete): update `no_options` docs description

---

packages/dnb-eufemia/src/components/dropdown/__tests__/Dropdown.test.tsx
packages/dnb-eufemia/src/fragments/drawer-list/DrawerListHelpers.ts

Following the same pattern as done here: https://github.com/dnbexperience/eufemia/pull/5172

fix(Dropdown): support CountryFlag in `selected_value` 

---

packages/dnb-design-system-portal/src/shared/parts/PortalStyle.scss

chore(Portal): vertically stretch the home page background

---

packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx

I have seen this failing a couple of times. So this version does work locally nicely.

chore(Field.PhoneNumber): add waitFor to flaky test

---

packages/dnb-eufemia/src/components/country-flag/style/dnb-country-flag-icons.scss

Even though this is quite manual, I think it's nice to know, and to update the version used in PRs like so: https://github.com/dnbexperience/eufemia/pull/5063

chore: add version used of flag-icons

---

packages/dnb-eufemia/src/extensions/forms/Iterate/Array/Array.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/Array/__tests__/Array.test.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/stories/Wizard.stories.tsx
packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts

Closes https://github.com/dnbexperience/eufemia/issues/5356
[Original reproduction from issue](https://stackblitz.com/edit/eufemia-starter-9wvvsxtb)
[Reproduction from this PR](https://stackblitz.com/edit/eufemia-starter-jxegwqg9?file=package.json)

fix(Iterate.Array): cannot delete from array when initial data is incomplete

---

packages/dnb-design-system-portal/src/docs/uilib/components/aria-live.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/section.mdx

Components were created approximately 2years ago

chore: remove new badge from AriaLive & Section components

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/feature-fields/more-fields/Upload/info.mdx

Closes https://github.com/dnbexperience/eufemia/issues/5044

docs(Field.Upload): add how to use `transformIn`

---

packages/dnb-eufemia/src/components/step-indicator/StepIndicatorItem.tsx
packages/dnb-eufemia/src/components/step-indicator/StepIndicatorTriggerButton.tsx
packages/dnb-eufemia/src/components/step-indicator/__tests__/StepIndicator.test.tsx
packages/dnb-eufemia/src/extensions/forms/Wizard/Container/DisplaySteps.tsx

Closes https://github.com/dnbexperience/eufemia/issues/4954

fix(StepIndicator, Wizard): screen reader improvements

---

packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/Iterate/Array/Examples.tsx

Closes https://github.com/dnbexperience/eufemia/issues/4557

chore(Iterate.Array): fix example `limit` bleeding to duplicate path

---

.github/ISSUE_TEMPLATE/bug.md
packages/dnb-design-system-portal/src/docs/contribute/style-guides/issues.mdx
packages/dnb-eufemia/src/shared/Eufemia.ts
packages/dnb-eufemia/src/shared/IsolatedStyleScope.tsx
packages/dnb-eufemia/src/shared/__tests__/Eufemia.test.tsx
packages/dnb-eufemia/src/shared/__tests__/IsolatedStyleScope.test.tsx

You can type `Eufemia.versions` in your browser console to get both JS and CSS versions.

feat: add support for Eufemia.versions

---

packages/dnb-eufemia/src/extensions/forms/Field/SelectCurrency/SelectCurrency.tsx
packages/dnb-eufemia/src/extensions/forms/Field/SelectCurrency/__tests__/SelectCurrency.test.tsx
packages/dnb-eufemia/src/extensions/forms/constants/allCurrencies.ts
packages/dnb-eufemia/src/extensions/forms/constants/currencies.ts

Preview of PR build: https://aec8244f.eufemia-e25.pages.dev/uilib/extensions/forms/feature-fields/SelectCurrency/

feat(SelectCurrency): make country names searchable

---

packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/stories/Date.stories.tsx

[Reprod of the reported issue.](https://codesandbox.io/p/devbox/jolly-brook-dp9zrc?workspaceId=ws_LbiDwJdEBdbwxH2AkyAyVE)
[Reprod of the fixed issue.](https://stackblitz.com/edit/dtjjfc17-kdgahms8?file=src%2FApp.tsx)

fix(Field.Date): valid range value should not display required error

---

packages/dnb-eufemia/package.json
packages/dnb-eufemia/src/components/date-picker/DatePickerCalc.ts
packages/dnb-eufemia/src/components/date-picker/DatePickerCalendar.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerInput.tsx
packages/dnb-eufemia/src/components/date-picker/DatePickerProvider.tsx
packages/dnb-eufemia/src/components/date-picker/__tests__/DatePicker.test.tsx
packages/dnb-eufemia/src/components/date-picker/hooks/useViews.ts
packages/dnb-eufemia/src/components/date-picker/stories/DatePicker.stories.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/stories/Date.stories.tsx
yarn.lock

- Update the way it's functions are imported

feat: upgrade date-fns to latest version (v4) – ⚠️ It may effect your direct usage of date-fns

---

packages/dnb-design-system-portal/src/docs/uilib/components/date-format/Examples.tsx
packages/dnb-eufemia/src/components/date-format/DateFormat.tsx
packages/dnb-eufemia/src/components/date-format/__tests__/DateFormat.test.tsx

PR preview: https://e5055021.eufemia-e25.pages.dev/uilib/components/date-format/#relative-time

feat(DateFormat): show Tooltip on hover when rendering `relativeTime`

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.d.ts
packages/dnb-eufemia/src/components/button/Button.d.ts
packages/dnb-eufemia/src/components/dropdown/Dropdown.d.ts
packages/dnb-eufemia/src/components/form-row/FormRow.d.ts
packages/dnb-eufemia/src/components/form-set/FormSet.d.ts
packages/dnb-eufemia/src/components/form-status/FormStatus.d.ts
packages/dnb-eufemia/src/components/global-status/GlobalStatus.d.ts
packages/dnb-eufemia/src/components/global-status/GlobalStatusController.d.ts
packages/dnb-eufemia/src/components/input-masked/InputMasked.d.ts
packages/dnb-eufemia/src/components/input/Input.d.ts
packages/dnb-eufemia/src/components/pagination/Pagination.d.ts
packages/dnb-eufemia/src/components/pagination/PaginationHelpers.d.ts
packages/dnb-eufemia/src/components/pagination/PaginationInfinity.d.ts
packages/dnb-eufemia/src/components/radio/Radio.d.ts
packages/dnb-eufemia/src/components/radio/RadioGroup.d.ts
packages/dnb-eufemia/src/components/skeleton/SkeletonHelper.d.ts
packages/dnb-eufemia/src/components/tabs/Tabs.d.ts
packages/dnb-eufemia/src/components/textarea/Textarea.d.ts
packages/dnb-eufemia/src/components/toggle-button/ToggleButton.d.ts
packages/dnb-eufemia/src/components/toggle-button/ToggleButtonGroup.d.ts
packages/dnb-eufemia/src/style/themes/theme-eiendom/properties.js
packages/dnb-eufemia/src/style/themes/theme-sbanken/properties.js

Happens when running `build` locally.

chore: update type definition files

---

packages/dnb-eufemia/jest.config.screenshots.js
packages/dnb-eufemia/src/core/jest/jestPuppeteerEnvironment.js

chore: print browser version during visual e2e tests

---

packages/dnb-eufemia/src/components/input/Input.js
packages/dnb-eufemia/src/components/input/InputDocs.ts
packages/dnb-eufemia/src/components/input/__tests__/Input.test.tsx
packages/dnb-eufemia/src/components/input/stories/Input.stories.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1756906297580879
[Issue can be experienced here](https://eufemia.dnb.no/uilib/components/input/demos/#search-text-placeholder), try to enter something, then press the search-button. The on submit returns `undefined`.
[Fix can be validated here](https://76f69211.eufemia-e25.pages.dev/uilib/components/input/demos/#search-text-placeholder).

fix(Input): correct `value` in `on_submit` events

---

packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
packages/dnb-eufemia/src/components/autocomplete/__tests__/Autocomplete.test.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1757328736581789
PR Preview: https://4a1c0142.eufemia-e25.pages.dev/uilib/components/autocomplete/demos/

fix(Autocomplete): ensure list shows up after input has cleared

---

packages/dnb-eufemia/src/components/upload/__tests__/__snapshots__/Upload.test.tsx.snap
packages/dnb-eufemia/src/components/upload/style/dnb-upload.scss

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1757098320462679
CSB of the issue: https://codesandbox.io/p/sandbox/aged-snow-tljhw4
StackBlitz of the fix: https://stackblitz.com/edit/erwzrpdz-kkqvr8ev?file=src%2FApp.tsx

fix(Upload): input element overflow

---

packages/dnb-design-system-portal/src/docs/uilib/elements/code.mdx
packages/dnb-design-system-portal/src/docs/uilib/elements/horizontal-rule.mdx
packages/dnb-design-system-portal/src/docs/uilib/elements/image.mdx
packages/dnb-design-system-portal/src/docs/uilib/elements/ingress.mdx
packages/dnb-design-system-portal/src/docs/uilib/elements/lead.mdx
packages/dnb-design-system-portal/src/docs/uilib/elements/lists.mdx
packages/dnb-design-system-portal/src/docs/uilib/elements/paragraph.mdx
packages/dnb-design-system-portal/src/docs/uilib/elements/span.mdx

Will make the following section a bit easier to read: https://eufemia.dnb.no/uilib/elements/#elements
Improvement can be seen here: https://85824839.eufemia-e25.pages.dev/uilib/elements/

chore(Elements): add description to elements

---

packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
packages/dnb-eufemia/src/extensions/forms/Field/Date/__tests__/Date.test.tsx

The following should not result in an error, as one should be able to clear the input?
https://github.com/user-attachments/assets/fba801bc-afca-4aae-bd0a-e5e24bcad2f3
TODO: The fix

fix(Field.Date): should not display error when clearing the value

---

packages/dnb-design-system-portal/playwright.config.ts

Could be another amount as well. But lets try with 3 first.

chore(CI): retry e2e tests for 3 times when failing

---

packages/dnb-design-system-portal/src/docs/uilib/usage/customisation/styling.mdx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1758635208336219

docs: how to use Tailwind with Eufemia

---

packages/dnb-eufemia/src/shared/Eufemia.ts
packages/dnb-eufemia/src/shared/__tests__/Eufemia.test.tsx

Motivation: https://dnb-it.slack.com/archives/CMXABCHEY/p1758525706822649?thread_ts=1758523292.109099&cid=CMXABCHEY

feat: attach `scopeElement` when calling `Eufemia.versions`

---

packages/dnb-eufemia/src/components/global-status/GlobalStatus.js

Motivation: https://dnb-it.slack.com/archives/C07JEJVSHJR/p1759232347266619

fix(GlobalStatus): scroll into view on Firefox

---

packages/dnb-eufemia/src/extensions/forms/Form/Isolation/Isolation.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/IsolationDocs.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/Isolation.test.tsx
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/__tests__/extractZodSubSchema.test.ts
packages/dnb-eufemia/src/extensions/forms/Form/Isolation/extractZodSubSchema.ts
packages/dnb-eufemia/src/extensions/forms/Form/SubmitConfirmation/__tests__/SubmitConfirmation.test.tsx

First part of the PushContainer schema support requested by @andlbrei

feat(Form.Isolation): inherit schema from Form.Handler

---

packages/dnb-eufemia/src/extensions/forms/Field/Number/__tests__/Number.test.tsx
packages/dnb-eufemia/src/extensions/forms/Field/String/__tests__/String.test.tsx
packages/dnb-eufemia/src/extensions/forms/utils/zod.ts

Motivation: Add missing translation support, as we do the same for Ajv.

fix(Forms): add Zod schema translations support

---

packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/PushContainer.tsx
packages/dnb-eufemia/src/extensions/forms/Iterate/PushContainer/__tests__/PushContainer.test.tsx

Reverts dnbexperience/eufemia#5570

Revert "feat(Iterate.PushContainer): inherit schema from Form.Handler"

---

packages/dnb-design-system-portal/src/docs/uilib/components/table/demos.mdx
packages/dnb-design-system-portal/src/docs/uilib/components/table/info.mdx
packages/dnb-design-system-portal/src/shared/tags/Anchor.tsx
packages/dnb-design-system-portal/src/shared/tags/Details.module.scss
packages/dnb-design-system-portal/src/shared/tags/Details.tsx
packages/dnb-design-system-portal/src/shared/tags/Summary.tsx
packages/dnb-design-system-portal/src/shared/tags/index.tsx

Lets us add collapsed content in our `.mdx` files:
```
<Details>
<Summary>Want to learn more?</Summary>
This is more information that is relevant, but not so much that we should dedicate screenspace to it.
</Details>
```

chore(Portal): add custom <Details> component
